### ISSUE TITLE
Implement web UI for enabling/disabling autotagging

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1003]
The Mailpile autotagger is good for more than just classifying spam; it can learn to automatically apply any tag. We should expose this feature in the app's user interface so people can use it.

See also: https://www.mailpile.is/blog/2014-01-12_A_Plan_For_Spam.html

**Comment by BjarniRunar** [comment]
This is done! When editing tags you can choose automation and there it is.
