### ISSUE TITLE
Where is the passphrase reset? And what passphrase is legal?

### ISSUE THREAD

**Issue by Sluimers** [mailpile/Mailpile#1006]
Hi,

I just installed Mailpile in arkOS and I have a problem that I cannot login anymore as my passphrase is not accepted. The passphrase I used looks something like this: 

n*uLIU#Xn/l?]d*)/{,Vu@sY2Z;C$z@d}[k#>A;p'zVD[ML6IbrBp38!c1YgRR)@F1^NAh1s:?/\sUP}gwxoQe(b6JKf|6s*5cMT6ze7!rGW'lke3lBw@x9122'}UF}H;=2;k>"|<+)r3,/]#&;\]cL^84+zgQ45V+Na"R0z65Nk|S%9dCWBazS'M1yc`'nv#8#!F!>rz$:vM4V8,2JC!PWdsamJ|^=<kol?9'IW2$sahotr98@#aek,.

If I reinstall the package the passphrase remains and I have no idea where Mailpile's passphrase is being stored on my server.

**Comment by BjarniRunar** [comment]
Hi! Thanks for reporting this. It's understood that we need to handle passwords and passphrases better - some progress has been made, but this isn't done. See #1300, #1302 and #1304.

**Comment by sybaz** [comment]
On that note...not sure if this is a bug but after installing MailPile successfully on Ubuntu, I then run ./mp, it loads in the browser and prompts me to create a password...I do so successfully...yet on the login screen it will not accept the password I chose...I then try many things (i.e. deleting the ~/.local/share/MailPile folder (nope), then deleting the whole virtualenv and starting over from scratch (nope)... No matter what I do I can't seem to get passed the login screen...

**Comment by BjarniRunar** [comment]
@sybaz Please don't comment on ancient, closed issues if you've found a problem! It's best to file a new issue. Note that this one has probably already been reported a few times and it's usually related to an unsupported version of GnuPG - recent versions of Ubuntu come with GnuPG 2.1, and Mailpile doesn't work reliably with GnuPG 2.1 yet. Work is in progress in PR #1746.

**Comment by sybaz** [comment]
@BjarniRunar...Ok, good to know...wasn't sure if it was related to PR #1746  I'll follow up there.
