### ISSUE TITLE
Sync certain actions with mail source (e.g. move to archive folder)

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#1017]
I would like to use an instance of Mailpile running locally on my computer and still manage my mail with an app on my phone (e.g. K-9 mail on Android). At the moment, archiving a message on Mailpile does not remove it from the inbox on the server (either with IMAP or with an offlineimap-synced maildir) and move it to the archive folder. This entails that I need to move every mail that I would like to get out of my inbox twice, once in each app. 

It would be very useful if Mailpile could be configured to move mails between source folders when it already knows which folders correspond to archive, spam, etc. For the beginning, syncing only the "archive" and "mark as spam" action with the mail source would already be very useful.

I am aware of the fact that, architecturally, Mailpile wants to use the mail source as a read-only data repository, so perhaps this is something that would be implemented by a plugin or by a third-party tool. 

But I would still like to submit this as a feature request, as
- it seems very useful for those who do not plan to use one single instance of Mailpile as the only access point to their mails (it's not trivial to run it on a server, and some people might not want to keep _all_ their mail and their private keys on a server)
- Mailpile seems already to collect all the data needed to implement the feature
- I would be willing to contribute towards a bounty for implementing that feature

**Comment by mrbiber** [comment]
The bounty for this is now at $210.

**Comment by denim2x** [comment]
I'd like to know if the bounty is still available

**Comment by mrbiber** [comment]
The bounty for this issue is now at ~$800

**Comment by biji** [comment]
Also, tagging as Spam also move to IMAP:Spam folder to also train mail server

**Comment by ferdiga** [comment]
probably it should be mentioned that mailpile 1.0 is currently not syncing with imap  servers, but just reads the message once. 
Hence no changes on the mail-server will be reflected in mailpile nor changes in mailpile will be reflected on the mail-server
hope I got that rigth....

**Comment by Leo2807** [comment]
What would be the best way to implment this? I see the following possibilities:
- Make a mailbox storage class that maps to an IMAP server.
- Extend the IMAP source to also have the mailbox interface.
- Refactor everything to make the storage and retrieval of mails be in the same kind of class.

What do you think?

**Comment by BjarniRunar** [comment]
@Leo2807, I know you mean well, but I do think you should research how the app works before making suggestions. Those things have already all, more or less, been done.

The issue is that the way Mailpile tags and actions should be mapped to IMAP folders is not obvious except in a few special cases. In general, this is tricky and confusing. Consider when the user has one set of tags, but four IMAP accounts. What then?

Figuring out what is the right thing to do needs focus and time, and we just haven't had that yet. Once we know what needs to be done, then we can start thinking about how to rejigger the code.

**Comment by dakira** [comment]
@BjarniRunar IMO the solution should be to have tags associated with an account and purely local tags (that of course don't sync).

PS: Just tried mailpile for the first time in a year and am very impressed by the progress you made! I also watched your SHA talk in which you state "mailpile is not a syncing IMAP client". Can you clarify what you mean by that? I mean what exactly are the goals on syncing. Is it planned to be able to sync read-state or actually delete mail from the server?

**Comment by Queuecumber** [comment]
Current bounty is at 1 grand, that would be a nice chunk of funding for the project

**Comment by BjarniRunar** [comment]
Hi @Queuecumber! Yes and no? That's less than a week of work at U.S. market rate salaries. Devs in less expensive locales might be willing to work two weeks for that? Two weeks of work? I am not sure I could pull this off in two weeks, and nobody knows the code better than me, so... I'd love to see someone claim the bounty though, that would be really neat.

I'm a bit worried about this though; $1000 is a large enough amount of money that it starts to matter how the project is defined. What is the criteria for claiming the bounty? Who makes the call whether a PR is good enough? If I do all the prep work until what's left *does* fit in a week of work... does someone else get to claim the money? How does this make any sense? :question:

**Comment by BjarniRunar** [comment]
... also, a bunch of those pledges are now 4 years old. I am not sure people will be happy to see money disappear from their accounts based on a pledge they made so long ago. So either the money won't actually arrive, or it'll make people mad. I'm not super comfortable with this situation.

**Comment by vibhuti019** [comment]
HI, this issue seems very old, I would like to work on this.
