### ISSUE TITLE
Support Multidirectionality out of the box.

### ISSUE THREAD

**Issue by seefood** [mailpile/Mailpile#102]
Two features I'm having a hard time leaving behind me in Gmail are the content management (tagged conversations instead of filed messages) and the great support for mixed Hebrew-English letters (or Arabic-Icelandic if you prefer, the point is RTL-LTR).

I'll try to dive into the code myself, though I admit I am really bad at this, but directionality is ultra-important to me and hundreds of millions of potential users, so it has to be picked up! Is it already in the design? Am I barging into an open door? I just found out about the project, I'll go clone it now and pour some money into it too.

**Comment by seefood** [comment]
Oh wow! I forgot about this project! Well, I haven't used Gmail in about 7-8 years, so... 

Well, if it's closed, I guess the RTL issues are solved, so... kudos  :)

**Comment by fjfnaranjo** [comment]
> Oh wow! I forgot about this project!

Me too! Nice to see the project in good shape :) I used it a lot, a long time ago.

**Comment by broccolli-linux** [comment]
Great project.

That said, I wish to unsubscribe please!

I've tried through GMail but unsuccesfully...

Thank you,

E

**Comment by fjfnaranjo** [comment]
> I wish to unsubscribe please!

Your GitHub account is probably watching this issue. I have a button to disable it over the list of participants, on the right sidebar.
