### ISSUE TITLE
Allow importing of existing keypair

### ISSUE THREAD

**Issue by stephen304** [mailpile/Mailpile#1022]
I already have a private key in mailvelope, but when I set up Mailpile, I didn't see anywhere to paste it and it instead insisted on generating a new key. Furthermore, I don't see anywhere in the interface to delete the key it generated me or import my other key. This makes it rather hard to transition to Mailpile from other PGP solutions.

**Comment by davidak** [comment]
i have downloaded and installed the latest beta of Mailpile on OS X 10.9.5.

i have a PGP Key-Pair on another computer and want to use it.

i expected an option to import my existing key in the setup in the webinterface but i could only generate a new one.

so i have done that and expected an option to change it later in the settings. i also don't found that.

please implement both, so a normal person can use it without going to the command line. i have no gpg installed in this computer.

i also found no "can i import an existing PGP-Key-Pair?" in the FAQ, instead a lot of stupid questions i wouldn't ask.
