### ISSUE TITLE
Spambayes snagging mail from Outbox

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1023]
I had a weird experience, I sent an email and it seemed to complete sending but the Outbox item didn't show in the sidebar, nor was it in my Sent mail. I searched and it came back empty. I looked at the CLI output and I never saw the sending data logged.

A bit later I realized it was in the Spam folder with the Outbox label still attached- it seemed to be stuck in non sending state!

**Comment by bnvk** [comment]
Closing this as it is a duplicate of #1023 and this has better details

**Comment by gdrooid** [comment]
@bnvk Your comment points to this same issue.
