### ISSUE TITLE
Add hints for how to choose a good passphrase

### ISSUE THREAD

**Issue by kehugter** [mailpile/Mailpile#1028]
During the first setup of the beta release, it would be useful to have a hint in

http://localhost:33411/setup/crypto/

about how the passphrase should look like: minimum recommended length, recommended character combination (upper/lower case, numbers, symbols).

A passphrase strength verification could be also part of the hints. I used 'asd' and the setup didn't complain.

**Comment by aviau** [comment]
Relevant:

![alt text](https://imgs.xkcd.com/comics/password_strength.png)

Please think of this when writing the hints.

**Comment by BjarniRunar** [comment]
This has been superceded by #1300. Closing as dup.
