### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by Subito** [mailpile/Mailpile#1038]
Since a few days ago sending mail stopped working. I deleted my whole Mailpile configuration and started over, because some things went wrong which I couldn't revert. After starting over, sending does not work anymore.

I configured the routes exactly like before and it does not show me any errors. If I send mail, it appears in the outbox, but never gets send. I noticed that, because after a few hours the mails where still in there. I got no visual clue that something was wrong.

Is that a bug or a misconfiguration?

**Comment by sg-s** [comment]
bump. mails are just sitting in the inbox for me. i checked that my sending routes work.

**Comment by BjarniRunar** [comment]
Sorry, but I'm closing this issue - it's ancient and doesn't provide any hints which I can use to debug. 

If you could try again with a clean setup (see the uninstallation instructions in our wiki) when Beta III is released, that would be helpful, but I'm afraid I cannot act on this issue as it is and with the new release right around the corner I'd rather start with a clean slate.

**Comment by sg-s** [comment]
@BjarniRunar ok, I'll do a clean install and report back. thanks.
