### ISSUE TITLE
CardDAV sync

### ISSUE THREAD

**Issue by mcduarte2000** [mailpile/Mailpile#104]
As an email client it will certainly have a contact database. Please create a functionality which will allow it to sync those contacts with a CardDAV server.

**Comment by BjarniRunar** [comment]
Note, issue #705 has a bunch of good comments, and I am currently considering the Radicale proposal as well.

**Comment by stevenroose** [comment]
Any news on this? Allowing the use of Mailpile with an existing CardDAV server would be awesome!
