### ISSUE TITLE
 After start and setup in Dcker container mailpile falls into loop

### ISSUE THREAD

**Issue by DoubleMalt** [mailpile/Mailpile#1042]
Exemplary stack trace:

> Save config failed in Save worker: global name 'safe_remove' is not defined  
> Traceback (most recent call last):
>  File "/Mailpile/mailpile/crypto/streamer.py", line 156, in **init**
>    self._proc, self._fd = self._popen(command, fd, long_running)
>  File "/Mailpile/mailpile/crypto/streamer.py", line 196, in _popen
>    bufsize=0, long_running=long_running)
>  File "/Mailpile/mailpile/safe_popen.py", line 153, in __init__
>    creationflags=creationflags)
>  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
>    errread, errwrite)
>  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>    raise child_exception
> OSError: [Errno 2] No such file or directory
> Save config failed in Save worker: global name 'safe_remove' is not defined    

It seems to be connected with this line in stdout:

> Popen(['openssl', 'enc', '-e', '-a', '-aes-256-cbc', '-pass', 'stdin', '-bufsize', '0'], <open file '<fdopen>', mode 'wb' at 0x7fb616639c00>, False)

**Comment by BjarniRunar** [comment]
This bug was caused by safe_remove not being defined in crypto.streamer; that's been fixed.
