### ISSUE TITLE
Stuck at "Finding Encryption Keys"

### ISSUE THREAD

**Issue by Jagermo** [mailpile/Mailpile#1048]
I was trying to add a pgp test account to verify if e-mails can be encrypted on my installation (Windows 8.1), however I am not able to find an encryption key for the user. 
Mailpile just seems to be stuck at the "Finding Encryption Key" dialoge. I let it run for the last half hour, however it does not come up with a key or an error. 
I verified it on a new contact as well as on an existing contact whos pgp key I already have. 
There is no unusual ressource usage I can see. 

My suggestion: Would it be possible to show more information where the the system is looking up keys? And is it maybe possible to add/delete keyservers if it is just a timeout problem?

**Comment by mikerrrrrr** [comment]
+1 I'm running on the master branch as of Wed Jan 7 2015 system:

```
Darwin 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
```

From the eventlog it looks like it's found but nothing else happens:

```
"date": "Wed, 07 Jan 2015 16:15:05 -0000", 
            "event_id": "54ad5b88.00078.bf5a", 
            "flags": "c", 
            "message": "crypto/keylookup: Found 1 encryption key", 
            "private_data": {
                "command": "crypto/keylookup", 
                "elapsed": "0.000", 
                "event_id": "54ad5b88.00078.bf5a", 
                "message": "Found 1 encryption key", 
                "result": [
                    {
                        "created": ... 
```

**Comment by mikerrrrrr** [comment]
And it does get imported...but you have to restart mailpile to actually use the new key.

**Comment by wngr** [comment]
I have a similar problem, it keeps searching for the public key forever. I even added the contact's public key manually, which now comes up in his contact. But still, mailpile doesn't encrypt the mail, as the key is still missing.

**Comment by csoghoian** [comment]
This may have been fixed. I deleted my mailpile directory, downloaded the latest git source, and the problem seems to have vanished.

**Comment by bnvk** [comment]
Yes, this has been fixed!
