### ISSUE TITLE
Question: How to update mp correctly?

### ISSUE THREAD

**Issue by IGonza** [mailpile/Mailpile#1053]
Centos 6.5
I made git clone, then setup mp and run.

Now I want to update all the scripts to the latest version from master.
Last time when I did "git pull" I couldn't login anymore because of passphrase did not work any more. So I had to uninstall and install again.

Is there another way to update?

**Comment by BjarniRunar** [comment]
Sorry we didn't help with this! :-(

Closing issue as obsolete.
