### ISSUE TITLE
stopped working at start up of program

### ISSUE THREAD

**Issue by jjsjjs** [mailpile/Mailpile#1061]
on win 7 32bit. program stops immidiately at start up. so can't test anything.
thnks. i've send an email with details to your team.

**Comment by step21** [comment]
I think this should be closed after a long period of inactivity and no helpful information for others except "I sent information in my e-mail"

**Comment by jjsjjs** [comment]
correct

step21 schreef op 24-2-2015 om 17:56:

**Comment by sg-s** [comment]
> only the messages windows gave and i copied them in my 1st email

i'm a random stranger - so i don't see emails sent you sent to mailpile. a good rule of thumb is to put all information you have in the issue, so that everyone can see them, and everyone can contribute.
