### ISSUE TITLE
Issues with lack of support for TLS?

### ISSUE THREAD

**Issue by albertocottica** [mailpile/Mailpile#1062]
Hello, we use IMAP-TLS on our server, and you don't seem to support that. Any plans? 

FYI, by setting the "Source" protocol onto plain IMAP we were able to make it work (though veeeery slowly). What does not work at all is the sending route (the error message is a rather unhelpful "error connecting"); might this be the same issue? Maybe we are trying to send non-TLS stuff over to a server that requests TLS, and the server would not accept it. Do you have any suggestions as to what we could do?

**Comment by BjarniRunar** [comment]
This is a year old, since then we have STARTTLS and normal SSL both verified to work well with IMAP. Thank you for filing, sorry we didn't respond sooner! :-)
