### ISSUE TITLE
LDAP Auth

### ISSUE THREAD

**Issue by imsoftware** [mailpile/Mailpile#1063]
As a user, i want to log in with my LDAP account.

**Comment by dashohoxha** [comment]
This related issue has been closed: https://github.com/mailpile/Mailpile/issues/52 So, maybe this one should be closed too.
It is not clear the reason for closing that issue, but I think that LDAP Auth usually is implemented on a mailserver (SMTP/IMAP/POP), while Mailpile is just a mail client, not a mail server. So, maybe LDAP Auth doesn't make sense, unless you want to use a single Mailpile installation for multiple users. I think that Mailpile is supposed to be installed and used locally, by each individual user.
