### ISSUE TITLE
When Conversation Encryption State Changes, Mailpile Should Remove Quoted Text

### ISSUE THREAD

**Issue by NickDaly** [mailpile/Mailpile#1066]
# Problem:

When I am quoting text while replying to or forwarding an email and I change the encryption state of the email I'm writing (to one different than when the conversation began), I am leaking key information.  Mailpile does not, but should prevent me from doing so.
## Examples

Examples for each use-case follow.
### Reply

When I quote text in an unencrypted reply to an encrypted message, I am sending the plain-text of the encrypted message.  This action leaks the original sender's key information.  For example, if Bob sends me an encrypted message and I reply with plain text while quoting the email, I have just leaked some amount of Bob's key.

Alternatively, when I quote text in an encrypted reply to an unencrypted message, I am leaking my own key: I am providing an encrypted form of a known plain text to someone else's public key.
### Forward

When I quote text in an unencrypted forward of an encrypted message, I am sending the plain-text of the encrypted message.  This action leaks the original sender's key information.  For example, if Bob sends me an encrypted message and I forward with plain text while quoting the email, I have just leaked some amount of Bob's key.

Alternatively, when I quote text in an encrypted forward to an unencrypted message, I am leaking my own key: I am providing an encrypted form of a known plain text to someone else's public key.
# Impact:

Mailpile allows me to leak my or another person's secret key data.  This exposes my private key rendering it useless for it's intended purpose (to remain private).
# Solution:

Mailpile should not allow users to quote text while changing the state of encryption on a message.  Mailpile could do this through either:
1. Erasing the quoted text when replying (possibly with a warning before doing so), or
2. Preventing the user from changing the encryption status of the message.

Of particular concern are usecases where users are forwarding messages to users who don't have secret keys, where the original author did.  In those cases, Mailpile might consider it reasonable to automatically decrypt the message behind the scenes, but that is unacceptable, as it again leaks the user's key.
# Metadata

Please tag this bug with the "privacy/security" tag, I am unable to do so in the GitHub app.

Thank you for your time in reading this bug report,
Nick

**Comment by JazzTp** [comment]
> Mailpile should not allow users to quote text while changing the state of encryption on a message. Mailpile could do this through either:
> 
>     1. Erasing the quoted text when replying (possibly with a warning before doing so), or
> 
>     2. Preventing the user from changing the encryption status of the message.

Copy&paste would still be allowed I guess... how would you prevent it anyway? Or a screenshot being taken?  
A journalist might want to quote "anonymous sources...".  

You are _always_ trusting somehow the person to whom you send anything, or otherwise limiting what you send to that person or modifying the form in which you send, e.g. allusions and questions instead of plain statements affirming things you might want to be able to deny. (You can also send sensitive material from an account not revealing your identity.)

And you can't assume that the recipient will be using Mailpile anyway and not another client or a modded Mailpile.
