### ISSUE TITLE
Search not recognizing special characters

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1072]
It's particularly painful when trying to setup filters for mailling-lists.

List-id are generally like "mylist.lists.host.tld", the search can only match on "mylist", which is not sufficient to filter the list correctly.

If I do 

```
s list:mylist
```

I get the emails

However, if I do

```
s list:mylist.lists.host.tld
```

I get nothing.

Imagine the number of lists called "talk" or "members" or "dev", you easily understand the issue :)

**Comment by BjarniRunar** [comment]
This is working as designed. Non-ASCII characters work fine, but some punctuation is used as breakpoints to break words into individual search terms. This is disabled for certain prefixes, such as email: , if more prefixes need to be treated that way we should file separate issues for those.

**Comment by JocelynDelalande** [comment]
It works ! Thanks, on behalf of the non-ASCII people ;-)
