### ISSUE TITLE
[Request] Add: Undo Sending

### ISSUE THREAD

**Issue by Jagermo** [mailpile/Mailpile#1077]
One of the reasons I am still with Google is one little feature that never made it to other mail clients: Undo Sending. 

Let me explain: You can activate a lab feature in Gmail that allows you to abort the sending for a few seconds after you clicked send. This is extremely helpful, e.g. if you forget to add the promised attachment or if you sent it to the wrong John Smith in your address book. 

I don't think it would be hard to implement: Mailpile basically would have to keep the email back for a few seconds (3 to 5) and display an "Abort"-Icon during that time. If the timer runs out without user interaction, the email can be sent normally. If the user hits abort, the sending process can be stopped and the mail can be returned to the draft state. 

I know it seems like a very simple, very luxury feature, however everyone who ever sent an email to the wrong person knows how helpless you feel after you hit "Send". 
More about how it works: http://www.businessinsider.com/how-to-undo-a-sent-email-in-gmail-2013-12

Please consider it for MailPile.

**Comment by BjarniRunar** [comment]
Undoing send has not yet been implemented. Although tagging can be undone. the send action is more than just a tag - the message is finalized and becomes un-editable.

That needs to change for undo to work meaningfully, generally hitting Undo should transform a message back into a draft.
