### ISSUE TITLE
missing RFC822.SIZE in imap

### ISSUE THREAD

**Issue by alon** [mailpile/Mailpile#1080]
I am using master (43c8168a11ef4cb9c0da05e369eb808ca88c0847), with patch below (just for giving more data on this issue) and getting sometimes that error. It seems imap import has stopped. I have ~20k messages in my imap account (pobox.com) and would like to get to the bottom of this. I have python experience just need a leg up on Mailpile.

Here is the patch:
```
diff --git a/mailpile/mail_source/imap.py b/mailpile/mail_source/imap.py
index fb80f28..415cd8c 100644
--- a/mailpile/mail_source/imap.py
+++ b/mailpile/mail_source/imap.py
@@ -317,6 +317,10 @@ class SharedImapMailbox(Mailbox):
 
     def get(self, key):
         info = self.get_info(key)
+        if not 'RFC822.SIZE' in info:
+            print('ERROR: missing RFC822.SIZE in info; info dump follows')
+            print(repr(info))
+            return
         msg_bytes = int(info['RFC822.SIZE'])
         with self.open_imap() as imap:
             msg_data = []
```

Here is the output with my patch:

```
ERROR: missing RFC822.SIZE in info; info dump follows
{'UIDVALIDITY': 1358823671, 'FLAGS': ['\\Seen'], 'UID': 39987}
```

Here is the location of the exception I am avoiding with my patch:

mailpile/mail_source/imap.py:320

```python
      def get(self, key):
          info = self.get_info(key)
->        msg_bytes = int(info['RFC822.SIZE'])
          with self.open_imap() as imap:
              msg_data = []
```

**Comment by BjarniRunar** [comment]
Very interesting, thanks for reporting this. Do you know if the problem is transient, or permanent? As in, does the IMAP server always fail to return a size at all for some messages, so they never get downloaded? Or do they reappear later? Or is this a message that got deleted from the server while Mailpile was trying to download stuff? :-)

**Comment by BjarniRunar** [comment]
This was fixed some time ago, the message downloader no longer relies on RFC822.SIZE.
