### ISSUE TITLE
Implement "Key Discovery" on adding new contact

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1089]
I want to implement some support in the "Add Contact" modal that makes it explicit and easy to lookup a key in the same action. A couple ideas are:
- Automatic key lookup after email address or name is entered in form
- A manual checkbox (preset with user's Security Setting) that performs the key lookup after the contact is added
- A button which requires manual user action to perform lookup

There are some considerations about how much of this I do in front-end and how it affects the process of adding a contact in general. Curious for other's thoughts about it!

Relates to #912

**Comment by BjarniRunar** [comment]
This issue does not apply, as we don't even have an Add Contact in the app atm.
