### ISSUE TITLE
Make PGP fingerprints have color coding

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1093]
A few ideas have been bouncing around on various other crypto projects like @cryptocat on how to offer better fingerprint visualization- like color coding and such.

https://github.com/cryptocat/cryptocat/issues/627

A guy named Samir Nassar did a good experiment about this and outlined it on his blog https://samirnassar.com/blog/2014-07-07-pgp-fingerprint-experiments

![samir1-color-coding](https://cloud.githubusercontent.com/assets/48677/4924257/bc82c318-6521-11e4-8c08-10230f4b2133.png)

It shouldn't be too hard to implement this in Javascript for Mailpile :)

Relates to #912

**Comment by BjarniRunar** [comment]
In a fit of procrastination, I did some related work. See the comments in `scripts/colorprint.py` for rationale, here's a snapshot of what they look like (at the moment):

![gpg-angels-sample](https://cloud.githubusercontent.com/assets/3943592/6173221/34fead8e-b2de-11e4-962b-9a4cbe766af9.png)

**Comment by BjarniRunar** [comment]
Relates to #912

**Comment by antanst** [comment]
You probably want something more professional looking, but let me mention http://robohash.org

**Comment by BjarniRunar** [comment]
@antanst That's really neat! I'd need to study their implementation a bit to understand how much of the input hash is preserved by the varying pictures. But it's very cool.

Another experiment in this vein, using emoji: http://www.windytan.com/2014/10/visualizing-hex-bytes-with-unicode-emoji.html?m=1

**Comment by cebe** [comment]
In case you did not know: a public key can actually contain an avatar image in it: http://tools.ietf.org/html/rfc4880#section-5.12.1

**Comment by bnvk** [comment]
@BjarniRunar cool stuff ;)

@antanst neat. I could see that principle- a sort of "assembled avatar" or image composed on other items being **really** on the right track. I love abstract color & shapes, but I have designer trained "for seeing color" eyes... not to mention color blind people would have a hard time with subtle color wheels.

@cebe avatars are actually a totally different situation than what @BjarniRunar's experiment is about. I'm a big fan of avatars in general as they humanize interfaces, but avatar's embedded in PGP keys do not offer any way to "verify" the key. Anyone can embed any image in any key they control the private for. I could "pretend" to be you and upload your picture to a key I control, just like I can add your email address to that key

**Comment by cebe** [comment]
yeah true, thanks for pointing that out.

**Comment by BjarniRunar** [comment]
Here is a screenshot of what Peerio do for this:

![peerio-avatar-screenshot](https://cloud.githubusercontent.com/assets/3943592/6188035/63f0d476-b385-11e4-9401-1f16671558f6.png)

**Comment by Sc00bz** [comment]
@BjarniRunar It's ~87 bits.

There are 15 bits for the toggle of set/unset block and 456 different colors (there are visual collisions but let's ignore that). There's a mess up in the implementation so two bits of the color directly affect the 15 bits for the toggle of set/unset block. There's a larger overlap (6 bits) but it's near negligible after 2 bits. So 4*(15+log2(456)-2) = ~87.33 bits.

Here's an image of all the unique colors in a zigzag pattern:
![colors](https://cloud.githubusercontent.com/assets/2030592/6365933/1ec7dfea-bc84-11e4-9d87-088bb9016577.png)

**Comment by wiml** [comment]
Another existing example of this is the colorcoding used by both APG and OpenKeychain on Android:

![colorized_fp](https://cloud.githubusercontent.com/assets/156891/7851422/89fe5a60-04a4-11e5-8f90-95a65e7634a2.png)

In general, fingerprint visualization schemes attempt to leverage the human visual system to *quickly reject a mismatched hash*, but as far as I know none of them really allow someone to *quickly accept a matching hash* (at least, not securely!). For this reason I'm not sure how useful they really are in the face of a malicious adversary.

I think it's extremely important that any visualization technique used by Mailpile should *either* be compatible with existing implementations, or else immediately obviously different. For example, if two colorization schemes use different algorithms for choosing colors, then users will have to be told that a color mismatch is not actually meaningful. And then the whole scheme becomes pointless, just a bit of distracting visual noise in the already confusing process of fingerprint comparison.

I've collected a few more links to this concept:

The only real study of distinguishability I've found is a paper from 2009, [A Study of User-Friendly Hash Comparison Schemes](https://sparrow.ece.cmu.edu/group/pub/visual_hash_acsac09.pdf).

Related papers: Two of its authors, Perrig and Song, earlier published [Hash Visualization: a New Technique to improve Real-World Security](https://sparrow.ece.cmu.edu/group/pub/old-pubs/validation.pdf) in CrypTEC '99. Also: R. Dhamija, [Hash visualization in user authentication](http://www.cs.berkeley.edu/~jfc/hcc/courseF99/projects/dhamija.pdf).

Techniques in use: Visprint and [The PGP "biometric" word list](http://cryptography.wikia.com/wiki/PGP_word_list). For SSH fingerprints, there's [OpenSSH's randomart](https://pthree.org/2013/05/30/openssh-keys-and-the-drunken-bishop/) (predecessor to [keyart](https://github.com/atoponce/keyart)), and Antti Huima's bubblebabble.

Techniques not, AFAIK, in use:

Around 1996, Ian Goldberg, Hal Finney, and Raph Levien [outlined Visprint](https://web.archive.org/web/20040307075448/http://www.cs.berkeley.edu/~iang/visprint.html) (a [related, still-reachable page is here](http://www.tastyrabbit.net/visprint/)); Raph Levien apparently proposed a related "PGP Snowflake" visualization scheme around 1996; I can't find a copy of his proposal, but I did find [an implementation](http://dlakwi.net/snowflake/snowflake.html). I have seen Visprint in the wild once or twice, so it's just barely "in use".

Like robohash, I could swear I've seen an article proposing the use of faces like [Chernoff faces](https://en.wikipedia.org/wiki/Chernoff_face) for PGP fingerprint comparison, but I can't find it now. The geometric shapes generated by Gravatar, Github, etc., to represent a user who doesn't have an avatar also serve a similar purpose, and are generated from the hash of an email address or userid: [Identicons (gravatar version)](http://scott.sherrillmix.com/blog/blogger/wp_identicon/), [identicons (github version)](https://github.com/blog/1586-identicons), [Monsterid](http://www.splitbrain.org/blog/2007-01/20_monsterid_as_gravatar_fallback), [Sigil](https://github.com/cupcake/sigil).

**Comment by BjarniRunar** [comment]
A crappy draft of this is in the PGP key management tool now, using the same algorithm as I used for the TLS certs. It's better than nothing - closing this issue, but I encourage folks to file new ones to complain or propose improvements to the scheme.
