### ISSUE TITLE
UTF8 in labels not working

### ISSUE THREAD

**Issue by jbreitbart** [mailpile/Mailpile#1094]
I just cloned the current github repository and connected mailpile to my Gmail account. In my Gmail there are labels named like "✉ yahoo". Mailpile shows them like "jwkyahoo".

When I start mailpile I get the following message in the log, not sure if that is related

Failed to configure i18n. Using fallback.

**Comment by jbreitbart** [comment]
That seems to be fixed in the  master branch, at least for me.

**Comment by BjarniRunar** [comment]
Yes, this was fixed in e3047e2a48dc8ecd461f5d15d484558121e277cc and is live in master and in Beta II.
