### ISSUE TITLE
Can't select Key to enrypt message (Button missing)

### ISSUE THREAD

**Issue by mad-de** [mailpile/Mailpile#1095]
See attached picture: Fedora 21 with Chrome
![button to encrypt message missing](https://cloud.githubusercontent.com/assets/7095883/4964130/631decb4-674a-11e4-83b3-47fa0435829b.jpg)

**Comment by BjarniRunar** [comment]
These UI elements have been fixed; there may be bugs still but they're new and improved, different bugs! Thanks very much for filing. :-)

**Comment by mad-de** [comment]
![screenshot from 2015-08-17 19 55 10](https://cloud.githubusercontent.com/assets/7095883/9311998/5b3e7b54-451a-11e5-9baa-16902bc51eef.png)
Can't confirm working behaviour. Probably an improved bug?

**Comment by BjarniRunar** [comment]
This sounds similar to #1360 , and the things I know are broken related to this are being tracked in #1370.  You have not given enough details for me to know whether you are experiencing something else or this same issue. :-)

**Comment by mad-de** [comment]
Jep. Duplicate of #1360 and #1370 now. Sorry for picking the wrong issue.
