### ISSUE TITLE
Add support for nested IMAP folders

### ISSUE THREAD

**Issue by deviantintegral** [mailpile/Mailpile#1105]
One of my mail sources runs Courier IMAP, which for folder support needs an "IMAP Prefix" specified in the client. As-is, I can't view any of the folders within Mailpile at all.

**Comment by BjarniRunar** [comment]
I think this should work now, as of #1180, and e8430318afb3efccca7be0574a9a250a3dfd042a and a few more. Please re-open if I'm wrong! :-)
