### ISSUE TITLE
Improve configuring of Mail Source Tags

### ISSUE THREAD

**Issue by paulfurley** [mailpile/Mailpile#1109]
![image](https://cloud.githubusercontent.com/assets/254290/5107490/1973dd54-6ffa-11e4-86ab-ec352ba626df.png)

"Configure which mailboxes to import & which tags to apply after mail is imported" - I'm really not sure what I'm supposed to do here.

**Comment by step21** [comment]
Not sure how far this is related but - for testing I imported an mbox source from thunderbird. I mapped inbox and drafts. However, for importing, it then seems that all mail is imported into inbox anyway, not just the one in the actual inbox folder. What am I missing here?

**Comment by BjarniRunar** [comment]
This has all changed, Beta III does these things a different (hopefully better) way.
