### ISSUE TITLE
I got "Not connected to server" or "Connection timed out" every time

### ISSUE THREAD

**Issue by N00D13** [mailpile/Mailpile#1120]
I have added 3 Mailing Sources, i got this Error every Time.

**Comment by maysara** [comment]
I have a similar issue, i get "Connection timed out" and today i got "shutdown" :S ; the diffrence is that it worked like a charm for a while, pulled 47k of mails, then stopped, then worked inconsistently, fetched a few, but would not show them next start and wont fetch new ones, now its been a while and last email showed dates to june 2nd. I'm using gmail, IMAP/SSL port 993 on imap.gmail.com and mail.google.com, I can't figure out how to debug the connection issue or how to trigger mailpile to connect (both from command line)

**Comment by BjarniRunar** [comment]
@maysara I'm going to close this bug as the original issue is obsolete and the advice from Brennan is obsolete as well. Too much has changed!

However, *if* you are running the latest code from github and experiencing this problem, I would appreciate it if you would file a new issue. We don't have a a lot of experience with GMail over IMAP, it's quite likely there are bugs.
