### ISSUE TITLE
Make newly imported PGP key be available in Contact data

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1123]
Currently calling the `crypto/keyimport` command completes, but there is 3 - 5 minute delay to when the contact data recognizes there is now a key. The contact data should update as soon as importing process is completed so that the front-end can update & do things for the user.

Relates to #912

**Comment by BjarniRunar** [comment]
Relates to #1228.

**Comment by BjarniRunar** [comment]
This was fixed in bcfe68a71e038c6e2f5d7d5bfb6dc287c67a2bcf, IIRC.
