### ISSUE TITLE
Forge partnerships with personal cloud projects

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1126]
There are numerous projects out there, aiming to provide general consumers with personal servers or "personal clouds" that will help them be more independent and private online. Mailpile should work with these projects both on technical and potentially business fronts, as their goals are strongly aligned with ours and the technology complementary.

Here are a few services or platforms that we consider "personal clouds":
- [CloudFleet](http://cloudfleet.io)
- [SandStorm](https://sandstorm.io)
- [OwnCloud](https://owncloud.org)
- [CozyCloud](https://cozy.io)
- [ArkOS](https://arkos.io)
- [UBOS](http://ubos.net)
- list others in the comments...

**Comment by ithinkihaveacat** [comment]
I assume <https://sandstorm.io/> is one personal cloud system that might be considered. Are there any others?

**Comment by ColinMaudry** [comment]
I also know [Owncloud](https://owncloud.org/) and [CozyCloud](https://cozy.io/en/).

**Comment by tryangle** [comment]
I deploy small "cloud-in-a-box" personal business setups using SmartOS from
the joyent family. I'm excited to weave mailpile into these deployments
when applicable.

**Comment by 3615pipou** [comment]
There is also [Yunohost](https://yunohost.org/#/index_en) !

**Comment by marxistvegan** [comment]
[Freedombox](https://wiki.debian.org/FreedomBox), though that is debian specific and may require getting this packaged in debian repos, but certainly good place to consider

**Comment by pmichard** [comment]
Don't forget [seafile](seafile.com). It's not an entire private cloud solution (no contacts, no calender) but it's a very robust and very fast cloud file server software based on git and also written in python afaik. It's more like the unix philosophy "do one thing and do it well".

**Comment by forteco** [comment]
https://mailinabox.email/   I love "Mail in a box". What I like is that it helps with SSL certificates; it alerts if one is on a spamlist, it alerts if there is some kind of mis-configuration in the dns entries, etc.  It alerts in case outbound SMTP port is blocked. ETC ETC.

**Comment by Eothred** [comment]
I see ownCloud already mentioned, but these days also Nextcloud should be mentioned separately I think (a fork of the former).
