### ISSUE TITLE
Perform usability studies on e-mail search and organization

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1128]
Performing usability studies, where people with diverse backgrounds and varying levels of technical skill, use the program can provide valuable insights into what needs to be improved and how. We should perform such studies with a focus on how to find and organize e-mail using Mailpile.

**Comment by grarpamp** [comment]
There may be some relevant models and/or tools to pull from here...
http://notmuchmail.org/mutttips/
