### ISSUE TITLE
Improve end-user documentation

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1130]
There is a large amount of work that should be done in terms of explaining how Mailpile and it's many components work. This covers everything from context-sensitive hints within the app itself, to long-form manuals, to video tutorials, to the website presenting Mailpile to the world. In addition, the most critical parts of the end-user documentation will need to be translated to multiple languages. The core team will not be able to do all of this work ourselves, but we need to be sure infrastructure is in place to work with our community on this important task and it might be worth spending a portion of our budget on hiring tech writers, editors or translators.

**Comment by ianhakes** [comment]
Let me know if you want me to lend a hand with docs - probably have to be on an ad-hoc, volunteer basis (as I'd face a conflict of interest with my day job).
Bona fides: https://ca.linkedin.com/in/ianhakes

**Comment by ConorIA** [comment]
Happy to help with a little direction
