### ISSUE TITLE
Upgrade to GnuPG 2.1 or later

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1133]
Mailpile currently relies on GnuPG 1.4. This is a tried and tested implementation of PGP, but it is slowly becoming obsolete. In particular, we need to upgrade to GnuPG 2.1 in order to allow Mailpile users to take advantage of Elliptic Curve Cryptograpy which will be a requirement in order to exchange secure messages with users of Google's End-to-End encrypted e-mail solution.

**Comment by develroo** [comment]
Given the recent revelations over Logjam and the inherent weakness in  DiffieHellman without elliptic curves ( https://weakdh.org/) we should commit to moving to GnuPG 2.1 asap to be able to deprecate non-elliptic ciphers.

**Comment by BjarniRunar** [comment]
@develroo As far as I am aware, GPG does not use a Diffie-Hellman key exchange anywhere, so I fail to see the connection? Please correct me (with links please) if I am wrong!

But don't worry, GnuPG 2.1 is definitely on the roadmap, in particular because Mailpile users will absolutely needs to be able to interact with users of EC keys. It's just not top of the list yet.

**Comment by BjarniRunar** [comment]
There is a PR open. #1621 , that implements this. I need to review that PR and consider whether we want to include it in the 1.0 or postpone. Putting this on the 1.0 milestone with that in mind.

**Comment by BjarniRunar** [comment]
Note: This has become a bit more urgent, since some distros are now shipping GnuPG 2.1 as the default gpg, instead of gnupg 1.4 as gpg, and gpg2 as GnuPG 2.x. *sigh*

**Comment by BjarniRunar** [comment]
Update: Mailpile will **not** default to **requiring** GnuPG 2.1 for the next year or two or three - until all of the main distributions have made the switch and users have had time to upgrade, we will maintain compatibility with GnuPG 1.4.

It is however now a requirement for 1.0 that Mailpile support GnuPG 2.1, since 1.4 is being dropped from major distributions.
