### ISSUE TITLE
Mark conversation read from conversation detail

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1135]
In the thread detail view, I often read big threads of small messages just scrolling, without needing to expand the messages (cause they are short). If I hit « precedent » then to come back to the threads list, the related conversation will still be marked as unread because I didn't expanded all the messages it contains.

What I suggest is a button at the bottom of a thread to « mark this thread as read ». Which would do what it says and brings the user back to the previous page.

**Comment by BjarniRunar** [comment]
Yes. This is a dup of #929, closing for that reason only.
