### ISSUE TITLE
Fix how the Mailpile listening port is chosen (multiuser, OS X, ...)

### ISSUE THREAD

**Issue by b-lyons** [mailpile/Mailpile#1139]
Thanks for the great work. I am running mailpile on an OS X desktop. As it is a multi-user machine, I intend to run an instance of mailpile under each user account and so need to change from the default port.
1) the port setting does not seem to be exposed in the "preferences" tab, maybe it could be?
2) what is the correct way to manually make this configuration change on OS X? Since I am not launching using ./mp I cannot just add the http_port option at launch
Thanks for any advice

**Comment by b-lyons** [comment]
Thanks Bjarni, I hope some more feedback from a multi-user OS X platform is useful:

* On initial launch, User 1 sees the configuration wizard, and is using the default port.
* Once set up, and logged in, User 1 can change the mailpile port to a new setting as you describe above. From then on, this mailpile server will run on the non-standard port.
* Switching to User 2, mailpile starts up back on the default port, but does not launch the configuration wizard. It seems to still expect User 1 to input their passphrase.  

Maybe switching the port does not accomplish what I intended: allowing a second user to run a different, clean instance?

Also one warning for changing ports on OS X. If the user changes port to a port considered "reserved / well known" then maniple will process the change, the user exits, but on relaunch Safari will not connect to the server, instead showing “Not allowed to use restricted network port” (WebKitErrorDomain:103). There is no way to use safari to log in, to revert the change, so the user is locked out until they connect with a more flexible browser. This is nothing to do with mailpile itself, but should be considered as part of the port-changing discussion.

**Comment by BjarniRunar** [comment]
This is resolved on Linux, by the mailpile-admin script and Apache integration. Other platforms will probably use a similar pattern.
