### ISSUE TITLE
Using the .asc extension for public key attachments is poor UX for the receiver

### ISSUE THREAD

**Issue by paulfurley** [mailpile/Mailpile#1141]
I was showing @zarino Mailpile and doing a GPG primer. I sent him an email from Mailpile and selected "attach my public key".

On receiving the email, Mail.app (v5.3) on his Mac (OS 10.7.5) didn't know how to open the `.asc` file.

QuickLooking the file doesn't work and double-clicking it prompts for an application to open the file with. He said that if anything it looks like a virus.

Furthermore there's no way of telling what to do with the file. A comment with a link to instructions or something would be a start.

Going further, we suggest (inspired by @frabcus) a custom email signature along the lines of "This email is being spied on. Upgrade to use PGP security. Find out how."

:P :+1:

**Comment by BjarniRunar** [comment]
This has been validated, reiterated and expanded upon in #1693. Closing this as a dup, moving the conversation there.
