### ISSUE TITLE
Add method to manually Upload PGP Key

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1142]
It makes a lot of sense that we have an easy way to just "import a key" from within Mailpile :package: 

Relates to #912

**Comment by BjarniRunar** [comment]
Pushed a potential fix, haven't tested in the UI whether it works yet. Will close once I've confirmed, unless you beat me to it. :)

This method still suffers from the overall pgp-key-delay problem, but is flagged as one place that needs attention during that sprint.

**Comment by BjarniRunar** [comment]
I tried to use the Upload Key thing to verify, but it gave me the following:

> Unable to create uploader, update your browser

This is Firefox 34, only one behind the latest so I don't think that's really the issue.

In the JS console, I saw: ReferenceError: plupload is not defined    app.js:304

Manual testing using the hacks/http method implies that I've got this working OK from my end though.
