### ISSUE TITLE
Double scrollbar on Firefox

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1150]
I'm seeing two vertical scrollbars in search view: one for threads list and one for the whole page. 

Fx. 24.8.1 ; does not seem to affect Chrome.

**Comment by jfreak53** [comment]
This also happens in Chrome for the main view
http://i.imgur.com/yda4GFb.png

**Comment by BjarniRunar** [comment]
I am pretty sure this got fixed when I rejiggered the CSS as part of the responsiveness work.

**Comment by JocelynDelalande** [comment]
@BjarniRunar you're right, I think you fixed it even before the work on responsive.
