### ISSUE TITLE
Uh oh! This web site may be dangerous! (debate)

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1153]
Just a ticket  to debate this feature (warning user via a popup when he clicks on an external URL) ; IMHO a bad feature, scaring casual users and stands in the way of power users.

What do you other thinks about it ? At least, could it be disabled by settings, or at least disabled for the user contacts.

**Comment by karlp** [comment]
Yeah, I've seen this too, on mail in my inbox.  Is it on _my_ spam flag, or spam flags in the X-headers?
