### ISSUE TITLE
forwarding message with attachments is buggy

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1154]
Hi,

If I receive a message with an attachment (eg: a pdf) and I try to forward it to someone else (message +its original attachment), I see the attachment in the compose view, but I can't remove it « Failed: unattach », and in any case, my recipients do not receive the attachment (forwarded message itself is fine).

In fact if I check the source of the message I forwarded afterwards (sent tag), there is no attachment.

I remain available for further details if needed.

**Comment by BjarniRunar** [comment]
Should have been fixed by ecd2b2a71fe4c259d644b8d6cdb4d840f8b14a7f. Thanks for filing!

**Comment by JocelynDelalande** [comment]
Bjarni Rúnar Einarsson <notifications@github.com> wrote:
> Should have been fixed by ecd2b2a71fe4c259d644b8d6cdb4d840f8b14a7f.
> Thanks for filing!

Yes, can confirm.
