### ISSUE TITLE
Copy/pasting an email to the compose zone removes carriage returns.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1160]
It's frequent for me to copy a part from an existing email body (from thread view) into another I compose.

However, in Mailpile, when I paste the text, it no longer has its carriage return, leaving me a big blob of text I have to re-format by hand.

**Comment by bnvk** [comment]
@JocelynDelalande weird. I assume you're using Firefox, right? This behavior does not happen in Chrome, but I verified it does happen in FF. 

Odd. Using Etherpad it's the exact opposite behavior. I guess I need to do some digging into what the issue is :/ thanks for reporting

**Comment by BjarniRunar** [comment]
I do not see this in Firefox 58 on Linux. Can anyone confirm whether this is still an issue?

**Comment by BjarniRunar** [comment]
Also tested on Chrome 64 / Android 7, no problem there either.

**Comment by JackDca** [comment]
Maybe @JocelynDelalande could clarify further.

The backend does "reflow" text in a way that can delete user-entered EOLs (e.g. end of paragraph). To see this you have to click "Save" then go to "Drafts" and reload. Also if the user reloads a message, then makes additions and deletions on some lines, then again saves and reloads, the backend's reflow algorithm can produce ugly results.

This happens in reflow_text() of mailpile/util.py called from Update() of mailpile/plugins/compose.py.

Roughly, it "reflows" groups of lines that start with non-whitespace, are longer than target_width - 10 and don't end with >= 2 blanks; target_width defaults to 65.

**Comment by BjarniRunar** [comment]
I am pretty sure this issue is/was just about what happens in the browser when stuff gets pasted into the composer. I remember seeing some awful behaviour, but it's been a while and I wonder if it was actually a browser bug that just got fixed in the meantime.

**Comment by JackDca** [comment]
If Copy/Paste from/to a text area caused EOLs to be dropped that would explain the exact symptoms reported.

Now that I have read the code, I see that the reflow when saving drafts mentioned above can be turned off by setting session.config.prefs.line_length < 40. I'm going to try that for a while and see if it has any bad effects. Is there any place to set it in the UI? There's also an attribute x-mp-internal-no-reflow which is checked in one place by the code but it does not appear to be set anywhere.

**Comment by BjarniRunar** [comment]
@JackDca: I think examining the text wrapper and improving it is very worth doing, but that's issue #1560 - this issue is just about javascript/browser behaviour.

And I'm tempted to close this, because I am unable to reproduce the described behaviour and this is pretty old now. I'll give @JocelynDelalande some time to respond though.

**Comment by JocelynDelalande** [comment]
That was fixed by #1424 I just forgot to close this ticket, sorry.

One free ticket, one !
