### ISSUE TITLE
Attachments size estimation is wrong

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1166]
I received a 5,2 Mo (5 203 373 octets) attachment, that's the actual size, once downloaded. However, mailpile tells me it's a 4MB attachment in web ui on the popup when I hover the attachment.

Maybe there is something wrong in the way mp estimates the size of attachments ?

**Comment by BjarniRunar** [comment]
That is actually 5203373 / (1024 * 1024.0) = 4.96MB ...

The number was getting floor()ed instead of round()ed. For "friendly" truncated number displays, rounding is probably what most users will expect. Will push up a fix for this in my next batch.

Thanks!
