### ISSUE TITLE
Automatically refresh Inbox (IMAP Mailsource)

### ISSUE THREAD

**Issue by Simon-L** [mailpile/Mailpile#1168]
I haven't found a way to refresh the Inbox to display newly received mails.
I would also like to have that done automatically.
I would have thought it is a relatively standard feature but can't find documentation/issues on this, maybe I misunderstood the purpose of Mailpile ?

I took a look at the code as well as the command line interface and found the "rescan" command that seems to help but doesn't refresh automatically as well.
Thanks in advance !

This is a report from my first day using Mailpile.

**Comment by BjarniRunar** [comment]
Your expectations are reasonable; Mailpile just isn't ready yet. This feature is a work in progress. :-)

**Comment by joshcartme** [comment]
Came here to report the same thing.  I think just adding a refresh icon that runs the rescan command and then reloads the page would be enough.  Something like:
![refresh](https://cloud.githubusercontent.com/assets/764456/6234884/28f39b54-b6ac-11e4-93e9-559a601be136.jpg)

**Comment by BjarniRunar** [comment]
This now happens on new installs and if people with older installs enable the autoajax plugin (`mailpile> plugins/load autoajax`).  You'll need to pull from HEAD to see it though, and it is a WIP which still has some bugs. :-)

**Comment by severin-lemaignan** [comment]
Works well for me. Is there a way to change the recheck interval to something more frequent? (I take that the duration is set [here](https://github.com/mailpile/Mailpile/blob/d4db5d5b45ca75aa1ac115a1114d4f725c78c272/mailpile/mail_source/__init__.py#L263), right?)
