### ISSUE TITLE
Mailpile contacts SMTP server on the wrong port?

### ISSUE THREAD

**Issue by albertocottica** [mailpile/Mailpile#1169]
Hello all, we are trying to run Mailpile on our own self-hosted email addresses. IMAP works, SMTP does not. I am no expert, but it seems that Mailpile contacts the SMTP server on the wrong port (my settings are correctly set to 587):
    `SMTP connection to: mail.edgeryders.eu:143 as alberto@edgeryders.eu`
If I try the same thing with Gmail, I get instead
   `SMTP connection to: smtp.gmail.com:587 as alberto.cottica@gmail.com`

Below I paste the whole logged error message: 
````
SendMail: from alberto.cottica@gmail.com  (), to [u'alberto.cottica@gmail.com ', 'test@mailpile.is'] via smtp.gmail.com:587
SMTP connection to: smtp.gmail.com:587 as alberto.cottica@gmail.com
connect: (u'smtp.gmail.com', 587)
reply: '220 mx.google.com ESMTP l9sm40919136wic.21 - gsmtp\r\n'
reply: retcode (220); Msg: mx.google.com ESMTP l9sm40919136wic.21 - gsmtp
connect: mx.google.com ESMTP l9sm40919136wic.21 - gsmtp
send: 'ehlo mailpile.local\r\n'
reply: '250-mx.google.com at your service, [151.217.212.176]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-CHUNKING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: mx.google.com at your service, [151.217.212.176]
SIZE 35882577
8BITMIME
STARTTLS
ENHANCEDSTATUSCODES
PIPELINING
CHUNKING
SMTPUTF8
send: 'STARTTLS\r\n'
reply: '220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: 2.0.0 Ready to start TLS
send: 'ehlo mailpile.local\r\n'
reply: '250-mx.google.com at your service, [151.217.212.176]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-AUTH LOGIN PLAIN XOAUTH XOAUTH2 PLAIN-CLIENTTOKEN\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-CHUNKING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: mx.google.com at your service, [151.217.212.176]
SIZE 35882577
8BITMIME
AUTH LOGIN PLAIN XOAUTH XOAUTH2 PLAIN-CLIENTTOKEN
ENHANCEDSTATUSCODES
PIPELINING
CHUNKING
SMTPUTF8
send: 'AUTH PLAIN AGFsYmVydG8uY290dGljYUBnbWFpbC5jb20gAGJwZndoZnZoeXplcXRscXM=\r\n'
reply: '235 2.7.0 Accepted\r\n'
reply: retcode (235); Msg: 2.7.0 Accepted
send: u'mail FROM:<alberto.cottica@gmail.com>\r\n'
reply: '250 2.1.0 OK l9sm40919136wic.21 - gsmtp\r\n'
reply: retcode (250); Msg: 2.1.0 OK l9sm40919136wic.21 - gsmtp
send: u'rcpt TO:<alberto.cottica@gmail.com>\r\n'
reply: '250 2.1.5 OK l9sm40919136wic.21 - gsmtp\r\n'
reply: retcode (250); Msg: 2.1.5 OK l9sm40919136wic.21 - gsmtp
send: 'rcpt TO:<test@mailpile.is>\r\n'
reply: '250 2.1.5 OK l9sm40919136wic.21 - gsmtp\r\n'
reply: retcode (250); Msg: 2.1.5 OK l9sm40919136wic.21 - gsmtp
send: 'DATA\r\n'
reply: '354  Go ahead l9sm40919136wic.21 - gsmtp\r\n'
reply: retcode (354); Msg: Go ahead l9sm40919136wic.21 - gsmtp
SendMail: from alberto@edgeryders.eu (ugrazyd_xfa6mcsvx36pwasaamq), to ['alberto@edgeryders.eu', 'alberto.cottica@gmail.com'] via mail.edgeryders.eu:143
````

**Comment by BjarniRunar** [comment]
It really looks like you had 143 as your SMTP port:

> SMTP connection to: mail.edgeryders.eu:143 as alberto@edgeryders.eu

That's not expected to work, unless you have an SMTP server listening on port 143.

**Comment by albertocottica** [comment]
Thanks, @BjarniRunar, but that's precisely my point: I set it at 587 through the GUI, but the program calls 143. I have no idea why :-(
![screen shot 2015-01-19 at 17 58 19](https://cloud.githubusercontent.com/assets/1976806/5802330/eb7a1982-a004-11e4-8eec-7c409383efa6.jpg)

**Comment by almereyda** [comment]
@albertocottica What happens when you click the "test route" button?

Also, as you pasted the working configuration, could you also paste the output when using the edgeryders mail service?

**Comment by albertocottica** [comment]
Hello @almereyda, thanks for your interest.
* When I clock the "test route" button I get the "error connecting" message. 
* Do you mean "how did I install Mailpile"? I simply downloaded the beta (for Mac: I am running  OSX 10.10.1), and followed the instructions. But maybe I don't understand the question, sorry!

**Comment by albertocottica** [comment]
@almereyda, any word on this? My installation of Mailpile now has also stopped receiving from Edgeryders. I can try to correct for the problem, but it is pointless if I can't send. Should I just default to Thunderbird + Enigmail for my Community Crypto project?

**Comment by almereyda** [comment]
Yes, you may be right here. Sorry for not having been responsive.

For deployment I would never install it on a system, but use Docker containers instead. To be able to serve multiple accounts.

Unfortunately I didn't look into the current Dockerfile and its performance under production environments lately. [Issues for a v1.0 Milestone](https://github.com/mailpile/Mailpile/issues?q=is%3Aissue+Docker+milestone%3A%221.0+Release%22+is%3Aclosed) should definately account for this, too.

I will have to look into https://github.com/mailpile/Mailpile/pull/962 again, to provide meaningful feedback. But according to @BjarniRunar in https://github.com/mailpile/Mailpile/pull/962#issuecomment-75109695 , this still seems to be a [low hanging fruit](https://github.com/mailpile/Mailpile/issues/323).

**Comment by albertocottica** [comment]
This is beyond me, @almereyda – but then I imagine it will be beyond most users, and "normal" users like me will not need multiple accounts. All I can do is volunteer to retry the installation from scratch and test again. But that does not make sense unless the send problem is solved.
