### ISSUE TITLE
Sending mails results in leaving them in Outbox

### ISSUE THREAD

**Issue by a42** [mailpile/Mailpile#1170]
Hi there 

I have installed Mailpile on a Linode Cloud server and want to use it as a web-mail client for my gmail accounts instead of the one google supplies...

But after the succession of fetch the emails via the IMAP protocol on gmail.com mails which I want to send still is located in the Outbox folder (6 hours after I have 'sent' them off)

I there a way in the configuration where I can overrule the fetching of mails to sent off outgoing mails at once?

Cheers && Happy new year!

/Adam

**Comment by BjarniRunar** [comment]
Outgoing mail *is* sent at once. I use Mailpile as my primary mail client, I promise you things don't just sit around in the outbox if everything is configured correctly. :-)

If things are sitting around in the outbox, then your outgoing mail route is not configured correctly, or a firewall is blocking your access to your SMTP server.

You can double-check your configuration by clicking on the gear icon at the top-right, select Sending Routes and double check your settings. Make sure to use the "test route" option on the editing dialogue to make sure things are correctly configured.

Hope this helps, sorry about the very late reply!

**Comment by a42** [comment]
Well, I have double checked the sending route twice - it's a gmail smtp connection which gave me the same result with port 465 and 587: successful connected.

Is there other way to check this? As far as I'm aware of there are no firewall attached to my router... the outgong ports are open, which I check with: nc -v portquiz.net 587 

I'm puzzled...

Cheers,
Adam

**Comment by a42** [comment]
mkay... I'm even more puzzled now: It's working now... Mails are been sent off 'instantly'

Cheers,
Adam
