### ISSUE TITLE
local mail source import messages are not very useful

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1172]
I just get "Analyzing mail sources..." irrespective of any input folder selected. It doesn't even say if the file is present or it is actually doing something, no progress message either. Selecting IMAP also doesn't give any useful messages - if it could connect with the server, did it find any mails etc

**Comment by BjarniRunar** [comment]
I think this relates to the fact that (per #1173) you were changing the mail source type. That makes weird things happen and a restart may be required. Closing this, it's basically the same issue as the other.

**Comment by pravi** [comment]
I have lots of mails in my thunderbird folder, I want to import those mails and switch to mailpile for newer messages. If you think that is not an expected use case, then fine. I think an automated way of switching from thunderbird with one click would be a very useful feature for many. At least all my friends who wants to try mailpile use thunderbird right now.

**Comment by pravi** [comment]
If a restart is required for changing the source, mailpile should warn and offer to restart like firefox or thunderbird do when plugin installations need a restart.
