### ISSUE TITLE
Mailpile defaults to 1024 bits when creating new encryption keys

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1174]
I installed Mailpile on a fresh Ubuntu 14.10 machine last night, by grabbing the source from github.

The encryption key that mailpile created for the test email account I setup is 1024 bit RSA. This doesn't seem like a good idea. At the very least, it should be 2048, or preferably, 4096.

There may have been an advanced configuration option to select a higher key-size, if so, I didn't see it. The default value should be strong though, since most people will use it.

**Comment by BjarniRunar** [comment]
Gah, this was done to make testing easier/faster and should have been changed for the beta. Fixed in my local, will push soon. Good catch.

**Comment by BjarniRunar** [comment]
Note:

We're mulling over how to deal with the keys that have been generated by this routine and are now out on the wild. This only impacts beta-testers that had no PGP keys already, and is only a problem for people that actively started using GPG/PGP after Mailpile generated the bad key. So it's not a huge group, and hopefully "high risk" users knew better than to trust an unfinished Mailpile... but at this point we really don't know how many people out there are using weak keys as a result of this.

A blog post will follow.

**Comment by malexmave** [comment]
You could also just implement a generic warning with key rollover instructions if the user is using 1024 bit keys, as that is bad practice no matter how they were generated.
