### ISSUE TITLE
URGENT: Non-existant static "pages" leak config data

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1177]
Accessing a static page URL such as `http://localhost:33411/page/non-existant-page-file/`whereby the .html template file `non-existant-page-file/index.html` is missing, appears to leak the ENTIRE contents of a users config (when authenticated)... While this is not exposing the data publicly to web (for hosted / non-authenticated) installs, this is still a bit bad.

Thanks to [@dattaz on Twitter](https://twitter.com/dat_taz/status/550409438092599296) for bringing this to my attention

**Comment by BjarniRunar** [comment]
Will push up a fix soon.

Note that I disagree about this being urgent, for all the reasons you mentioned in the bug text. :-) Crying wolf is just stresses folks out, let's not do that.
