### ISSUE TITLE
[Feature Request] Mark all as read option in GUI

### ISSUE THREAD

**Issue by balasankarc** [mailpile/Mailpile#1178]
When using IMAP, initially all the mails are marked unread. Is there any way to mark all of them read?

**Comment by simonwoerpel** [comment]
+1

**Comment by BlackEdder** [comment]
Not sure about the gui, but in the mp command line you can do:
```
search in:new
tag -new all
```

**Comment by simonwoerpel** [comment]
thx that worked for me!

**Comment by JocelynDelalande** [comment]
@balasankarc please mark as solved if it actually answered your request.

**Comment by balasankarc** [comment]
Well, the command line way did solve my issue, but I beleive it would be better to get this in GUI. So I am gonna edit the issue to point it out. Hope that is fine.

**Comment by bnvk** [comment]
This is possible and should be relatively easy to implement as the REST API had support added a few months ago. There is just some arg that needs to be passed when making the `Mailpile.API.tag_post()` request

**Comment by BjarniRunar** [comment]
We need to support bulk tagging ops in general. Similar to how GMail allows a "select all", and all the tag ops will then work.

This is just a special case of that, which makes this a dup of #1027. :-)

**Comment by balasankarc** [comment]
Ah.. Sorry. I missed that.
