### ISSUE TITLE
Implement a mail source using the Gmail API

### ISSUE THREAD

**Issue by kolomanschaft** [mailpile/Mailpile#1181]
Gmail accounts are currently set up using the ImapMailSource. Gmail is a tag-based system, so is Mailpile. The IMAP protocol is based on mailboxes. Gmail tags are now mapped to IMAP mailboxes to be further mapped back to Mailpile tags.

Instead, one could implement a mail source using the Gmail API and thus mapping Gmail tags to Mailpile tags directly. Its a bit of a shame BaseMailSource dictates a mailbox paradigm. Though, I don't know if this really states a problem.

**Comment by thomwiggers** [comment]
See also #741 for the other side of the equation.

**Comment by kolomanschaft** [comment]
@thomwiggers Can you explain how the two issues are related? Aren't these two disjunct problems?

**Comment by thomwiggers** [comment]
they aren't dependent or anything but they are both about the GMail API

**Comment by BjarniRunar** [comment]
While overworked and understaffed, Mailpile's core back-end team (that is to say, me) is not likely to implement proprietary protocols like this any time soon. Others are welcome to contribute, but in my opinion engineering time and effort is better spent on things which benefit all users, not just GMail users.
