### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by exoteric** [mailpile/Mailpile#1182]
I have installed the beta and it appears that downloading old messages is quite slow. I have downloaded for a couple of days now. :-) (Sources: GMail, Outlook and Unoeuro service provider; IMAP, non-SSL).

It would be kind of nice to have a list of concurrent tasks that Mailpile is running to see what operations is it currently performing.

**Comment by tmxnst** [comment]
I'm not sure about other servers, but at least with gmail it's known that google throttles the bandwidth on IMAP pretty aggressively. I've synced my 3 GB gmail mailbox to mailpile a couple of times, and it always takes several days. When downloading old messages, I seem to get only about 10 messages per minute.

Other IMAP downloaders like mbsync seem to be faster though, so maybe mailpile is not completely innocent here.

**Comment by exoteric** [comment]
I see. Thanks for the tip!

**Comment by BjarniRunar** [comment]
The beta had bugs which made this unusually slow. These are mostly fixed (or at least greatly improved) in HEAD, and we will update the beta packages very soon.
