### ISSUE TITLE
Make HTML view of message properly resize & style

### ISSUE THREAD

**Issue by a42** [mailpile/Mailpile#1184]
Hi there

I would like to have to the option to enable viewing HTML e-mails in Mailpile - anyone been working with that ?

Cheers,
Adam

**Comment by JocelynDelalande** [comment]
@a42 You can already ; although, there is no way to default to HTML viewing for what I know. 

On the top of an-email you read, hit the *circled "i"*  (top-right) and click *HTML*.

**Comment by a42** [comment]
@JocelynDelalande Oh, yes I see that now... The height of the viewing pane (when view a mail in HTML-state) is fixed; is there a way to make this more dynamic ?

Cheers,
Adam

**Comment by JocelynDelalande** [comment]
> The height of the viewing pane (when view a mail in HTML-state) is fixed; is there a way to make this more dynamic ?

@a42 Never noticed that, could you provide more details ?

**Comment by a42** [comment]
Hi again @JocelynDelalande 

What I really ment was the width ... see 
![fixedwidth_viewinghtml_mailpile](https://cloud.githubusercontent.com/assets/1033874/5816000/ac8c811e-a09b-11e4-9862-bdc46a887663.png)

Cheers,
Adam

**Comment by JocelynDelalande** [comment]
@a42 ok, so what would be required is that the viewport on html emails could expand horizontally, or that a horizontal scroll is displayed (depending on UI choices). Right ?

**Comment by a42** [comment]
@JocelynDelalande yep! that is correct. As I see it could probably be done with some styling. I found the body tag for the viewing an email is set to width: auto and table to width:90%; ... I don't have the full overview of where the html view is been triggered... maybe you have a suggestion for where to look ?

Cheers,
Adam

**Comment by bnvk** [comment]
Hi @a42 I'm the front-end core dev, thanks for your interest. I think the current issue is it calculates the size (of iframe) often before all the assets loaded and HTML styling of the message have completed. This should be pretty easy to adjust the JS to properly resize the iframe & set the correct CSS properties. 

All the front-end code lives in the `/mailpile/www/default/`directory of this repo. I believe, the specific files needed to work on this feature are:

* ... html/partials/thread_message.html
* ... html/jsapi/message/message.js
* ... less/app/thread.less

I'm happy to answer any questions (here or on IRC freenode.net in #mailpile) and help you get up to speed ;)

**Comment by BjarniRunar** [comment]
This is effectively the same issues as #631 - we need to display HTML mail nicely. Thanks for the feedback!
