### ISSUE TITLE
JS: Scroll to message selector incorrect and missing from DOM

### ISSUE THREAD

**Issue by f3ndot** [mailpile/Mailpile#1185]
### Steps to reproduce:

1. Have an email thread open
2. Reload the page

### Expected:

No JS errors and scroll to the message in the thread

### Actual:

JS Error:
`Uncaught TypeError: Cannot read property 'top' of undefined`

### The Potential Problem:

The problem is potentially two-fold:

1. The message in the thread is minified or collapsed in some way and in this collapsed mode there is no `id` attribute with a value of `message-somethreadidhere`. Clicking on the collapsed message will put into the DOM a `div` element with such an attribute

2. The `id="message-somethreadidhere"` that appears in DOM after expanding the message appears to be the wrong one. In my demo .gif, it shows it expects a `thread_id` var of `12I` but the DOM has `10X`.

### Shitty Gif:

![scroll-bug](https://cloud.githubusercontent.com/assets/740289/5608096/6f325d14-9445-11e4-956d-772dc72ea9d0.gif)

**Comment by BjarniRunar** [comment]
Not sure when it got done, but testing implies this has been fixed.
