### ISSUE TITLE
Unable to send mail: Nebulous "Failed: mail" toast when encrypting or signing mail

### ISSUE THREAD

**Issue by f3ndot** [mailpile/Mailpile#1186]
**OS:** Mac OS X 10.9.5
**Mailpile:** Latest Mailpile binary for OSX

### Steps to reproduce:

1. Compose a new email or respond to an existing one
2. Enable encryption, signing, or both
3. Click "Send" or "Reply"

### Expected:

Delivered email! :dancer: 

### Actual:

Getting this toast:

![screen shot 2015-01-04 at 7 18 50 pm](https://cloud.githubusercontent.com/assets/740289/5608129/8a9b78c8-9446-11e4-949d-ba04e5c9353c.png)

There are no errors in console, or any follow up information. I've verified my route is configured properly, as is my mail sources. Sending unsigned, unencrypted email works just fine.

**Comment by f3ndot** [comment]
Hmm. My mistake. It appears to only apply to encrypting, not signing, email.

Shitty .gif:

![mail-send-bug](https://cloud.githubusercontent.com/assets/740289/5608146/c3ad9a3c-9447-11e4-8c43-5ed09965b86f.gif)

**Comment by BjarniRunar** [comment]
That .gif is great. :)  Are you trying to send encrypted mail to yourself? Or someone else?

**Comment by f3ndot** [comment]
Yes, I'm attempting to send encrypted email to myself, using Gmail SMTP.

**Comment by bnvk** [comment]
I can have been experiencing this same issue. I can confirm it's still happening. I just tested it with a few keys for different contacts. Here is a stack trace:

```
bg/log(50): POST: /api/0/message/update/send/ qs = {} post = {'body': ['Yo Dude! Just trying to send a silly encrypted test email as it keeps failing for many other contacts... not sure if I have bad keys for them, or something is wonky with vCards... just testing...'], 'from': ['Brennan Novak <hi@brennannovak.com>'], 'cc': [''], 'encryption': ['openpgp-sign-encrypt'], 'mid': ['1E0O'], 'bcc': [''], 'to': ['Sm\xc3\xa1ri McCarthy <smari@mailpile.is#08A650B8E2CBC1B02297915DC65626EED13C70DA>'], 'subject': ['Just a silly test email']}
bg/log(20): Elapsed: 0.000s (output: Set output mode to: json)
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 564, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 562, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 982, in command
    return Update.command(self, create=create, outbox=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 932, in command
    email.update_from_string(session, update_string, final=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 740, in update_from_string
    sender, rcpts, outmsg, ev = PrepareMessage(self.config, outmsg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 325, in PrepareMessage
    ).wrap(msg, prefer_inline=cpi)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/mime.py", line 415, in wrap
    raise EncryptionFailureError(_('Failed to encrypt message!'))
EncryptionFailureError: Failed to encrypt message!

bg/log(10): mail error: Failed: mail 
54d1f3da.0a6ce.127f6=UpdateAndSendit:c mail: Failed: mail 
bg/log(20): Elapsed: 0.550s (mail: Failed: mail )
bg/log(20): http://localhost:33411 "POST /api/0/message/update/send/ HTTP/1.1" 200 407
```

**Comment by Robsteranium** [comment]
I'm unable to send signed mail but encrypted mail seems to send ok.

Using Mailpile f26dea1 on Linux Mint 17.1 with GMail SMTP.

I'd gladly share a log if I knew where to find it!

**Comment by maxrp** [comment]
I am seeing similar behaviour. I have configured an identity using the gmail infrastructure and my preexisting GPG keys. I can send messages without signing, but if I enable signing I get "Failed: mail" regardless of recipient.

In one instance (but only one out of about 10 attempts), this yielded the following console message:
```<StreamWriter(gpgi-output(--clearsign --armor --local-user 5D99D92993FEEE791645D77AD771E87520CBD918), started daemon 140159254075136)>(gpgi-output(--clearsign --armor --local-user 5D99D92993FEEE791645D77AD771E87520CBD918)/write): 74 bytes left
Traceback (most recent call last):
  File "/home/[redacted]/Mailpile/mailpile/crypto/gpgi.py", line 381, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe```

Which is strange, as while I have my old CBD918 key in my keyring, it is not the key I configured for my Mailpile identity and thus should not be the key used for signing. It seems as if it is choosing the first key, despite the configuration. For reference, I typically manage four or more secret keys at any given moment in time.

Reviewing the eventlog did not yield anything apparently related to these failure-to-sign events.

I'm using Fedora 21 and Mailpile dc468e4

**Comment by Robsteranium** [comment]
Ah... perhaps it has to do with having multiple secret keys. I couldn't sign when I had two secret keys. Upon deleting my obsolete key, leaving only the key I'm authenticated with, signing now works. The obsolete key had not expired; it was the second one I used for Mailpile. As @maxrp says perhaps Mailpile is choosing the first key, regardless of which key it has been configured to use.

gpg (GnuPG) 1.4.16

**Comment by lukebranch** [comment]
@f3ndot ,

I've run into the same issue on OSX 10.9.5. Unrelated; what are you using to create that gif? Looks like it would be very useful for demonstrating issues on github in the future.

**Comment by f3ndot** [comment]
@lukebranch [LICEcap](http://www.cockos.com/licecap/). It's perfect for illustrating UX issues. You can set the frame rate at which it records as well.

**Comment by maxrp** [comment]
Tried this again with 97143a2971b00cf6340f19371d13b11fbdc468e4 and GNUPGHOME set to a path with only a single secet key in it's secring but got the same result.

**Comment by lukebranch** [comment]
@f3ndot ,

Thanks!

**Comment by BjarniRunar** [comment]
The toasts have been improved to be more informative, and the common case where this happens because a PGP key's passphrase is needed is now handled by a dialogue asking the user to unlock their key. Thanks for filing! :-)
