### ISSUE TITLE
Login with keyfile

### ISSUE THREAD

**Issue by ggondim** [mailpile/Mailpile#1187]
It would be nice to increase the login security with a keyfile instead of password, like CounterMail does: https://countermail.com/?p=keyfile.

By the way, thanks for the Mailpile initiative.

**Comment by BjarniRunar** [comment]
I don't think we're going to do this; this conflicts pretty strongly with our goals of allowing remote logins to the Mailpile. People are welcome to contribute code that does this, but I don't think it's likely to be on the core team's roadmap any time soon.
