### ISSUE TITLE
Windows 7 Memory Leak trashed HDD?

### ISSUE THREAD

**Issue by rockman73** [mailpile/Mailpile#1188]
Hi folks, I previously downloaded and installed the latest beta on my Win7 64-bit PC and tried it out. Very nice. I decided to un-installed it. Then, a few days later, I decided to install it again and give it another try. However, this time, I entered my PGP Passphrase instead of my Mailpile master key. This completely locked up my PC and trashed the hard disk. After unsuccessful attempts at restore, I resorted to re-installing Windows. Yuck. Just be forewarned, beta software is risky.

I hope someone out there is willing to attempt a repro on this bug, legitimize it and get is squashed.

Cheers

**Comment by BjarniRunar** [comment]
I don't see how this is even possible.

Mailpile opens normal files in normal folders on disk, using completely standard Python file I/O. It's not like we install operating system drivers or attempt any sort of low-level IO.  It's just normal files.

Without further details (or other reports), I'm going to chock this one up to a tragic coincidence and close the issue.

**Comment by rockman73** [comment]
@BjarniRunar I tend to agree with the tragic coincidence assessment of this bug. I filed it nonetheless. Thx for considering it.
