### ISSUE TITLE
IMAP folders not recognized on runbox.com server

### ISSUE THREAD

**Issue by hyperglitch** [mailpile/Mailpile#1189]
When I add my runbox.com IMAP account (secure.runbox.com, IMAP(ssl), 993) only folder that is recognized is INBOX.
![untitled](https://cloud.githubusercontent.com/assets/2551403/5643473/3336bcae-9659-11e4-9742-74453a7493c7.jpg)

Server has multiple folders on it:
![untitled2](https://cloud.githubusercontent.com/assets/2551403/5643484/4e106232-9659-11e4-8d84-1022d46af33d.jpg)

**Comment by bitbybit** [comment]
Same problem.

**Comment by BjarniRunar** [comment]
This is effectively a dup of #1105, a proposed fix is being discussed in #1180.
