### ISSUE TITLE
"Download or leave" choice not saved

### ISSUE THREAD

**Issue by busla** [mailpile/Mailpile#1190]
Version: Osx installer from 7. jan, 2015.

My mail source doesn´t save the "Do not download" option and reverts to "Download".

![screen shot 2015-01-07 at 14 48 48](https://cloud.githubusercontent.com/assets/3162968/5647311/c29fc232-967c-11e4-8dcf-09ffb977e322.png)

**Comment by BjarniRunar** [comment]
This is the beta. It's obsolete. :)

**Comment by BjarniRunar** [comment]
Actually, scratch that. You said from the 7th of jan, that's building from HEAD. Sorry!

**Comment by BjarniRunar** [comment]
Reproducing fails and my dialog looks different from yours. Could you verify that the problem persists in HEAD?
