### ISSUE TITLE
Can´t save mail source, no error msg

### ISSUE THREAD

**Issue by busla** [mailpile/Mailpile#1191]
Can´t save a mail source with POP3 selected. I can save the same source, with the same info, if I change the protocol to IMAP(ssl). 

The user text input becomes yellow but no error message is visible anywhere.

![screen shot 2015-01-07 at 15 09 44](https://cloud.githubusercontent.com/assets/3162968/5647625/9966d4c0-967f-11e4-9161-7665631e47ac.png)

**Comment by TomDrinkwater** [comment]
I also have this problem with POP3. I can't get IMAP working either, but it does at least save the source configuration with IMAP selected.

**Comment by BjarniRunar** [comment]
Is this the beta, or head? If beta, please try head.

**Comment by BjarniRunar** [comment]
This code is gone. :-)  The new code may be broken, but it deserves new bug reports if so.
