### ISSUE TITLE
An encrypted message I sent has status "missingkey"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1192]
This is a dubiously strange case. I sent a message to a contact whom I have a PGP key for. I wasn't paying attention and Mailpile automatically encrypted my message to them. 

However, slight problem **my message** that I sent is unviewable and has the status of `missingkey`

```
encryption: {
  have_keys: [
    "F951B453C19F64E3",
    "E527510F17097636"
  ],
  missing_keys: [
    "F951B453C19F64E3 ",
    "F951B453C19F64E3 "
  ],
  protocol: "openpgp",
  status: "missingkey"
}
```

Tiny bit of history that might be helpful... the first time this particular contact messaged me encrypted, they encrypted to my **old PGP key** whereby I no longer have the private key. Is it possible Mailpile recorded the crypto history of that key and tried to reuse it? If so, we should probably error check for missing privates in the future.

**Comment by BjarniRunar** [comment]
Is F951B453C19F64E3 the old unusable key? If the public part of it is on your keychain, Mailpile may have decided to encrypt to it.

**Comment by bnvk** [comment]
@BjarniRunar I'm a tad bit unsure what those values in the `have_keys` represent. Are they the short ID? None of those values are present in the fingerprints of any of my (or the contact I was messaging) keys.

Is it possible this issue is related to #1186 ? That there is something wonky with `pgp_keys` value in a users profile? As it could be that is missing on my instance.

**Comment by BjarniRunar** [comment]
Closing this, there is not enough information here to reproduce the bug.
