### ISSUE TITLE
Empty language selector on master

### ISSUE THREAD

**Issue by andrewtch** [mailpile/Mailpile#1193]
Master checkout, run setup; mailpile loads, shows empty lanugage selector (only with "Select language"...), pressing "Next" button stays on the same page. Any suggestions? )

**Comment by andrewtch** [comment]
Also, configuration wizaed <title> shows Error. Where can I find error log?

**Comment by andrewtch** [comment]
I have enabled logging, and I'm getting trace like that:

```
bg/log(50): http/log(50): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/commands.py", line 563, in _run_sync                                                               
    return self._finishing(command(self, *args, **kwargs))                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/commands.py", line 561, in command                                                                 
    return self.command(*args, **kwargs)                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/plugins/setup_magic.py", line 361, in command                                                      
    return self.setup_command(session, *args, **kwargs)                                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/plugins/setup_magic.py", line 504, in setup_command                                                
    'languages': ListTranslations(config),                                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/i18n.py", line 140, in ListTranslations                                                            
    for lang in os.listdir(locales):                                                                                                                                                            
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/locale' 
```

the file '/usr/local/lib/python2.7/dist-packages/mailpile-0.4.0.dev20150109-py2.7.egg/mailpile/locale'  indeed does note exists. Am I missing some python package here?

**Comment by BjarniRunar** [comment]
You appear to have used setup.py to install Mailpile globally on your machine. Although that's an entirely reasonable thing to do, it probably doesn't work yet as we haven't finished the reorg necessary to play nice with standard Linux/Python packaging.

For now, Mailpile is "under development" and you're expected to just run it from the source folder like so: ./mp

This will be fixed as part of our packaging efforts, which are tracked elsewhere. Thanks for reporting!

**Comment by andrewtch** [comment]
Ergh. And what should I do with this issue, remove dist-package?

**Comment by smetj** [comment]
I appreciate the herculean effort done with Mailpile and understand that supporting everything in detail is difficult but this is a pretty lame case of user support....

I imagine *many* people fall into this trap (including myself) and extensive searching only revealed this bug report only to be found close without any follow up.

closing comments mentions:

> This will be fixed as part of our packaging efforts, which are tracked elsewhere. 

And where might that be?

**Comment by BjarniRunar** [comment]
@smetj I don't know the answers to those questions. People manage to get themselves into all sorts of situations that I don't know the solution to.

Part of being under development *by one person* means there is no user support, except what the community can provide. We - I - simply don't have the resources.

You can make demands until you're blue in the face; all you're going to accomplish is demotivating people. If you're worried about user support, how about you research the problems and provide solutions? Contribute to our wiki? Do something, anything, except place further demands on the people that are already working as hard as they can. Thanks.

And here's the issue you were too lazy to search for yourself: #996

**Comment by smetj** [comment]
Hi  @BjarniRunar,
Thank you for the feedback.

I'm sorry you ended up in that place.
Good luck with Mailpile!

**Comment by BjarniRunar** [comment]
@smetj: Thanks. And sorry about the pushback, but if people are going to start yelling at us for every single poorly resolved issue (we have well over a thousand issues closed already), life is going to become pretty crap.

The answer in these cases is always the same: "we're were overworked, we didn't know the answer offhand, and if you couldn't figure it out then the software probably isn't ready for you yet". Yes that's discouraging, but honestly I'd rather people be discouraged than use unstable software and suffer data loss or worse.

Things will improve over time.
