### ISSUE TITLE
Mailpile does not work with GnuPG 2.1

### ISSUE THREAD

**Issue by diederick76** [mailpile/Mailpile#1194]
Hi,

I'm having trouble completing the setup process. Mailpile asks me to select the key I wish to use. I select the key and enter the passphrase. Though I know the passphrase is right (I use that key all the time and I have checked the fingerprint) I keep getting "Invalid passphrase".

I'm trying to setup Mailpile on a different machine from the one I'm using it on, so I don't have to carry it around. I use Arch linux, which uses a mailpile user. Prior to installing Mailpile, I copied the .gnupg folder of my laptop to the mailpile's home on the Mailpile machine.

["Wed, 14 Jan 2015 08:33:56 -0000", "54b629f4.00265.174e", "R", "setup/crypto: Starting", ".plugins.setup_magic.SetupCrypto", {"output": "json", "ui": ".ui.HttpUserInteraction", "elapsed": 0}, {"data": {"choose_key": ["D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A"], "passphrase_confirm": "(SUPPRESSED)", "passphrase": "(SUPPRESSED)", "_method": "POST"}}]
["Wed, 14 Jan 2015 08:33:57 -0000", "54b629f4.00265.174e", "c", "setup/crypto: Invalid passphrase", ".plugins.setup_magic.SetupCrypto", {"output": "json", "ui": ".ui.HttpUserInteraction", "elapsed": 1076}, {"data": {"choose_key": ["D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A"], "passphrase_confirm": "(SUPPRESSED)", "passphrase": "(SUPPRESSED)", "_method": "POST"}, "error_info": {"chosen_key": "", "invalid_passphrase": true}}]
["Wed, 14 Jan 2015 08:34:09 -0000", "54b62a01.00266.174e", "c", "sendmail: The outbox is empty", ".plugins.compose.EmptyOutbox", {"output": "text", "ui": ".ui.BackgroundInteraction", "elapsed": 4}, {}]

Is there something I did wrong? It seems odd to me that Mailpile can find my keys but can't correctly match the passphrase.

**Comment by tfla** [comment]
I'm having the same issue on Arch Linux with the mailpile-git package from AUR. 
The key is one I use daily, so I'm certain the GPG setup is good.

**Comment by BjarniRunar** [comment]
Not sure what is going on here. If you on the Mailpile CLI do this:

    mailpile> set sys.debug = log
    ...
    mailpile> eventlog/watch

And then go try to log in again, do you get any stack traces or helpful output on the console? (To exit the log-viewing mode, press CTRL-C)

**Comment by tfla** [comment]
Not really.

´´´
mailpile> eventlog/watch
Watching logs: Press CTRL-C to return to the CLI
bg/log(20): http/log(20): Elapsed: 0.001s (output: Set output mode to: json)
54bc3077.00011.820=SetupCrypto:R setup/crypto: Starting
bg/log(10): http/log(10): setup/crypto error: Invalid passphrase (chosen_key= invalid_passphrase=True)
54bc3077.00011.820=SetupCrypto:c setup/crypto: Invalid passphrase
bg/log(20): http/log(20): Elapsed: 0.053s (setup/crypto: Invalid passphrase)
bg/log(20): http://localhost:33411 "POST /api/0/setup/crypto/ HTTP/1.1" 200 2217
bg/log(40): Starting: refresh_command_cache
´´´

**Comment by diederick76** [comment]
Here's mine. Also not very helpful:

mailpile> eventlog/watch
http/log(20): Verstreken: 0.001s (output: Set output mode to: html)
http/log(20): Verstreken: 1.049s (setup/crypto: Configure crypto preferences)
http/log(20): Verstreken: 0.040s (setup/crypto: Configure crypto preferences)
http://bender:33411 "GET /setup/crypto/?_path=%2F HTTP/1.1" 200 6103
http/log(20): Verstreken: 0.001s (output: Set output mode to: css)
http/log(20): Verstreken: 0.005s (jsapi: Generated Javascript API)
http/log(20): Verstreken: 0.001s (output: Set output mode to: js)
http/log(20): Verstreken: 0.001s (output: Set output mode to: setup.js)
http/log(20): Verstreken: 0.018s (jsapi: Generated Javascript API)
http/log(20): Verstreken: 0.020s (jsapi: Generated Javascript API)
http://bender:33411 "GET /jsapi/as.css HTTP/1.1" 200 5655
http://bender:33411 "GET /api/0/jsapi/as.js HTTP/1.1" 200 69090
http://bender:33411 "GET /api/0/jsapi/setup.js HTTP/1.1" 200 61354
http/log(20): Verstreken: 0.001s (output: Set output mode to: json)
http/log(10): setup/crypto error: Invalid passphrase (chosen_key= invalid_passphrase=True)
http/log(20): Verstreken: 0.128s (setup/crypto: Invalid passphrase)
http://bender:33411 "POST /api/0/setup/crypto/ HTTP/1.1" 200 2817
Onbekend commando: eventlog/watch

**Comment by BjarniRunar** [comment]
My bad - I should have suggested:

    mailpile> set sys.debug = log gnupg
    ...

Might need a restart of the app, then try to log in.  And be careful what you paste, that's verbose and may contain private information.

**Comment by diederick76** [comment]
With that, I get, as soon as I request the page:

mailpile> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDOUT<< sec:r:2048:1:8B69AEA222EA4A10:1329981667:::u:::sca::::::
<<STDOUT<< fpr:::::::::A345246020953E71C3ED3D828B69AEA222EA4A10:
<<STDOUT<< uid:r::::1329981667::796A40DDB76AF8ADCB3247967020DFD6B26C4BF3::Diederick de Vries (Private emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:r::::1329998009::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:r:2048:1:2B3EEF215D57ABCE:1329981667::::::e::::::
<<STDOUT<< sec:u:1024:1:0B1C4AD6FDD3D1C8:1330064952:::u:::scaESCA::::::
<<STDOUT<< fpr:::::::::E89B4EEB0BA37441B893136B0B1C4AD6FDD3D1C8:
<<STDOUT<< uid:u::::1330064952::C8D521DB0F7A7194C2195F532DB175B90C07F4D8::Diederick de Vries (Private Emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:u::::1330069427::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:u:1024:1:5E48FC06A0E03541:1330064952::::::e::::::
<<STDOUT<< sec:u:2048:1:FBEBBDFA5619404A:1392841618:::u:::escESC::::::
<<STDOUT<< fpr:::::::::D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A:
<<STDOUT<< uid:u::::1392841618::5006AD501F4B77BAEAC7EB7930382DE4A61705E3::Diederick de Vries (Private Emailbox) <diederick@diederickdevries.net>:
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDOUT<< sec:r:2048:1:8B69AEA222EA4A10:1329981667:::u:::sca::::::
<<STDOUT<< fpr:::::::::A345246020953E71C3ED3D828B69AEA222EA4A10:
<<STDOUT<< uid:r::::1329981667::796A40DDB76AF8ADCB3247967020DFD6B26C4BF3::Diederick de Vries (Private emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:r::::1329998009::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:r:2048:1:2B3EEF215D57ABCE:1329981667::::::e::::::
<<STDOUT<< sec:u:1024:1:0B1C4AD6FDD3D1C8:1330064952:::u:::scaESCA::::::
<<STDOUT<< fpr:::::::::E89B4EEB0BA37441B893136B0B1C4AD6FDD3D1C8:
<<STDOUT<< uid:u::::1330064952::C8D521DB0F7A7194C2195F532DB175B90C07F4D8::Diederick de Vries (Private Emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:u::::1330069427::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:u:1024:1:5E48FC06A0E03541:1330064952::::::e::::::
<<STDOUT<< sec:u:2048:1:FBEBBDFA5619404A:1392841618:::u:::escESC::::::
<<STDOUT<< fpr:::::::::D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A:
<<STDOUT<< uid:u::::1392841618::5006AD501F4B77BAEAC7EB7930382DE4A61705E3::Diederick de Vries (Private Emailbox) <diederick@diederickdevries.net>:

And then, when I click "Authenticate":

mailpile> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDOUT<< sec:r:2048:1:8B69AEA222EA4A10:1329981667:::u:::sca::::::
<<STDOUT<< fpr:::::::::A345246020953E71C3ED3D828B69AEA222EA4A10:
<<STDOUT<< uid:r::::1329981667::796A40DDB76AF8ADCB3247967020DFD6B26C4BF3::Diederick de Vries (Private emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:r::::1329998009::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:r:2048:1:2B3EEF215D57ABCE:1329981667::::::e::::::
<<STDOUT<< sec:u:1024:1:0B1C4AD6FDD3D1C8:1330064952:::u:::scaESCA::::::
<<STDOUT<< fpr:::::::::E89B4EEB0BA37441B893136B0B1C4AD6FDD3D1C8:
<<STDOUT<< uid:u::::1330064952::C8D521DB0F7A7194C2195F532DB175B90C07F4D8::Diederick de Vries (Private Emailbox) <diederick76@gmail.com>:
<<STDOUT<< uat:u::::1330069427::3C5192CC4B5D13E427AFC358526953EAC23B79F3::1 5583:
<<STDOUT<< ssb:u:1024:1:5E48FC06A0E03541:1330064952::::::e::::::
<<STDOUT<< sec:u:2048:1:FBEBBDFA5619404A:1392841618:::u:::escESC::::::
<<STDOUT<< fpr:::::::::D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A:
<<STDOUT<< uid:u::::1392841618::5006AD501F4B77BAEAC7EB7930382DE4A61705E3::Diederick de Vries (Private Emailbox) <diederick@diederickdevries.net>:
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --version
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDOUT<< gpg (GnuPG) 2.1.1
<<STDOUT<< libgcrypt 1.6.2
<<STDOUT<< Copyright (C) 2014 Free Software Foundation, Inc.
<<STDOUT<< License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
<<STDOUT<< This is free software: you are free to change and redistribute it.
<<STDOUT<< There is NO WARRANTY, to the extent permitted by law.
<<STDOUT<<
<<STDOUT<< Home: ~/.gnupg
<<STDOUT<< Supported algorithms:
<<STDOUT<< Pubkey: RSA (1), ELG (16), DSA (17), ECDH (18), ECDSA (19), EDDSA (22)
<<STDOUT<< Cipher: IDEA (S1), 3DES (S2), CAST5 (S3), BLOWFISH (S4), AES (S7),
<<STDOUT<<         AES192 (S8), AES256 (S9), TWOFISH (S10), CAMELLIA128 (S11),
<<STDOUT<<         CAMELLIA192 (S12), CAMELLIA256 (S13)
<<STDOUT<< Hash: SHA1 (H2), RIPEMD160 (H3), SHA256 (H8), SHA384 (H9), SHA512 (H10),
<<STDOUT<<       SHA224 (H11)
<<STDOUT<< Compression: Uncompressed (Z0), ZIP (Z1), ZLIB (Z2), BZIP2 (Z3)
Running gpg --status-fd=2 --passphrase-fd=0 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --detach-sign --armor --local-user D7A5E7B51B689FF33E69C2ADFBEBBDFA5619404A
<<STDOUT<< Sign This!
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STATUS<< [GNUPG:] PROGRESS stdin ? 0 0
<<STATUS<< [GNUPG:] BEGIN_SIGNING H8
<<STATUS<< [GNUPG:] PROGRESS stdin ? 10 0
<<STATUS<< [GNUPG:] PINENTRY_LAUNCHED 9660

**Comment by tfla** [comment]
My output, with most of the STDOUT-lines removed and <id> inserted instead of the actual key id in the gpg commands:
```
mailpile> eventlog/watch
Watching logs: Press CTRL-C to return to the CLI
bg/log(20): http/log(20): Elapsed: 0.000s (output: Set output mode to: html)
54becb55.00011.4a2=SetupCrypto:R setup/crypto: Starting
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys <id> --list-keys <id> --list-keys <id>
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
54becb55.00011.4a2=SetupCrypto:c setup/crypto: Configure crypto preferences
bg/log(20): http/log(20): Elapsed: 0.041s (setup/crypto: Configure crypto preferences)
54becb55.00012.4a2=SetupCrypto:R setup/crypto: Starting
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys <id> --list-keys <id> --list-keys <id>
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
54becb55.00012.4a2=SetupCrypto:c setup/crypto: Configure crypto preferences
bg/log(20): http/log(20): Elapsed: 0.027s (setup/crypto: Configure crypto preferences)
bg/log(20): http://localhost:33411 "GET /setup/crypto/?_path=%2F HTTP/1.1" 200 5749
bg/log(20): http/log(20): Elapsed: 0.001s (output: Set output mode to: css)
54becb55.00014.4a2=JsApi:c jsapi: Generated Javascript API
bg/log(20): http/log(20): Elapsed: 0.002s (jsapi: Generated Javascript API)
bg/log(20): http://localhost:33411 "GET /jsapi/as.css?ts=0.4.0-1421790015 HTTP/1.1" 200 5655
bg/log(20): http/log(20): Elapsed: 0.001s (output: Set output mode to: js)
54becb55.00016.4a2=JsApi:c jsapi: Generated Javascript API
bg/log(20): http/log(20): Elapsed: 0.004s (jsapi: Generated Javascript API)
bg/log(20): http/log(20): Elapsed: 0.001s (output: Set output mode to: setup.js)
54becb55.00018.4a2=JsApi:c jsapi: Generated Javascript API
bg/log(20): http/log(20): Elapsed: 0.018s (jsapi: Generated Javascript API)
bg/log(20): http://localhost:33411 "GET /api/0/jsapi/as.js?ts=0.4.0-1421790015 HTTP/1.1" 200 110345
bg/log(20): http://localhost:33411 "GET /api/0/jsapi/setup.js HTTP/1.1" 200 63857
bg/log(20): http/log(20): Elapsed: 0.000s (output: Set output mode to: json)
54becb60.0001a.4a2=SetupCrypto:R setup/crypto: Starting
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys . --list-secret-keys a --list-secret-keys e --list-secret-keys i --list-secret-keys p --list-secret-keys t --list-secret-keys k
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-secret-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys <id> --list-keys <id> --list-keys <id>
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: Note: '--list-keys' is not considered an option
<<STDERR<< gpg: using PGP trust model
Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --version
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STDOUT<< gpg (GnuPG) 2.1.1
<<STDOUT<< libgcrypt 1.6.2
<<STDOUT<< Copyright (C) 2014 Free Software Foundation, Inc.
<<STDOUT<< License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
<<STDOUT<< This is free software: you are free to change and redistribute it.
<<STDOUT<< There is NO WARRANTY, to the extent permitted by law.
<<STDOUT<<
<<STDOUT<< Home: ~/.gnupg
<<STDOUT<< Supported algorithms:
<<STDOUT<< Pubkey: RSA (1), ELG (16), DSA (17), ECDH (18), ECDSA (19), EDDSA (22)
<<STDOUT<< Cipher: IDEA (S1), 3DES (S2), CAST5 (S3), BLOWFISH (S4), AES (S7),
<<STDOUT<<         AES192 (S8), AES256 (S9), TWOFISH (S10), CAMELLIA128 (S11),
<<STDOUT<<         CAMELLIA192 (S12), CAMELLIA256 (S13)
<<STDOUT<< Hash: SHA1 (H2), RIPEMD160 (H3), SHA256 (H8), SHA384 (H9), SHA512 (H10),
<<STDOUT<<       SHA224 (H11)
<<STDOUT<< Compression: Uncompressed (Z0), ZIP (Z1), ZLIB (Z2), BZIP2 (Z3)
Running gpg --status-fd=2 --passphrase-fd=0 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --detach-sign --armor --local-user C6CE5EFBAFB18D8FF9F2C473F8EF8B11092F4A92
<<STDOUT<< Sign This!
<<STDERR<< gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
<<STATUS<< [GNUPG:] PROGRESS stdin ? 0 0
<<STDERR<< gpg: writing to stdout
<<STATUS<< [GNUPG:] BEGIN_SIGNING H10
<<STATUS<< [GNUPG:] PROGRESS stdin ? 10 0
<<STATUS<< [GNUPG:] PINENTRY_LAUNCHED 1279
<<STDERR<< gpg: signing failed: Operation cancelled
<<STDERR<< gpg: signing failed: Operation cancelled
bg/log(10): http/log(10): setup/crypto error: Invalid passphrase (chosen_key= invalid_passphrase=True)
54becb60.0001a.4a2=SetupCrypto:c setup/crypto: Invalid passphrase
bg/log(20): http/log(20): Elapsed: 0.049s (setup/crypto: Invalid passphrase)
bg/log(20): http://localhost:33411 "POST /api/0/setup/crypto/ HTTP/1.1" 200 2217
  54becb46.0000f.4a2=Watch:c eventlog/watch: That was fun!
Elapsed: 33.175s (eventlog/watch: That was fun!)
```

**Comment by BjarniRunar** [comment]
Ah. GnuPG 2.1. Mailpile only works with 1.4.x at the moment.

This isn't exactly a WONTFIX - I would love to be compatible with GnuPG 2.1. But it's not going to happen right away...

**Comment by BjarniRunar** [comment]
Actually, this is a dup of #1133 ... closing! Thanks for taking the time to debug guys, I will be sure to ask people to check the gpg version earlier in the process next time.

**Comment by diederick76** [comment]
May I suggest changing the name of this issue back? When someone else wants to report this bug, they won't find report, and you'll end up with lots of duplicates.

**Comment by klevin** [comment]
How do I tell mailpile to use a different gpg than the default (i.e. /sbin/gpg1)?
