### ISSUE TITLE
regression: opening a message do no longer mark it as read

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1195]
In web GUI.

That used to work before.

Tested at commit 773e41f6175a6353b4f6a59420a76b94aee6fb5e with Fx 31.3.0 and chrome 33.0

**Comment by BjarniRunar** [comment]
This was a caching bug,should have been fixed by bff0d2ec6cc3c38feb9983b5fc175c796cef6b28
