### ISSUE TITLE
Allow Mailpile to register with OS for opening related files

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1199]
Currently (on Mac OS) if I double click on a `message.eml` file it only gives me the option to open it in MacMail. We should Make Mailpile.app register with the OS as being capable of opening certain mime types.

**Comment by BjarniRunar** [comment]
Good idea, but Mailpile will need to know what to do with such files first. It doesn't at the moment. :)

**Comment by OJFord** [comment]
@BjarniRunar Do you mean that Mailpile doesn't know what to do with <single file>, or that it can't parse `.eml` files specifically?

**Comment by BjarniRunar** [comment]
@OJFord There are a couple of subtleties here. One is that yes, Mailpile doesn't yet have a mode where it simply displays the contents of a .eml file. The other is that generally Mailpile is a long-running background process.

I think a good implementation of this would be a small tool which, when the user attempts to open a .eml file, spawns a new browser tab with a URL to the running Mailpile, that requests Mailpile open and display the file. So this requires adding a new API endpoint for displaying such files, and writing the tool.

This would actually make a pretty good starter project for someone who wants to learn how to add features to Mailpile's API, and this could be done as an external plugin if the implementor wanted to learn about that part of the app. I'm marking as low hanging fruit, and recommend that anyone who takes this on find me on #mailpile on Freenode (IRC).
