### ISSUE TITLE
Recognize when internet connection is dead instead of reporting no encryption keys found

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1201]
I was in the process of composing an email on a machine which was hooked up to a wifi router that, at that moment, did not have a valid internet connection.

I typed the "to" address in, clicked the email address, and then clicked "Find encryption keys". After a minute or so, a dialog box was presented which said "No encryption keys found matching: <the email address.com>"

The actual problem was that the Internet connection was down. Mailpile didn't tell me that it couldn't reach the Internet and thus could not contact the keyserver. Instead, it told me that it didn't find any keys.

It would be great if this error message were more useful (and more accurate).

**Comment by BjarniRunar** [comment]
People always want this. Knowing that an internet connection is down is virtually impossible for a portable user space app (please don't respond with suggestions on how to do this, none of them work reliably - even Google with all their engineers can't get this right and Chrome persists in showing me "no Internet connection" dialogue when actually a site was just slow).

The messages and feedback can certainly be improved though.

**Comment by BjarniRunar** [comment]
Not sure whether to close this as "WONTFIX, IMPOSSIBLE" or rephrase the issue to only cover the feedback part of this problem. :-)

**Comment by miguelbernadi** [comment]
Maybe just display a suggestion to check connection problems if no keys are found. Or a "could not establish connection to keyserver" if it didn't respond. That way message explains what problem has been found and suggests the problem may be in the connection.
