### ISSUE TITLE
UI presented when a contact has multiple keys is not useful

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1203]
When searching for keys for a contact, the UI presented if that user has multiple keys on a keyserver is really, really confusing.

In the attached example, which is a search for Roger Dingledine's keys, the default Mailpile UI shows 4 different keys. As the default view does not include additional information, there is no way for the user to know which one to pick. Is the first one the one that Mailpile thinks is best? How should the user know.

Once the user clicks on the stars to learn more information (something that isn't entirely intuitive), they can then compare the various keys, and try and guess which one is best. In Roger's case, one key has a huge circle of trust and is more recent, but there are no visual cues to let the user know that it is the best of the bunch.

![arma](https://cloud.githubusercontent.com/assets/4551147/5811743/9dc2cfca-a029-11e4-8822-382a44ab6051.png)
![arma-2](https://cloud.githubusercontent.com/assets/4551147/5811742/9dc10dd4-a029-11e4-90f2-77cee5a559dc.png)

**Comment by BjarniRunar** [comment]
You are right, we should probably look at the WoT when ranking keys, even if we don't want to encourage our own users to use it for privacy reasons. Thanks for bringing this to our attention.
