### ISSUE TITLE
Really confusing error when trying to encrypt an email

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1204]
Steps to reproduce:

1. In the compose message window, type in an email address as the recipient
2. Right click on the email address, click find encryption key.
3. Accept the encryption key (such that the drop-down box inside the key window says "use this key")

![got-key](https://cloud.githubusercontent.com/assets/4551147/5817117/647733e4-a076-11e4-89f0-02925b6f82df.png)

4. Back in the main message window, click the lock icon (which is initially open, not closed)

Get the following error, which is odd, because I just added the key.

![still-can-encrypt-to-key](https://cloud.githubusercontent.com/assets/4551147/5817134/941e9ede-a076-11e4-987b-a2b403e6d052.png)

5. Once I've re-added the key, I get the next error, which is just confusing.

![yay](https://cloud.githubusercontent.com/assets/4551147/5817139/9f1abebc-a076-11e4-9159-ff59a44ec1cc.png)

Clicking on the "send encrypted" button does nothing. I can, however, click the send unencrypted window.

Warning: The recipient address has subkeys (valid and expired). Perhaps this is making things worse, I do not know.

**Comment by mad-de** [comment]
Same here - ubuntu 14.10 and Firefox

**Comment by jbreitbart** [comment]
Here as well. Ubuntu 14.04, Chrome 40 beta. Current master head.

**Comment by BjarniRunar** [comment]
Thanks for reporting guys, sorry about the confusion. This is known to be broken due to a lack of plumbing at the back-end for GPG key data. Unfortunately, the UI shipped implying that it works, while in fact it does not.

The bugs to watch is #1123.
