### ISSUE TITLE
Cosmetic issue when adding new contacts

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1205]
See the attached screenshot from a system running a fresh install of Ubuntu 14.10

The email address should all be on one line. There is no need to break it up onto two lines.
![email-address](https://cloud.githubusercontent.com/assets/4551147/5817242/c6679dd6-a077-11e4-9c98-56a371f258bb.png)

**Comment by bnvk** [comment]
@csoghoian that detail card definitely needs some refining, thanks for filing this as a reminder ;)
