### ISSUE TITLE
RawChannel read error (connection broken)

### ISSUE THREAD

**Issue by jbreitbart** [mailpile/Mailpile#1208]
I see the following error message in the command line client. Mailpile is still synchronizing with my gmail account, so my guess is that this message is related to the gmail connection

mailpile> [2944:2979:0121/114612:ERROR:channel.cc(258)] RawChannel read error (connection broken)

I have no idea how to provide further information on that issue.

**Comment by BjarniRunar** [comment]
What operating system is that?  That is not an error message generated by Mailpile itself.

**Comment by jbreitbart** [comment]
Ubuntu 14.04
