### ISSUE TITLE
^C Does not Kill Mailpile Process

### ISSUE THREAD

**Issue by FutariEcchi** [mailpile/Mailpile#1209]
Starting mailpile with `./mp www`, but not working so i pressed ^C, several time but mp process doesn't killed. Can only killed with sigkill (9).

**Comment by BjarniRunar** [comment]
That is not a valid way to start Mailpile anyway.

You're not the first to report problems doing this - where are people getting this idea from, is it on some wiki somewhere or something?

Some examples of valid ways to start Mailpile:

    ./mp
    ./mp --www --wait
    ./mp --www=0.0.0.0:12345 --interact

**Comment by jbreitbart** [comment]
https://github.com/mailpile/Mailpile/wiki/Using-the-Web-Interface

**Comment by BjarniRunar** [comment]
Thank you!  Fixed that page.
