### ISSUE TITLE
Could not connect, http server not started?

### ISSUE THREAD

**Issue by FutariEcchi** [mailpile/Mailpile#1210]
Started mailpile with `./mp www`, it says `OK: Started the web server on http://localhost:33411` but that address clould not be accessed from firefox or curl. 

Netstat doesn't show if that port is opened/serving.

**Comment by ardoster** [comment]
Have you tried to access locally or externally? By default, Mailpile is only accessible in local. You can test is for example doing a wget http://localhost:33411 and you should get the Mailpile index.html content.

Check this web to configure Mailpile and access it externally. https://www.bentasker.co.uk/documentation/linux/294-installing-mailpile-on-centos-6

**Comment by BjarniRunar** [comment]
As mentioned in #1209, this is the wrong way to launch Mailpile. See the other issue for instructions on how it's actually done. :)
