### ISSUE TITLE
Slow IMAP sync - No IMAP folders status sync

### ISSUE THREAD

**Issue by Krishath** [mailpile/Mailpile#1211]
As the title says, the IMAP sync is very slow (I'm using GMail's servers). Furthermore I see each mail as unread when it is.

**Comment by BjarniRunar** [comment]
My tests (also using GMail's servers) show that the bottleneck for mail syncing is now actually the time it takes for Python to read all your mail and update the search index. So this is not an IMAP issue, this is a matter of how fast we can update the search engine and improving that is a long term project. This will indeed feel slow to folks that are used to mail clients that just download the headers and do nothing else.

The other issue is just a known bug. :-)

Both are known and being tracked elsewhere, so I am closing this bug. But thank you for taking the time to file it.
