### ISSUE TITLE
Add Google Contacts sync

### ISSUE THREAD

**Issue by peperunas** [mailpile/Mailpile#1212]
That would be great having a plugin which imports every contact in a Google account.

**Comment by BjarniRunar** [comment]
Agreed. This is probably a prime candidate for exploring the GMail API (see issue #741).

Sample code which imports other types of contact details can be found in `mailpile/plugins/vcard_*.py`.

**Comment by Epse** [comment]
This would require  a maintainer to register Mailpile as a google application as documented in the API docs. Someone else can write the code using testing apps, but the token would have to be added in later.
