### ISSUE TITLE
Import and use a new private GPG key

### ISSUE THREAD

**Issue by Krishath** [mailpile/Mailpile#1213]
I already use a GPG key and, if I'm not wrong, it is not possible to import and use my "old" key instead of the new one created while installing MailPile. I think this is a key feature.

**Comment by jgonsior** [comment]
+1

**Comment by BjarniRunar** [comment]
For most advanced keychain manipulation operations, we do not envision adding a UI to Mailpile in the near term. Advanced GPG users can just use GPG directly.

Mailpile can be configured to use any key on your chain, improving the UX of this is far as I feel we should go on this issue. Otherwise we're just duplicating low level functionality that is already well understood and well documented elsewhere.

**Comment by gjedeer** [comment]
I just updated my Mailpile installation and, for a fresh start, removed ~/.local/share/Mailpile.

In the /setup/crypto/ screen I'm prompted to select my PGP key but out of the 3 private keys found by gpg --list-secret-keys, it only found one (and, unfortunately, the only irrelevant one).

**Comment by bnvk** [comment]
@gjedeer when does the key that you want to have show up expire? I believe currently keys that expire in less than 1 year do not show up due to a recent change we made

**Comment by gjedeer** [comment]
The key expires this year, that's confusing as hell. I've patched your
source to remove that constraint, removed Mailpile dir and it
works as expected now.

**Comment by Robsteranium** [comment]
Also hit this problem. Indeed it's not obvious why certain secret keys aren't available for selection.

See also #1238.

**Comment by maysara** [comment]
Regarding the original issue, I do not mind changing the key manually directly using gpg ; but it would be great if instructions/pointers are shared; I assume that all messages and configurations are encrypted using the mailpile key (i'll call it old key, from mp perspective), so i need to decrypt it all and re-encrypt it using the "new" key, right? ... well , how ?

**Comment by BjarniRunar** [comment]
@maysara If the code were stable enough for me to spend time documenting such details... then we would be in a good place indeed. :-)

That said, this stuff may improve with some of the setup-related work I am doing for Beta III. Fingers crossed!

**Comment by BjarniRunar** [comment]
Importing keys and creating new ones is now possible during account setup. The avoiding-soon-to-expire keys code is disabled for now.

Further configuration options will follow, but the basic use case in this issue are now handled. Thanks for filing!
