### ISSUE TITLE
Mail import does not show progress

### ISSUE THREAD

**Issue by jdhoek** [mailpile/Mailpile#1215]
During the e-mail import, there appears to be no feedback on the progress:

![mailimport](https://cloud.githubusercontent.com/assets/683699/5859225/00a74a04-a259-11e4-8d29-81207d7b0cc7.png)

Is the `Copying [LIVE DATA] Mail` text a place-holder in Beta II?

**Comment by BjarniRunar** [comment]
It is indeed. Progress is show on the mail sources view, but that only recently became nice enough that it's worth the effort to plumb it into the import page. So yes, it's a placeholder at the moment!
