### ISSUE TITLE
Can't create passphrase after setup

### ISSUE THREAD

**Issue by lucafaggianelli** [mailpile/Mailpile#1216]
When submitting the form for creating the passphrase after MP setup i get this error in the JS console:
Cannot read property 'invalid_passphrase' of undefined.
File: /mailpile/www/default/html/jsapi/setup/passphrase.js:83

**Comment by jschaul** [comment]
I'm experiencing the same issue. Running a fresh install of mailpile (latest master, git sha `a844ccc79395aaf3f9d363da7bd54d538059feab` on a raspberry pi. Here is a stack trace:

```bg/log(50): POST: /api/0/setup/crypto/ qs = {} post = {'choose_key': ['!CREATE'], 'passphrase_confirm': REMOVED, 'passphrase': REMOVED}
bg/log(20): Elapsed: 0.007s (output: Set output mode to: json)
54c17cbe.0004e.1bae=SetupCrypto:R setup/crypto: Starting
bg/log(50): Logged in xSLQtg_2rELQ3_MvISiZ-DytEpk as DEFAULT
bg/log(50): Traceback (most recent call last):
  File "/home/pi/mailpile/mailpile/commands.py", line 564, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/pi/mailpile/mailpile/commands.py", line 562, in command
    return self.command(*args, **kwargs)
  File "/home/pi/mailpile/mailpile/plugins/setup_magic.py", line 365, in command
    return self.setup_command(session, *args, **kwargs)
  File "/home/pi/mailpile/mailpile/plugins/setup_magic.py", line 662, in setup_command
    session.config.prefs.gpg_recipient = choose_key
  File "/home/pi/mailpile/mailpile/config.py", line 805, in __setattr__
    self.__setitem__(attr, value)
  File "/home/pi/mailpile/mailpile/config.py", line 851, in __setitem__
    ) % (self._name, key, value))
ValueError: Invalid value for config/prefs/gpg_recipient: !CREATE

bg/log(10): setup/crypto error: Failed: setup/crypto 
54c17cbe.0004e.1bae=SetupCrypto:c setup/crypto: Failed: setup/crypto 
bg/log(20): Elapsed: 0.165s (setup/crypto: Failed: setup/crypto )
bg/log(20): http://192.168.178.32:33411 "POST /api/0/setup/crypto/ HTTP/1.1" 200 452
```

**Comment by BjarniRunar** [comment]
Just to clarify, you said *after MP setup*. Does that mean you are trying to change your password using the Mailpile UI later on?

I don't know if that works, I strongly suspect it does not. We should probably tweak the UI to not falsely imply that it does (cc @bnvk).

**Comment by yastupin** [comment]
I'm experiencing the same error here, *during* setup. (head is 6d0f270759fbba9b5746fa095026c4c9a38269d4)

**Comment by lucafaggianelli** [comment]
During setup, when the Ui asks to pick a password. I'm not changing the
password....

**Comment by jschaul** [comment]
@BjarniRunar : The issue does not appear on the release/beta, but it does appear on the current master.

It is a direct consequence of commit 25b12e000afb2bdcce26586a80ff1a6cc2ad5062: This commit restricts configuration values for `gpg_recipient` to have to adhere to `gpgkeyid` instead of simple string. This however causes an error when trying to set the `gpg_recipient` value to `!CREATE` in the setup_magic (/home/pi/mailpile/mailpile/plugins/setup_magic.py", line 662). 

The exact issue happens when a new user without a gpg key follows the user setup in the browser for the first time.

**Comment by BjarniRunar** [comment]
jschaul: The !CREATE thing is a very silly mistake on my part (scrambling to revert now), but most of the reports on this thread predate that bug. I worry this issue is now very muddled. I'll run some more tests at my end and ping folks once I've fixed the things I know to be broken.

**Comment by BjarniRunar** [comment]
This part of the UI no longer exists, closing this issue. Thank you for filing. :-)
