### ISSUE TITLE
Add method to feed a URL to import a PGP Key

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1225]
Often times people keep their PGP listed on their website with a link provided such as [My PGP Key:  01AE EADB 9EED](https://brennannovak.com/uploads/security/brennan-novak-public-key.asc)

Of course, this is not that helpful to a user until one is learned in the ways of PGP and knows what to do with that. While we can't make people smarter, we can try to make this process easier. 

Looking at the current flow with a URL:
- Click on link to key (sometimes, but rarely, this forces an auto download)
- Or some people know how to right-click and save to download URL
- Copy text from key URL
- Open a blank text file
- Paste key into text file
- Then import file into PGP key app

This above flow would be possible once #1142 is finished. I propose adding a simple method that shortens this process to:
- Copy URL of page (with key)
- Paste into Mailpile modal and submit form
- Done

Of course, adding a little helper that explains this URL procedure slightly is needed.

**Comment by BjarniRunar** [comment]
I agree, it would be good to be able to download keys directly from URLs.

I'll look into where this sort of thing fits into the backend API. Had you thought about where you wanted this presented to the user?

**Comment by BjarniRunar** [comment]
Added this in one place. You can now post on or more key_url=... requests to /api/0/crypto/gpg/importkey/.

Might want to also add to the keyimport search method, depending on where in the UI you would like to do this. Being able to query arbitrary URL would allow for interacting with HTTP key search engines, so that might be worth implementing even if the current use case does not call for it.

Thoughts?

**Comment by bnvk** [comment]
Yah, I coded in a stub for this feature in the **"Import Encryption Key"** dropdown which is accessed on the `/contacts/`part of the app.

![screen shot 2015-01-27 at 9 13 15 am](https://cloud.githubusercontent.com/assets/48677/5915340/f1677c3a-a604-11e4-8160-302a2a37d574.png)

I'm thinking of that as the catch-all UI location for importing keys. All the other "hooks" i'm using like on a users Profile (vcard) page, in a message thread, already have a value (e.g. email address) ready to submit. However, we could offer this in a few other places:

* If a Contact's vcard has a URL show a button "Look for encryption keys on website" 
* In the main topbar search field, make the currently working `keys: domain.com/key.asc` accept URL as well as name, email, etc...

As per your question "Might want to also add to the keyimport search method..." I don't think I understand what you're asking unless I just answered it in the above two bullet points!

**Comment by bnvk** [comment]
Oh and @BjarniRunar down the line, adding support for [microformats u-key](http://microformats.org/wiki/u-key) style parsing would be super as one of the things that came up in user studies with GusGus was when she said "send encrypted email to Smari" a couple users found themselves at Smari's website staring at the links to his PGP keys. Ideally, we people hosting their keys to add the markup class and then voila, even just pasting `domain.com` properly finds and imports key correctly! I know, pipe dream... but one can dream!

**Comment by ClashTheBunny** [comment]
It would also be really nice if there were just a "paste in key" option.  Something that hand a big empty text box where you could copy-pasta the key from wherever it didn't download.  Maybe put it in another tab of a dialog?
