### ISSUE TITLE
Add method to copy-paste ASCII armor to import a PGP Key

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1226]
Similar to #1225 and #1142, we should allow copy-paste to import a PGP key.

If I am looking at the key on the web, copying the key is a far more natural action than copying the URL of the page, and key data may come from other random sources as well - e.g. the text part of an e-mail that isn't being read via. Mailpile.

This is already well supported by the back-end. :-)

**Comment by bnvk** [comment]
@BjarniRunar I absolutely agree with a place to just "paste key data" makes a lot of sense and should be implemented regardless. Easiest solution is add an item to the dropdown like **"Paste Encryption Key"** to that same location as URL import:

![screen shot 2015-01-27 at 9 13 15 am](https://cloud.githubusercontent.com/assets/48677/5915340/f1677c3a-a604-11e4-8160-302a2a37d574.png)

This should be super simple to implement. If I remember correctly, the backend is working for this as per #647 which I tinkered with back in October.

I don't agree copying the text is necessarily more natural than a URL. Some people are quite comfortable copy + pasting URLs, e.g. people share URLs on social media sites all the time, whereas ASCI armor & key data look very foreign and kind scary- i'm going off my memory & reaction the first many times I saw a raw PGP key, and I can only assume to non-programmers find it even more scary. Of course, people who attend crypto parties are a different case.



Relates to #912

**Comment by BjarniRunar** [comment]
All depends on the user I guess!

If I see the key in front of me, copying what I see seems relatively intuitive. Understanding URLs and the abstraction they imply is actually more advanced. It comes naturally to web developer of course (you being a prime example), and is obviously both easier to copy or transcribe (less data), but the general public is increasingly not very aware of URLs at all, to the point that many browsers these days (in particular mobile browsers) hide it completely.

It was only yesterday that a relatively internet savvy user sent me over Jabber some weird link to Facebook, that then redirected to the page he wanted to show me. Turns out he clicked some "share" button and followed the instructions, because he didn't think to just copy the URL directly from the location bar. This from a user advanced enough to use Jabber! So you'd be surprised, I think. :-)

Not that it matters, since we can easily cater to both crowds. Glad you like the idea!
