### ISSUE TITLE
Fix Mailpile Contacts / VCards

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1228]
Mailpile contacts and the internal VCards have the following problems:
- Loading of VCards is currently very slow. They are encrypted anyway, so switching to a more efficient storage format won't reduce compatibility in any meaningful way.
- The merge algorithm (which merges data from gpg or gravatar) is buggy.
- Cards do not update promptly when things like the GPG keychain change, in particular leading to abysmal user experience when importing keys.
- It needs to be possible for a user to edit a card, without the merge/import jobs overwriting his or her changes. In particular, deleting of lines (actually, disabling), editing (overriding the imported data) and specifying preferences must be possible and respected by the import merger.
- It needs to be possible to download contact information as a VCard, either for one contact at a time, or in batches for groups or the entire address book for various export/interop scenarios.

**Comment by malexmave** [comment]
Regarding the storage format, I've had some positive experiences with [Protocol Buffers](https://developers.google.com/protocol-buffers/), which could probably be used for this. However, it *would* add another dependency, as the python version of protobuf-generated code is not self-contained but depends on the library being installed.

**Comment by miguelbernadi** [comment]
If you look at Protocol Buffers, also consider Cap'n'proto. Same designer, intended to be even faster and more efficient but it's still a WIP (beta).

**Comment by BjarniRunar** [comment]
I think our current contacts are "good enough" for the first release. This will be revisited, but bumping from the 1.0 milestone.
