### ISSUE TITLE
provide a docker image to have mailpile up and running

### ISSUE THREAD

**Issue by opensas** [mailpile/Mailpile#1229]
warning: complete docker newbie talking...

I was thinking that it would be great to have mailpile up and running with just a docker command, telling where is the folder with the data, and the port to expose. Like I said, I'm no docker expert, but I think it's feasible, and it would be a very comfortable way to deploy it.

**Comment by bnvk** [comment]
@opensas there is a `Dockerfile` in the repo. None of us core devs use Docker, so the degree to how easy it is to get Mailpile up and running using this file is untested / might chance due to Docker evolving. Please give it a try and report back.

**Comment by szymonszydelko** [comment]
Huh, it seems to be working pretty ok. This was sent from inside of dockerized mailpile.

![selection_002](https://cloud.githubusercontent.com/assets/3144357/6543794/7a367a98-c52c-11e4-9e2f-f6157e413fd6.png)
