### ISSUE TITLE
mailpile is "killed"

### ISSUE THREAD

**Issue by erutique** [mailpile/Mailpile#1232]
I am running mailpile on Debian 7 under non-root user by ```./mp```

If i do not log in on the web, the server will not begin to sync and everything seems good.

But if i do, the server will begin to sync and the service will crash after a while (maybe 30min).
And if I restart mailpile. some recent synced mails are lost (syncing over IMAP + no downloading). 

The cmd shows 

```
mailpile@:~/Mailpile$ ./mp
Failed to decrypt configuration, please log in!
Mailpile.py          a tool                 Copyright 2013-2014, Mailpile ehf
               for searching and                   <https://www.mailpile.is/>
           organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation or the Apache License 2.0 as published by the Apache
Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>
   * You can log in using the `login` command.

mailpile>

mailpile> Killed
mailpile@:~/Mailpile$ 
```

**Comment by gamag** [comment]
Mailpile can use quite a lot of RAM when syncing. I tried to run in on a machine with 250MB. While this was possible without syncing, when it started downloading mail, the memory would fill up quite fast. This can be a reason for it being killed by the operating system...

**Comment by erutique** [comment]
Got it.

I am running it on a 128M VPS
