### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by exoteric** [mailpile/Mailpile#1233]
Right now, to mark all messages in a folder as read it is necessary to (as far as I can tell):

0) select folder
1) select unread
2) mark all
3) select read
4) refresh page
5) goto 1

A better approach would be

1) right click on folder
2) select mark all as read

:-)

**Comment by BjarniRunar** [comment]
This is more or less a dup of #1027 - the solution you propose is different, but it's the same problem.
