### ISSUE TITLE
HTTPS for remote servers

### ISSUE THREAD

**Issue by jfreak53** [mailpile/Mailpile#1235]
I'm finding a problem and not finding any documentation on it anywhere. How do I get mailpile to run over HTTPS with a self-signed cert? I don't use it on a local machine, the whole point is having it available. I have it hosting on a VPS on one of my nodes. So it would make sense if I could access it over SSL, but I'm not finding an option for this. Did I miss something?

**Comment by BjarniRunar** [comment]
At the moment, I do not recommend exposing Mailpile directly to the wider Internet.

Putting it behind a security-mindful reverse proxy (I like Pound) will add an important layer of protection. That proxy then handles the SSL. A slightly more geeky solution which also provides strong security is to use SSH tunneling from your desktop to the VPS.

We have not decided what our long-term solution is for this use-case. On Linux, making something like Pound a dependency is not a problem and is going to be the best overall technical solution. For desktop (win/mac) installations that people still want remote access to, we may need to bundle something ourselves.

**Comment by rpadovani** [comment]
Just a witness.
I configured Apache to work as Reverse Proxy, it's easy and doesn't require too much work.
Of course you have to enable right plugins (mod_ssl and mod_proxy IIRC).

Why Apache and not ngix? Because I already use apache for other services :-)

Anyway, this is my conf, hope could be useful.

```

<IfModule mod_ssl.c>
	<VirtualHost *:80>
   		ServerName webmail.rpadovani.com
   		Redirect permanent / https://webmail.rpadovani.com/
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName webmail.rpadovani.com

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		SSLEngine on
		SSLCertificateFile	/etc/apache2/ssl/mailpile.crt
		SSLCertificateKeyFile /etc/apache2/ssl/mailpile.key

		ProxyPass / http://localhost:33411/

		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

	</VirtualHost>
</IfModule>

```

**Comment by BjarniRunar** [comment]
Update: I am working on native HTTPS support in Mailpile's httpd. It will know how to generate a self-signed cert or use an existing one. Letsencrypt support and some other niceities are planned as well.
