### ISSUE TITLE
Mailpile does not properly recognize GPG key expiration dates in the future

### ISSUE THREAD

**Issue by necopinus** [mailpile/Mailpile#1238]
Steps to reproduce:

1. Create a new GPG key, and set it's expiration date for 11 month in the future (so, if today's 2015-02-03, set the key expiration to 2016-01-03).
2. Start up a fresh install of Mailpile Beta II (2014-01-24 release) on Mac OS 10.10.2.
3. Notice that your key is not available for use.
4. Shut down Mailpile and clear out relevant data directories.
5. Change the expiration date of your key and subkey to 13 months in the future (so, if today's 2015-02-03, use 2016-03-03).
6. Start up Mailpile again.
7. Notice that your key is now available for use.

I haven't tested out 100% of the cases here, but it looks like Mailpile may not be looking at the *year* a given key expires, only the month and day.

**Comment by BjarniRunar** [comment]
This is a recent attempt to evaluate how good keys are and avoid using ones that expire in the near future. I may well have chosen a date that is too far out, a full year is indeed a bit much. I'll push up a fix with a less aggressive cut-off point later today. Thanks for filing and tracking things down!

**Comment by Robsteranium** [comment]
I would actually suggest that Mailpile should not prevent the use of certain keys. Indeed, as I understand it, it's [good practice to have short-lived keys](https://help.riseup.net/en/security/message-security/openpgp/best-practices#use-an-expiration-date-less-than-two-years). Further, not displaying these keys for selection (without explanation) is pretty confusing.

Instead I would recommend that this judgement be left to the user. The interface should show all keys, perhaps with a "warning this key will expire in 2 months". Indeed if that is the intention then perhaps the warning would be better shown in the inbox UI, not the only during setup "don't forget your key expires next month and you've not yet added a replacement".

**Comment by BjarniRunar** [comment]
This code has been removed for now and the issue will be handled differently when a 2nd attempt is made to avoid soon-to-expire keys.
