### ISSUE TITLE
Save Security Setting fails

### ISSUE THREAD

**Issue by puggan** [mailpile/Mailpile#1240]
After entering the password in the "Save Security Setting", nothing happens, and if I open the console i can see 2 error messages:

POST http://localhost:33411/api/0/setup/crypto/ 500 OK Internal error
"NetworkError: 500 OK - http://localhost:33411/api/0/setup/crypto/"
Oops, an AJAX call returned as error :(
status: error method: POST base_url: /api command: /0/setup/crypto/
Object { readyState=4, responseText="Internal error", status=500, more...}

TypeError: text is undefined
text.replace(matcher,function(match,esca...
libraries.min.js (line 1, col 21237)

Can't find a version number, but
Installed by gentto "mail-client/mailpile-9999", using git, at 2015-02-03 01:47 CET

**Comment by bnvk** [comment]
This is a duplicate of #1044 sorry for the trouble and confusion. Thanks for filing the issue though ;)
