### ISSUE TITLE
Fail to download attachment

### ISSUE THREAD

**Issue by puggan** [mailpile/Mailpile#1241]
Sent a encrypted message to my gmail.
gmail shows it as an attatchment.
I forward it to my other account and recives it in mailpile.

The hover says the file is 6kB, but when I click it, i get a 12 bytes file.

It would be nice if I get the hole file if I download it, and even better if mailpile notice it's an encrypted message, and can decrypt it and view it in the webbrower.

**Comment by puggan** [comment]
Return-Path: <srs0=7w4i=cw=gmail.com=puggan@puggan.com>
X-Original-To: pgp@puggan.com
Delivered-To: pgp@puggan.com
Received-SPF: Pass (sender SPF authorized) identity=mailfrom; client-ip=209.85.220.174; helo=mail-vc0-f174.google.com; envelope-from=puggan@gmail.com; receiver=pgp@puggan.com
Received: from mail-vc0-f174.google.com (mail-vc0-f174.google.com [209.85.220.174])
	(using TLSv1 with cipher ECDHE-RSA-RC4-SHA (128/128 bits))
	(Client CN "smtp.gmail.com", Issuer "Google Internet Authority G2" (verified OK))
	by chi.puggan.se (Postfix) with ESMTPS id 501502C86C6
	for <pgp@puggan.com>; Wed,  4 Feb 2015 20:51:58 +0100 (CET)
Received: by mail-vc0-f174.google.com with SMTP id le20so1295926vcb.5
        for <pgp@puggan.com>; Wed, 04 Feb 2015 11:51:57 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:sender:in-reply-to:references:date:message-id:subject
         :from:to:content-type;
        bh=/NTaxpD+wXzLAdkCV1ZNcf2+1VLTyeShTvf1w1pawAM=;
        b=scOmQEHAoFE2elov2KzBR0zQ7kdOBovvjNNvDXA6XTOFjowpLBJ95LNJDfx5Ri+3Bv
         ST0V8MbvWpenm5nMnHlytDXkeSMAvmTxNr8sseGRKZJ22BvIMoHUIH2q1MsjA2EIP44J
         h5PoTiPows4YmApFngsI+Zf4PeXvnhAl5C8xQnBW5Knn+I6KxIWxqbJNPltTW2jFq2o1
         jhRo6CfmebYB0Zf0CMVjTvdIHfD6vb7p9Yc7FKs9VJlKnci3XZFsnnt1oBHqhoD/0y+P
         T+/U9WN399UEEqolH6vzWXqMNSTJ+8VioFnfSMsCRs7uDUtan6mSEl/Hj9tVBfaP7063
         08mg==
MIME-Version: 1.0
X-Received: by 10.52.87.209 with SMTP id ba17mr24062vdb.28.1423079516996; Wed,
 04 Feb 2015 11:51:56 -0800 (PST)
Sender: puggan@gmail.com
Received: by 10.52.84.231 with HTTP; Wed, 4 Feb 2015 11:51:56 -0800 (PST)
In-Reply-To: <20150204194234-3726-64385-mailpile@asuna>
References: <20150204194234-3726-64385-mailpile@asuna>
Date: Wed, 4 Feb 2015 20:51:56 +0100
X-Google-Sender-Auth: 3FHEHpseuFmMOmpj8FGf0fDahK4
Message-ID: <CAFF8RwU5+BUwL1_5-i=3oKy=P9xyoYJB3NHi9gxCTkFGiaL5Tw@mail.gmail.com>
Subject: Fwd: test enc+sign from pug to ifw
From: Puggan <puggan@puggan.se>
To: pgp@puggan.com
Content-Type: multipart/mixed; boundary=bcaec50407fe19246a050e488595

--bcaec50407fe19246a050e488595
Content-Type: multipart/alternative; boundary=bcaec50407fe192466050e488593

--bcaec50407fe192466050e488593
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Fick n=C3=A5got krypterat...

--

Thorbj=C3=B6rn 'Puggan' Backlund
Sweden

---------- Forwarded message ----------
From: Puggan <puggan@puggan.se>
Date: 2015-02-04 20:42 GMT+01:00
Subject: test enc+sign from pug to ifw
To: Thorbj=C3=B6rn 'Puggan' Backlund <thorbjorn.backlund@interfaceways.se>

--bcaec50407fe192466050e488593
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Fick n=C3=A5got krypterat...<br clear=3D"all"><div><div><d=
iv class=3D"gmail_signature"><div dir=3D"ltr"><div><div dir=3D"ltr"><br>--<=
br><br>Thorbj=C3=B6rn &#39;Puggan&#39; Backlund<br></div><div>Sweden<br></d=
iv></div></div></div></div>
<br><div class=3D"gmail_quote">---------- Forwarded message ----------<br>F=
rom: <b class=3D"gmail_sendername">Puggan</b> <span dir=3D"ltr">&lt;<a href=
=3D"mailto:puggan@puggan.se">puggan@puggan.se</a>&gt;</span><br>Date: 2015-=
02-04 20:42 GMT+01:00<br>Subject: test enc+sign from pug to ifw<br>To: Thor=
bj=C3=B6rn &#39;Puggan&#39; Backlund &lt;<a href=3D"mailto:thorbjorn.backlu=
nd@interfaceways.se">thorbjorn.backlund@interfaceways.se</a>&gt;<br><br><br=
></div><br></div></div>

--bcaec50407fe192466050e488593--
--bcaec50407fe19246a050e488595
Content-Type: application/pgp-encrypted
Content-Disposition: attachment
Content-Transfer-Encoding: base64
X-Attachment-Id: 59e0d2755e784fbc_0.0

VmVyc2lvbjogMQ0K
--bcaec50407fe19246a050e488595
Content-Type: application/octet-stream; name="msg.asc"
Content-Disposition: attachment; filename="msg.asc"
Content-Transfer-Encoding: base64
X-Attachment-Id: 59e0d2755e784fbc_0.1

LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tDQpWZXJzaW9uOiBHbnVQRyB2Mg0KDQpoUUlNQXpW
anFaNHFzNnlnQVEvL2NVQW1mMFFicy9ZZUlwNmJQbnVwNk9EbVozUytKM2NaY1YwVjYvYkxGelFs
DQpGcXRXeThmdFZtaWNFS3ZWSEF3MDRRZ3pnTWc2TEI0emxSSnVCaWlTa2JsVmV3RWtocklxVVdp
VHh4OFR6K3RYDQpXVG1rM3VKRGlKWjQ5UTI3aWFseHMzQXM4Mk9QYldrRVJQd1BRUElFVldwWlBv
RnRoRTRBOS9vNVplRlhRdXpODQpUMkJoZW1WaGN5QmpYQmhZVEhaQlpjRWRzZWp1dEdWVCt6TGhS
dllscklyL2lrbmhEcnZhNzBVWEQ2WHNyRXJDDQp1Y3QxOENUb0pYMjZ1MlBSVTRHUHdNZ0dJVVBO
VVdBUFNQMU1QQ2hIdzZkS2VValNDZmtmazF3cjhqandHYi9mDQpsZ1RCZ05oVGlrMmxkYnVwa21E
U2lzRGx3YStuZlpCOGhMK1NaODVPT2N4YWNQUWJjazhwTldwK1U0TWl2bmZRDQoxV2kvMWFuYjJN
dUltcTR6djFKc05Cb2VmUXRIWGhqdFFlZWdyQm1Gb2R4WE1PR3JZaFMrKzh0VHYzUlFuZmhXDQpO
Y1dVRmhKTTh4VmZwdkxSbkd2dTdmK3I5c0NHeVkwNWU2QktWaS91V2VSVWhvcitLVnJuNHZlYXBL
Q1M1UUw4DQp0U2lBTEFCRFc3RVVwclcwZCt4WWJRZlNPOEF5dFZVdXA3Um5aR1VodWlTWWZ2NW8w
SG9PN0ZQa2NWM2JRTE1jDQo3QXRjYzRvTVJ3eGJacjFrcThvOGo4TERGNTIyRHo5UXdYMHFPWFJs
WlZNN29MSTJETlNVN1g1cFJZUUg1NEpiDQprYWJlaFUzcG83U2E2SFZtWVR0b1FoeHFheFlSbEM5
SFAweWJrNXFCRjlSWi90OUhQY0NYREZ4dU1GVml4R3lGDQpBZzREQkt4clJ4Z1ZsZDBRQi85TWhO
b0p1b1pMOEVnd3cvejNITndNdW8rSUtaYThoNVhabTNSVnB0SEZoSE9RDQoyV3dJTGFUa3E4T1du
ek04VEdrMlBkR1BoNUZ3RTkrTG84czJyem10SXBkbUFXTWg2ZjlvQTJPS1BvTkZlZEM0DQp4UEpi
ZVVjaEhLQ2VsaVhhNmhTRmFDLzBuUGMvSkprUjhxbGJTYzRZd0FhUmFuanFaYUZrWmt2SCs2Ymho
Ryt3DQpoc1JuNmpQZlhVU2ppaTJFZnhOdUowWVQrRTV4Z01OcllwSmt2NnhRaXRGM3d2Z0FvQitJ
R1I2bnZyazhuMVNEDQo4R3l5OG9KNE0vMHhRYjBZc1lFVytWTVlicVpnMUFZMlZzUHFObis4NmRK
SlhURTVDMEFMQjZ4MHB4cHVZanJvDQoyNTdaOWk0eEJxelJxVkhiTkNYNGExM2dPdHhycEZjcFU2
dGJtUXJiQ0FDVWlXMzlqM05pSWFqWlRIOWF6N3dXDQppQWFENnp5Z1lQUzlZWmFTNFlMeGhnTEQ5
RGVzaGJ2TUU3cGt6VnZPcVUrWWNXM0s4WEs3YXdQT1lWcmJ3YUZrDQpSR0I3QzhKMmNmY1hTTVV4
M3RBNEIwUkhWQ3pIRCtrdDgrVDE0T1pzaW5kTWE5Z1hIRWNIWlZiakFwb3QxbVdvDQpRK24rTXMy
OEp6aVUrSnhOSWk1QmdSYXNRd2tVR1hZOTVoMzNhRGthYWpXL0hJelltZHU3OUhLalZzWnJKRGlX
DQo1eEYxWGRTSzdKQVk2MDd0QkQxSFRieTcrVlhWT3RTdS9MNERjSUJSUG4wamNYSGVjM0tGNG1a
eFlNQ0FKZ3ZYDQpXdjkybW9ZVzNyY2ZxV1VqQ0VsMHJrWjBJSytORXF4NlRWVXR6YjgxVHRVVW94
cWJGbWtlMmpTTjV3QzVsd1FODQowdXNCZCtPdHBPQ0Z4czFNRk94K2w5dXM2dWdHbFMwL0V4YUYx
STIzTTVxN29ieWtsNnNLZ21kejJwTzU2VjJ0DQowOE9ua3RiS0dkVlRCaVdkRHBIRnI5UXdNc2pY
eU0waEk3OTF4UzJWU2dlY0lpcTljR3NpZzdqSlZ6RERma0kvDQo5QUQ4a25kdVJkazJWRHMwVEN5
NmEwWDRSeE1rTGtoRU9NajIyVW0wUEZWVmpQcHJEVEFJdU8vRjdpYUtMZGxRDQpGYTRQcEFkN3gy
QThkSXYxa085akYzME1XVnBaUFZ1Vnc0RUYzMUtON0lBVTM5dEw3Z21Rb3JHZi9yQ0xlSlFZDQps
NDZCUzNvYTc3enE4di8zYVdRTGZGM3ZjR1orZGVEY3ZDaHVEbGVMeUJxd3BVRkZ5aTZya3lzUXlF
MWpRYUhhDQpEdG45dkY2VUtqM3hseWJuVkFPTS94ei9waXF2K041Zi9BUm9ja1ZXeUo1cDRkUGw1
OW1vazNXdzRWejdzVnB6DQpJU1drQXZHZU5vMGFLMXBmZ0E1L3BNb0JMeXRMemNMVjNYWW85eE52
NXFRcGZDdDlBNTMxNXJtNWcrWXhOa05BDQpvSVhwWC9VTGt0bHBvemlvUUxxWkNuV084cEpvdk0w
dkg5R3BEMHlNaFloU2V6SGIzT1NncUIxYkhtc3JHRlJtDQpjdDlrUEQ4RWE3RS9NeG1PZVJhVm9Z
bzlLZDhGUUFDaVBoZnZuY2creGpPdTI4NWhKTXE1SXNtK0ppNEZUSjVBDQpWTGkzbzNPTWN2WGhQ
NElaSm9yN0NCNzJmWUpzNjRiY1NkWGNkSkF3TGk1YUpSSVZJUDR0VGZvVm5JenorSDExDQo1Ykk3
SnVjRnltVXYrNDYyR1NwY2NpcDMrTUd5OTgvbFdUT3ZmeU1hUHYyeERaQ3JvRU9tMUMzRjA5K3Rq
dHpRDQozdnJQcVkyMmZ4WVFmM2ZEUG9oZkpvU21SVGJmTzBnZjFDdU1VWmRwR2Z4aDBoS2hNOTNT
TlpQL2NFL21CNmF6DQpmYnptb1J1MlQ5Yk9wZkNnRnMvdjJkR29JMmlzdllqQ3JUOFFQd2pMbUlo
cnVNVDdvbXhtcGNObEJFTHpuSDJKDQpub1BpUnRSc3F5djhuRGcvdXpsR0Q2eTlnWWtBa3Nzb1oz
ZVdpM2ppcUppZ0NwOVQwRjNJWTRkektGSW9MaTg3DQpTVHB5bnkwcEtLbXZDNFdDK0MrWU9hZWJt
dDdGMmVsL0lDNnh4Ung4MkJxdmcvSWdpcjMzZnVsMXFCTDAwREdTDQpSdTBuVnFoUjlZdzhTa1k3
WlpXdlE5VEwxc2Jyb3RZeURnVEExdGFyOXk2bXptR0FuWlZ3N21jYlNHOXo5NzJ4DQpYc2hTWDBZ
Ky9vM0ZJN3lEd1pjcmdUcHlmV293MUlDclVwR0o1VUNzM2tGMEdsYTJTbUxjdG9WcHBUMHlTZXpa
DQptSlY0YTlBZEYyanIrU1RhUkl5NDVpVDc5ai9GQ1JjZlV3TVZDdG5BelVIQWgzdS9uQWNHcXRS
bEoydkN2eW1BDQpvaGFVK2xPT3ZLQlZoTXp0Q1JCZkZWWE1VdngxOUljTGthSVZkNFlCR0RONEtV
VCsxL2VGeXdkQ1lobHlaZiszDQowQVlycE5DazZFTE5FeUZ1SEM1TkV2Unl2bDN1RUEvczFBdSt4
WGV5TDdGVDVSS1dKRDZkTGdyN2FvL0kxZVd6DQpHTDFDTGgxa2lWVG1uRHErV1ZVV0JFK3ZXWitQ
S0puRVRnVnk5enpmUWdOZG1jYWdlNHl3Z0tLM1Z6UVFSUk5JDQptWXJONmhBZEE4UEsvaGN2ZTdO
a1dSTmN0bEsvNnI2RDBJTjJIMUlpZTBKUGVIdW1sSlJvU3Y1cEZHemVRWnhtDQpqa2VYS3pyUlVr
R2Q0ZWxYTXpwb09VdDBLeEFrejhRSFhvcFR5OFhsUHRHYnd0cHZvdno4KzJyNm5HQ3YyU2ZxDQo0
dVB3alZZVzB0bTZ4ZkJ0UVFDK3dnRGxhNFd6QStOTEdmT0lwSGp4bXVKS2o4eUFUcHd2eE5BTWFU
YWpQTndCDQplUEdIMzFQMXNUWW92VGh0WHhlK0VTRmx4ck9mMm4wYll0bnpNeEx4TVhKNWFEd0dy
S1pjWVBSbGM1clpHbU5GDQp5ZE9sRGxsU09XM2xlL2xBZDV6aUk4RkdPRFNaOVMzbmQ2YUhiNUY2
em13cFcwYWNVeVFuUk80QzBVY1ZZSEFGDQp2VzAwL2lpZTduWWEvSE0zVWc3QVIwdjBJR3NaQ3RT
SFZzcEduazYzK2pheTRLcTZwenVRRkdpaFN2R0lzVWdCDQo4Z3IwMmxBS21vWlZlWlg2ekhQa3BH
RFdSOVM2ekNzTmZJdk0xNTh0S0lRbzBnd2pyTjVhODBROWJ5L1FwcFJoDQpLekpIQVdrNDRJcm5Z
elBLSHBWci9CbmNjdlJaM1dmRThjb3grQ3lwenE4NExJNDdJaVJTRTdsdFExVFhZc1J5DQpFbjdu
YzN4VVV3WXFsMDRHMFVheTQ5TlNCYTVBRUU0TnNsYTF6c2M4SVRSMHBRQlVFWUo1aEVhSVlybnlL
bFErDQpBZ1J5VVg0YndtZkJ2WVArU3RaL3llWi9ucnpKb2NiYnV3RGhqSzNLS0sxRzVJRCtkeU5w
bCtqaGNmM3Z1YVRXDQpNNlpVSXdnL1A3S2lnSnFxRkwyZk5GRGVmdFZ2dzFPc1lwbnNodHVVcDJv
VU5CYmtYRzFVbCtYQVVWR05ORjNjDQpkNkMydy9qTlNjUFlXWm5nbEtxbDVIcUJ2L0x5eDYvVll5
WG4wa0JCSlJwZ0VNRWZyWXo0Q0k2ZWZyVk13bkN6DQpRa0pUOWZlcER2ZE90QzdGdXVwbk5ocjNq
akE4WnhhR1FOMVZlaFB4ZCt5Y25qWkNEMXVTUDJZcHNEMmJIYnBiDQpESWJwemVEQzNoaUFXNmZH
QldaZC9SWmxWOVpVcDk5MVk2MWNMckZOcTdhVHJMSzJXKytxU1NsZWJuT2psNVdLDQplUTQ3UnZj
MGIvOW1tbzlCK2UzWEh1NEdiUVY4TnpTN0VybXFYd0JsRDYxN05Ic2FuVGxVbmFNQWVOUmtYYXZP
DQowSk1KWmhOOW9rTmw2MnJ2N3NuWjBhczAxbE9Ubml0bk9vbk92UGtOZ2VrQVVCK1VMaFFGcW4w
NjErSUNPZWMyDQpNVmZyaUk2dTlQOUxDUmRDTHRIbnphUHdmYWVOVUllRzI4SUNnUjNkL3h1UkJQ
ZGJ1Mm9Nb3dZVDRjWUpZN0QvDQp2MnIvODNkdTh5amUyK29xWGxmNjZaK0hDKy9BbXlad05seUxS
ejU1NkxSbkxLSHJHNlJHQW9odXV3ZzFkMkxCDQpXTzE0UmlCTENpdVRGb3BVeS8zVnBIUTRiS2Uv
ckNDcmpxQkZ3aXlzVW5ESklZVnFmRHdRM2F5cXlqQ2NPNXQrDQpSVzNmS01oaWhpVTQzYWdMUDlH
cWpzS1g4N3IwUTJWbit2NlQ5aUh5NWh3ZDI4WjhJbk1hWWFwNVpyMFNNV0FYDQprUzZYYkZVeU41
MEVFRkN0NSthL3pGNUd1M044OWViNVVwdWFYM0lyOFc0UjJqc25UMlFkWFU4Y1ZBREZBZHo3DQpm
ekgrYlA1NitHd3lGcVNWWjk0UTRRQkJVM0hXcFJGbnNjdXIzenhFQ0NiRFh1cGlLSllMYlNhd3FY
MTVSTnh4DQpvd3NzTHNrYzRCRGIvakpRTFJGL0RJQXhYMHFGVEJpemlYRVBpMXhOQjFkQm1ka3dM
ZHg4Y0ZSRGlndTZjUUNBDQo1NlZ2UmhPUzR0RHg1Rm1wZms2amE2TWg0TmJabFFoVFUrV2lDeWFx
YTVaUTFVcG9zUmtPZk5VYWdCOGk4dlhIDQpHUGk2RnkrUjhiSnJOSlFGNGp4QXJxcG1QTFZldm5m
Vnp4M0tsUlZUR0VtczRwNkVNK1JMT1JWQ054VlZlc3FtDQptWlNiZWcwSGZ2cWNEanVrNzJrbVg3
a3IxdUhzcE4yaEQyRWlRK3FuaitxbWJBNWJ4QnhjblpVN0ZMUVIxOWNVDQpuaWJDdDJlVHBJSitZ
OHFlVDhKZStnNDcyZkwvSUViNTE0SWxqaHpMZWUxTG9qKzVVNVFUZlhjY2pBcmJrWm5sDQpjd2Fk
N3dzajYzUExWMG1zdGk1YW0rSE8veG9BY1hoSHV5NG5EKzAwYmc4dUw0MUUzc3RxTFFEZDlZRk9i
YVRODQptRjVrR1M3Q1Z1WWo5VThUSUFsd0pTem0yRkpqWjl2L00xVzNBOXR1U3o1QndxVHVuUnlW
T1BwMVgyRnlna05oDQp1dHhzazMvWlF0WGFFN0UvZWRURklNQWh3UCtsZjA3WGhDMjJuZ1dWeHdC
RWgvZDRWRFZ1OVVCOUJEejdIbUxSDQovTzlMTUxTWWM4TzdYQjY3RUpjZ1hGQi9jOUxFMDZDK1pj
OFNuRnNOK2l0R0orRUJaVUJKdjJhOTdBRDkvemxBDQpyQ09hS3VRRjcvWVNnblNGTmUycHk4YStS
VHV4WHdhN0xTZWxhb3pVV3diOFBvWDlWWFVMd2VmUHBVWks0ODd3DQpxdmtwdFV1T0hmNHlCWjBL
bnZCWGFqaVNjbE9YY0Y0N1U5VE1NZzdlVDRVZjVqR0ZCRTM2eTM3OTFrY3VHS0Q2DQpBZ3BxUmRT
NVNld3cvUngyQmkwVWt5QTR2VklYRURSaTBRNWMyazBSR1VTZWhGL2R3dnVsa3drSVY3bFBwcE9t
DQpDcmlVVUpDczhtTVBVYkJLMnVVcVJPLy9OZlh3bUEyZ3RERXlYdEdmRitZS05QTmtUQ1VjN0FK
eWdTUnlxWExvDQplenBBZUJSaWpvMU4yejNRM29EQXpuL1k5R0tDZXJ1OHltZ1R4QVZDcHlEblFl
Ry91TWJYNFRaTWNXUy8rbXBiDQplNjdIQ2FrM1c4Tndnc052aFJZMTNnT21vWFRvTXp2NFRETXlV
TjBjVGZtbzZKdHduRENHVHpLd0MycWFGZ202DQp1UEc4blJaVFU4dTdOSGsxSEk4SlFoWFRCMy9H
M3ZzNUwwSXJESFFNL25FYzVFaW5SUW9uWW1oVGtSdzNPQzZrDQpGOWd1dUg3dlFuOEg4Q09GOGhZ
MkxNR0daWGdNcHpqMDFIQ3c0anNKUDVZWEJENjhHbGh2eHRYNGlibkJ6c2FGDQpGTlFwR3pINzhI
S24zdTFEMnI0OHIvL3RaaDFzdFNmN1RxV1lPWi9uZzRqK2lRWHVGVVkvdkJPU2orL2ZLVmYrDQpx
T1laeFZseFpMOGZCRzZMTXBTdU9sNnp2aWtPYVBHajFiMnBEbEs0azV0cUIwWUdwV2JLcnRUUmFS
ODBUUFJiDQpCak05SVNQYVNjVHJ4Qk9qbjRoNUxLS3lBUnpIV0kxMVlHR2pqTmM0OWFyekVOSDdV
a0pVTnBuV2pUdUtueW5HDQpKcjhHZ0tUblI1WUpWbkhScEk5L0JpcmtBc0VEb3N1bm82dnk3cG5F
ZXdJWGdqWkZSZjIvR0Z4aXFqWHZvUWoxDQpzQVFLNlhKREt1NnBhQTJoWHVRY2RRUGRGSGNWTWtj
RmZIMXFMUTVYbUtrV2VITjZKbnhUNnJMRU10c0FpRHdHDQp1cjZPYXZERWdDVVlrUldJeE1zYys0
VElhVE5PVVEybHJ0RVc5TkYrMDc1cWNDaDRpaWJ2VEJLRDRGNHM2TVNFDQpsZFZid3BVYnB5QmlO
TUlkWER3eFJGSGI4VzBlRlFtUW12MFllZmdZdWVaK25sZG1ScnpCY1pkUlkrdldCVWdXDQpDYnRj
b3BUZTQ0VlFGQklNVzlSYUtQRHlJTGNOYWtyNE5HNGF3eDhhUk9lem9hbTRkcThFbVBRV0JKL09i
SEJjDQpDYnZUaXdtQ3JPZENtMzJsS2w0b2puaUM3b0VQNlVFMUFJazRxWGlkUHQrUzRNV3EzRnN5
TzBTeWphcUhjSHRhDQpIOG93OW5BZzMvemZqMVY5Y25PeFYwdEFXajc0bFI3VG1YU2lSUDNuTXBT
Z25EeTFkd1NZZzZJT2NrbnJrVzFYDQpuRVJvZ2dqS2hBbEZFK0xUazlqelhneUdOaEFxaHg0R09P
RzBnZGVrZkc3NVRZUHk1dDdoMmRHSDhZK3dHd3JzDQoxZFVKZmNma1pPVHYzRE9Ldk9uTXZqeGNC
S3AzQUE2aXpvZ2V2R1lHa1dvM3B5cDY1eHZwR1VoZ0o2dUhEclMrDQpCWGo5SzFMRlk0SmVWSDJN
SGtyOGw2d1J5d1NVaGx2NERGeHVhSTdaUURGajFZbXRaYkVWQktwNzFXYkFVMU8xDQplakRVOTIz
eUF1OFlITk03WDQ5RE5XMU5LSU43SXdDRTBESWoxTlZvSy9XUEFoK3ViV2JWempNUnVyR202cVYr
DQpIZ2FMZnR5YkhhZytPbFZjNWgxTGFxbk5HaWJFenZ1NndCU1JHbllHVG9NLytXVGV3STY5Y3pj
UlU0SzVYRHQwDQpZNVAxUlNrMmk2V3N3UnFkK21QVlZIRHpxbDNZT1Z3aC9oa0gvMlJmekhTVmhQ
YTJhL2hOVkxxSFUycHhqR1NQDQpzYWJubmxhOXhjZmNZcjFJclpCa0kzYmRJbERZZG51UlkzTGpG
d2pQWmErd3pZYWpucWEvT1FiZFhNcGd4NU9zDQpXc2lIN0VEYlMvVDVoQzYxWUFNb3FJa1l0QmNT
U1lucTBubDQwbHh0T1JJWmp0N25KM29mYThleFViajlQWDMxDQo2T1F4ZVZQRXd0SlhKTGZLWFJK
QUVWd2t4U0VRNFozTG1XSy85QkswOU9yeTJqRUV2VTIzTE9vNjF4V3JuWVdnDQpRdGgzWXQ2YTJu
YWc5ZEFaalZ2MDlpVHZFcmZ4QllzcUR5eE15YkRZVFA1dWV6djRnWHAxcVBDK01iclJLQllZDQpW
ZTExTzdRaFJHdmJqbk1EOCtRMFpYeUh2Uzk1UHI4TE82VjZaZHZYRDdGaTl4cThPUHRCVzk2RmQ4
d1pOSWJ2DQpIdVF5eUdhQnlYL1grUUsvK3FtYjVybHpDZFhLb1VzQytjd29vam1hWUJWdUdyb1kN
Cj1SZWlEDQotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tDQo=
--bcaec50407fe19246a050e488595--

**Comment by BjarniRunar** [comment]
I am pretty sure this is obsolete and has been fixed; attachment downloading has worked well for quite some time AFAIK. Thanks for filing!
