### ISSUE TITLE
Search term with "@" causes "internal error"

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1242]
Try a search with "`@foo`" in the web interface and you will get an HTTP 500.

**Comment by BjarniRunar** [comment]
That's not a bug, that's a feature!

Well, actually it is a bug. Thanks for filing, this is the CLI interface and the web interface disagreeing, and we should make sure that no input into the search box ever causes a 500.

**Comment by Andrew-Wang-IB45** [comment]
I have tried a search with "@foo" in the web interface and did not receive such a message. I tested this on Ubuntu 18.4.2 LTS using Mailpile version 1.0.0rc5.
![Mailpile Issue 1242 Tested](https://user-images.githubusercontent.com/37257276/65378993-fa0af680-dc8e-11e9-8dec-be1e47eb9506.png)

**Comment by BjarniRunar** [comment]
Thanks @Andrew-Wang-IB45, you are correct. This was fixed.
