### ISSUE TITLE
Mailpile creates key with sha1 hash rather than current best practice

### ISSUE THREAD

**Issue by chuckpeters** [mailpile/Mailpile#1243]
Newly installed Mailpile on Ubuntu 14.04 and created a new gpg key and the key shows a sha1 hash.  Please check the gpg.conf and provide instructions for fixing the issue with a stonger hash prior to gpg key generation.  
For example use https://github.com/ioerror/duraconf/raw/master/configs/gnupg/gpg.conf provided by Jacob Appelbaum.

See https://help.riseup.net/en/security/message-security/openpgp/best-practices

mailpile@cp:~$ gpg -K --keyid-format long
/home/d64/mailpile/.gnupg/secring.gpg
-------------------------------------
sec   4096R/DB345A2D4A1F30D6 2015-02-07
uid                          Chuck Peters <cp@example.org>
ssb   4096R/9969F0C5C7B4A33C 2015-02-07

mailpile@cp:~$ gpg --export-options export-minimal --export 'DB345A2D4A1F30D6' | gpg --list-packets | grep -A 2 signature | grep 'digest algo'
        digest algo 2, begin of digest ec b1
        digest algo 2, begin of digest 53 8d

**Comment by BjarniRunar** [comment]
Thanks, we'll add that to the list of PGP things to fix (#733).

**Comment by BjarniRunar** [comment]
After giving this some thought, I've decided to close this issue, for now at least.

We are depending on the upstream GnuPG for crypto expertise, and their defaults should be sane. If they are not, that's a gnupg bug and should be treated as such.
