### ISSUE TITLE
Keyboard shortcuts j and k are backwards

### ISSUE THREAD

**Issue by MatthewWest** [mailpile/Mailpile#1248]
j should scroll down and k should scroll up, at least if you want to be consistent with Vim, Gmail, and anyone else who does j and k for up and down.

**Comment by jceb** [comment]
+1, would love to see it the other way around!

**Comment by ethanwhite** [comment]
+1

**Comment by MatthewWest** [comment]
I've been trying to fix this but have been looking for several hours and haven't found the keyboard shortcut map yet. Could someone point me in the right direction?

**Comment by bnvk** [comment]
@MatthewWest 99% of the JS application logic lives in:

`https://github.com/mailpile/Mailpile/tree/master/mailpile/www/default/html/jsapi`

Currently the keybinding shortcuts live in `index.js` in an array. It should be straightforward what does what. Those should probably be migrated to the `global/keybindings.js` file though

**Comment by MatthewWest** [comment]
Thank you! I was trying to use the minified javascript, and this is SO much easier.
