### ISSUE TITLE
Windows packaged build may fail if Python is already installed

### ISSUE THREAD

**Issue by step21** [mailpile/Mailpile#1252]
[edit, bre: Original subject: Issue starting beta 2 on Win 7 64 bit (dll load fail)]

Hi,

I successfully tested beta2 on Ubuntu, but also wanted to test it on Win7 64bit.
When I run it, I get the following error:

```
File "scripts\mailpile", line 10, in <module>
    from mailpile.app import Main
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\__init__.py", line 1, in <module>
    import mailpile.app
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\app.py", line 7, in <module>
    import mailpile.util
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\util.py", line 21, in <module>
    from mailpile.i18n import gettext as _
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\i18n.py", line 5, in <module>
    from jinja2 import Environment, BaseLoader, TemplateNotFound
  File "C:\Python27\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 13, in <module>
    from jinja2 import nodes
  File "C:\Python27\lib\site-packages\jinja2\nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "C:\Python27\lib\site-packages\jinja2\utils.py", line 14, in <module>
    from jinja2._compat import text_type, string_types, implements_iterator, \
  File "C:\Python27\lib\site-packages\jinja2\_compat.py", line 141, in <module>
    from urllib import quote as url_quote
  File "C:\Python27\lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Python27\lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application. 
```

I also have python installed separately as a development environment. So if I just type `python mp` in the mailpile directory, it starts up and seems to work. So this seems to be either a problem with the python/libraries shipped with mailpile or those somehow conflict with my installed version?

**Comment by dietmar4711** [comment]
Starting mailpile.exe "by hand", there pops a "python" window up for a short time - then it dies.
I thought that it maybe has something to do with my local installed Python development, and deinstalled it - didn't help.

Then, I tried "python mp" as step21 did. This produced this output:

Traceback (most recent call last):
  File "mp", line 10, in <module>
    from mailpile.app import Main
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\__init__.py", line 1, in <module>
    import mailpile.app
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\app.py", line 7, in <module>
    import mailpile.util
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\util.py", line 21, in <module>
    from mailpile.i18n import gettext as _
  File "C:\Program Files (x86)\Mailpile ehf\Mailpile\mailpile\i18n.py", line 5, in <module>
    from jinja2 import Environment, BaseLoader, TemplateNotFound
ImportError: No module named jinja2

HTH,
Dietmar

**Comment by step21** [comment]
Well, 'by hand' is simply to see the log output. When you run "python mp" in which terminal and in which directory do you run it? If you uninstalled your local python install (assuming it was in PATH) "python mp" in the mailpile directory actually shouldn't work. It actually only worked for me with the python already installed on my system. If this was with another python from your system, try pip install jinja2

**Comment by dietmar4711** [comment]
Ok, my "python" seems to be python.exe from a GitStack installation (regarding the PATH variable).
But running "mailpile.exe" "by hand" does not show me any log output. as I stated above. :/

**Comment by step21** [comment]
Thanks. Regarding your python install, then the error message you posted is legitimate, you may try installing require modules as I wrote above.
When I said "running by hand" I didn't mean clicking on mailpile.exe or running that on terminal. I meant runnin "python mp" on the command line/terminal, and you got some output from that.

**Comment by dietmar4711** [comment]
Ok, I failed with the installation of the missing modules.

So I tried a different Python distribution for windows (WinPython portable). Installation is 900MB and >30.000 files *ouch*

Finally, I removed all local Python installations and Mailpile is running! It's a bit nasty since I want a local Python on my Win* to test my linux scripts here, but for testing Mailpile now, it's ok.

Would be nice if this could be fixed in future versions...

Dietmar

**Comment by step21** [comment]
I guess there might be a packaged version at some point. Otherwise, from personal experience, Windows always gives issues with things like that, especially if you have multiple interpreters/compilers installed and they all want to be found. It's like they don't design it with that in mind, after all you can just use Visual Studio ... ;-)

**Comment by BjarniRunar** [comment]
Thanks for all the detailed bug reports and troubleshooting, guys!

It sounds like the way our current Windows packages are built, we end up with conflicts if the user already has Python installed on their machine. We'll have to examine that carefully (and get help from some more experienced packagers) to avoid this problem in future releases.
