### ISSUE TITLE
Mailpile dies after starting on Win7

### ISSUE THREAD

**Issue by dietmar4711** [mailpile/Mailpile#1253]
Hi,

I just downloaded the latest beta to experience "MailPile". I am using Win7 Home Premium 64Bit.

After starting, you can see the MailPile icon in the windows traybar for some seconds, then it disappears. HTTP connection on the port does not work, the application died and you can not find it in the process manager.

I was searching for some log evidence, but could not find one...

Please advise, thx!

Dietmar

**Comment by step21** [comment]
This is already covered in #1252 This should be closed because it looks like a duplicate. If you start Mailpile from commandline manually (ideally powershell) you should get log output.
