### ISSUE TITLE
Tag creation erreor : accented character

### ISSUE THREAD

**Issue by klorydryk** [mailpile/Mailpile#1254]
Hi,
I'm trying to create a new tag for the word "copropriété" (french word).
-> I put "Copro" in the name, then "copropriété" in Slug.

When I push the "+ add" button, I get an error "Template error" on a blank page. I need to go back to "previous page" to continue using Mailpile (but obviously need the remove the accents to be able to "+ add" my tag).

**Comment by BjarniRunar** [comment]
This appears to have been based on some sort of misunderstanding of what the slug was for; it's just used in URLs relating to the tag.

Either way, this has been fixed; users are no longer given the option of choosing a slug when creating a tag and the Add Tag form has been reworked so the code in question is no longer in use.
