### ISSUE TITLE
Can't send encrypted message after selecting encryption key

### ISSUE THREAD

**Issue by maxrp** [mailpile/Mailpile#1255]
When clicking the "encrypt" lock in the compose dialog for a contact without a known public key, after selecting "find encryption keys" then selecting the correct public key I get this ambiguous screen:
![2015-03-01-150622_619x322_scrot](https://cloud.githubusercontent.com/assets/194949/6433527/3a901756-c026-11e4-9ba3-9c0393b77326.png)

Neither of the buttons seem to permit progress toward an encrypted message. This is in Firefox 35 pn Gentoo Linux, though I've also observed it with Firefox 36 on Fedora 21, revision 97143a2971b00cf6340f19371d13b11fbdc468e4.

This seems similar to https://github.com/mailpile/Mailpile/issues/1095 but isn't quite the same.

**Comment by davidrot** [comment]
Can confirm! Ubuntu 14.04 latest, chrome latest.

Do you need some logs? Found this in my dev console

Is Not Ephemeral
app.js?ts=0.4.4-1431244415:1646 -1
app.js?ts=0.4.4-1431244415:1648 yay, all have been searched & imported
(index):1 Uncaught ReferenceError: mid is not defined
app.js?ts=0.4.4-1431244415:1646 -1
app.js?ts=0.4.4-1431244415:1648 yay, all have been searched & imported
app.js?ts=0.4.4-1431244415:1646 -1
app.js?ts=0.4.4-1431244415:1648 yay, all have been searched & imported

**Comment by maysara** [comment]
I had the same issue, but it then literally "went away" ! can this be related to  #1123

**Comment by nilsws** [comment]
I'm having the same problem on OSX, and it makes mailpile essentially useless for encrypted email, which I think makes this bug quite urgent.

**Comment by BjarniRunar** [comment]
Yes, this code is not finished and is not expected to work in its current state. Thanks for filing though!

**Comment by nilsws** [comment]
Is there any way right now to import public keys? Or does mailpile not encrypt yet? 

-----Original Message-----

**Comment by maxrp** [comment]
Hmm, it might be good to temporarily disable the buttons or provide some sort of hint to the user that it's not supposed to work yet.

**Comment by BjarniRunar** [comment]
@maxrp That is a task on the roadmap, planned for a couple of weeks from now before prepping our Beta III. Everything takes time, including figuring out what doesn't work and commenting it out.

Commenting things out of HEAD is not an option though, I'm actively working on that stuff. Sorry if you were misled, I'll be thinking about what I can do to prevent that in the future.
