### ISSUE TITLE
when tagging folder with inbox, not only inbox shown in inbox but all mail

### ISSUE THREAD

**Issue by step21** [mailpile/Mailpile#1258]
This was observed when importing an mbox inbox from thunderbird. Mail folders were tagged appropriately, apart from Archives as no corresponding tag exists in mailpile.
Then when import was done, all mail seems to show up in inbox, not only the one actually in inbox.

**Comment by step21** [comment]
I tested this some more - with two different mailpile installs, from three different imap servers. The expected behaviour as I see it, and other mail interfaces do it, is that if a message is in Inbox, it shows up in the Inbox, but otherwise, it is is in All Mail or Archives it does not.
However, Mailpile insist to sort all Mail that is not Junk, Deleted, Drafts or Sent into the Inbox. Is this me, or is this expected behaviour?

**Comment by BjarniRunar** [comment]
This should depend on how you configure individual IMAP folders when you set up the import. If you tick the inbox checkbox, they'll be imported into the inbox. I suspect the bug here is that that interface, the setup of IMAP importing, is just too confusing. Does that sound plausible?

**Comment by step21** [comment]
I thought that at first as well, and granted, especially with a lot of labels/folders, it can be quite confusing. However, I think that is not the problem. I made very sure that inbox was tagged properly. What could be an issue is that I have (either made by hand or by GMail or some other mailclient) a lot of folders/labels. Normally these qualify as "All Mail" or "Archive" or a subfolder thereof, but if I remember correctly there is no such label in Mailpile.
So it might be that these untagged folders are placed under Inbox. ?

**Comment by BjarniRunar** [comment]
The current source setup is being replaced by a different approach; we'll be doing much less auto-classification of remote folders than before, but instead provide the user with a browsing interface that lets them import the things they care about, organized the way they prefer.

I don't know whether that will address the issue, but it changes things sufficiently that I don't think this exact issue will get resolved directly (so closing this issue).

Thank you very much for taking the time to test and file - your feedback was part of what made me decide to explore a different avenue for configuring these things.
