### ISSUE TITLE
How do I configure Mailpile to use my domain name?

### ISSUE THREAD

**Issue by cloudformdesign** [mailpile/Mailpile#1260]
I've gone through all the documentation and I haven't been able to figure out where I set my dns settings and domain name. Where is this documentation?

**Comment by BjarniRunar** [comment]
Your question is incomplete. What do you want Mailpile to do with your domain name?

**Comment by cloudformdesign** [comment]
I want to send and receive mail as garrett@cloudformdesign.com  (I own the domain name cloudformdesign.com)

**Comment by BjarniRunar** [comment]
Mailpile is a mail client, so assuming you have a mail server for cloudformdesign.com, you can configure Mailpile to use it. However, Mailpile's really not ready for non-developers to use it yet, so you might want to wait a bit while we fix a whole bunch of things first...

**Comment by cloudformdesign** [comment]
sounds good. I guess I didn't realize that!
