### ISSUE TITLE
Mailpile does not shut down Python on exiting (Win)

### ISSUE THREAD

**Issue by dietmar4711** [mailpile/Mailpile#1261]
Hi,

when exiting Mailpile via the Icon in the Windows traybar, there remains a "stale" python process in the system which has to be killed manually.

Occurs here on Win7 64Bit Home Premium.

Dietmar

**Comment by dietmar4711** [comment]
Oh, I just saw also that openssl.exe is also not terminated properly and consumes cpu usage...

**Comment by audax** [comment]
Same here, the openssl process has a very high cpu usage. I do not have a stale python process however, just the openssl process.

**Comment by BjarniRunar** [comment]
Note: improvements to the Mailpile Windows desktop integration should take place in the gui-o-matic project so the results can be re-used by other projects: https://github.com/mailpile/gui-o-matic

**Comment by BjarniRunar** [comment]
We are removing the dependency on openssl. See PR #1684.
