### ISSUE TITLE
An @ symbol in "name" in recipients breaks parsing

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1271]
A recipient header like

```
From: "Name @ Cool" <name@cool.org>
```

Ends up looking like this in the JSON like this:

```
3HH: {
  address: "@",
  flags: { },
  fn: "Name Cool <namecool.org>",
  protocol: "smtp",
  rank: 0
}
```

**Comment by bnvk** [comment]
Adding to this issue- even if a user manually removes the offending contact (but is replying to a thread which contains bad character in previous message), the mail then fails to send as the header contains this character as a contact `x-mp-internal-rcpts: name@domain.com, @, other@domain.net...`

**Comment by BjarniRunar** [comment]
I think I've got this one fixed, watch for my next big push.
