### ISSUE TITLE
no way to manually adjust keys used when sending out to mailing lists etc.

### ISSUE THREAD

**Issue by droopy4096** [mailpile/Mailpile#1273]
I have an issue with MailPile not picking up gnupg-defined group. When I try to send email, say from Thunderbird, to mailing list - it'll pop up asking which key[s] to use and I can select defined group. In Mailpile - it completely disregards group that is named similarly to mailing list ( ML: group1@site.com GROUP: group1 )

Mailpile should either present an option of associating mail address with the group of keys or some other means of dealing with similar situations.

**Comment by BjarniRunar** [comment]
Mailpile just doesn't support multiple keys at all at the moment. This is a known limitation, which is being tracked elsewhere - so I'm closing this issue for now. Once we have multi-key support it will make sense to file new issues if it still doesn't handle this sort of use case gracefully. Thanks for taking the time!
