### ISSUE TITLE
Adding New Sending Route Doesn't Work On Iceweasel

### ISSUE THREAD

**Issue by SwartzCr** [mailpile/Mailpile#1275]
When I am in the Add Profile prompt to add a new email sending route when I click "+ Add New Route" nothing happens, preventing me from adding a new email route.
What should happen is that it should move me to a new view where I can enter information about the route.
I am using Iceweasel version 31.5.3 on Debian Jessie. 
When I open the Sending Routes drop down, and when i select the "+ Add New Route" prompt I get the console error: "Empty string passed to getElementById()" in jquery.min.js:2
I don't get this error when using chrome, and on chrome I am able to get to the corresponding subsequent page.

**Comment by BjarniRunar** [comment]
This part of the setup flow is being removed and replaced by a different system; as a result this bug will never get fixed. :-)  Closing, thank you for taking the time to test and file!
