### ISSUE TITLE
SSL for XML-RPC/HTML UI

### ISSUE THREAD

**Issue by GRMrGecko** [mailpile/Mailpile#128]
It is a must to have SSL when dealing with Web technology and private messages.

Here are my suggestions on implementing SSL (Sorry if it's already done):
1. Have it generate a self signed certificate and accept a custom certificate if for some reason the user knows how to get a SSL certificate and wants to use it.
2. Have detailed instructions on installing the certificate into the trust store so that they are only alerted whenever the certificate changes or someone is trying to be a man in the middle. For iOS, generate a iPhone Configuration file.

**Comment by BjarniRunar** [comment]
Progress has been made on this, it will be in 1.0.

**Comment by BjarniRunar** [comment]
Actually, to clarify - SSL at the server side will be supported. Client certificates will come later (if ever, the browser UX for such things is atrocious).
