### ISSUE TITLE
Make outgoing SMTP connections make use of SOCKS

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1281]
Currently, if a user has SOCKS configured to route requests through TOR, Mailpile does not take advantage of this the way some applications do.

I know it's on the roadmap to add Tor support natively at some point, but I am curious if it is a low hanging fruit to make use of SOCKS for the interim right now?

**Comment by BjarniRunar** [comment]
Yes, adding SOCKS support would be a milestone on the road towards proper Tor support. Some groundwork has been laid (the connection broker code), but it's really unclear at this point how it should be configured/managed/presented to the user.

**Comment by BjarniRunar** [comment]
This should work now, if the sys.proxy.* variables are set accordingly.
