### ISSUE TITLE
Implement "copy all addresses" from an email button

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1283]
Upon watching @nycdubliner resort to viewing HTML page source (in Gmail) in order to copy & paste "all contacts" from one message thread to another- seems that a simple button / feature like this should be implemented

**Comment by karlp** [comment]
:+1:

**Comment by BjarniRunar** [comment]
This seems like a neat feature, but it also really feels like one that might not be used often enough to justify the screen real-estate required for a dedicated button or menu item. At least not if that is all it does.

In the short term, I wonder if this need might be addressed by the datadig plugin, possibly with some enhancements?  (Thus the low-hanging-fruit labeling)

A better long-term solution might be to implement the Groups concept which was brainstormed very early on in the project. If a user is copying recipients from one thread to another, but doesn't want to just reply-all and change subjects... then perhaps that means he really wants to treat those folks as a "group" or "mailing-list" of some sort? The Group concept is quite powerful, so adding dedicated UI elements to both create and interact with groups makes total sense.
