### ISSUE TITLE
Doesn't fully update the contents index from remote IMAP folder

### ISSUE THREAD

**Issue by yurivict** [mailpile/Mailpile#1285]
I have the large IMAP folder.

In "Mail Sources", when I click "Edit"->"Save Source", it shows "Getting Status ...", then "Not connected to server", but this IMAP folder only shows about half of it contents. It never gets updated in Mailpile to the latest message in IMAP. And it doesn't look like it fails to connect.

**Comment by BjarniRunar** [comment]
Thanks for filing! This code is being replaced as part of the Short Setup Flow theme of the current roadmap (see https://www.mailpile.is/roadmap/ and linked blog post).  As such, this bug will never be directly fixed. If it resurfaces in the new setup tools later on, please re-file.
