### ISSUE TITLE
Please replace bash with sh where not needed

### ISSUE THREAD

**Issue by yurivict** [mailpile/Mailpile#1286]
Like 'scripts/compile-messages.sh'.
Dependency on bash in BSD is not automatically satisfied, like in Linux, and there is no need to have it if not essential.

**Comment by BjarniRunar** [comment]
Makes sense. However, those scripts are for developers... and developers are welcome to file pull requests. ;-)

**Comment by wolfpackmars2** [comment]
Not sure how important this is.  One can easily create a link in BSD for BASH -> SH  or install bash.  looking through the scripts, some may not be compatible with sh.  I don't have a BSD instance ATM to test this, but it should be simple enough to test using BSD by running 'ln /bin/bash /bin/sh' and then testing the scripts in BSD to ensure they work.
