### ISSUE TITLE
Template not found while replying to any message except last in thread

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1287]
With recent commits, clicking « reply » on any message of a thread, except last one (which already has its form displayed by default) do not displays the composer but that in the displayed HTML instead :

```
Template not found

In html/message/draft.html:
html/message/draft.html
DATA:
[...sniped data…]
```

**Comment by BjarniRunar** [comment]
I'll take a look, thanks!

**Comment by BjarniRunar** [comment]
Found and fixed locally, will be in my next push.

**Comment by JocelynDelalande** [comment]
@BjarniRunar <3

**Comment by JocelynDelalande** [comment]
Confirmed to work, thanks :)
