### ISSUE TITLE
Delete mail off source.

### ISSUE THREAD

**Issue by GRMrGecko** [mailpile/Mailpile#129]
I do not know if anyone has heard about this, but the US government says that if you leave your mail on Gmail (or any other web service) for 6 months, it is available for their taking without a warrant. http://www.wired.com/threatlevel/2011/10/ecpa-turns-twenty-five/

An option to delete mail off the server mailpile is receiving from would be a great option. There should be the ability to remove immediately, remove when deleted, or remove after a specific period of time. Look at Apple mail pop advanced tab.

I am already working on installing my own IMAP server as an archive server where once a month I will take all my email from my mail accounts and archive them there. Completely delete the copy from Gmail so the only copy is on my sever and is backed up encrypted to multiple places.

**Comment by unhammer** [comment]
Yeah the `local_copy` thing is quite confusing. I was just about to try out Mailpile, but I don't feel confident that it won't delete all my e-mail :-) 

https://www.mailpile.is/faq/#wha-6 seems to imply that deleting happens, though it's very unclear if mailpile does it or the user should do it manually or what. https://github.com/mailpile/Mailpile/wiki/Getting-started says to follow https://github.com/mailpile/Mailpile/wiki/Configuring-mailpile but that page isn't written.  It also mentions https://github.com/mailpile/Mailpile/wiki/Indexing-Mail which seems partly geared towards developers, but at least mentions `local_copy` which seems relevant, but doesn't explicitly say whether anything is deleted or not.

(I just now noticed that https://github.com/mailpile/Mailpile/wiki/Getting-started says to just follow the browser setup thing, but I prefer knowing what's going to happen before pointing new programs at my data.)

**Comment by BjarniRunar** [comment]
Hmm, sorry I haven't spoken on this issue yet. To clarify the Mailpile position on this:

1. We absolutely want to be able to delete from the sources, for all sorts of good reasons :-)
2. This doesn't work yet, Mailpile currently treats all sources (local and remote) as read-only.

Point 2. is safe from a data-loss point of view, but it was meant to be temporary while we worked on other things. It should have been done long ago, but that goes for many other things as well. I am very sorry this hasn't been fixed yet, but that's just how it is.

The FAQ is aspirational, explaining to people the concept. The implementation lags behind. This undoubtedly adds to the confusion.

**Comment by BjarniRunar** [comment]
This should work now! Closing; bug reports deserve have issues of their own.

**Comment by Overpass4014** [comment]
Can anyone tell me how I can configure deletion from the source?

**Comment by BjarniRunar** [comment]
I can tell you to please not use Mailpile v1!

It's unsupported and not being developed and depends on an obsolete tech stack. Sorry. :-D
