### ISSUE TITLE
Ability to realy delete a message.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1290]
If I « delete » a message, it goes to trash. That's expected.

But then if I delete it from the trash it… remains here.

It may seem minor issue, but IMHO, the ability to delete (or better : shred) a file is an important privacy feature.

**Comment by BjarniRunar** [comment]
Yes, absolutely. This issue is a duplicate of #945 , closing for that reason only. :-)

**Comment by JocelynDelalande** [comment]
Oh, sorry, I didn't stumbled uppon #945 during my search before opening that issue.
