### ISSUE TITLE
NAT-PMP/UPnP Port Forwarding

### ISSUE THREAD

**Issue by GRMrGecko** [mailpile/Mailpile#130]
Many users still have NAT-PMP or UPnP enabled on their routers. We might as well take advantage of this and try to open the necessary ports for the user.

I was thinking that once Mailpile is installed, they'll be directed to a setup process in their web browser where they would be asked questions and maybe this will be one of the questions. Allow access from the internet or something to that extent. Mailpile will try to open the port, if it can't, it'll direct people to opening the port with instructions at http://portforward.com/ or something like that.

**Comment by BjarniRunar** [comment]
Actually, this is a no for the forseeable future. Thanks for filing though! :-)
