### ISSUE TITLE
Set password/passphrase improvements

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1300]
The dialogue for setting a password/passphrase needs the following improvements:
1. Generate a passphrase for the user (the Peerio method is worth emulating)
2. Offer feedback on password strength
3. Passphrase or password?  Make sure terminology is consistent.

The last point is an annoying one - "passphrase" is a more logical and transparent term (recommended by usability experts at the DCSS conference this weekend), but the current ModernPGP recommendation is to use "password" because it is more familiar to users.

**Comment by NoahAndrews** [comment]
I'd go with passphrase. It may not be the term that typically gets used, but I doubt very many people at all would be confused by it. Then again, I may just be underestimating some people's ability to get confused by things.

**Comment by BjarniRunar** [comment]
Going with password. Geeks can deal, normals have no idea what passphrases are. :-)
