### ISSUE TITLE
Add a tool to change the Mailpile password

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1302]
Currently there is no way to change the Mailpile password/passphrase. This needs to be possible.

**Comment by digen** [comment]
Finding out now that my passphrase which worked perfectly earlier few times now doesn't work at all.  The terminal has the following message at the top, 

```Failed to decrypt configuration, please log in!```

Will try and report if re-installing provides a fresh way to start again.

**Comment by BjarniRunar** [comment]
I cannot comment on this without knowing more about your history with the app. Did you upgrade? Did you try an older version (Beta I or II)? Are you using Beta III now? Do you have old PGP keys which have expired since you last tried Mailpile?

**Comment by BjarniRunar** [comment]
@digen Actually, please file a NEW issue for this, the problem you describe is unrelated to this issue and should be handled separately.
