### ISSUE TITLE
Doesn't break line in the right place

### ISSUE THREAD

**Issue by rpadovani** [mailpile/Mailpile#1308]
I sent a mail, and it breaks all the line at the 80th(?) char, but in a line. See screenshot.

I'm not sure if it's due the `'` or other.

Let me know how I could provide more informations :-) (I can send also the raw of the mail to devs, but I' d preferer don't do it in a public issue)

![mailpilebug](https://cloud.githubusercontent.com/assets/1713343/8431009/62c0747c-1f36-11e5-9f23-33c9132fb525.png)

**Comment by BjarniRunar** [comment]
Thanks for reporting - the reflow logic had a bug where if a " or ' or * or some other punctuation character was at the beginning of the line, it would not be reflowed. This was an attempt to not mangle ascii-art and bullet lists and such.

I've reworked the algorithm to be a bit smarter about such things, but it probably still needs work. The case you describe at least should be solved. Please feel free to reopen or file a new issue if it still gives you grief!

**Comment by rpadovani** [comment]
Thanks for the fast fix Bjarni :-) Keep up the good work!
