### ISSUE TITLE
The "bulk action hints" makes bulk action buttons unclickable

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1310]
At my current resolution, the buttons up until the red arrow are unclickable once an item is selected. 

![bug image](https://brennannovak.com/uploads/snapper/Mailpile_bulk_action_hints.png)

However, the number of unclickable buttons varies depending on browser width.

I believe the issue is the `div.bulk-actions-hints` has it's `width:85%` which causes it to spill over the buttons. Switching that attribute to `display:inline-block;` seems to fix it!

**Comment by BjarniRunar** [comment]
Good catch! I think I'll fiddle with the z-index instead, the width is for positioning.

**Comment by BjarniRunar** [comment]
Bah, too fiddly. Did it your way, looks fine. Thanks again!
