### ISSUE TITLE
Possibility to turn off authentication

### ISSUE THREAD

**Issue by DoubleMalt** [mailpile/Mailpile#1312]
As discussed with @BjarniRunar it would be great to make it possible to turn off authentication altogether and handle it externally. 

Use Case: For CloudFleet we will run mailpile behind an nginx proxy and have a central user storage. It would be great if we could authenticate the user at nginx server.

**Comment by BjarniRunar** [comment]
Should be done!

Just add `http_no_auth = True` to your predefined config file. When testing, note that setting this on the CLI requires the --force flag, so `set --force sys.http_no_auth = True

**Comment by DoubleMalt** [comment]
:+1: WIll test it today!
