### ISSUE TITLE
"Template not found" for `http://localhost:33411/help/crypto-signaling.html`

### ISSUE THREAD

**Issue by paulfurley** [mailpile/Mailpile#1313]
As a new user, I clicked the "Details" link next to "Signal a preference for encrypted mail" and got a "Template not found" error. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/254290/8495030/27a1c05c-2162-11e5-9c85-474251f010b0.png)

**Comment by BjarniRunar** [comment]
We know. It just hasn't been written yet!

Thanks for filing, but please see the reporting bugs hint within the app (hover over the blurry topbar) so you don't waste your time reporting stuff we already know about. :-)

**Comment by paulfurley** [comment]
Ah, apologies.

I saw the blurry bar but couldn't work out what it did.... Also tried
searching through Github issues to no avail - ah well!

Paul

**Comment by BjarniRunar** [comment]
No worries, just didn't want you wasting your time. :-) Not all the loose ends are in github, if I'm actively iterating on something I don't bother creating an issue for all the things I haven't finished yet.

**Comment by BjarniRunar** [comment]
This is adequately covered by #1413 which also reports other related problems. Closing as a dup. :)
