### ISSUE TITLE
Improve support for non-standard GPG binary locations / Qubes OS

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1314]
I am trying to configure Mailpile on the [Qubes OS](https://www.qubes-os.org) using their "[Split GPG](https://www.qubes-os.org/doc/UserDoc/SplitGpg/)" scheme whereby you have your mail client and your GPG keychain in separate VMs and they talk over a special script that poses as GnuPG binary. In Enigmail it is configured like this:

![GnuPG path Enigmail](https://www.qubes-os.org/attachment/wiki/UserDoc/SplitGpg/tb-enigmail-split-gpg-settings-2.png)

As was being discussed in #926 PGP smartcard support, I tried configuring Mailpile as per @BjarniRunar suggestions about changing the localhost config to point to the settings that work for Engimail, but alas it does not work. 

This is super unusual use case that only pertains to a small percentage of users, so I'm just assigning this to "Ideas - Code" milestone! Who knows, it might be something on Qubes special script that needs tweaking!

**Comment by BjarniRunar** [comment]
I just pushed up a minor tweak to the CLI gpg command, which should make this easier to debug. Steps:

1. Pull down the latest code
2. mailpile> gpg --list-keys

... that will either successfully print a list of GPG keys (which means it should work and further debugging is necessary), or give an error message which might help debug this.

**Comment by bnvk** [comment]
@BjarniRunar awesome, thanks for giving a glance to this weird edge case issue :smile: \

I did as you suggested and upon running the command Qubes showed it's normal permissions dialogue, and lo and behold, it showed all the keys from the other VM. w00t! However, Mailpile doesn't seem aware of or is doing anything to import those keys either as my encryption key nor as contacts!

**Comment by BjarniRunar** [comment]
... normal permissions dialogue? Sounds like it only works with an agent and Mailpile's attempts to feed it passwords may be causing things to break.

I can't deal with this now, but figuring things out will probably require reading this source to understand what the Qubes wrapper can and cannot handle, and then figure out whether Mailpile can be shoehorned into that model:

http://code.metager.de/source/xref/QubesOS/qubes-r2/qubes-app-linux-split-gpg/

**Comment by mfc** [comment]
fyi this is the relevant repo:

https://github.com/QubesOS/qubes-app-linux-split-gpg

not sure what that other site is.

**Comment by rysiekpl** [comment]
Started playing with [Qubes OS split GPG](https://www.qubes-os.org/doc/split-gpg/), trying to get Mailpile to work with it. Moved `/usr/bin/gpg` and `/usr/bin/gpg2` out of the way and replaced them with `/usr/bin/qubes-gpg-client-wrapper`. Running `gpg --version` directly from Bash does go through the split GPG thingy and gives me:
```
$ gpg --version
gpg (GnuPG) 2.1.13
libgcrypt 1.7.9
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/user/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

(Obviously `/home/user/.gnupg/` does not exist in the `mailpile` VM.)

Running `./mp` blows up with:

```
$ ./mp
Metadata index not found: /home/user/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.042s (Loaded metadata, 0 messages)                                  
Traceback (most recent call last):
  File "./mp", line 14, in <module>
    Main(sys.argv[1:])
  File "/home/user/Mailpile/mailpile/app.py", line 191, in Main
    config.load(session)
  File "/home/user/Mailpile/mailpile/config/manager.py", line 303, in load
    self.gnupghome = GnuPG(self).gnupghome()
  File "/home/user/Mailpile/mailpile/crypto/gpgi.py", line 574, in gnupghome
    rv = self.run(["--version"], novercheck=True)[1]["stdout"][0]
IndexError: list index out of range
```

Any specific place I should look at? Any specific things I should try?

**Comment by rysiekpl** [comment]
Looks like `--no-use-agent` is not a thing in Qubes' split GPG wrapper:

```
qubes-gpg-client: unrecognized option '--no-use-agent'
```

**Comment by BjarniRunar** [comment]
Those error messages suggest the qubes-gpg-client wrapper is just insufficiently clever to work here. You're going to keep having annoying problems, and in practice having an unreliable interface to your crypto tools is a good way to lose data. So, beware of dragons here...

It might be possible to avoid the passphrase-fd and pinentry-mode=loopback code-paths, if you do this: `mailpile> set prefs.gpg_use_agent = true` However that code-path is poorly tested and likely to be buggy.

I quite don't remember why we're using `--expert`, but there is almost certainly a "good" reason - my best guess is it's required to get gpg to provide output that contains all the information our parser is looking for.

**Comment by rysiekpl** [comment]
Will try working with QubesOS devs to make `qubes-gpg-client` smart enough, then!

**Comment by rysiekpl** [comment]
Turns out there's a [new version of split GPG](https://github.com/HW42/qubes-app-linux-split-gpg2). Testing it with Mailpile ends with two issues so far:
1. Mailpile uses `pinentry-mode=loopback`, which is filtered by `split-gpg2`
2. when I comment-out `pinentry-mode=loopback` in Mailpile code, it complains about "Invalid password policy", even for secret keys which are *not* protected by a password

(a key that resides in a special virtual machine, on an encrypted disk, and is only accessible via a well-defined `split-gpg2` protocol doesn't seem to be necessary)

**Comment by rysiekpl** [comment]
Looks like `GETINFO s2k_count` is also being filtered out by `split-gpg2`. So, similar question as above: is it required for Mailpile's operation? Is there a way to disable its use?

Relevant `split-gpg2` issue: https://github.com/HW42/qubes-app-linux-split-gpg2/issues/5

**Comment by BjarniRunar** [comment]
No idea! :-) What's that? I forget, if I ever knew...

And, yes, Mailpile DOES make strong assumptions and try to manage keys itself. It generates passphrases and stores them in its config. Fun stuff like that. That's kinda the whole point of our crypto support, we're trying to make encryption accessible to a wider audience, asking Joe Random to manage keys is just not an option. Also, all the fancy cool stuff we want to do with remote access (letting people access their Mailpile over Tor or the web, Mailpile on a Raspberry PI, etc. etc.) breaks if you start involving an agent and require the user sit at a desktop.

There is a setting, `prefs.gpg_use_agent` which can be set to true to try and allow the agent to do its thing. I already mentioned this above - if you've set it and it's not working then it's probably buggy? It's not well tested, because frankly it's not a use case we care about much for the above stated reasons.

Maybe that's dumb of me. Maybe we should be trying to woo the Qubes community and get motivated developers that way. But I'm struggling here, I already have too many things in my head... dealing with just GnuPG was a PITA enough, dealing with wrappers that arbitrarily remove functionality isn't something I'm keen to add to my plate.

**Comment by rysiekpl** [comment]
That is entirely understandable, and I did miss the `gpg_use_agent` setting (also, now tested it, as mentioned above, but not with good results).

Obviously nobody expects you to jump into this and redo Mailpile dramatically just to get it working with `split-gpg2` in QubesOS!

However, I am still a bit bummed out that Mailpile does not support the standard `gpg2` way of doing things (i.e. via `gpg-agent`). I understand *why* this is the case, but I still think it would be beneficial for Mailpile to support `gpg-agent` well, not only for QubesOS `split-gpg2` sake, but also for all the greybeards and their weird setups which rely on it. Again, not saying that you should jump in and fix it, just stating my reaction.

I am happy to spend time getting `split-gpg2` to be nicer to Mailpile, and on trying to figure out what I can do to get Mailpile to be more workable with 'gpg-agent` and `split-gpg2`. But I need help with that, as I am unfamiliar with Mailpile's inner workings.

**Comment by BjarniRunar** [comment]
The goal has always been to reach people who *aren't* using PGP already. The number of people who are, in the grand scheme of things, is a rounding error. A admittedly, a very important rounding error! I'll do my best to help you here, but you're digging through code I haven't touched for a while so I won't always know the answers right off the bat. I do encourage you to poke me on IRC though, that might be a bit more fun than exchanging essays here.

**Comment by BjarniRunar** [comment]
@mfc The project is made of of its contributors, we don't all have to have the same goals. I have my own priorities and do my best, in particular, I want to try and live up to the promises made in our IndieGoGo campaign, and Qubes wasn't anywhere close to being on that list. I understand your priorities may be different.

Installing and getting familiar with Qubes is a huge task, and one I simply do not have time for. I welcome contributions from people who have skills I lack. But if all you've got is snark, please consider whether that's really constructive or just another log on the burnout fire. I will happily ban people from this repo whose only contribution is to damage morale and demoralize. Thanks.

**Comment by mfc** [comment]
hey sorry not trying to contribute to burn-out fire - your statement was just clarifying for me about whether Mailpile intends to be functional in use-cases that i had previously thought it would be functional in. 

obviously i hope @rysiekpl is able to dig into the inner workings of Mailpile and figure out how to get it to behave in more standard `gpg2` way for these niche needs, but i now understand the amount of work that would be involved and have a sense of the priority and likelihood. 

your approach makes complete sense for what you stated you are trying to do and i hope it goes well.

**Comment by DemiMarie** [comment]
So one approach here would be to use the `gpg2` CLI with split-gpg2.  `gpg2` will then use gpg-agent under the hood.
