### ISSUE TITLE
Example email address in account add dialog should comply with RFC 2606

### ISSUE THREAD

**Issue by nathans** [mailpile/Mailpile#1315]
While I understand the spirit of it, I think it is best to comply with RFC 2606 email domains when displaying example email addresses.

Pic of what I am takling about:

![manning](https://cloud.githubusercontent.com/assets/206383/8515281/8e00c336-2354-11e5-96bb-619a277e3923.png)

**Comment by BjarniRunar** [comment]
See discussion in pull request: https://github.com/mailpile/Mailpile/pull/1316

**Comment by BjarniRunar** [comment]
I think the consensus is we like the current statement too much to change it. :-)  Thanks for filing though!
