### ISSUE TITLE
Tag names with special characters cause issues

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1326]
I created a tag called `M. Fowler` and now I am unable to edit this tag. It appears to be because the period in the name. In the tag editor that pops up, the title reads as `m.-fowler` and the form below does not load at all. I am unsure if the backend supports tags with special chars in the slug, or if this is just something in front-end.

**Comment by wiml** [comment]
May be related to  issue #1254 ?

**Comment by BjarniRunar** [comment]
I am unable to reproduce this problem. I tried - I created all sorts of tags with dots and spaces and non-ascii characters in the names (and slugs), and all were created without a hitch and the edit dialog worked fine.

Are you using the CURRENT edit dialog, or something you accessed through the back-door by visiting the old /tags/ page which isn't currently exposed to users and is not expected to work?

**Comment by bnvk** [comment]
Yes, using CURRENT edit dialogue on freshly installed instance with debugging turned off. However, I believe it was a tag adding the CLI that then I tried to edit via web interface. Will test again once I get my HT dump instance back online

**Comment by BjarniRunar** [comment]
So you're clicking the "edit" button on the search result page?

If you've got `sys.debug = log http` do any error messages show up on CLI?

**Comment by bnvk** [comment]
Ok. I researched this more and more and tried to replicate the issue and i'm not able to, so I will chalk that up to the slowness of the server I was working from. However, I'm still noticing slightly odd behaviours that I think (combined with slow server). 

- Tag creation of `M. Fowler` creates tag with slug `m.-fowler` which seems to resolves fine
- Editing an EXISTING tag's slug `m.-fowler` to `new-m-fowler` refreshes the old search for `m.-fowler` which now shows no messages since the tag name has changed
- The edited tag does not show changes in sidebar (name + display position) for a delay, which is probably caching, yes?

So, maybe rename this issue as you see fit or close it!

**Comment by BjarniRunar** [comment]
OK, thanks for taking a 2nd look. The wonky behaviour of the UI post-edit is a known issue, one which I hope to improve as part of the ajaxification-of-everything. This is not something folks do every day, so we can live with it being a bit lame in the meantime.
