### ISSUE TITLE
Make paths in HTML relative where possible.

### ISSUE THREAD

**Issue by palday** [mailpile/Mailpile#1329]
Using absolute paths in the served HTML files prevents using a reverse proxy with Mailpile not in the root location, e.g. `http://server.com/mailpile` does not work because the resources fail to load. More complicated rewrites of the HTML body are possible with Nginx and Apache, but require loading additional (and in the case of Nginx, non standard) modules.

**Comment by BjarniRunar** [comment]
This isn't going to happen. :-)  Making the URLs relative requires the code generating the URLs to know the path of the page displaying them and is generally hard to do in a way that allows for reuse of HTML snippets in different context.

However - to solve exactly your problem, there is a setting sys.http_path which defines the root path of Mailpile.  You can set it directly with `mailpile> set sys.http_path = /foobar` or you can use the www command and an URL to set the host name and port numbers at the same time: `mailpile> www http://0.0.0.0:12345/foobar/`

Thanks for filing, hope this solves your issue!
