### ISSUE TITLE
Header errors on parsing addresses

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1332]
Below is the `as.json` result of the parsing of message filed in #1325 

```
"result": {
    "address_ids": [ ],
    "data": {
    "addresses": { },
}
```

The results in the interface is displaying nothing in the To: or From: fields and says "No Subject" in the subject fields.

I'm not sure what is ideal handling of this in a UI. I feel the No Subject bit is decent, and probably the same thing in the recipient fields. However, these fields should be something that if a user tries to click "send mail to" should explain that this is a non-existent / error email account, or hide the "Compose To:" feature altogether!

**Comment by BjarniRunar** [comment]
I don't understand this issue; it's rather old so I'm closing it. :-)
