### ISSUE TITLE
dovecot: log: Error: Received master input for invalid service_fd

### ISSUE THREAD

**Issue by GitHubGeek** [mailpile/Mailpile#1334]
Not sure if this is a Mailpile or Dovecot issue. Anyway... The following message keeps spamming my syslog every minute or so. Does not seem to affect Mailpile's functionalities.

```
dovecot: log: Error: Received master input for invalid service_fd 27: 27 2913 BYE
```

Running Debian Jessie, Dovecot 2.2.13-11

**Comment by BjarniRunar** [comment]
This sounds like dovecot is unhappy that we just drop the connection instead of logging out. I've added a graceful shutdown; if you pull now (master) do things behave better?

**Comment by GitHubGeek** [comment]
Just did a git pull - on version c287477991e12a88d627d2f5b1318814a1cfea9b now. Same errors in the logs :(

**Comment by BjarniRunar** [comment]
OK. I'm going to punt on this one - unless someone can point out what Mailpile is doing that dovecot dislikes, this isn't high priority enough to warrant further work. Sorry - just too many other issues that need attention, reducing log spam in some other app doesn't make the cut. :-)

Please feel free to re-open if you figure out what is going on.
