### ISSUE TITLE
Mails are movable to 'sent'

### ISSUE THREAD

**Issue by ashwin31** [mailpile/Mailpile#1338]
I think its better to restrict the move functionality to not to be able to move mails in 'inbox' to 'sent'

**Comment by BjarniRunar** [comment]
I disagree: when importing mail from other apps or remote servers, Mailpile may not always map things correctly and the only way to correct that is to allow manual application of the Sent tag.

In general, letting the user arrange things as he or she likes is part of the core philosophy of Mailpile. The only places where we deviate from that is where users might actually *break* something. As far as I can tell, this is not such a case.

Thanks for filing though, it's an interesting discussion and if stronger arguments are made my opinion could still be swayed. :-)
