### ISSUE TITLE
Name of account takes too much space in sidebar (beta III)

### ISSUE THREAD

**Issue by Lich4r** [mailpile/Mailpile#1339]
I could change the name of one "account" in beta II but I don't find it in beta III. The result is my entire email adress 'patati@mail.com' as the name of the account in the sidebar. Therefore the number of unread mails can't be read and the name of the account goes out of the grey rectangle.

So there are two problems here : 
- Change the name of one account 
- Sidebar is not resizable / doesn't have a features for hiding the end of a long account name

![mailpile_graphic_bug](https://cloud.githubusercontent.com/assets/9169020/8816056/e29b3154-2fd6-11e5-84b1-2da4bc2b6b3b.png)

**Comment by BjarniRunar** [comment]
I think this is addressed by @bnvk 's latest pull request. Brennan could you comment and close if you feel this was resolved by your changes?

**Comment by bnvk** [comment]
Yes, this is much better as of pull req #1335 feel free to pull. However, the collapsible item / unread number is still an issue.
