### ISSUE TITLE
'All Mail' not visible in sidebar when subtags are pull down (beta III)

### ISSUE THREAD

**Issue by Lich4r** [mailpile/Mailpile#1340]
I add an account and have many subtags on it (21). When those subtags are visible from the sidebar the 'All mail' one is not accessible. Looks like 'Documents' is the last one

<img width="224" alt="mailpile_bug" src="https://cloud.githubusercontent.com/assets/9169020/8816153/d42ddfc6-2fd7-11e5-9284-d68cfd5d5d0a.png">

(My bad if it's on purpose..)

**Comment by BjarniRunar** [comment]
That's not on purpose, looks like a CSS buglet where the bottom tools overlap the final tag. Thanks for reporting this!
