### ISSUE TITLE
Mailpile password is now different from GPG priv key password

### ISSUE THREAD

**Issue by FromBabylon** [mailpile/Mailpile#1341]
While I do understand and support this choice for security reasons I was wondering if this choice was made for any other reason ? I couldn't find it. 

I think about the guy that has bad habits and will find it a pain to have 2 strong passwords..

**Comment by BjarniRunar** [comment]
This is deliberate and is not a bug. :-)

The 2 strong passwords issue will be avoided by default for newbies, because Mailpile will generate both the keys and passwords and manages automatically. Power users can still do power user things.
