### ISSUE TITLE
Import Encryption Key just downloads file

### ISSUE THREAD

**Issue by JollyOrc** [mailpile/Mailpile#1342]
There is a handy "Import Encryption Key" button, if there is a key found in an email. Alas, it only downloads the .asc file, instead of actually importing the key to the keystore, lest alone attaching it to the correct contact.

Slightly related: I find no way to add a key to a contact...

**Comment by bnvk** [comment]
@JollyOrc thanks for filing this. It totally should work but still needs to be fixed / implemented. There's a few open issues tracking this #1142 and #647 will close this as it's a duplicate, but thanks :)
