### ISSUE TITLE
Command interface on Windows doesn't work

### ISSUE THREAD

**Issue by MartiCode** [mailpile/Mailpile#1343]
Firing up the command line interface with Beta 3 on Windows leads to a prompt that doesn't accept Mailpile commands (typing "help" shows up the MS-DOS result of the help command). Also prompt is intermittently the DOS prompt.

**Comment by BjarniRunar** [comment]
Very strange!  Which version of Windows?

**Comment by MartiCode** [comment]
Windows 8.1 64bit
This is the "off the shelf" beta 3 install - no tweaks or extra package installs. This is what the command line prompt (started in admin mode) gives when starting "mp"

Failed to configure i18n. Using fallback.
dLoading plugin: eventlog
iLoading plugin: smtp_server
Failed to decrypt configuration, please log in!
rhelp/splash: Displayed welcome message
Mailpile.py          a tool                 Copyright 2013-2015, Mailpile ehf
               for searching and                   <https://www.mailpile.is/>
           organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under the terms of either the GNU Affero General Public License as published by the Free Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>
   * You can log in using the `login` command.
   * Check your web browser!

mailpile> help
'dirhelp' is not recognized as an internal or external command, operable program or batch file.

C:\Program Files (x86)\Mailpile ehf\Mailpile>

**Comment by BjarniRunar** [comment]
Thanks for reporting this; that is very disconcerting.

**Comment by BjarniRunar** [comment]
Note: improvements to the Mailpile Windows desktop integration should take place in the gui-o-matic project so the results can be re-used by other projects: https://github.com/mailpile/gui-o-matic
