### ISSUE TITLE
Suggest encryption key that was used to encrypt to

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1344]
There is often the case where the following happen:

- Someone has sent you an encrypted email and you don't have their key
- You look them up and they have numerous keys in the keyservers
- Upon looking at the keys, more than one looks good (by date, strength, etc...)

In the event that the user encrypted the email to themselves as well as you (the recipient), Mailpile should be able to deduce which key they used to encrypt to them. With this information, Mailpile should very strongly suggest you import and use this key to send them an encrypted response!

**Comment by BjarniRunar** [comment]
Yes, absolutely. This is the same issue as #1305.
