### ISSUE TITLE
Keylookup when done with fingerprint errors out

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1345]
Currently when doing a key lookup using a fingerprint, the system returns that it cannot find any keys. However, when doing a lookup for the same fingerprint in GPG Tools it returns the expected key.

I'm not sure if this unique to my machine + GPG Tools, but I tested other keys (even ones already in my keychain) and none of them show results in the keys in the lookup modal. Upon looking at the CLI, i'm not seeing any errors!

**Comment by BjarniRunar** [comment]
I have seen this now and then, I think our time-outs may be too short. Haven't managed to reliably reproduce though. Thanks for reporting.
