### ISSUE TITLE
Composed mail being auto tagged as spam does not send

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1346]
A fresh message (not from a previous thread) that I just composed, did not show the "Outbox" in the sidebar. Upon looking for it in "Sent" I could not find it. Upon running "sendmai" it returned "True" Upon further investigation, the message was in my Spam folder with another autotag (as well as Spam tag) applied.

I tested with the same message a second time, and it happened again.

**Comment by BjarniRunar** [comment]
That sounds very exciting. Thanks for reporting this, I'll have to take a look and see what might be causing it.  Is there any possibility this was user error - that you tagged it as spam yourself by accident? Seems unlikely, but have to ask. :-)

**Comment by bnvk** [comment]
@BjarniRunar absolutely not an intentional thing- I wasn't adding or doing anything with tags- literally just pressed "send" It recently happened with another unrelated message as well.
