### ISSUE TITLE
Make it possible to remove e-mail accounts

### ISSUE THREAD

**Issue by fvanrenterghem** [mailpile/Mailpile#1350]
In Beta 3, I can't find a way to delete an email account after having set it up. I tried setting up 2 - just to rule out the app doesn't like ending up with zero accounts. Disabling the account does not remove the associated emails from the inbox.

**Comment by BjarniRunar** [comment]
You can't find it because this feature doesn't exist yet. :-)  Thanks for filing, I am going to rename this issue to reflect the missing feature, I don't think we had a bug tracking it yet.

**Comment by yagilm** [comment]
is there a workaround for this?

**Comment by BjarniRunar** [comment]
You can manually delete the profile/vcard using the `mailpile>` prompt and clear out the relevant bits from the `routes` and `sources` config section.  It's rather klunky.

There is no way yet to delete e-mails that have been downloaded, short of wiping the entire Mailpile data folder (yes, this is a big issue).

**Comment by Beast141** [comment]
Hi guys, i too am looking for a way to delete my one email account because id like to redo it with tags enabled so i can see my imap folders. Please can you tell me how to remove the account, whether its through the interface or through the terminal.. I appreciate it.

**Comment by hermann88** [comment]
same here, need to delete account to activate "Enable Visible Mailpile tags for all folders".
You can check the box after you added a new account, but it doesn't change anything.
Delete account would be a workaround to get this fixed, if it would be possible at all...
thanks in advance, btw. nice project!

**Comment by kimwue** [comment]
+1

**Comment by alexthemitchell** [comment]
+1

**Comment by JocelynDelalande** [comment]
> You can manually delete the profile/vcard using the mailpile> prompt and clear out the relevant bits from the routes and sources config section. It's rather klunky.
> 
> There is no way yet to delete e-mails that have been downloaded, short of wiping the entire Mailpile data folder (yes, this is a big issue).

@BjarniRunar Could you detail a bit on how please ? (if you do, I'll add it to https://github.com/mailpile/Mailpile/wiki/Configuring-mailpile)

**Comment by BjarniRunar** [comment]
Note: There is a lot of overlap between this issue and #1173.

**Comment by BjarniRunar** [comment]
Moving this to 1.0 - we probably won't handle duplicate accounts gracefully ( #1867), so being able to remove one becomes more important as a "workaround."

**Comment by Kabouik** [comment]
@BjarniRunar, does this delete downloaded emails for the deleted accounts as xell (i.e., free some disk space and *totally* delete the account from Mailpile data)?

**Comment by BjarniRunar** [comment]
@Kabouik It gives you the option to move mail to the trash. The trash is then emptied "later" if you enable deletion, which will purge the e-mails themselves.
