### ISSUE TITLE
Allow to: from: search queries to match domain names

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1352]
Currently, using the `to:name@email.com` and `from:name@email.com` search queries does not accept wildcard queries like `from:*@email.com` however, this would be really useful to bulk sort "all contact from a given company / org / domain into one search"

**Comment by BjarniRunar** [comment]
Wildcards are never going to happen, because of the way the search index is built. It just can't do that.

However, making it possible to search from/to/... by domain is easy and accomplishes what you want. I'll rename the issue; I agree this would be very useful.

**Comment by BjarniRunar** [comment]
I think this was fixed by #2057. Thanks @takano-akio !
