### ISSUE TITLE
How to start from scratch?

### ISSUE THREAD

**Issue by kramer65** [mailpile/Mailpile#1353]
I've been following this project from the start, and installed some early version a while back. Since it wasn't quite ready yet back then I decided to wait. Today, while fighting with Thunderbird I decided I could give mailpile another try. So I deleted the version I had installed, downloaded the latest version and installed that again.

Unfortunately it then asks me for my passphrase, and I totally can't remember what I gave as a passphrase the last time. 

Does anybody know how I can remove all data and put in a new passphrase? I'm running on OSX 10.10.4. All tips are welcome!

**Comment by gdrooid** [comment]
You have to remove `~/.local/shared/Mailpile/`.

**Comment by johannes1** [comment]
That's the directory for Linux.

For OS X, you have to delete `~/Libary/Application Support/Mailpile`. If that does not work for you, check if there is a `~/.mailpile` directory and delete it, too.

**Comment by kramer65** [comment]
Awesome, thanks!

I just configured my first email. If this works good, I'll probably switch over with my main mail pretty soon.. :-)
