### ISSUE TITLE
add "back" button to thread view

### ISSUE THREAD

**Issue by otosciurus** [mailpile/Mailpile#1354]
I noticed that the thread view currently does not have a back button on the top.

It is possible to use the browsers back button, however, I think many users have accustomed to using an in-page back button (similar to what gmail provides).

In addition, an in-page button also significantly reduces the distance the mouse pointer has to be moved when a user switches back from thread view to inbox/label view.

Possibly related to #1256

**Comment by bnvk** [comment]
Right you are, this is related to #1256 and one of the reasons this has not been implemented, as the message forward / back, seems a more sensible use for this sort of button.

I don't think replicating something that is basically the browsers back button for just that behavior. On mobile apps this makes more sense. Happy to hear counter arguments / user demand though.

**Comment by BjarniRunar** [comment]
Closing to tidy up, this is now tracked in #1256.
