### ISSUE TITLE
Left Menu disappears when browser window is resized

### ISSUE THREAD

**Issue by JoEiner** [mailpile/Mailpile#1355]
When I open Mailpile with a large browser window and then resize the window without reloading the browser page, the left hand side menu disappears after a certain treshold. When I reload the page afterwards, it becomes visible again.

Resized Window before reloading:
![screen shot 2015-07-29 at 20 56 42](https://cloud.githubusercontent.com/assets/6161032/8967120/66feeb7a-3635-11e5-866a-e724010726b7.png)

Resized Window after reloading:
![screen shot 2015-07-29 at 21 06 55](https://cloud.githubusercontent.com/assets/6161032/8967228/feb0f332-3635-11e5-86a8-efd78b240d3f.png)

Mailpile Version: Beta III

**Comment by BjarniRunar** [comment]
This isn't exactly a bug, this is unfinished work towards making the UI responsive and adapt to smaller screen sizes. However, until it's finished, it is admittedly indistinguishable from a bug. :-)

I'm leaving this open as a reminder to either fix this behaviour by finishing the responsiveness work, or disable it.

**Comment by BjarniRunar** [comment]
I think this is sorted. Thank you for filing this!
