### ISSUE TITLE
Left Menu behind top bar when browser window not maximized

### ISSUE THREAD

**Issue by johannes1** [mailpile/Mailpile#1356]
When I do not maximize my browser window (below a certain treshold), the left menu disappears behind the top bar and the Drafts and Inbox menu item are no longer visible.

![screen shot 2015-07-29 at 21 06 55](https://cloud.githubusercontent.com/assets/6161032/8967497/944acf48-3637-11e5-8dc5-dda5bab8402a.png)

Tested with today's nightly build!

**Comment by bnvk** [comment]
This is pretty much the same bug as #1355 so closing this issue to track it on that one!
