### ISSUE TITLE
Make mailpile not use CRLF line endings

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1357]
I'm filing this on behalf of someone who receives messages from my Mailpile and uses Mutt as a client. They ask that we:

```
not use CRLFs line endings, as many of us see your messages polluted with lots of "^M" characters at the each of each line, making it difficult to read. Please adhere to the standards.
```

Not sure how you feel about this @BjarniRunar i'm sure you've already considered / weighed this. Feel free to close.

**Comment by BjarniRunar** [comment]
Something else msut be going on here; https://tools.ietf.org/html/rfc2822#section-2.1 explicitly states that e-mails should use CRLF line endings.  A mail client that cannot handle those is pretty clearly broken; however as a long-time mutt user, I am pretty sure mutt handles CRLF line endings just fine.

So I don't know why your friend is having problems.  Without further details, this bug isn't actionable. Please feel free to re-open or file a new one if further debugging at his end sheds new light. :-)
