### ISSUE TITLE
Improve visibility of "Notifications" for better visability

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1361]
The notifications that pop-up in the bottom right hand corner of the screen are not ideal IMO. I designed them hastily and didn't take into account factors like if a user has more notifications than can fit on screen. Also, beyond a few messages, the white space gaps between are use more space than they should be.

![screen shot 2015-08-02 at 3 35 50 pm](https://cloud.githubusercontent.com/assets/48677/9026370/379bd4f6-392d-11e5-8438-ee4a8b8a9b63.png)

Here is a few minor changes that I propose to improve the notifications

![notification menu](https://cloud.githubusercontent.com/assets/48677/9026499/89f39b54-3931-11e5-8800-d3e235ef736a.png)

With this approach a user can dismiss all messages at once. And once the stack grows to fill browser window it can push older messages out of the container.

**Comment by BjarniRunar** [comment]
Agreed!

In general, borrowing any and all applicable UI features from Android notifications would be worth doing IMO, in particular making it possible to hide/minimize the notifications without dismissing, a dismiss-all button.

And of course more and more useful notifications, but that's a larger task.

**Comment by BjarniRunar** [comment]
Note: I've made progress on this in my local repo, I don't recommend anyone tackle it to avoid duplicate effort
