### ISSUE TITLE
sent mail is added to INBOX

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1365]
Even though I have INBOX and Sent mbox files from thunderbird mapped to mailpile as source, sent mail is added to INBOX and not Sent mbox file.

**Comment by BjarniRunar** [comment]
Is this happening for all sent mail, or only mail you send using Mailpile?

If the latter, this is probably "expected", albeit unfortunate. Mailpile will by default bcc you on sent mail, which will make it appear in the INBOX folder when Thunderbird downloads it, thus causing the tagging you report. The bcc behaviour can be disabled, but you probably don't want to do that while you are still using other mail clients (as it's the only thing that guarantees the sent mail appears in all clients).

**Comment by pravi** [comment]
Ok. I have to live with it then. May be its too much hassle, but can there be one more mail source for just send mail? I'd like to use an imap account for sent mail as well so all clients see it. This could be activated only if local mailboxes are configured.

**Comment by BjarniRunar** [comment]
When Mailpile learns to sync data back to IMAP servers (instead of just reading from them), this will improve. Closing this as "Won't fix... yet". :-)
