### ISSUE TITLE
Need to build signed Mac OS X packages

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1366]
The Mac packages do not run on recent versions of OS X without disabling all sorts of scary sounding code signing checks which Apple have switched on by default.

Obviously we don't want to tell users to do things which degrade their security, so we're going to have to figure out how to sign our app packages properly.  This is a showstopper for 1.0 on the Mac.

**Comment by NoahAndrews** [comment]
While it would certainly be ideal to sign the OS X builds, it is possible to run unsigned code without disabling Gatekeeper. If you access the Security and Privacy System Preferences pane after attempting to run an unsigned program, there will be a button allowing you to launch the program, which will whitelist the application for Gatekeeper.

**Comment by AngusHardie** [comment]
You can also right click on the app in question and choose open 

Apple has a page about it:
https://support.apple.com/en-gb/HT202491

This isn't as good as getting the thing signed, but is relatively easy to explain and technical users may already know it.

**Comment by NoahAndrews** [comment]
I'm pretty busy, but I'm taking a look, starting with following the Mac build instructions. Why is the brew-package script written for and tested on such an ancient version of OS X?

**Comment by NoahAndrews** [comment]
I'm beginning by making that build script compatible with the current version of OS X.

**Comment by NoahAndrews** [comment]
As for the actual task of signing the OS X packages, that will need to involve paying Apple a $99/year fee for their Developer Program. If I sign up on behalf of Mailpile, can I be reimbursed once I hand the credentials over to you?

**Comment by NoahAndrews** [comment]
Is there a reason that the brew-package script uses symlinks 1.2 instead of 1.4? 1.2 has a makefile incompatible with the current version of OS X.

**Comment by BjarniRunar** [comment]
Hi @NoahAndrews! Thanks for looking at this; it is most appreciated.

I don't think you can (or should) sign up on behalf of Mailpile, if they even allow that that would be a rather major security flaw in and of itself. What I was hoping for here, was enhancements to the script and some docs so once Mailpile has an app ID, we can make our own builds.

The reason the build is/was for an ancient version of Mac OS X, was to guarantee folks can install the app on ancient versions of Mac OS X. Developers live in a special imaginary world where everyone upgrades their laptops all the time, I had a desire to target non-technical users and make something that would actually work on older machines too, so I used an older box for both testing and packaging. At this point I've conceded that I'm too resource constrained to do everything perfectly, so if volunteers step up that don't value this I won't push the issue. :-)

This issue is not super high priority at the moment though, because user tests showed that the contents of the package itself were not really acceptable - the way we launch Mailpile, the app startup/shutdown experience, etc etc. were just not good enough. We need to rethink our mac support quite a bit. I think I've failed to file an issue for that describing what I think needs to be done - I'll go fix that and link the issue from here.

**Comment by NoahAndrews** [comment]
What I was thinking there was that I'd make a fresh clean Apple ID, use it to sign up for the dev program, and then send you the credentials once I was happy with how it was working (or someone else was ready to work on it). Once I did that, you could change the email address to the Mailpile one, and email Apple to request that all previous signing certificates be revoked. At whatever point they asked for a name, I would put "Mailpile". I'm not sure how Apple would prevent that besides just saying not to do it. And if I had your permission, I wouldn't be doing anything wrong. Let me know if I'm missing something.

To be clear, my intention was ultimately to do exactly what you're hoping for. Having access to the certificate would be a temporary measure while I got the scripts working. BTW, I've already started on a generate-package script. 

My mom was still using Snow Leopard until about a year ago, so I definitely understand. Still, you're not going to get too much developer support by requiring that the build scripts be run on old versions. Obviously that was unintentional, but writing and testing the build scripts on current versions of OS X would be prudent going forward.

Heh. I couldn't agree more. I downloaded the most recent Mac version and couldn't get it to work at all! The version I packaged myself wouldn't work either. Neither of them seemed to be starting the server.

**Comment by BjarniRunar** [comment]
@NoahAndrews - if you want to sign up for an Apple ID and transfer that to us, we'll reimburse you. Just double-check to be sure it's possible!

I'll gladly accept your help on that aspect of the problem, getting scripts that can generate signed packages will be useful no matter what else we do.

**Comment by NoahAndrews** [comment]
So, my plan won't work. Apple demands legal names. If you're not an officially registered business, only your personal name can be attached to the App ID. Either way, I can't be the one to sign up for the account. 

Does Mailpile Ehs. have a DUNS number? That's the only way you can have a company name as the listed developer.

**Comment by sg-s** [comment]
Is this the only thing preventing packages for macOS? I'd rather have an unsigned build that I can verify manually than having no package at all.

**Comment by BjarniRunar** [comment]
Hi @sg-s ! No, it is not.

Our user-experience is terrible and confusing since we don't have anything resembling a native GUI. It's bad enough, that we're better served recommending techies pull from github and ask everyone else to please wait.

Note that the OS X Desktop milestone is incomplete, I just created it this week and am still in the process of curating our issues and filing issues where they are missing.

**Comment by sg-s** [comment]
HI @BjarniRunar , thanks!

But perhaps mention somewhere that macOS users can still use Mailpile -- all they need to do is clone the repo and `./mp`

**Comment by BjarniRunar** [comment]
When we publicize a release candidate, we will be sure to do that.
