### ISSUE TITLE
SCARY WARNING relating to gpg seen in CLI

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1367]
Was just viewing a few email threads, new msgs downloading from server, and viewing one msg which was encrypted and I noticed this:

```
mailpile> SCARY WARNING: FAILED TO REAP THREAD <StreamReader(gpgi-stdout-parsed(gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys), started 4869459968)>(gpgi-stdout-parsed(gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys)/read, lines=True)
```
Figured I would file it since it read "SCARY WARNING"

**Comment by BjarniRunar** [comment]
Thanks for filing this. Is this invoking the qubes wrapper, or normal gpg?

**Comment by bnvk** [comment]
@BjarniRunar no, this is on my MacOS install of Mailpile. I can't get Mailpile to function properly on Qubes machine so assume all bugs I file do not pertain to that unless explicitly stated

**Comment by BjarniRunar** [comment]
It sounds like your Mailpile was just so busy it took over 15 seconds (the time-out after which a SCARY WARNING is printed) for that particular job to get scheduled and to complete.

This is probably harmless and I've tweaked things to make the scary warning less scary and even more rare.  Thanks again!
