### ISSUE TITLE
mailpile doesn't support STARTTLS for imap

### ISSUE THREAD

**Issue by FirefighterBlu3** [mailpile/Mailpile#1374]
needs STARTTLS support added to support modern mail as plain "SSL" is deprecated

**Comment by BjarniRunar** [comment]
Why in the world would plain SSL/TLS be deprecated?  Citation needed, good sir!

I'd argue quite the opposite; STARTTLS in all protocols is a horrid kludge and hack compared with opening a secure circuit first before speaking any IMAP (or POP3 or SMTP) at all. STARTTLS in all protocols suffers from man-in-the-middle vulnerabilities, where an interfering party can suppress and prevent the STARTTLS option from being listed in server capabilities and the STARTTLS command from working; some mail clients may then "fall back" to clear-text logins.

Anyway, regarding STARTTLS, it does actually work as of a couple of weeks ago. You may need to upgrade.

If you select IMAP as a protocol and the IMAP server reports it supports STARTTLS, the connection will be upgraded automatically. You can mandate use of STARTTLS (and avoid the attack I describe above) by ticking the appropriate tickbox in the form.

If it still doesn't work and you are running the latest code... then maybe you've found a bug! Please feel free to reopen this or file a new issue. Thanks for filing!

**Comment by FirefighterBlu3** [comment]
Plain SSLv3 is deprecated in favor of TLS. that is, don't write software that speaks raw SSL protocol such as imaps or smtps. Use STARTTLS to initiate the SSL session. I disagree with your position. SSL2 and SSL3 are considered broken and not fixable as of the attacks in the last year.

TLSv1.2 doesn't have known MITM vulnerabilities. OpenLDAP is deprecating ldaps in favor of starttls. Dovecot is deprecating imaps in favor of starttls. OWASP rules for implementations direct you to not use SSL 1, 2 or 3 and provide strong support for TLSv1.2 with only backwards support for <1.2 as needed. Under no circumstances should SSLv2 or SSLv3 be enabled. Plain SSL does not support SNI which is only feasible with TLS. OSNexus is removing SSLv2/v3 support for TLS. Postfix deprecates ssl in favor of tls. SSL code removed from ejabberd in favor of TLS (this actually happened 9 years ago). Apache organization deprecated SSL in favor of TLS by default in numerous products.

https://blogs.akamai.com/2014/10/ssl-is-dead-long-live-tls.html
https://blog.talpor.com/2015/07/ssltls-certificates-beginners-tutorial/

I'd rather you just google "ssl deprecated in favor of tls", the first few pages are full of big names and well known projects.

I'm quite new to Mailpile but decently versed in many of the things involved. I spent a few hours digging into Mailpile but couldn't convince it to connect to either an SSL or TLS dovecot service which works dandy for other clients. It simply insisted on timing out or aborting the connection promptly as STARTTLS was offered. There may be mismatches under the hood that I haven't found yet. I did have to fix some code such the rfc822 module iirc, as that code was deprecated way back in python 2.3. The oldest python I can test this on is 2.7 and even that took a bit of shoehorning.

I cloned MP a few hours before filing this issue and last pulled and tested it a few hours before this reply.

**Comment by BjarniRunar** [comment]
OK... you're ranting against SSLv2 and SSLv3, which will get no argument from me. We haven't yet made sure SSLv2 or SSLv3 are not used (Mailpile still uses library defaults, which are widely considered insecure now), but that is a known issue which will be dealt with.

Those early versions of TLS (which used to be called SSL) should not be used. That does not change my stated opinion that STARTTLS is a horrible kludge and it would be better to make a TLS connection first and speak IMAP second. That's all I was saying. Making such a direct connection is far from deprecated, it is still preferred.

The main takeaway I get from this, is I should avoid using the abbreviation SSL anywhere a user can see it, as they might misunderstand what is going on under the hood. People do love jumping to conclusions when they think they've found a security vuln! So thanks for that, I'll file an issue to fix the naming.

I also have noticed time-outs and other connection issues in the current IMAP connection code, thanks for reporting your experiences there.
