### ISSUE TITLE
Strings use accents grave as quotation marks

### ISSUE THREAD

**Issue by RiseT** [mailpile/Mailpile#1375]
I've noticed that Mailpile's original (i. e. English) strings use accents grave **( ` )** instead of real quotation marks, which is very wrong.

Valid options are

- **Single "dumb" quotes ( '...' )**
- **Double "dumb" quotes ( "..." )**
- **Typographic (curly) single quotes ( ‘...’ )**
- **Typographic (curly) double quotes ( “...” )**

The first two options are quick & dirty, but better than misusing accents, the latter two are  hard to reach on some keyboard layouts (might want to use copy & paste), but pretty & typographically correct.

Currently only 4 strings use quotation marks, so this should be quick to fix.

See http://quotesandaccents.com/

**Comment by BjarniRunar** [comment]
Hello! Thank you for your comment!

This convention is being used as a signal to differentiate commands which are to be literally typed/copied into a command shell, from other types of text.

Technical folks will recognize this as being the same syntax as is used for the same thing in Markdown. Non-technical folks will not interact with these strings and messages anyway.

As far as I know, the ability to accurately communicate this concept through punctuation (a literal command to be typed) is a facility traditional English lacks. Until someone fixes English, I am inclined to continue using this workaround.

I would also strongly encourage our translators (in case any happen to read this) to preserve this syntax and not assume this is simply a mistake; it's not.  Cheers! ;-)

**Comment by breard-r** [comment]
Dear RiseT, in your examples you uses three dots ( “...” ) instead of an ellipsis ( “…” ), which is **not** typographically correct. By the way, did you know it is in fact very easy to write special characters using a [compose key](https://en.wikipedia.org/wiki/Compose_key)?

**Comment by BjarniRunar** [comment]
@breard-r Please be nice. In my opinion that comment was neither on topic nor helpful; we're not competing for pedant points here, we're trying to build useful software.

**Comment by RiseT** [comment]
Hi Bjarni,

Thanks for your reply!

*This convention is being used as a signal to differentiate commands which are to be literally typed/copied into a command shell, from other types of text.*

Wouldn't normal quotation marks achieve the same thing? Any other software I've translated (which are a few) uses normal quotation marks for that purpose. If the backticks themselves weren't shown in the application and induced some sort of special formatting instead, it would be different of course (is this the case?).

*I would also strongly encourage our translators (in case any happen to read this) to preserve this syntax and not assume this is simply a mistake; it's not.*

Well, even if these were normal quotation marks, a translator would replace them with their local version of quotation marks as this is part of their job.
Anyway, if the usage of backticks is of importance, I suggest you put that fact into the string's instructions at Transifex.

**Comment by BjarniRunar** [comment]
Yes, I'm starting to realize that I need to provide our translators with guidance and explanations (and discuss these things with people who may know better). I don't know how I will find the time, but I *am* aware of the issue. Thank you for reaching out!

**Comment by RiseT** [comment]
@breard-r I'm fully aware that I'm using dots here instead of ellipsis. But since this is an issue tracker and not a master's thesis, I have no ambitions in writing typographically correct.

**Comment by RiseT** [comment]
@BjarniRunar I guess it won't be *that* much work, as only a few strings would need some sort of instructions or explanation. But thanks for considering!

**Comment by RiseT** [comment]
@BjarniRunar I kindly suggest you check at least the 'Issues' at Transifex as a start. Just browsed them, and there is a bunch - some as old as one year - which never got resolved or replied to.

https://www.transifex.com/otf/mailpile/translate/#issues
