### ISSUE TITLE
Messages pile up in Outbox, aren't send (automatically)

### ISSUE THREAD

**Issue by tatome** [mailpile/Mailpile#1378]
Hi, like #1038 and #1170, I'm having trouble with e-mail being relegated to Outbox instead of being sent.  The thing is: I'm sure my settings are ok, because when I do a `sendmail` on the command line, mails are sent just fine.

I checked out Mailpile from github yesterday and I'm on an Arch Linux system.

**Comment by BjarniRunar** [comment]
As described, this is almost certainly caused by #1379. Thank you for reporting this!

**Comment by tatome** [comment]
Oh, I'm sorry, I only found those closed issues, not the open one.

**Comment by BjarniRunar** [comment]
That is perfectly understandable, as I just created the other issue! :-) I did that to better describe what is going on. The root cause is the same; I don't see a need to keep multiple issues open for the same thing.
