### ISSUE TITLE
Periodic background jobs fail to run

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1379]
There are multiple bug reports indicating that the periodic background job scheduler is failing in some cases. This includes:
- Failing to periodically run the spam filter's statistical training (autotagger)
- Failing to empty the outbox

This needs to be investigated and fixed ASAP.

**Comment by tatome** [comment]
Let me know if you need any info or debugging.

**Comment by BjarniRunar** [comment]
I don't have any current bug reports on this, and haven't seen it myself for quite some time. Closing as unactionable.
