### ISSUE TITLE
A Better Approach to "Forwarding" in Multi-User systems

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#138]
Instead of simply forwarding a mail thread, I'd like to be able to say "Let my colleague Z see and respond in this thread too" 

This feature (in a multi user environment) could function a bit differently than current email "forwarding" where by instead of sending a copy of an email in the content there could be a simple "notification" layer that shares the original message with the new user.

UDPATE: This functionality only really applies to "forwarding" on a multi user system say for a small business or organization- forwarding to email@otheremailplatform.com will just default back to normal forwarding!

**Comment by BjarniRunar** [comment]
Based on all the designs and discussions over the past year or so, I think it is safe to say multi-user will not be implemented in a way that makes this possible.

Compartmentalization is very important to prevent bugs of all sorts, so a multi-user install of Mailpile will most certainly consist of multiple independent Mailpiles, making this kind of direct sharing impossible.

Something like what @fjfnaranjo describes could well happen at some point though.
