### ISSUE TITLE
Translatable strings typo collection

### ISSUE THREAD

**Issue by RiseT** [mailpile/Mailpile#1387]
Typo in both XML key and string.
- Unthreaded %d messaages [messages]
- Failed to loaded metadata index [load]
- Failed to started the web server [start]
- Displayed settings [Display settings?]
- Server rejected recpient [recipient]
- Required paramter missing. Required parameters are: %s [parameter]
- Enabling spambayes autotagger [SpamBayes]
- Found key in DNSPKA [DNS PKA]
- Parts of this message has a signature that are invalid or bad ['Part' or 'have'?]
- Watch out, the signature was made with a key that has beenrevoked- this is not a good thing [been revoked]
- Filters are a very powerful aspect of Mailpile that is not yet available to non techie users. However, if you are technically inclined [there's obviously missing something at the end]
- Error accesing your encryption key [accessing]
- Dont look now, we are copying things [don't]
- Damn kids. Theyre all alike. [They're]
- All of your config settings & passwords are encrypted with AES 256 [AES-256]

**Comment by BjarniRunar** [comment]
Thanks for reporting these.

One question - are you now duplicating the issues from Transifex? I'm aware there are a great deal of issues filed there, but I haven't yet had a look... I worry it isn't going to make my job easier if I have to close issues on both systems. If you're actually going to copy all the issues from Transifex  over here that *will* actually help, but if it's spotty and I have to look at both and compare it's probably best not to. Does that make sense?

Also, sorry if responding here (and on Transifex) is taking me a while. If you're wondering why, please know that although I truly appreciate your efforts, I am bit burnt out and am trying to take it easy for a bit: <https://www.mailpile.is/blog/2015-08-18_On_Crowdfunding_and_Burnout.html>

**Comment by RiseT** [comment]
@BjarniRunar You're mostly correct - except for #1384 , those are duplicated from Transifex.

My line of thinking has been that some of these Transifex issues have been there for a rather long time and putting them here makes them more visible to someone who is able and willing to correct them.

I've only included Transifex issues that have a clear-cut solution, i. e. typos. In that regard, the list to my knowledge is complete. Others, asking for context and other questions and suggestions, weren't included.

Don't worry about responding times. It's not my intention to push you. Take all the time you need.

In order to make up for any trouble duplicating the Transifex issues may have caused, I've just done a PR which hopefully fixes the complete list of typos of this issue (plus a couple more I've found along the way), except for one (the uncomplete sentence - I have no idea how to complete it).

Regarding those open issues at Transifex which now can be closed:
I could either message the corresponding translators and ask them to close those issues (not sure if all of them are still available, though) or you could temporarily elevate my privileges at Transifex to a level that allows me to close them myself. That would reduce the pile of open issues there somewhat.

**Comment by BjarniRunar** [comment]
I nuked that partial string in 0780151721bbf6ad51c35837c54775748b307f12.

The .pot has been rebuilt and pushed to Transifex. :-)
