### ISSUE TITLE
Init on boot

### ISSUE THREAD

**Issue by timotk** [mailpile/Mailpile#1391]
Hi!

I'm using Mailpile on a Raspberry pi, and it works fine (even with the Nginx proxy), but I have to start the program manually every time, which is kind of annoying.

What I've done:
- Searched for an init script, but  only found [this](https://github.com/coeusite/mailpile-debian-init-script). It uses screen, which I think is unneccessary.
- I've also tried to run Mailpile with Gunicorn (`gunicorn mailpile:app`), but this gives me a `TypeError: Application object must be callable.`
- I could use cron, but what if Mailpile crashes? Checking it every couple of minutes would be a stupid solution.
- Looked through the manual and issues, but couldn't find anything about it.

I would like to run it as a service so I can restart it any time. How do you guys do it?

**Comment by root-io** [comment]
If your OS support systemd, google `systemd service files`and try something like:

```
[Unit]
Description=Mailpile app
After=nginx.target

[Service]
ExecStart=YOUR_MAILPILE_COMMAND
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by BjarniRunar** [comment]
Agreed, this needs to be done in some sort of standard way in Linux packages. We will probably need to have two packages, a `mailpile-server` package for folks running Mailpile headless and remotely, possibly on behalf of others, and `mailpile-desktop` for people using it locally.

**Comment by BjarniRunar** [comment]
Note that this sort of exists - "multipile" is a thing. See #1538 for progress on documentation etc.

**Comment by BjarniRunar** [comment]
After thinking about it a bit, I'm closing this issue.

The current strategy is multipile, which integrates with an existing web-server. So Mailpile itself won't start on init, the webserver will take care of it as needed.
