### ISSUE TITLE
using Mozilla Autoconfiguration for determining mail server settings

### ISSUE THREAD

**Issue by ferriswheel** [mailpile/Mailpile#1393]
just installed and now testing mailpile. 
the auto setup did not find my imap server settings.

i have used the mozilla autoconf setup for many years for myself and tech support clients.
mozilla created this method as an additional means of helping thunderbird users.
it does require a subdomain in the form of autoconfig.<domain name> and a couple of files on a webserver at that url.
no other involvement from mozilla and no secrets are kept in the config xml file. 

see  https://wiki.mozilla.org/Thunderbird:Autoconfiguration
and  https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

regards

**Comment by sycoso** [comment]
FYI: I'm trying to implement that :)

**Comment by BjarniRunar** [comment]
@sycoso excellent!

The autodetection code actually has FIXMEs in place for this, in `mailpile/plugins/setup_magic.py`, which is where most of the autoconfig magic takes place. Please feel free to find me on IRC (BjarniRunar on #mailpile on Freenode) if you have any questions at all.

**Comment by sycoso** [comment]
This issue should be closed, right?

**Comment by ferriswheel** [comment]
hello,

i tested the master branch and found that moz autoconfig did not work.
i suspect that the port number specified in my config.xml file was ignored.
i suggest using all the the values in the xml file to give a user the control they require.
 

regards

**Comment by sycoso** [comment]
What exactly do you mean by "did not work"?
I just tested it and it seems to take the port from the config…

**Comment by ferriswheel** [comment]
On Wed, 30 Sep 2015 08:04:24 -0700
Jannis <notifications@github.com> wrote:

> What exactly do you mean by "did not work"?
> I just tested it and it seems to take the port from the config…
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mailpile/Mailpile/issues/1393#issuecomment-144439287


hello,


i am using non-standard ports.
on one email server i have multiple instances of imapd,  one per domain.
each domain is assigned a different port number.
thunderbird responds appropriately by reading the port number from the config.xml file.

i am hoping mailpile, in the next few months, is working sufficiently well to start trials in a community group.
mailpile would become the recommended and supported email application with a potential 19K user base.
       

regards

**Comment by sycoso** [comment]
Oh, I think I get it… do you have multiple <emailProvider>s in your config.xml? It's just that I've never seen that before.

That sounds great :)

**Comment by ferriswheel** [comment]
hello,


i have one config.xml file per domain with one 'emailProvider id' entry.
however, the set of domains use different instance of imapd configured to
match the values (port, etc) in the respective config.xml file.
the mta and mda may have different ip addresses and different locations
specified by the 'hostname' entry  in the config.xml file

on first reading of your question i could not see how multiple
'emailProvider id' entries would work. maybe that could done with all
autoconfig urls reading a common config.xml file as configured in the
web server. 


regards

**Comment by sycoso** [comment]
Hi,

Then I don't know what's going wrong. Would it be possible to post the domain so I can test it or would you rather not do that?

I don't know if anyone has ever done that but I know that Mailpile wouldn't support it right now.

**Comment by BjarniRunar** [comment]
If you don't want to post your domain to the github for all to see, perhaps come to #mailpile on Freenode and chat with myself or @sycoso there?  This is hard to fix with any confidence without having a proper test case.

**Comment by ferriswheel** [comment]
hello,

sorry for delayed reply.

try autoconfig.jetechserv.com


regards

**Comment by carlos157oliveira** [comment]
This issue hasn't seen any recent activity. Maintainer, should you close?
