### ISSUE TITLE
Please add target .NET Framework 4.6

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#1394]
![capture](https://cloud.githubusercontent.com/assets/13931231/9592217/af5d6a92-5073-11e5-87fe-778693d6fe5a.PNG)

**Comment by BjarniRunar** [comment]
I don't know if we can, for licensing reasons. This will need more research.

**Comment by fd74a05d0b** [comment]
You have compiled it with older .NET Framework. How could there be licensing problems?

**Comment by 07d6** [comment]
Any update?

**Comment by BjarniRunar** [comment]
Haven't had time, sorry. PRs are welcome!
