### ISSUE TITLE
"Require STARTTLS encryption" not set when autodetecting

### ISSUE THREAD

**Issue by sycoso** [mailpile/Mailpile#1401]
When a server only provides IMAP with STARTTLS and no IMAP/TLS, "Require STARTTLS encryption" is not ticked although that seems like the option you would want to default to. That is the case for versatel.de among others.

**Comment by BjarniRunar** [comment]
We should probably upgrade the settings for a mail source to enable this once we have discovered that STARTLS is indeed available - the current approach is to opportunistically use it if possible, but it seems unlikely (and possibly a security risk) if that then gets downgraded again at a later date.

**Comment by BjarniRunar** [comment]
This is fixed in my local tree. Will push up soon.
