### ISSUE TITLE
Incorrectly parses mail names, sending mail to incorrect addresses

### ISSUE THREAD

**Issue by dkm** [mailpile/Mailpile#1406]
I'm using master branch (c95de4) and discovered a nasty bug.
If I'm sending a mail to : 
  `"foo@toto.com" <bar@tata.fr>`

The mail will be sent to the address `foo@toto.com`. This can be abused if a valid email is used in the name... Mostly, this causes incorrect bounces whenever someone has a `@` in the name string.

**Comment by BjarniRunar** [comment]
Thank you for filing this. This is indeed a nasty bug.

**Comment by karlp** [comment]
Possibly related to #1271

**Comment by BjarniRunar** [comment]
I think I've got this one fixed, watch for my next big push.

**Comment by dkm** [comment]
great! thanks ! will definitely test it !

**Comment by dkm** [comment]
Looks like the bug is still here, or at least something with the same symptom: in the Cc field, there is a "someone else@gmail. com" (I don't know which MUA did that....) and mailpile is all lost...

Cc field (names and mail have been changed, of course)
```
"Cadeau R Bla" <someone1@yah.fr>,
 Someone <someone2@yah.fr>, Cla <hey@hey.fr>,
 "Foo Bar" <someone3@gma.com>,
 "Nicolas Test" <test@gma.com>,
 BarFoo <toto@gma.com>,
 Pouet Pouet <pouetpouet@gma.com>,
 "fofo barbar@gma. com" <barbar.fofo@gma.com>,
 "another guy" <another.guy@gma.com>
```

And mp header are:
```
x-mp-internal-rcpts: .....
 barbar.fofo@gma.com, ...., barbar@gma., ....
```

**Comment by dkm** [comment]
@BjarniRunar maybe I should ping here instead of IRC, as you're currently away :)
