### ISSUE TITLE
Emails to myself do not end up in inbox

### ISSUE THREAD

**Issue by Railslide** [mailpile/Mailpile#1407]
If I try to send an email to myself, such email does not show up in inbox when using Mailpile. If I check my mailbox from another program/interface the email is there, but for some reason Mailpile doesn't see it. 

Running rescan from the CLI interface shows that there is a new message

```
{
    "mailboxes": 1, 
    "messages": 1, 
    "vcard_sources": [
        "gravatar", 
        "mork", 
        "gpg", 
        "carddav"
    ], 
    "vcards": 0
}
```

but nor the GUI nor the CLI seems to acknowledge that message in the inbox.

**Comment by BjarniRunar** [comment]
This is expected behaviour; if the message was sent from Mailpile then Mailpile already has it filed away (in Sent) and it won't show it to you again even if it rediscovers it later on at some point.
