### ISSUE TITLE
Receiving my own sent email / email not parsed as sent by other mail clients

### ISSUE THREAD

**Issue by Railslide** [mailpile/Mailpile#1408]
I am using master branch (c95de4cbe) and whenever I send an email from MP I receive that very same email in my inbox (the intended recipient receives as well). Mailpile doesn't seem to receive it (nor via GUI nor via CLI), but my other mail clients do and for some reason they display it in my _inbox_ instead of in the _sent_ folder.

**Comment by riX2000** [comment]
Confirmed, I have the same issues.
Using the mailpile-git AUR package, version r4459.829adbb-1.

**Comment by bimac** [comment]
Same here on rc6.

**Comment by BjarniRunar** [comment]
This is deliberate. It can be disabled from the preferences tab on the settings page if you prefer, look for the "Always BCC self" setting.

The reason Mailpile does this, is to allow other mail clients you may be using to see the messages you've sent. Someday Mailpile will learn how to copy sent mail to the IMAP Sent folder and this will become unnecessary.
