### ISSUE TITLE
Using proxy to connect to mail server

### ISSUE THREAD

**Issue by user0000001** [mailpile/Mailpile#1409]
I'm trying to make mailpile go through a proxy before it connects to the mail server. With hints from issue #724, from the cli I set (for using Tor):

    set sys.proxy.protocol=socks5
    set sys.proxy.host=localhost
    set sys.proxy.port=9050

My questions:
Do I have to restart mailpile for the settings to take effect?
Will this change how my mailpile web interface is served (can I still use the instructions on the "Accessing the GUI Over the Internet" wiki page)?
Will the Tor exit node I go through show up in the mail headers?
Is there anything on the mailpile side to test my proxy settings? (so show me what IP the mail server will see me coming from)
Will it ever be possible to set different proxies for different mail accounts?

My use case is, I don't want the giant advertising corporation owned mail server I'm connecting to to be able to track me by my connection history, but I don't care if the mail server my friend runs can see where I'm coming from.

**Comment by user0000001** [comment]
To partially answer my question, checking my email without a restart showed me coming from my mailpile server IP address, and restarting reset all the proxy settings I changed back to default. After restart, I also get the message "WARNING: Any changes will be overwritten on login" when I try to set the proxy settings again (but it didn't do that when I set the initially).

**Comment by BjarniRunar** [comment]
Thanks for reporting this - I haven't been able to look into this yet so I'm not sure why it isn't working, but thank you for reporting, this will get looked at next time I work on the connection broker tor/proxy integration.

To answer your questions:

- A restart should not be necessary
- It should not change how the UI is served (there will be separate settings for that)
- Most mail servers record in the headers the IP of the sending client, so yes the IP of the Tor exit node is likely to appear in headers.
- No interfaces exist yet for testing/debugging proxies. Someday!
- No thought has been given to the need/usefulness/ability to set different proxies for different addresses. That does not seem like a feature many people will want, so I doubt it'll be high priority any time soon.

Note that in our threat models, we consider friends and family to be at least as untrustworthy (generally more so) than faceless corporations and governments. Big Surveillance is certainly a problem, but it is not the only problem, and arguably it is not even the most important problem for most users. Consider that almost everyone has jealous or nosey friends or acquaintances - and both homicide and rape statistics show that most victims are attacked by people they know.

We will definitely not be building "everyone trusts their friends" into our assumptions or prioritising that threat model in any way. :-)

**Comment by BjarniRunar** [comment]
I've been working with and testing the proxy code a bit lately; it all seems to work as expected now after squashing a few bugs.

There is also an interface to view recent network activity (/logs/network/ is the URL), and a way to list hosts which are *not* supposed to use the proxy. Restarts are not necessary.

I think this addresses all of your concerns. Thanks for filing!
