### ISSUE TITLE
“Template not found” for /help/crypto-policy.html

### ISSUE THREAD

**Issue by wjt** [mailpile/Mailpile#1413]
When setting up a new account, in the _Security and Privacy_ section there is the following tickybox:

> [×] Best-effort digital signatures and encryption (**details**)

Clicking **details** does two things:

a. toggles the tickybox – this seems like a bug
b. opens http://localhost:33411/help/crypto-policy.html in a new tab, which just displays **Template not found**

I'm using 9ef1fbaef8fb4e1223a89c150bc056c7b2d5a76a (ie master as of right now).

**Comment by wjt** [comment]
(I have read the "issues not welcome, PRs very welcome" blurb! but don't have time to dig into this just now, maybe later this week.)

**Comment by wolfpackmars2** [comment]
account-form.html line 675.
I believe if the link is placed outside of the span class="checkbox" tag, may fix the first part of this issue.
