### ISSUE TITLE
Implement unlimited results per page for search results

### ISSUE THREAD

**Issue by Konzertheld** [mailpile/Mailpile#1426]
I hope I'm not just missing this option but there should be a possibility to change the number of returned search results per page. And though I really like the "you marked all on this page, click here to mark all matched" feature, there should also be a no paging option.

**Comment by BjarniRunar** [comment]
(Configuring the number of search results is possible in settings, prefs.num_results, or on a per-page basis by specifying begin and end values (see the next/previous buttons for examples)... renaming this issue to cover the other things you mentioned. :-)

If by no-paging you mean "infinite scroll" ... perhaps. However, that would actually *break* the current functionality of having a manageable number of things on screen that you can select-all and tag at once. If the select-all toggle always applied to *all* results, you would be much more reluctant to use it. This could be handled by making it easy to select ranges, but it's not obvious how to make that would be as discoverable and clear to new users as the current interface.

**Comment by Konzertheld** [comment]
Thanks for the advice for changing the number of results per page. Setting it from the console worked. I couldn't find a config file so far, those in ~/.local seem to be compiled somehow.

And no, I don't mean infinite-scroll. I'm actually an opponent of infinite-scroll. :) I meant a setting to set num_results to a value that always means "all", like 1 billion or so. But I just tried that with 1300 messages and realized it was a bad idea. So, closing this. :)

**Comment by Konzertheld** [comment]
Oh, I just answered the config thing myself. I didn't realize there is no such thing as a config file and instead configuration changed via CLI is saved. I thought it was temporarily when changed from CLI. :)
