### ISSUE TITLE
Replace (or enhance) Mailpile's icon font with standard emoji

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1428]
Rather than attempting to roll our own icons for everything, we should make use of the existing emoji fonts out there to give our users the maximum set of icons to chose from for their tags and take advantage of existing (and ongoing) work.

Potential sources:
- https://github.com/MorbZ/OpenSansEmoji (Apache 2.0)
- https://github.com/jslegers/emoji-icon-font (license unclear)

Not sure which is better, comparing and choosing would be part of the project. Something that seems likely to be updated and improved over time is preferable, as is something that adheres to Unicode standard code-points so the font can be replaced with minimal effort at a later date.

**Comment by BjarniRunar** [comment]
Also worth considering: http://fontawesome.io/

**Comment by BjarniRunar** [comment]
Also: https://github.com/github/octicons/

**Comment by Epse** [comment]
Is the goal to this issue to change the standard font so people can use emoji everywhere, or to change how the icons, for example the compose one, are displayed? Would fix and PR but not entirely sure what is meant

**Comment by jeremylow** [comment]
I think you'll find some issues with using an icon font for the UI. The following article lays out some of the concerns and links to others with additional info:

https://sarasoueidan.com/blog/icon-fonts-to-svg/

**Comment by BjarniRunar** [comment]
@jeremylow we are already using an icon font. Best practices on the web seem to change every two weeks or so - this was "the thing to do" at the time. :-)

@Epse as discussed in the issue, the goal is to not have to maintain our own icons for everything; the project doesn't an active artist/designer participating at the moment, and it seems we'd be better served by using community resources than trying to roll our own everything.

I think both of the things you mention are worthwhile - allowing people to use/see emoji in their e-mail is already something other mail clients have started doing. So that would be "nice to have".

But I think it's more critical that our current development process is broken in this respect: it depends on an artist/designer that we don't have "on staff". Changing / augmenting where we get the UI icons from would allow artistically impaired devs to still illustrate their work.

Also, a related "nice to have", is one of the features of Mailpile is users can assign icons to the tags they create. Currently the only icons they can use are the ones that @bnvk drew for the project. They're very nice, but there's not very many of them and they don't cover nearly all the use-cases people have for tags in their mail.

**Comment by Epse** [comment]
My personal propositions would be these:
* [Ionicons](http://ionicons.com/)
* [Font Awesome](http://fontawesome.io/icons/)

**Ionicons** have a reasonably large amount of icons, some in multiple styles, in general quite fitting with the current, minimal and slick icon theme we have going.

**Font Awesome** is really widely used, has a ton of icons, possibly too much. The style of the icons is more cartoonish (compare their *pencil* icons for example).

Those are the two that seem most appropriate. *Font Awesome* has more icons that could be used to assign to tags, whereas *Ionicons* mainly have UI icons.

Style-wise I prefer *Ionicons* but I can see the advantages of *Font Awesome*.

Would be happy to implement any of them both

**Comment by Epse** [comment]
Last option I found recently and would recommend are the *Google* [Material icons](https://design.google.com/icons/). Appropriate license, and fitting style IMHO.

**Comment by Epse** [comment]
And for a font, I might suggest the newly crafted [Google Noto](https://www.google.com/get/noto/) font, made to support *all* languages and the *entire* UTF-8 spec. Can be included using Google Fonts API, but that would defeat the "Works offline" principle of Mailpile. Can also be used in a statically included webfont manner

**Comment by BjarniRunar** [comment]
Note that we cannot use any fonts that do not have a proper Free Software compatible license.

Web-fonts are not an option, because we distribute Mailpile as an AGPLv3 application, including any required fonts.

I am also not sure we want to replace the general-use font we have already, but if we had a larger more unicode-enabled font available as a fallback for glyphs we're missing, that might make sense.
