### ISSUE TITLE
Fix things broken by recent mega-UI-update

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1429]
Here's a list of things known to have broken in the recent mega-UI-update:

Expect this list to get longer before it gets shorter! Growing pains... :-)
1. ~~Startup fails completely on some systems #1425~~
2. Replying in the middle of a thread does not work (relates to #1372, #891  )
3. ~~PGP key unlock dialogue no longer works~~
4. ~~Attachment uploads are broken (CSRF failure)~~
5. ~~Key importing is broken~~
6. ~~View HTML / View plain text is broken~~
7. ~~Keyboard shortcuts are broken: m-a, m-d (probably all the tagging shortcuts)~~
8. ~~Subtag expanding arrow is broken~~
9. ~~Shutdown could be stalled by persistent HTTP/1.1 connections~~

Feel free to ad more in the comments. Or fix things!

**Comment by karlp** [comment]
Workaround for number 3:
```
20:23 <@BjarniRunar> karlp: yes
20:24 <@BjarniRunar> 1. find the gpg key ID: pipe less crypto/gpg/keylist/secret
20:24 <@BjarniRunar> 2. tell Mailpile the passphrase: set/password KEYID cache-only
20:24 <@BjarniRunar> IIRC it'll ask you for a passphrase
20:25 < karlp> yay! that works
```

**Comment by JocelynDelalande** [comment]
> PGP key unlock dialogue no longer works

I can confirm it now works

**Comment by bnvk** [comment]
Autosave now generates a draft for every message thread you view if you have "quoted replies" disabled

**Comment by JocelynDelalande** [comment]
page `<title>` does not change while navigation with auto-ajax enabled.

**Comment by BjarniRunar** [comment]
Closing, moved the stragglers to #1703.
