### ISSUE TITLE
Cannot launch Mailpile on Windows 7

### ISSUE THREAD

**Issue by BrunoMi** [mailpile/Mailpile#1432]
Hello,
I've been trying to install Mailpile beta III on my computer without success. I had installed and run the first beta and, as I thought that it may have caused the problem, I carefully uninstalled it, including by deleting all AppData folders.

The symptom is the following one: when I try to start Mailpile after installation (even if I launch it as administrator), all I get is the following error (screenshots attached, local language is French, version of Windows is 7 Professional SP1)
![mailpile error 1](https://cloud.githubusercontent.com/assets/15175132/10561017/40f2d5f0-751d-11e5-8112-14e0cb03508a.JPG)
![mailpile error 2](https://cloud.githubusercontent.com/assets/15175132/10561018/40f4f236-751d-11e5-9f18-055a4ae37793.JPG)
Any help would be most welcome.
Regards,
Bruno

**Comment by BjarniRunar** [comment]
Thank you for reporting this, this further underlines what we already knew - that our packages are not good enough and need to be redone.

Unfortunately, I don't have anything immediately useful to say about how to work around this, someone with more Windows expertise will need to chime in.

**Comment by BrunoMi** [comment]
​You are welcome.
If you are able to provide me with a build in verbose mode, I might be able
to send you back extra information which would help you solve the issue,
without necessarily be experts on Windows.
Kind regards,
Bruno​

**Comment by BjarniRunar** [comment]
Hi Bruno! I'm afraid we don't have such a thing as a verbose mode build. We should, but that goes back to the problem of lacking skilled Windows developers and our Windows package needing work...

**Comment by BrunoMi** [comment]
Hi Bjarni,
Thanks for your reply! I used to be a skilled Windows developer but it was
a long time ago. Anyway I unfortunately do not have the proper 'bandwidth'
at the moment to dig into this problem myself. I think I will try to go for
a network based installation hosted behind a router, on Raspberry Pi
instead.

**Comment by infinite-Joy** [comment]
Will try to work on it as I am mainly working in the windows platform. Any help or useful advice is welcome..:)

**Comment by BrunoMi** [comment]
Hi Joydeep Bhattacharjee,
What I can propose is to test your versions (my platform is Windows 7
Professional SP1).
If you can provide me with a verbose installer, it will be much simpler to
identify the cause of the failure.
Bruno
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Cet
e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BjarniRunar** [comment]
Note: improvements to the Mailpile Windows desktop integration should take place in the gui-o-matic project so the results can be re-used by other projects: https://github.com/mailpile/gui-o-matic

**Comment by sergeevabc** [comment]
Any news about Windows installer?
