### ISSUE TITLE
not obvious how to debug connection issues

### ISSUE THREAD

**Issue by titaniumbones** [mailpile/Mailpile#1434]
HI,

yay! new interface!

It looks great.  I am having trouble setting up an IMAP connection and it's not obvious to me how I ought to be debugging.  In Thunderbird, my settings are:

server: xxxxxx.utcc.utoronto.ca
port: 993
connection: ssl/tls
authentication: normal password

in mailpile, I have tried both IMAP and IMAP/TLS methods of connection; both fail.  In my log I see this:

["Wed, 21 Oct 2015 15:43:19 -0000", "5627af9e.00c47.4fea", "R", "Connection timed out", ".mail_source.imap.ImapMailSource", {"have_unknown": false, "name": "username@xxxxxxx.utcc.utoronto.ca", "mailbox_state": {}, "connection": {"live": false, "error": ["timeout", "Connection timed out"]}, "id": "76c5627af625", "counters": {"copied_messages": 0, "indexed_messages": 0, "unknown_policies": 0}}, {}]

but I'm not sure how to investigate the timeout issue; I don't have this issue with thunderbird, so I assume Mailpile or the underlying python libraries is at issue.  

Thanks for eveyrthing!

Matt

**Comment by BjarniRunar** [comment]
Hi Matt,

Our connection debugging interfaces definitely still need work. If your IMAP server is on 993, then you almost certainly want the IMAP/TLS protocol. Why it's timing out is hard for me to say; that seems is the sort of thing that a firewall or might cause - possibly combined with a mistake in settings; trying to connect to an invalid port or hostname could result in a time-out due to common firewall policies.

If you are far away from the server or have a crappy (packet-lossy) network, the timeout might actually just be a timeout -  Mailpile being too impatient.

Hope this helps...

**Comment by titaniumbones** [comment]
thx Bjarni!  

Is the underlying connection command available directly, either at the mp cli interface or just from python? If I could tweak parameters or inspect packet loss, that might help.  

Meanwhile I will also try from a better network (network where I am right now is in fact rather crappy).

**Comment by BjarniRunar** [comment]
I'm afraid the commands you are quite right to ask for, do not yet exist. They should!

Sorry this is klunky, making mail sources (and routes) easier to test and debug is something that is slowly bubbling up to the top of my TODO list.

Thanks for your patience, if you figure out what is going on please do report back so I can improve things at my end.

**Comment by BjarniRunar** [comment]
Actually, to not leave you completely hanging, here is what *is* possible when debugging a connection:

    # Turn on lots of verbosity (you might want to omit imap)
    mailpile> set sys.debug = log sources imap
    ...

    # Watch the log messages fly by, CTRL+C exits
    mailpile> eventlog/watch 
    ...

    # Trigger a rescan of mail sources by hand
    mailpile> rescan sources

None of that is exactly what you were asking for, and I suspect it won't matter much while Mailpile is failing to make its initial connection, but those are the tools we've got at the moment. :-)

**Comment by titaniumbones** [comment]
Well, embarassingly, it seems I mistyped my password...  gaah.  sorry for the noise, though I guess a better error message might have helped me fix the issue quicker.  thanks again, m

**Comment by BjarniRunar** [comment]
That's very odd - we do try to detect and relay to the user any authentication failures, they should not result in a timeout! Curiouser and curiouser...

In any case, let's leave this issue open for folks to find the instructions on how to debug and as a reminder that I need to improve the built-in troubleshooting tools.

**Comment by benzkji** [comment]
I'm on RC1 / xubuntu. Guess this has changed a lot, but I more or less struggle with the same stuff...having connection timed out messages, but works with thunderbird.

**Comment by BjarniRunar** [comment]
The Mailpile web UI now has a few different views for troubleshooting. If you click on the Privacy Settings, or on the word Notifications above the notifications bubble, you will find yourself in the "technical settings and troubleshooting" context of the app - the toolbar area contains a bunch of goodies: Privacy, Event Log, Network, TLS Certs, Account Password Management, Encryption Key Management, Command Line Interface and the "Tips and Tricks" list.

The network page in particular is useful for getting a feel for what Mailpile is doing (or trying to do with the network).

The above CLI debugging advice also still applies, but note that it doesn't work in the web CLI, you need to be in the terminal.
