### ISSUE TITLE
add button in outbox to send email

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1437]
The outbox should have some way of allowing the user to issue a "send email" command

**Comment by BjarniRunar** [comment]
Agreed, it should.

**Comment by waseem18** [comment]
@BjarniRunar Where should the 'Send email' button be placed? Before 'reply'?

**Comment by waseem18** [comment]
@BjarniRunar Where should the 'Send email' button be placed? Before 'reply'?

**Comment by BjarniRunar** [comment]
@waseem18 The right place for this is in the context-dependent activity section. That's where the "Save" or "Edit" buttons appear when viewing searches or tags.

See the very end of `shared-data/default-theme/html/partials/tools_search.html` - a check there to see if the user is viewing the outbox tag, adding another action, seems like a sensible way to do this.

**Comment by garoller** [comment]
Hi! This is my first time contributing to an open source project, and I am currently working on this issue. As suggested above, I started to implement the "Send" button and placed it to the right of the "Edit" button while viewing the outbox tag .

**Comment by HarendraSingh22** [comment]
Has this issue been solved?

@garoller have you submitted a PR?

**Comment by BjarniRunar** [comment]
It has not been solved AFAIK. It sounds like @garoller had the right idea (that sounds completely reasonable, even replacing the Edit button might have made sense), but the PR never materialized.

This isn't purely a front-end task, it may also require API work at the back-end. There is currently a `sendmail` CLI command which flushes the outbox, but I don't remember if it exposes itself to the web API. It wouldn't be hard to do, but this does steepen the learning curve somewhat.

**Comment by garoller** [comment]
@HarendraSingh22 and @BjarniRunar, I have not submitted a PR for this issue and am no longer working on it. I apologize for the inconvenience.
