### ISSUE TITLE
Blurred topbar sometimes disables buttons

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1438]
When the [DEV MODE] message spans more than one line the button below them are disabled.  
[DEV MODE] We know about the blur, working on it! for instance spans two lines for me
resolution 1366*768, chromium

I would drop the whole blur completely. If I am going to do regular development, I would do that using the git version. Having the blur is just annoying. I understand you do not want to have normal people use the git version, but you should also think about the developers.  
If you are really that concerned, you could force all development to happen in branches and only merge them after they c.ontain tests and the travis doesn't object

**Comment by JocelynDelalande** [comment]
Hi, thanks for taking time to report :)

> I would drop the whole blur completely. If I am going to do regular development, I would do that using the git version. Having the blur is just annoying. I understand you do not want to have normal people use the git version, but you should also think about the developers.
> 
> If you are really that concerned, you could force all development to happen in branches and only merge them after they c.ontain tests and the travis doesn't object

From what I get, at the moment, no branch/version of mailpile is ready for production, not even the master, that's why the blur is still around.

However…

> When the [DEV MODE] message spans more than one line the button below them are disabled.

I agree that is an immediate issue, feel free to post a PR with some CSS fix, there is no reason it won't be accepted IMHO :)

**Comment by BjarniRunar** [comment]
Wontfix. The blur is there to annoy people, set expectations and make the app look a bit shit. In short, it's working as expected. If it bugs you, edit your source to disable it locally.
