### ISSUE TITLE
Counter for unread mail in 'All Mail' is always 0

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1442]
It seems that the counter for the unread mail in 'All Mail' is always zero

**Comment by BjarniRunar** [comment]
The All Mail tag is a weird edge case; it's not actually a normal tag, it's a short-cut to a search for "all mail".

As a result the code which counts how many messages are tagged returns no results; returning a proper number would require actually running the search which may well be prohibitively expensive. I'm not sure how best to resolve this; the least-bad easy quick fix would be to not show an unread count at all if a tag has search terms associated with it.
