### ISSUE TITLE
Rework the template that lists the emails

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1445]
I think that the overview page for showing mail could be made more user friendly with a couple of changes:
- move checkboxes to the left side
- move action buttons to the left side

Most of the links and button users would use the most are on the left side (navigation, filters, ...)
Moving the selection checkboxes and the corresponding action buttons would improve usability, as the users would not have to move from left to right that often.

**Comment by BjarniRunar** [comment]
You have a valid point; the current design may well favour aesthetics (a nicely balanced page) over functionality and usability. That said, aesthetics aren't without value and we already have some rather important things on the left - if we want to move the action buttons over, we need to consider where other things go and how it all fits together.

I am actually pretty happy with the current layout - I think it can be improved, but there are other things that need fixing first. However if someone would like to sketch some proposals for alternatives, discussions are always welcome.
