### ISSUE TITLE
Fix (or remove) bulk-tag popup

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1446]
Regardless of the amount of message selected, when trying to assign tags it always shows 'Tag 0 Messages'

**Comment by BjarniRunar** [comment]
Context is missing. I tag things all the time, works fine.

Are you talking about the bulk-tag popup tool? It is indeed broken.

**Comment by simonsmiley** [comment]
I am selecting messages and then using the small tag icon in the bar on the right side
http://imgur.com/a/zWUIo

**Comment by JackDca** [comment]
In my opinion, for what it is worth, the bulk tagging is a useful feature and should be retained, even if not operational for this release.

One of my reasons for moving to Mailpile (aside from my interest in enabling end-to-end encryption for the casual user) is to get a grip on my massive Inbox, which grows faster than I am able to move messages to specific folders.
