### ISSUE TITLE
Make whole tag clickable for assigning tags

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1447]
When assigning tags, the whole tag should be clickable not just the checkbox

**Comment by BjarniRunar** [comment]
There are many ways to assign tags, you need to clarify which you are talking about.

**Comment by simonsmiley** [comment]
I am selecting messages and then using the small tag icon in the bar on the right side
http://imgur.com/a/zWUIo

**Comment by BjarniRunar** [comment]
That makes this effectively a dup/subset of #1446 - it doesn't matter whether selection works or not while the whole popup is useless.

As mentioned elsewhere, please show some restraint in filing issues. You mean well and I appreciate your enthusiasm, but you're spamming.
