### ISSUE TITLE
per-thread message count in search view is wrong

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1450]
# Steps to reproduce
- run `./scripts/mailpile-test.py -i` (and wait for it to finish)
- start web UI typing `www` (may require 2 trials)
- Set password and login to the web UI
- Look at the first message (thread `8`)
# Expected result
- message count is _1_ (and thus, message count badge is not even displayed)
# Actual result
- message count is _3_

(to check, you can open the thread and see that it contains only 1 message)

**Comment by JocelynDelalande** [comment]
Template context is here : https://outils.crapouillou.net/zerobin/?75cdc5c0e55fe989#EjOs/ubNBI6pqktNt0tuMBJtgeNN6jv8Yz9VXL8lLnk=

I think the bug has two parts :

1. It seems to be an arbitrary +1 in code that makes *every* count wrong by +1 (easy to fix)
2. there is an extra +1 count on threads containing a *ghost* message (missing ancestor), IMHO, the ghosts should not be counted, because they are not displayed

## Ghost counting

I would be happy to provide a solution for 2. but I need some input, currently, data includes :

```
"data": {
...
    "threads": 

{
...
"9": 
    [
        "8",
        "9"
    ],
...
},
```

… But *9* is (to my understanding) a ghost… so [the counting on data.threads in search_item.html](https://github.com/mailpile/Mailpile/blob/master/mailpile/www/default/html/partials/search_item.html#L8) breaks here.

Would not showing ghosts in result.data.threads break threading logic/behaviour ?

Another way would be not to exclude ghosts from the count in the template, but from what I see, no information in search item template context allows to tell if a given message is a ghost.

**Comment by JocelynDelalande** [comment]
btw, tests seems to be [curently broken](message) for same reason.

**Comment by BjarniRunar** [comment]
Thanks for reporting this and working on fixes. I broke this while working on threading improvements (some of which I have yet to push).

Do the merged PRs above fix this, in your opinion?

**Comment by JocelynDelalande** [comment]
@BjarniRunar not, one issue over two is solved, the test case I give in the ticket is half-solved.

The displayed count is supposed to be 1, it was 3, it's now 2. We're getting better though :-)

… @BjarniRunar so sadly I have to suggest that we you re-open the ticket @BjarniRunar ?

(and sorry for delay)

**Comment by BjarniRunar** [comment]
Alrighty. :)

**Comment by BjarniRunar** [comment]
You're right, I was hasty - the ghosts should be omitted. The question is, at which stage they should be filtered away. They are *already* filtered away in some places -  but that code may all be sitting on my laptop, waiting for me to push it up. I'm going to suggest we just ignore this issue until I've pushed my backlog and then revisit.

**Comment by JocelynDelalande** [comment]
@BjarniRunar ok, let's hope another you fixed it already ;) and let this bug open just so that we think about checking later.
