### ISSUE TITLE
padlock: find encryption keys fails, but by contact works

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1453]
A contact has sent me a mail with their public key, and "has:pgpkey" shows this mail.

`crypto/keylookup <email>` shows a nice blob of json that shows the key nicely.

Mousing over a contact in a "TO:" box and clicking "Find Encryption Keys" pops a dialog saying, "searching for keys for <email>" and correctly finds the key and offers to import it.

However, clicking the padlock on the mail body instead says, "You are missing encryption keys for the following contacts" and lists the same email, with a button "Find Encryption Keys"

_this_ dialog fails, even though in this case I have only a single recipient.  The error is just "No encryption keys found matching:" with nothing after the ':', implying it's not actually searching for the right thing.

http://i.imgur.com/HKYPLsS.png?1 shows the failing mode.

**Comment by BjarniRunar** [comment]
I've fixed this in my local branch, will push up soon. Thanks for finding & filing this. :)
