### ISSUE TITLE
Unable to unlock keys with different passphrases

### ISSUE THREAD

**Issue by controesempio** [mailpile/Mailpile#1455]
I have a GPG key in my keryring which is not associated to any accounts on Mailpile. When I receive a message encrypted with that key, Mailpile correctly recognises the situation and informs me that "You have the encryption key to decrypt this message, but the key itself is locked." Pushing the "Decrypt message" button opens a modal dialog in which I can insert the passphrase (and select how long to store it in cache).

The problem is, something does not work as expected, and the passphrase is not accepted / the key does not unlock, and I am back to the same page with the message "Password incorrect? Try again!".

I've tried to set sys.debug = log gnupg and this is what I get (I have filtered out private details, let me know if I've removed something important). $KEYID is the keyid of the key in question,  $SUBKEYIDE is the subkey for encryption of the key, $SUBKEYIDA is the subkey for authentication (which I am not sure why is being considered here, but then...)

> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys $KEYID
> [cut..]
> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys $SUBKEYIDA
> [cut..]
> 5655b2a3.000b3.2f9a=SetPassphrase:c set/password: Enter your password
> http/log(20): Elapsed: 0.097s (set/password: Enter your password)
> bg/log(20): http://localhost:33411 "GET /settings/set/password/as.jhtml!minimal?id=$KEYID&ui_redirect_back=1 HTTP/1.1" 200 4881
> http/log(20): Elapsed: 21.576s (eventlog: Found 2 events)
> bg/log(20): http://localhost:33411 "GET /api/0/eventlog/?since=1448456845.153617&gather=1&wait=30 HTTP/1.1" 200 1588
> http/log(20): Elapsed: 0.001s (output: Set output mode to: json)
> http/log(20): Elapsed: 0.002s (output: Set output mode to: html)
> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-secret-keys $SUBKEYIDA
> [cut..]
> Running gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --fingerprint --list-keys $SUBKEYIDA
> [cut..]
> 5655b2ab.000b7.2f9a=SetPassphrase:c set/password: settings/set/password
> http/log(20): Elapsed: 0.083s (set/password: settings/set/password)
> http/log(20): Elapsed: 0.007s (output: Set output mode to: html)
> Running gpg --status-fd=2 --passphrase-fd=0 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt
> <<STATUS<< [GNUPG:] PROGRESS stdin ? 0 0
> <<STDOUT<< -----BEGIN PGP MESSAGE-----
> [cut..]
> -----END PGP MESSAGE-----
> [cut..]
> <<STDERR<< gpg: using subkey $SUBKEYIDE instead of primary key $KEYID
> [cut..]
> <<STATUS<< [GNUPG:] BAD_PASSPHRASE $SUBKEYIDE

I've tried to fiddle around with set/password, but apart from this message nothing else seems to change

> 5655b5b6.00116.2f9a=SetPassphrase:c set/password: Password stored temporarily
> Elapsed: 5.352s (set/password: Password stored temporarily)

Decrypting the message manually with gpg works, so it should not be a problem of the key or the passphrase. Any ideas?

**Comment by BjarniRunar** [comment]
Associate it with an account? :)

Thanks for the report, I'll look into it when I have a moment.

**Comment by controesempio** [comment]
Ok, maybe this has nothing to do with keys not connected to an account: I've tried to create one, associated it with the existing key, and nothing seems to have changed. Sorry for the bad bug-reporting, this is probably a different issue. I have just realised that sending encrypted emails with and existing key does not work, unless I first go in the account setting page and insert the key passphrase from there.

Maybe there is a problem in the dialog window?

**Comment by controesempio** [comment]
Ok, some more investigation has led this to me: Mailpile has some problem in unlocking the passphrase of my other GPG keys, unless they all use the same passphrase as the main one. Being connected to an account or not is actually irrelevant.

I am not sure if the problem is in the passphrase input form or in the logic behind it (maybe it is always sending the "main" passphrase?).

**Comment by BjarniRunar** [comment]
Just a quick question - can you tell if Mailpile is talking to gpg 1.4 or gpg 2.x ?

**Comment by BjarniRunar** [comment]
Seems the trail has gone cold here, closing this issue. FWIW, I have in the meantime created and worked with multiple keys using different passphrases, so I think this got fixed somewhere along the way.
