### ISSUE TITLE
contact names drawn from magic hat

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1462]
I don't even know how to describe this properly.  See the attached image, I've seen this sort of thing relatively regularly, with both my own name being mangled in the reply, and some of my contacts being mangled.  My only theory is that some spam has arrived that forged the same address as (in this case) my mother, and it's using that name instead of the "right" one.  Possibly related to "editing contacts" ?  "Gabriel" is not even remotely right or useful at any point :)

![image](https://cloud.githubusercontent.com/assets/127907/11918876/c4680cf0-a738-11e5-9e34-6cadbad1e60b.png)

**Comment by bnvk** [comment]
I've noticed this sort of bug before as well (and for a long time now). It seems as though there is no "canonical" name for a given contact, unless maybe I have a PGP key for them, or manually added them, or some other fluke!

**Comment by BjarniRunar** [comment]
This should have been much improved by 921eb30a9cabd59f21de032ff4a594a28265334f.

I am leaving this open however as the underlying issue (the internal email/name cache) is still vulnerable to the underlying issue and will still get confused. Things are only better now because we are using it less.

We need to either get rid of the name cache entirely, or fix its bugs.

**Comment by danger89** [comment]
Yea I see similar problems. In my case when I search on somebody else his name, my e-mail addresses will be mentioned with their name :S?

**Comment by srd424** [comment]
tc424 on IRC here - wondering if this is the root of the weirdness I am seeing? At least one contact, when I reply to his messages, now gets his email address DUPLICATED on outbound (but this isn't shown in the UI.) Looks like some internal database is corrupted? Anyway to inspect this?
(I also note with another test case, that when replying MP seems to ignore the real name in the original message, and pull it from its internal database instead.. not sure if that's desirable or not, but I don't think it's what other clients do...
