### ISSUE TITLE
remove all minified javascript from this repository

### ISSUE THREAD

**Issue by aviau** [mailpile/Mailpile#1465]
To help with packaging, remove the following files:

- ``` ./mailpile/www/default/js/libraries.min.js```
- ```./mailpile/www/default/js/plupload.full.min.js```
- ```./mailpile/www/default/js/jquery.min.js```

they can be replaced with non-minified JS. They will be minified at build time.

**Comment by BjarniRunar** [comment]
Noted; not doing this just yet, as it will mean changing our documentation to warn people they need to build those files - we currently check in compiled JS and CSS as a convenience for people testing from Github.

That doesn't mean we'll never do this... just not sure now is the time.

**Comment by aviau** [comment]
Solved in #1470
