### ISSUE TITLE
Content Security Policy error on Chrome and Firefox with HTML display

### ISSUE THREAD

**Issue by unixfox** [mailpile/Mailpile#1475]
When I read an email with HTML display, Chrome and Firefox refuse to load images due to content security policy :
![](https://i.unixfox.eu/20-12-12.png)
![](https://i.unixfox.eu/20-11-23.png)

## Informations about my browsers
- Chrome : Chromium 47.0.2526.106
- Firefox : Firefox Nightly 45.0a1 (2015-11-18)

**Comment by BjarniRunar** [comment]
Closing this, as I just replaced that code with a completely new (and more robust) way of displaying HTML. Please feel free to file a new issue if the new code has bugs too. Thanks! :-)
