### ISSUE TITLE
Make the HTML viewer display in-line images

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1476]
The current HTML viewer can display remote images, but lacks the ability to display in-line (attached) images. Fixing this requires updating the Javascript (`mailpile/www/default/html/jsapi/message/html-sandbox.js`) to detect CID image URLs and convert them to attachment download URLs.

This should be relatively straightforward, marking as low hanging fruit. :-)

**Comment by loidor** [comment]
Is this still an issue or am I doing something wrong? I can't get inline images to display at all.

**Comment by BjarniRunar** [comment]
This is still an issue.

Since the HTML support has been completely insecure until very recently, fixing things like this wasn't a priority. This isn't on our roadmap for 1.0 (because priorities), but if someone does the work and sends a pull-request... :-)

**Comment by loidor** [comment]
This is cleared by #1735.
