### ISSUE TITLE
Improve mailpile-admin.py Apache integration

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1478]
The Apache integration offered by the current `mailpile-admin.py` relies on a .htaccess file to function; this .htaccess file is edited on the fly as users launch their Mailpiles to create rewrite/proxy rules mapping /mailpile/USER/... to the correct Mailpile instance (mapping usernames to port numbers).

This is a slightly brittle and potentially insecure design; if the .htaccess file gets corrupted then all Mailpiles will become inaccessible. If a hacker figures out how to trick *any* CGI on the system into editing the .htaccess, they may be able to escalate their privileges.

Ideally the .htacces hack would be replaced by something using rewrite maps, but I was unable to get that to work so here we are. If someone could figure that stuff out and fix the recipe in `mailpile-admin.py` that would be awesome.

**Comment by aviau** [comment]
I'll take this issue.

**Comment by BjarniRunar** [comment]
Hey @aviau, trying to run ./mailpile-admin.py --install-apache now results in the following error for me when I try to log in using the web interface:

> The requested URL /cgi-bin/mailpile/admin.cgi was not found on this server.

... basically, you've baked in an assumption that /cgi-bin/ exists and is configured, but that's not guaranteed by the mailpile.conf file, so this is brittle and unreliable. IMO we can't assume anything about the paths of the existing Apache, everything has to be self-contained within the /mailpile/ namespace.

**Comment by aviau** [comment]
What is your distro? Out of curiosity. 

Anyways you're right, I'll fix it.

**Comment by BjarniRunar** [comment]
I'm on Ubuntu atm, but I tend to not use the distro Apache defaults because I have old configs lying around from who-knows-when.
