### ISSUE TITLE
No image is displayed in the HTML mode.

### ISSUE THREAD

**Issue by unixfox** [mailpile/Mailpile#1479]
When I read an email with HTML display, no image is displayed.
Chrome console returned me some logs about blocked script execution :
>Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.g.backupProps @ content.js:7
>3about:srcdoc:1 Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

![capture du 2015-12-23 12-55-53](https://cloud.githubusercontent.com/assets/4016501/11976040/8bc681b8-a974-11e5-99ef-8bee01756322.png)

### Email displayed on Mailpile
![capture du 2015-12-23 13-02-54](https://cloud.githubusercontent.com/assets/4016501/11976137/8678b284-a975-11e5-8475-3163eb443bcd.png)
### Email displayed on Gmail
![capture du 2015-12-23 13-05-20](https://cloud.githubusercontent.com/assets/4016501/11976166/d89a912c-a975-11e5-8231-5c0f1f225b60.png)

**Comment by BjarniRunar** [comment]
This is the old HTML viewer; it has been replaced completely, and images are partially supported (see #1476 for missing functionality).

Please pull down the latest code. :-)

**Comment by unixfox** [comment]
I've already pull down since my last issue #1475. I just didn't see the warning message about :
> This message references images or other content from the web. Downloading and displaying these images may notify the sender that you have read the mail.

It's working by : 
>Okay, display the images
