### ISSUE TITLE
Gracefully recover when PGP key generation fails due to insufficient entropy

### ISSUE THREAD

**Issue by johnmci** [mailpile/Mailpile#1480]
I've a gmail user with TFA on. We setup a google app password and his IMAP configuration works fine. 
What we can't seem to get working is send mail (SMTP). 

If we do 
set sys.debug = log sources imap sendmail
we just don't see any sendmail events in the log (assuming that is the correct debug setting). 

Does someone have a correct gmail smtp setting (smtp type/port) they can share. Or some more info on how to get some more logging. 

Note later if we do 
sendmail
we get 
567f7219.000ce.2415=EmptyOutbox:c sendmail: The outbox is empty
bg/log(20): Elapsed: 0.002s (sendmail: The outbox is empty)
567f7273.000cf.2415=EmptyOutbox:c sendmail: The outbox is empty
bg/log(20): Elapsed: 0.002s (sendmail: The outbox is empty)
567f72ce.000d0.2415=EmptyOutbox:c sendmail: The outbox is empty
bg/log(20): Elapsed: 0.002s (sendmail: The outbox is empty)
567f7315.000d1.2415=EmptyOutbox:c sendmail: The outbox is empty
Elapsed: 0.002s (sendmail: The outbox is empty)

True

Oh and in the web interface the "Preparing to send... " just never goes away.

**Comment by BjarniRunar** [comment]
If the outbox is persistently empty, then you're never reaching the SMTP stage. The question becomes: why isn't the message entering the outbox?

**Comment by johnmci** [comment]
Ok, we deleted the data, tried again, then saw after some many 10's of minutes the PGP key generation fail. So given that we were setting up this on a Ubuntu 14.04 server under XenServer 6.2 with 2 virtual CPUS/ 1GB ram we ran a quick check of  /proc/sys/kernel/random/entropy_avail which gave us a number of 54  So we fell victim of insufficient entropy which caused reads to /dev/random to stall out. A year back I had read about this being an issue at startup time for virtual machine servers, but hadn't realized the actual impact on a machine post boot. 
  
Although we've not confirm this, we'll assume the step of generating signed email or some other part of the security process (logging?) stalled due to the entropy issue. 
 
The digital ocean folks have a nice writeup and solution here: https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged

**Comment by BjarniRunar** [comment]
Thanks for following up. I'm going to rename this issue, I don't think we have a bug to track problems to do with PGP key generation failures due to insufficient entropy, this one may as well be it.

**Comment by BjarniRunar** [comment]
We might want to prevent the user from trying to create two keys at once, as that will just consume all the entropy and make no progress at all.

Similarly, while the user is generating a key, the settings dialog should disable the security section completely so the user doesn't do weird things.

**Comment by BjarniRunar** [comment]
(I think there may already be an issue for the latter, and it doesn't really belong here, but somethingsomething)

**Comment by loidor** [comment]
I don't know if it's doable, but one way to solve this would be to call an entropy generator of some sort while generating keys. That would generate them faster, and if it's fast enough there could simply be a "Generating keys. Wait..." message while it happens.

**Comment by BjarniRunar** [comment]
@loidor It's an idea that has come up, and it would certainly help in some circumstances.

However, I feel that's not really within our domain. Generating random numbers is security critical for a great many applications and operating systems do a good job, using well scrutinized and reviewed systems. If we start interfering with that, and get it wrong, we could cause a lot of harm - and short of patching GnuPG we can't influence this without going through the shared OS randomness subsystems. I don't think we should go there.

**Comment by loidor** [comment]
Point. 

How about hiding the mouse pointer and then generate a lot of random mouse movement until it's done? I don't know if it would accept that since it's not hardware input per se, but if it did then that might be a way to do it.

**Comment by BjarniRunar** [comment]
@loidor I don't think that's even possible; I'm not aware of a Javascript or Python API that lets me jiggle the user's hand. ;-)  I don't think JS can hijack the mouse pointer, and even if it could, it would be at a high level, not something the kernel would be listening to. It wouldn't have any effect on the entropy in the kernel... and IF it did, it'd still be a bad idea: where do you think Mailpile would get the entropy to "randomly" move the mouse? It's not like we're sitting on some untapped entropy source, we rely on the kernel just like everything else.

**Comment by loidor** [comment]
See? This is why I do designing rather than programming :)

**Comment by BjarniRunar** [comment]
Note: @FlakyBit is working on this. If you had made any worthwile progress, @smari , it would be interesting if you could push it up to a branch we can see to compare notes.

**Comment by BjarniRunar** [comment]
I think our current behaviour is much improved; the timeout is now longer (so we'll fail less often), we only create one key at a time (so not fighting over the entropy pool) and there are some helpful messages.

I'm going to close this, we'll see if someone opens a new one after this has been in the wild for a bit.
