### ISSUE TITLE
Please investigate whether case sensitivity of e-mails causes conflicts with gpg

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1488]
The case arose where I manually added a contact "name@email.com" and then imorted the key, whereby the address was listed as "Name@Email.com"

The experience I have, is the key shows with a lock when searching in the Select2 plugin, but then upon choosing it, it reverts to the lower case "non encryptable" contact, thus blocking me from encrypting at all.

**Comment by BjarniRunar** [comment]
Thank you for filing this. :-)

**Comment by bnvk** [comment]
Perhaps relating to same issue. User has a key in their keychain with two UIDs with same email address `hi@jackjones.com` but each UID has a different name

Jack <hi@jackjones.com>
Jack Jones <hi@jackjones.com>

When an email comes from the first address (with name "Jack") the receiving user can encrypt, but if the email comes from the second address "Jack Jones" user cannot encrypt!
