### ISSUE TITLE
Why even allow generating a 1024 bit key?

### ISSUE THREAD

**Issue by FSMaxB** [mailpile/Mailpile#1490]
I noticed that the user interface when adding a new mail account allow generating 1024 bit keys (and says that they are weak). My Question: Why even allow the user to generate weak keys in  the first place?

In my opinion, this option should be removed from the user interface entirely.

**Comment by BjarniRunar** [comment]
This facilitates testing; generating keys takes more time the bigger they are.

This option will be hidden from release-packaged code for the reasons you cite, but will remain in the dev versions.
