### ISSUE TITLE
"Leave mail on server" is unchecked but mail is left on gmail account.

### ISSUE THREAD

**Issue by johnmci** [mailpile/Mailpile#1491]
"Leave mail on server" is unchecked but mail is left on gmail account, is this a bug or not implemented feature? I would have expected that  if it's unchecked that once mailpile read and stored the email it would delete it from the imap server.

**Comment by BjarniRunar** [comment]
You are right, this is an unimplemented feature. It will be hidden from release-packaged code until it actually works.

**Comment by paolosg** [comment]
Is this still open or has been completed as part of #129 ?
Is it possible now to download all emails through IMAP, keeping labels structure, while deleting them from the server (e.g. Gmail)?

**Comment by paolosg** [comment]
@BjarniRunar need your input here.
If I misunderstood the issue, sorry for bothering.

**Comment by BjarniRunar** [comment]
@paolosg It is possible to download emails using IMAP, and delete from the server. So this issue can be closed, thanks for the reminder.

However: labels are however not perfectly preserved - that's a separate, unresolved issue.
