### ISSUE TITLE
Issues with contacts and encryption

### ISSUE THREAD

**Issue by skadge** [mailpile/Mailpile#1509]
I list hereafter the 'workflow' I've tried to follow to send an encrypted email to a friend, and the several issues that arose:

- First, I clicked on 'compose'. I started to type the name of my friend, correctly found by mailpile. By hovering the mouse on top of his name, I see 'Find encrytion keys'. So far so good, I click.
- The 'Find encryption keys' UI tells me that the key is on my key chain. Good. I try to click on the key, but nothing happen: a big nice message saying 'Everything looks good: this key will be used if you try to send an encrypted message to <name>' would be helpful.
- I close the dialog. If I hover again on the recipient name, I still see 'Find encryption keys'. Did Mailpile pip the key or not? hum, this is confusing! a little green symbol to say 'I've a key for this person!' would be nice.
- when typing the first letters of a contact, some contacts do display a green lock (I assume this means: I know a key for this person), but other do not, even after successfully importing their key.
- (as a side note, I've other contacts with several keys: it is not clear what key is actually used by mailpile in that case)
- Because  no identity is selected by default (ie, I need to select myself by click on the small head on the bottom left -- not obvious), the first experience is not good -> when I click on 'Send', nothing happen at all, if I click on the lock to encrypt, I get a misleading error message: "You are missing encryption keys for yourself"

- Once I've selected my identity, if I click on the lock, Mailpile complains the encryption key for my friend is missing...? well, it is still there if I check the contact manually.

So at the end, I've not been able to send the encrypted message.

I can split this issue into several smaller ones if needed. I've put it this way for now so that the whole interaction process is visible.

**Comment by BjarniRunar** [comment]
Hi, thanks for filing!

First: You haven't told us which version you tested - was this a beta, or the latest code from HEAD?

Regarding the contacts page - it's inaccessible for a reason, it's not ready and if you managed to find it using the current HEAD, then I'd like to know how so I can hide it even more thoroughly.

The rest of your issues I cannot respond to without knowing which version you are running. We had many issues like this in the last beta, but I most are fixed by now.

**Comment by skadge** [comment]
@BjarniRunar  Sorry for the delay! Everything was tested with the current git. I just restested after a fresh 'pull', and I've updated accordingly the issue above.

**Comment by skadge** [comment]
This issue is not present anymore in the current version. CLosing.
