### ISSUE TITLE
Re-generate the locale with proper copyright headers

### ISSUE THREAD

**Issue by aviau** [mailpile/Mailpile#1518]
Hello,

I don't mind the locale data staying where it is right now.

However, could you please update them so that they have a proper copyright header?

Currently, they say the following:
```
# Translations template for mailpile.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the mailpile project.
```

All there is to change is the word  ```ORGANIZATION```.

Thanks!

**Comment by BjarniRunar** [comment]
Will try!
