### ISSUE TITLE
Unable to upload attachments

### ISSUE THREAD

**Issue by Stefan-Code** [mailpile/Mailpile#1519]
I am using Mailpile [`ba6981c`](https://github.com/mailpile/Mailpile/tree/ba6981c658d167b0f6ed7b1526c839060ecd2144) (that's from January 5th) and Chromium `Version 45.0.2454.101` as well as Firefox `41.0.2`. I am facing the following problem when writing an email:
![Unable to upload attachments](http://i.imgur.com/7ObMXue.png)
> Unable to upload attachments, update your browser

I guess the two broswer versions should be up to date enough to support file uploads.
Is there any known reason why this is happening?

**Comment by BjarniRunar** [comment]
Should have been fixed as of 99751ea47450b55a06e54b6ea45ebba0486d9290 :-)

**Comment by Stefan-Code** [comment]
Yup, working now :+1:
