### ISSUE TITLE
Multiple tabs cause performance delays & failures

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1525]
I consistently experience the case whereby having multiple tabs (usually > 3) starts to make various operations (simple tag ops) performed in one tab to take many seconds or sometimes not complete at all. I find that closing a few tabs (usually < 3) makes this problem stop and things resume normal.

Does anyone else experience this to some degree?

**Comment by BjarniRunar** [comment]
Interesting. I wonder if our crappy built-in web server gets sad ad slow when you have many eventlog polls outstanding at once (you will have one per tab).

**Comment by bnvk** [comment]
Yah, that's what I'd suspect as well or something along those lines. Are you able to reproduce this as well? I used to notice it on my Mac, but also now in Linux even with autoajax support it's still quite prevalent

**Comment by BjarniRunar** [comment]
This one in particular may be out of Mailpile's hands - this may be a browser limitation: https://stackoverflow.com/questions/22866552/http-simultaneous-connections-per-host-limit-are-per-tab-browser-instance-or says:

> I have read in various forums where people have problems with SSEs when more than x tabs are open (I think 6 in chrome), and this is because browsers limit the number of simultaneous connections to a single ip address. 

If this is indeed the problem, then we need to research whether the tabs can somehow talk to each-other and share the eventlog. I think there may be some fancy modern APIs that facilitate such things. Hints welcome. :-)

**Comment by BjarniRunar** [comment]
I think the solution is here: https://stackoverflow.com/questions/4079280/javascript-communication-between-browser-tabs-windows (localStorage for the event updates!) ... someone just needs to code it. :-)

**Comment by bnvk** [comment]
Yah using localStorage is definitely one solution. Note- it does have a 5 MB limit per domain, and choosing what to cache in there and pass between windows matters somewhat, I guess. 

There's a whole trend in front-end dev to make apps work [offline first](http://offlinefirst.org) which *would* apply to Mailpile users who choose to run it from a server and access it over the web. There are entire libraries and plugins for Backbone, Angular, etc... which cache the JSON data models in localStorage and facilitate this sort of "offline" usability of downloaded (to browser) data.

**Comment by BjarniRunar** [comment]
Offline-first would be nice, but as you know Mailpile is very much not written that way. :-)

We don't need a framework or library to solve this problem; all we need to do is allow one (or more) tab(s) to piggy-back off the EventLog loads of another, using localStorage as a communication channel between them.

I've created a first draft of this and pushed up, take a look and let me know (close the issue) if it helps!

**Comment by bnvk** [comment]
Thanks for pushing a fix. I stress tested this as best as I could with the user actions & routines I was noticing the issues with before. Here is what I'm noticing now:

- Seems to fix the aspect of tagging actions never completing - yay :)
- Things are still a bit sluggish overall
- Even with only one tab open, it usually takes > 1 sec to load a search of a single tag or a message inside of a search
- Loading the old "full thread view" seems a bit faster than loading new tabs of expanded messages in search view

I'll close this since things aren't actually failing per se anymore which was more of an issue!

**Comment by BjarniRunar** [comment]
Thanks for confirming. I'm chasing down other performance issues, I see them as well. We'll see if I make any headway...
