### ISSUE TITLE
Unable to start setup

### ISSUE THREAD

**Issue by rmenessec** [mailpile/Mailpile#1526]
After following the instructions for getting started on Linux (Ubuntu 15.10), creating and using a virtualenv, etc., I can't get Mailpile to work. Instead, I get this error:
```
Template not found
```
The URL is http://localhost:33411/auth/login/?_path=%2F, redirected from http://localhost:33411/

I tried running "setup" (which seemed to succeed) in the shell, but nothing changed. I'm relatively sure that I followed all the directions correctly. Is there a problem with the current master, or is something else going on? I can't find any logs created by Mailpile, so it's hard to know what's going on.

Thanks!

**Comment by karlp** [comment]
Quick workaround from irc until this is fixed...
```
MAILPILE_SHARED=$(pwd)/shared-data python  -m mailpile
```

**Comment by aviau** [comment]
That is because mailpile is not installed in the virtual env. The install instructions only install the dependencies inside the environement.

We can fix this in two ways:
- add ```setup.py install`` to the instructions
- MAILPILE_SHARED variable when using from the ```./mp``` script.

**Comment by rmenessec** [comment]
Still not working, even after attempting to use the workarounds mentioned above. Exciting new error, though.
```
(mp-virtualenv)localhost Mailpile [0]# ./mp
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Traceback (most recent call last):                                             
  File "./mp", line 14, in <module>
    Main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/mailpile/app.py", line 186, in Main
    config.load(session)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/config.py", line 1409, in load
    rv = self._unlocked_load(session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/config.py", line 1526, in _unlocked_load
    self.load_plugins(session)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/config.py", line 1577, in load_plugins
    self.plugins.load(plugin)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/plugins/__init__.py", line 220, in load
    return self._load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/plugins/__init__.py", line 172, in _load
    module = __import__(full_name)
  File "/usr/local/lib/python2.7/dist-packages/mailpile/plugins/setup_magic.py", line 209
    data=None, timeout=10).read()
       ^
SyntaxError: invalid syntax
```
Once again, I'm following the documentation exactly.

**Comment by BjarniRunar** [comment]
Your Mailpile should not be in /usr/local/ if you are running in a virtualenv - your setup is strange and I don't know why, but it looks like you may have conflicting versions installed in multiple places.

I've just followed the instructions myself on ubuntu 15.10 and it worked fine. I don't think this is a Mailpile bug, leaving this closed.

**Comment by rmenessec** [comment]
This was entirely my fault. I managed to install Mailpile via PIP while I was having trouble getting it to start / run setup the first time. I forgot it was installed, and its presence caused some kind of problem.

After removing the system-wide install with PIP, Mailpile now starts correctly.

Once again, I'm very sorry for the demand I made earlier. :(

**Comment by BjarniRunar** [comment]
:)
