### ISSUE TITLE
Raspberry Pi Zero Mailpile Appliance

### ISSUE THREAD

**Issue by renne** [mailpile/Mailpile#1528]
Hi,

the [Raspberry Pi Zero](http://swag.raspberrypi.org/collections/pi-zero/products/pi-zero) is a interface-stripped 5,- $-version of the Raspberry Pi A+ but 40% faster. With a Micro-SD-card, housing, PSU and WLAN-stick you get a tiny 25,- $ Mailpile server.

Providing a ready-to-run SD-card (-image) with Rasbian + Mailpile would allow John Does to set up their own Mailpile-based mail server.

**Comment by BjarniRunar** [comment]
Yes, this is exciting!

However, note that we're not in the distro image building business; there is a lot of work involved in doing that well, and I am not interested in doing something like that poorly! Consider security updates, for one thing. Our job is big enough already...

We will be providing Debian packages that any Rasbian user can install, and testing on the Raspberry Pi will be something we will do. I have a Pi II myself for just that purpose... Considering the amount of tinkering the user will need to do to configure the WLAN in your scenario, I don't think an extra 'apt-get install' to install Mailpile itself will be a noticeable burden. :-)

Thanks for filing - the Pi family of devices is definitely on our radar and will be supported as well as we can.
