### ISSUE TITLE
Feature: Create "Bundles" of messages that are available publically

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#153]
More info coming soon...

**Comment by nkoehring** [comment]
The "more info coming soon" is there for 1.5 years. I like the idea but have no clue how to manage this in the scope of email. Or is it meant to be usable inside one multi-user install only?

**Comment by bnvk** [comment]
@nkoehring  you're right. This issue was never expanded upon. That functionality is quite far from existing. Closing it. Thanks ;)
