### ISSUE TITLE
Find Encryption Keys only displays results already in keychain 

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1539]
I've tested this with multiple keys and the experience seems to repeat. Whenever I use the "Find Encryption Keys" or "Cannot Encrypt" feature in the normal reading mail thread to discover a key for someone- it returns "no encryption keys found" unless the key is already in the keychain.

However, upon looking up a key manually via `gpg --search-keys name@email.com` results are found. 

I'm using current master of Mailpile on Fedora with gpg (GnuPG) 1.4.19

so it might just be something in the async JS making it fail to show results, but there are no JS errors in my console.

**Comment by BjarniRunar** [comment]
It would be useful to know what those JS errors are...

**Comment by bnvk** [comment]
@BjarniRunar sorry, typo. Updated "...no JS errors in my console"
