### ISSUE TITLE
Weird space above compose-mail content-view

### ISSUE THREAD

**Issue by libscott** [mailpile/Mailpile#1540]
Screenshot below. Above the compose section there's a white gap that looks out of place, it's the `top` offset in the `content-view` element.

![screenshot from 2016-01-14 18 42 37](https://cloud.githubusercontent.com/assets/125019/12332412/9c604172-baee-11e5-92db-6f13df89701e.png)

**Comment by BjarniRunar** [comment]
Thank you for filing this. It was on my offline TODO-list, but there wasn't an issue tracking it.
