### ISSUE TITLE
JSON error on refreshing a page

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1541]
Experienced a loading crash issue whereby upon doing CTRl-R to refresh the following search view the error was:

```
There was an error parsing the JSON document. The document may not be well-formed.
unexpected character at line 1 column 1
<!doctype html>
...
```

The content of the rest of the page was the full HTML view of my Mailpile search view! The behavior I was doing was
1. Viewing messages in http://localhost:33411/in/16/?q=is:unread
2. Performing various tagging operations
3. Then once the search view neared empty (from moved msgs) pressing CTRL-R
4. The page would flicker for a second with the interface, then go to the JSON parsing error

Seems like something with autoajax + the .jhtml format.

**Comment by BjarniRunar** [comment]
I have also seen this, every now and then. I think there is a bug somewhere which causes the wrong MIME-type or output format. It's a heisenbug, most likely in the command cache. :-(
