### ISSUE TITLE
Implement OpenPGKEY/DNS/WKS for getting public keys

### ISSUE THREAD

**Issue by rugk** [mailpile/Mailpile#1552]
It would be good to have another source for getting the public PGP key.
It e.g. can already be used at mail.de and [posteo.de](https://posteo.de/en/blog/new-posteo-webmail-interface-can-find-public-keys).

Here is a test site: https://openpgpkey.info/

The special thing is that the keys are verified if you use DNSSEC (what is obviously difficult on a client), but you could e.g. also use the [API from Posteo](https://github.com/posteo/mailvelope_client) (@posteo).

**Comment by BjarniRunar** [comment]
We already support DNS PKI discovery, is this something else?

**Comment by rugk** [comment]
I don't really know what you mean by DNS PKI discover, but it does not sound like this, because it does not rely on a PKI. Just in case you mean S/MIME: No I did not mean this - I meant PGP keys.
It really only relies on the DNS and [DNSSEC](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions).

I've already linked to some descriptions, but here are some more:
* [Easy description of the system by Posteo](https://posteo.de/en/blog/new-posteo-public-key-directory)
* [IETF working draft on `OPENPGPKEY`](https://tools.ietf.org/html/draft-ietf-dane-openpgpkey-02)

**Comment by BjarniRunar** [comment]
You are right, this is something different. Our current find-a-key-with-DNS code is here (https://github.com/mailpile/Mailpile/blob/master/mailpile/plugins/keylookup/dnspka.py) - this should be enhanced to support the IETF draft at some point.

I don't know whether it's possible (or how hard it is) for Mailpile itself to verify DNSSEC, that needs further research, but we should at least support the record type. Using the Posteo API could make sense, although it places a lot of trust on Posteo - but is probably still better than nothing, especially if accessed over Tor and if the DNS records are looked up over a separate channel.

Thanks for raising this!

**Comment by rugk** [comment]
> I don't know whether it's possible (or how hard it is) for Mailpile itself to verify DNSSEC

Quite hard AFAIK as you usually need a local resolver to do this if you do not want to rely on the data send by your DNS server.

> Using the Posteo API could make sense, although it places a lot of trust on Posteo - but is probably still better than nothing, especially if accessed over Tor and if the DNS records are looked up over a separate channel.

Yes, I completely agree. But at first I don't know another service, which does this - except https://openpgpkey.info/, but this does not seem to have an API - and if this check is only an additional verification it obviously does not hurt to check it as you said.

The only other possibility I can imagine is somehow working together with the developers of the [DNSSEC/TLSA addon](https://www.dnssec-validator.cz/) to implement some API there, which allows this addon to retrieve the necessary data. The disadvantage of this method obviously is that you need another addon as a user, but possibly it could also be made optional so that you recommend users to install this addon too and if they do so it is used.

**Comment by renne** [comment]
DANE-OpenPGP has just been released as [IETF RFC 7929 - DNS-Based Authentication of Named Entities (DANE) Bindings for OpenPGP](https://www.rfc-editor.org/rfc/pdfrfc/rfc7929.txt.pdf). ;)

**Comment by BjarniRunar** [comment]
Adding WKS to the list of things we should support... https://www.gnupg.org/blog/20160830-web-key-service.html

**Comment by BjarniRunar** [comment]
WKS/WKD is supported, it is awesome.

Other things I've been actively removing - the user experience of keys coming from DNS was atrocious, and even the pros were failing to update/maintain their keys because DNS is just not an accessible data store for anyone.

Closing this issue, thank you for helping make Mailpile better! :-)
