### ISSUE TITLE
Can I deactivate deletion of mails from my server?

### ISSUE THREAD

**Issue by rugk** [mailpile/Mailpile#1553]
Possibly also a good question for the FAQ:
**Can I deactivate deletion of mails from my server?**
I would just like to use this is an usual mail client by syncing mail to the server.

**Comment by BjarniRunar** [comment]
Mailpile doesn't actually do any deletion at all at the moment, so the answer is "no", but not the way you'd think. :-)

This will change, when we do actually support deletion (and syncing), we will of course make it optional.

**Comment by rugk** [comment]
Oh okay. From what i read at your website I thought this would be a thing you already do: Trying to download all mails from the server as soon as they arrive so that they are hopefully not that long on this server.
