### ISSUE TITLE
Can I use Mailpile

### ISSUE THREAD

**Issue by lalop** [mailpile/Mailpile#1556]
Hello,

I'm really really interested to move to mailpile as mail client but I'm answering if this is a reasonable choice for the moment.
Is there people using it as their day to day mail client ?

**Comment by BjarniRunar** [comment]
We have not made a "stable" release yet. It's coming soon, but we're not quite there yet.

That said, there are a few people, myself included, that have been using Mailpile as their day-to-day mail client for quite some time.

If you decided to join our ranks, you're most welcome - we need testers, and our best feedback comes from people who use the softare. I would recommend you join #mailpile on Freenode (IRC), so you can chat with us live and get a feel for the state of things.
