### ISSUE TITLE
Unable to do many javascript actions if WebNotifications are disabled by client

### ISSUE THREAD

**Issue by foxyantho** [mailpile/Mailpile#1558]
__Hello__ :smile: 

Unable to do many javascript actions if WebNotifications are disabled by client
.
Example 1 : Unable to list contacts in Mail composer & add attachments to mail ( [screen capture](http://imgh.us/c_8.png) )
Example 2 : Can't switch text/html view in mail viewer

**How to reproduce :**
- In Firefox, set "dom.webnotifications.enabled" to "false"
- compose new mail : try adding a receiver ; try adding attachments
- try switch html/text in mail viewer

**Version** : bleeding edge master

---

**What I found :**

If WebNotifications are disabled, this code : https://github.com/mailpile/Mailpile/blob/master/shared-data/default-theme/html/partials/head.html#L73-L79  will cause a `ReferenceError: Notification is not defined` preventing executing next code.

Temp solution : it should be wrapped in
```js
if (window.Notification) {

} else {

}
```

Goodbye!

**Comment by BjarniRunar** [comment]
Thank you for the detailed bug report! :-)
