### ISSUE TITLE
Protect message headers in encrypted mail (renamed)

### ISSUE THREAD

**Issue by danx0r** [mailpile/Mailpile#156]
Old subject: Optional encrypted subject line

if the option is checked, the unsecured subject header would be something generic like "subject:ENCRYPTED", and the real subject would be in the text of the email, possibly an extra MIME part.  Mailpile would gracefully use the encrypted subject when possible, suppressing it from the body and showing it in the subject field (and threading on it of course)

Just a thought

**Comment by BjarniRunar** [comment]
Update: This work is now happening as part of the Memory Hole initiative, http://modernpgp.org/memoryhole/ and some code exists in `mailpile/contrib/experiments`

**Comment by ralfhauser** [comment]
To have an overview of encrypted mailing lists see

https://systemausfall.org/wikis/howto/CryptoMailingLists

**Comment by BjarniRunar** [comment]
This is incoming! As a quick reference to the implementation I've ended up with, here is a super-brief discussion of how Mailpile will implement header protections (Memory Hole)...

## E-mail generation

1. When Mailpile generates a PGP/MIME encrypted or signed message, a selection of standard rfc2822 headers (From, To, Cc, Subject, ...) is copied to the header section of the outermost MIME part within the PGP-protected envelope. These copies are considered **protected**.

2. When Mailpile generates a PGP/MIME encrypted message, a subset of the *protected headers* will be **obscured** from the main message header. Obscuring means different things for different headers; for Subject it means replacing the subject with the words "Encrypted Subject", for From/To/Cc it means stripping names and comments (leaving e-mail addresses).

3. The process of obscuring headers can be tuned for more privacy, at the expense of less compatibility with e-mail apps that don't implement Memory Hole. As an example, obscuring the `in-reply-to` header would be good for privacy, but would break threading in many apps. Mailpile will offer one public setting in the UI "minimize metadata" which will choose a slightly more aggressive policy than the default. The default is to only obscure the Subject.

4. When headers are obscured, Mailpile will add a `text/rfc822-headers` part (with the attribute protected-headers=v1) as the first visible part (content-disposition: inline) within the encrypted section. This part will contain a copy of the original (unobscured) headers, so users with mail user agents that don't support Memory Hole can still see the content.

## E-mail parsing

1. When parsing a PGP/MIME e-mail, any non-MIME headers found in the outermost MIME part are copied to the main rfc2822 message header (overriding anything that was there before).

2. When parsing a PGP/MIME e-mail, if a `text/rfc822-headers` part is found which has the `protected-headers` attribute, Mailpile will a) copy any headers to the main rfc2822 message header and b) delete the part from the parsed structure. Note that this takes place after 1) above, overriding anything found in the in the MIME header if there is a conflict. This behaviour is compatible with Enigmail's implementation and guarantees that all users see the same data (whether they have Memory Hole support or not).

## Future work

Currently nothing in the user interface indicates that a header was protected. We just silently update what is displayed using the most reliable data available to us from the signed or encrypted part. Is is currently unclear whether notifying the user on conflicts would have a low enough false-positive rate to actually be useful.

We expect both the default obscuring settings and the "minimize metadata" behaviour to change over time and become more aggressive as Memory Hole support (hopefully) becomes more widespread. Ultimately, it should become possible to obscure nearly everything from the unencrypted header, preventing all metadata leakage that isn't actually necessary for correct routing of mail and bounces (the SMTP envelope).

Just like we tune Mailpile's default encryption policy depending on the perceived capabilities of the recipients, it would be possible to tune Memory Hole as well. If someone always sends us mail using Mailpile or Enigmail (or some other known-good MUA), it might make sense to use more aggressive strategies to obscure metadata.

**Comment by BjarniRunar** [comment]
Merged. Filed new issue to track future improvements. Closing!
