### ISSUE TITLE
Text wrapper is too aggressive

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1560]
The code which wraps text before sending e-mail is too aggressive.

There also needs to be a clear, easy way to disable the wrapping for when people are pasting code or doing ASCII-art. The current auto-detection of such things fails badly in many cases and it's unlikely that we'll ever get this 100% right; some form of manual controls are justified.

We should also consider the role of generating simple HTML mail in this context; if we are re-flowing the text successfully then we must know something about the semantics of the message. That is much more accurately communicated via. HTML tags, which should increase the odds that our mail renders cleanly and elegantly in receiving mail clients.

**Comment by BjarniRunar** [comment]
Relevant: https://www.ietf.org/rfc/rfc3676.txt (and http://joeclark.org/ffaq.html).

**Comment by JackDca** [comment]
Also relevant: #1638 and #1862.

**Comment by BjarniRunar** [comment]
See #1862 for more details (including screenshots) of how this currently misbehaves.
