### ISSUE TITLE
BCC of encrypted messages should send/encrypt separately

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1561]
The user expectation when using BCC is that the people in the To/CC lines are unaware of the BCC'ed recipients.

PGP may violate this expectation, by including the key IDs of the BCC'ed folks. We should fix this by making sure BCC'ed folks get a separate copy of the message that is encrypted only to them.

Relates to #733.

**Comment by BjarniRunar** [comment]
As a stop-gap until this is fixed, the UI should warn the user about this unexpected behaviour.

**Comment by BjarniRunar** [comment]
An alternate solution is to use --hidden-recipient for the BCC'ed recipients. The usability of this on the receiving end should be examined before we go this route.

**Comment by ed-davies** [comment]
Just came back to say that Thunderbird/Enigmail gives the hidden recipient option and I see you've found it. As always with this sort of thing, though, the Enigmail dialog box for it is a bit difficult to understand. Still, it seems Thunderbird/Enigmail, at least, can read hidden-recipient keys OK.

**Comment by BjarniRunar** [comment]
Thanks @ed-davies! For the record, this is exactly the sort of thing that shouldn't require a setting; the semantics of BCC are clear, if we don't keep the implied promise then we're buggy. It's just a matter of figuring out how best to do it...

**Comment by NoahAndrews** [comment]
I believe this should be reopened. Commit 2eec6f2 fixed issue #1651, not this issue, #1561.

**Comment by BjarniRunar** [comment]
Update: I'm back to strongly believing we should encrypt separately to each BCC recipient.
