### ISSUE TITLE
Make sure styles and scripts are cached when config does not change

### ISSUE THREAD

**Issue by DoubleMalt** [mailpile/Mailpile#1570]
I will look into that

**Comment by DoubleMalt** [comment]
It seems that default.css is handled by send_file() in httpd.py#236 which overwrites cache control thus removing the no-store property, while jsapi/as.js, jsapi/as.css and jsapi/app.js get this header from _real_do_GET() in httpd.py#331 (header is set at line 443).

Is there any danger that these files contain information that should not be cached?

**Comment by BjarniRunar** [comment]
Late reply, but... I suspect you're right @DoubleMalt and this is just a bug. The routines that handle static content in `httpd.py` shouldn't prevent caching.

**Comment by BjarniRunar** [comment]
I have this fixed in my local tree. Will push soon, nobody touch this. :)
