### ISSUE TITLE
pop3 internal error (sleeping)

### ISSUE THREAD

**Issue by chrisamow** [mailpile/Mailpile#1571]
mailpipe looks awesome and I like the command line and web design as well as python.  Hopefully I can get it to work!

The problem is with receiving email - this (subject line) is verbage from the Notifications list.

My pop3 info is configured correctly and verified working from another email client.  I'm not sure if this message means that mailpipe thinks the error is internal to the pop3 server or itself.

I'm a mailpipe newb so I don't want to start filing a deluge of issues in case it is just my pilot error.
The outgoing smtp works fine, although an email after sent, does not show up in the Sent box.  It also did not show up in the outbox (while it was presumably doing encryption stuff.)  Both just say "Hrm, We Could Not Find Anything"  Although Drafts says "1" even though I didn't save any drafts.  I verified that the email was sent by checking from another email client also (although it didn't seem to have encryption related data attached.)

Maybe this will be of interest/use:

mailpile> ps
Elapsed: 0.000s (ps: Listed events, threads, and locks)

Recent events:
  56b6f94d-00012-23e7=ListProfiles:c profiles: Listed 1/1 results
  56b6f94d-00016-23e7=MessageOfTheDay:c motd:
  56b6f94d-00018-23e7=JsApi:c jsapi: Generated Javascript API
  56b6f94d-0001a-23e7=JsApi:c jsapi: Generated Javascript API
  56b6f94d-0001c-23e7=JsApi:c jsapi: Generated Javascript API
  56b6f950-00025-23e7=Search:c search: Found 0 results in 0.001s
  56b6f950-00026-23e7=ListProfiles:c profiles: Listed 1/1 results
  56b6f952-0002b-23e7=Search:c search: Found 0 results in 0.001s
  56b6f953-0002c-23e7=ListProfiles:c profiles: Listed 1/1 results
  56b6f9a8-00039-23e7=EmptyOutbox:c sendmail: The outbox is empty

Events in progress:
 56b6d71b-000a2-2024=Pop3MailSource:R Internal error!  Sleeping...

Live sessions:
  HNk3PA4yWYAR6RtVee4uWLnUyAuIREAf/{'t': '56b6f94d'} = DEFAULT (18s)

Postinglist timers:
{'load': 0, 'load_count': 0, 'save': 0, 'save_count': 0, 'render': 0}

Threads: (bg delay 0.069s, live=0, httpd=0)
  <Cron(Cron worker, started daemon 140633054504704)>: Finished refresh_command_cache (0s)
  <HttpWorker(Thread-3, started daemon 140633039709952)>
  <ImportantWorker(Save worker, started 140632781739776)>: Idle (111s, jobs=0, jobs_after=0)
  <Pop3MailSource(chris@amow.com, started 140633031317248)>: Idle(790)
  <Thread(DONE:/api/0/cached/sidebar.jhtml!minimal, started daemon 140632773347072)>
  <Thread(DONE:/jsapi/as.css, started daemon 140633022924544)>
  <Thread(WORK:/api/0/logs/events/, started daemon 140632760624896)>
  <Worker(Scan worker, started 140632790132480)>: Finished refresh_command_cache (0s, jobs=0, jobs_after=0)
  <Worker(Slow worker, started 140632798525184)>: Finished sendmail (20s, jobs=0, jobs_after=0)
  <_MainThread(MainThread, started 140633140049728)>

Locks:
  <Cron(Cron worker, started daemon 140633054504704)>: Finished refresh_command_cache (0s).lock is unlocked
  <Pop3MailSource(chris@amow.com, started 140633031317248)>: Idle(790)._lock is unlocked
  config._lock is unlocked
  config.index._lock is unlocked
  config.index._save_lock is unlocked
  config.vcards._lock is unlocked
  mailpile.plugins.compose.GLOBAL_EDITING_LOCK is unlocked
  mailpile.plugins.contacts.GLOBAL_VCARD_LOCK is unlocked
  mailpile.postinglist.GLOBAL_GPL_LOCK is unlocked
  mailpile.postinglist.GLOBAL_OPTIMIZE_LOCK is unlocked
  mailpile.postinglist.GLOBAL_POSTING_LOCK is unlocked

**Comment by chrisamow** [comment]
I should have added that I am using linux mint 17 and my pop3 server is arvixe windows host

**Comment by BjarniRunar** [comment]
Thank you for reporting this. I am travelling, so it'll take a few days before I can respond properly.

**Comment by chrisamow** [comment]
Thanks Bjarni, let me know if there are any logs to check or ways I should debug it - I didn't see any faqs on it.

**Comment by chrisamow** [comment]
An IOError exception was getting thrown by POP3Mailbox._connect()
when trying to use SSL.  This happened even when my "Receiving Mail" is set to POP3 (instead of POP3/TLS) so I forced it to not use SSL (commenting out the 3 SSL lines so it would fall through to the code that ends with self.secure = False)

and was hoping that letting it continue to run would result in my inbox getting filled.

At the top of the web page it does say "Processed 1 mailboxes" now (instead of giving an internal error notification at the bottom), but it says my inboxes are empty.  If I then check it with another email client it downloads some emails.

Don't have time to step through the pop3 downloading code to see what is going wrong right now.

**Comment by chrisamow** [comment]
I checked my pop3 server (telling it to "Use SSL")
https://www.wormly.com/test_pop3_mail_server

Resolving hostname...
Connecting...
S:+OK Welcome to the plumeria POP3 server.
C: QUIT
S:+OK POP3 server saying goodbye...
POP3 test completed successfully.

**Comment by kklot** [comment]
I quote this part because it exactly describe what happen on Ubuntu 16.04/Gmail/IMAP

> I'm a mailpipe newb so I don't want to start filing a deluge of issues in case it is just my pilot error.
The outgoing smtp works fine, although an email after sent, does not show up in the Sent box. It also did not show up in the outbox (while it was presumably doing encryption stuff.) Both just say "Hrm, We Could Not Find Anything" Although Drafts says "1" even though I didn't save any drafts. I verified that the email was sent by checking from another email client also (although it didn't seem to have encryption related data attached.)

**Comment by mathiasfriman** [comment]
Hi!

This bug (or whatever) affects me too. I'm running a local pop3 mailserver that listens to 192.168.1.117:1110 i.e. not the ordinary pop3 port 110. It does not handle SSL or any encryption but it is just for testing purposes now. I can telnet to port 1110 and list and retreive mail:

    Connected to 192.168.1.117.
    Escape character is '^]'.
    +OK POP3 Server Ready
    user admin
    +OK you may try login as admin
    pass password
    +OK admin maildrop logged in, you have 2 messages (2902 octets)
    list
    +OK 2 messages (2902 octets)
    1 1452
    2 1450
    .
    retr 2
etc.

However, when trying to fetch mail with mailpile, it reports Internal error - Sleeping.. and when expanding the error message I get

    {
     "data": {
      "connection": {
       "error": [
        "network", 
        "A network error occurred"
       ], 
       "live": false
      }, 
      "counters": {
       "copied_messages": 0, 
       "indexed_messages": 0, 
       "unknown_policies": 0
      }, 
      "have_unknown": false, 
      "id": "b9557f4c8c4", 
      "mailbox_state": {}, 
      "name": "admin@192.168.1.117", 
      "plan": [
       [
        "0002", 
        "Internal error: Not a mailbox: src:b9557f4c8c4", 
        "src:b9557f4c8c4"
       ]
      ], 
      "traceback": "Traceback (most recent call last):\n  File \"/var/tmp/Mailpile/mailpile/mail_source/__init__.py\", line 924, in run\n    self.sync_mail()\n  File \"/var/tmp/Mailpile/mailpile/mail_source/__init__.py\", line 264, in sync_mail\n    elif (self._has_mailbox_changed(mbx_cfg, state) or\n  File \"/var/tmp/Mailpile/mailpile/mail_source/pop3.py\", line 77, in _has_mailbox_changed\n    prefer_local=False)\n  File \"/var/tmp/Mailpile/mailpile/config/manager.py\", line 825, in open_mailbox\n    mbox = OpenMailbox(mfn.raw_fp, self, create=editable)\n  File \"/var/tmp/Mailpile/mailpile/mailboxes/__init__.py\", line 56, in OpenMailbox\n    raise ValueError('Not a mailbox: %s' % fn)\nValueError: Not a mailbox: src:b9557f4c8c4\n"
     }, 
     "date": "Wed, 05 Oct 2016 12:13:25 -0000", 
     "event_id": "57f4c910-002d9-106e", 
     "flags": "R", 
     "message": "Internal error!  Sleeping...", 
     "private_data": {}, 
     "source": ".mail_source.pop3.Pop3MailSource", 
     "ts": 1475669605.007942
    }

Even if i recreate the mailbox with the same settings, I get the same error. :/

**Comment by matthewbloch** [comment]
I'm also stuck on an initial import with IMAP, which I assume is a data-related bug. Is there any way to trace the IMAP connection, or decrypt the logs in .local/share/Mailpile/default/logs ?

**Comment by BjarniRunar** [comment]
I did a bunch of work on the POP3 mail source recently, fixing some bugs and testing. As far as I know it works reasonably well now. I am going to close this issue; if people experience new problems with the updated code filing new bugs would be the right thing to do.

Thanks everyone for testing and reporting!
