### ISSUE TITLE
Mailpile should not start a browser

### ISSUE THREAD

**Issue by rmenessec** [mailpile/Mailpile#1574]
Every time Mailpile is started on Linux, it attempts to start a browser. Since I'm working with Mailpile as root, that means a new Firefox instance starts under the root account.

I get that Mailpile is trying to be helpful here, but it's a little too helpful. Please add a way to disable this behavior.

Thanks!

**Comment by BjarniRunar** [comment]
To disable this, simply unset the X DISPLAY environment variable:

    export DISPLAY=

Or:

    set prefs.open_in_browser = False

...using the Mailpile CLI.

**Comment by rmenessec** [comment]
@BjarniRunar , this does not work.
```
mailpile> set prefs.open_in_browser = False
WARNING: Any changes will be overwritten on login
Elapsed: 0.001s (set: Updated your settings)

{
    "prefs.open_in_browser": "False"
}

mailpile> 
```
After quitting Mailpile and restarting, either this preference is gone, or it did not work as intended.

#1526 is also still not fixed, but you've left the issue closed, and the documentation has not been changed to reflect the workarounds mentioned in the issue.

Please address both issues.

**Comment by BjarniRunar** [comment]
Please don't make demands.

Thank you for reporting the problems, I'll take a look when I have time.

**Comment by BjarniRunar** [comment]
The prefs setting works just fine if you log in first. Changing settings when not logged in does not work - and I am honestly not sure whether that is a bug or a feature. :-)

**Comment by rmenessec** [comment]
I'm very, sincerely sorry. I should have worded that differently. I did not intend to make a demand.

Please accept my apologies.

**Comment by BjarniRunar** [comment]
@rmenessec Apology accepted :)  I know buggy software can be frustrating, but we're all doing our best here.
