### ISSUE TITLE
Don't depend on $HOME/.gnupg in tests (mailpile 0.5.2)

### ISSUE THREAD

**Issue by sjagoe** [mailpile/Mailpile#1577]
The test `mailpile.tests.test_command.TestGPG.test_key_import` implicitly depends on the user's existing `$HOME/.gnupg` directory. I don't want unit tests messing with my GPG keyring.

I noticed this when attempting to build mailpile 0.5.2 for NixOS (which currently packages only v0.4.1). NixOS build tools isolate the whole environment to ensure a reproducible build, causing the above test to fail.

I modified the test to set `self.mp._session.config.sys.gpg_home` to a temporary directory, but I was not able to _unset_ this config value. Attempting a `delattr()` fails, as does setting it to `None`, so I don't consider my change pull-request ready.

**Comment by BjarniRunar** [comment]
Thanks for reporting this! I think adding this configuration change to the shared environment used by the tests would make sense - and cleanup is not necessary in that case. Had you considered that approach?

**Comment by sjagoe** [comment]
I didn't dig far enough in to see the shared test environment; I just stayed in the confines of the one test.

I'll have a look and open a pull request early next week.
