### ISSUE TITLE
MathJax plugin for Mailpile

### ISSUE THREAD

**Issue by cbz20** [mailpile/Mailpile#1580]
from @BjarniRunar's comment in closed issue #1579:

> Adding support for composition-time conversion, that converts Markdown or Asciidoc or even LaTeX to HTML and plain-text would not have the same security implications. I would encourage people to consider this instead of changing the format of e-mail and complicating the receiving end.

For rendering LaTeX code in html, there is a nice Javascript library called [MathJax](https://www.mathjax.org/). By using a local installation of MathJax and choosing the right configuration, this should be pretty safe.

Actually, I have already written some MathJax code for Mailpile. ​So far, the features are quite basic: Firstly, an on/off button for displaying maths in email conversations, and secondly, a field below the email composer which displays a preview of the email with typeset maths. This preview gets updated as the email is being written (onkeyup):

![mathjaxformailpilecomments](https://cloud.githubusercontent.com/assets/9016969/13725487/4507bcc2-e89b-11e5-82e2-d3b0886fc578.PNG)

However, I did this before the major changes to the compose/display layout last autumn. I decided to wait until the first stable version is released, before I look into it again, but I'd be happy to!

**Comment by BjarniRunar** [comment]
That is very exciting!  Turning this into a proper plugin will probably require we fix/add some plugin hooks, but this is absolutely something we would like to support. Let's talk more when things settle down a bit. :-)

**Comment by cbz20** [comment]
Would you say that things have "settled down" sufficiently? (The inline-reply still looks a bit rough, in my opinion.) But I would be happy to look into this issue again. Perhaps, there does not have to be a switch button -- I do not see any reason why MathJax should not be enabled by default if configured properly.
