### ISSUE TITLE
Make CLI more discoverable

### ISSUE THREAD

**Issue by rmenessec** [mailpile/Mailpile#1581]
While attempting to guess how to set up Mailpile to connect to a Tor (SOCKS5) proxy other than localhost, I happened to stumble across the ability to use the "print" command in the CLI to list certain classes of config variables; for example, "print sys" or "print prefs".

I can't find this in the wiki or anywhere in the CLI's inline help. What other configuration variable classes are there besides "sys" and "prefs"?

Please consider adding this information somewhere in the CLI help; with 90% of the configuration variables accessible via the CLI only, it should be easier to find / print / set them.

Thanks!

**Comment by BjarniRunar** [comment]
Yep, our docs need work.

We need to explain the settings on the CLI and also explain which things are dangerous to modify; the web UI does a good job of that now, but only for a small subset of the app's configuration. The CLI is where all the power is, and all the opportunities to shoot ones' self in the foot. :-)

It's a big task.

**Comment by BjarniRunar** [comment]
I think this is largely addressed: there is now a button in the web UI which opens the terminal in the browser, and the browser based terminal gives some hints to get people started. The CLI help still needs an overhaul, but there's a separate issue for that: #1942 

Thank you for filing this!
