### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by lpaware** [mailpile/Mailpile#1582]
1. There is open redirect issue at ( http://localhost:33411/auth/login/?_path=%2F ) .The parameter _path= / leads to the issue.
2.   With reference to the Improve redirector, issue #360 , 
   
   ```
       if '//' not in destination:
                   destination = '%s%s' % (self.server_url(), destination)
   ```

The above 2 lines are not present in the latest version of mail pile I downloaded.When the necessary changes were made, that is the above two lines of code were added to httpd.py and rerun the program again. Mail pile isn't starting up.

**Comment by BjarniRunar** [comment]
Thanks for reporting this, it's a good point. Isn't this an incorrect fix anyway though?

Without the host part, it'll just always redirect to localhost (which is safe, GET requests never modify state in a dangerous way in Mailpile) - it's when // is present and the destination is malicious that we have a potential vulnerability.

I'll take a close look at my end. Regarding the fact that your Mailpile isn't starting up - I can't comment on that, you didn't post any details. :)

**Comment by BjarniRunar** [comment]
Confirmed; in the default setup it is possible to get Mailpile to redirect to external sites. Working on a fix.
