### ISSUE TITLE
threadview should show full subjects

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1585]
At least in some manner.  Currently subject lines are truncated to fit the column, and tooltips provide a preview of the body text.  Particularly when reading patch series's, the subject lines are actually not all the same and do contain useful information. see example below

![example](http://i.imgur.com/g8hpC9i.png)

**Comment by BjarniRunar** [comment]
I would prefer this get fixed by improving the tooltip. Currently the thread view uses the browser native tooltips, but a qtip would allow for more formatting - and should probably include the subject.

**Comment by sh4d0wst0rm** [comment]
Hi this is my first time trying to contribute to an open source project , could help me locate the code for this issue

**Comment by BjarniRunar** [comment]
Hi @sh4d0wst0rm!

This is all in the user interface templates and the Javascript code. If you look in `shared-data/default-theme/html/`, there are two locations that matter in this case.

One is `partials/pile_thread.html` which renders the data into HTML; you may need to adjust this template or consult to make sure the full subjects are available in the DOM, and perhaps adjust slightly to remove the existing tooltip (which is currently just a title= attribute on the thread-message "a" tag).

The other location is the `jsapi/message/` folder; there are various Javascript helpers there to do with the display of individual messages (for example formatted qtips for displaying crypto state). You will need to take a look at how those other qtip-tooltips are implemented (browse around the jsapi folders) and implement something similar for this.
