### ISSUE TITLE
Mailpile not running on Win10 Pro x64

### ISSUE THREAD

**Issue by AlexandrKir** [mailpile/Mailpile#1588]
Installed Mailpile (package Monday, 2015-08-10). After doubleclick on Mailpile icon, something runs, message appears "Mailpile is running now" in right bottom corner. And thats all.

**Comment by BjarniRunar** [comment]
Yes, that sounds perfectly fine. :)  If you visit localhost:33411 in your browser, you should be able to use the app. There might even be a tab already open in your browser at this point.

Making this less confusing is however recognized as an issue in and of itself, and is being tracked elsewhere.

**Comment by AlexandrKir** [comment]
D
![2016-05-30_16-01-01](https://cloud.githubusercontent.com/assets/18376998/15650239/c8704670-267f-11e6-84e8-0172a37aebd7.png)
id not help
