### ISSUE TITLE
Clicking on read message in unread conversation after filtering on unread leads back to list of unread messages

### ISSUE THREAD

**Issue by DaLynX** [mailpile/Mailpile#1589]
Steps to reproduce the issue:
1. Go to _Inbox_
2. Click _Unread_
3. Open a conversation that has both read and unread messages
4. Click on a read message.

Could someone confirm you also have the same problem?

**Comment by BjarniRunar** [comment]
Confirmed. The logic which forces the display of an explicitly requested message, even if it no longer belongs to the search result context (the message is no longer unread, so no longer a valid result) appears to be incomplete.

**Comment by BjarniRunar** [comment]
I'm pretty sure this was fixed in a7955a46f7bd28a4b7115393e62a5f08c48caa16.
