### ISSUE TITLE
cannot send encrypted message to anyone but my self

### ISSUE THREAD

**Issue by webdawg** [mailpile/Mailpile#1594]
Is this supposed to be working?  I know mailpile is supposed to have bugs but I cannot get a message to encrypt.

It finds the key, am I supposed to select it?  Is a button supposed to pop up?

Is it not working because it is still syncing to an IMAP server.

I imported my own gpg key then set the password to the same pass as the web interface.

I also cannot send any messages to any manually imported keys.

I can send a encrypted message to myself.

**Comment by BjarniRunar** [comment]
I send encrypted messages all the time, so I'd need a bit more information about what you are doing, what you expected to happen, and what actually happened.

To encrypt a message, you click the lock icon in the composer. If you have keys for the recipients, it will change to a green padlock. If you don't, it'll prompt you to search for keys.

Closing this, as it's quite old and not actually a bug as far as I can tell. Feel free to reopen the issue if you feel I've missed something.
