### ISSUE TITLE
Encryption Key Password

### ISSUE THREAD

**Issue by scouseman** [mailpile/Mailpile#1601]
I have successfully added my email account to Mailpile and during the setup process for my email account I created a new 2048 key for my account. The problem I have is I have now idea of  knowing what the password is for the key as I never had the chance to create one when I created the key is there a default password?. When is the password for the key set? How do I know what it is?
Cheers

**Comment by BjarniRunar** [comment]
If I recall, Mailpile keeps track of the passphrase for you when it creates a key. All you should need is the passphrase for your Mailpile account.

This may however be a misfeature and may need to be rethought a bit. Relates to #912.

**Comment by BjarniRunar** [comment]
It is now possible to request Mailpile display the passphrase using the PGP key management dialog.
