### ISSUE TITLE
Message composition window should not scroll to put cursor at bottom.

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1604]
When composing a long email, the area for entering the message can become larger (vertically) than the window that displays it.  Then, the message entry area scrolls automatically so that the cursor is at the bottom of the window.  If the scroll bar is used to manually move the line containing the cursor to the middle of the window, when the next key is pressed, the message entry area automatically scrolls so the cursor is at the bottom of the window again.

One result is that the Notifications pop-up can cover the cursor if the cursor is near the right side of the window.  (Especially on a small screen e.g. a tablet.)

Another result is that, when making corrections in the middle of the message, the message scrolls down when making one correction, which hides the next line to be corrected, so that the user must scroll up manually using the down arrow key to get to the place for the next correction.  If there are multiple corrections this becomes time-consuming.

I've observed this using Firefox on Debian and using Chromium on Android.

Usability would be better if the window were to scroll automatically **only** when the cursor would otherwise move out of the visible part of the window.

**Comment by JackDca** [comment]
Perhaps a more general issue should be opened regarding the message composition window.  I just finished sending an important - and lengthy - email.  I wanted to format it with blank lines separating some (not all) headings from text, and using the hyphen "-" to "bullet" some points, and indenting to emphasize other points.  I saved and reloaded the draft several times.  Here's what I found:
- Saving/reloading results in insertion of newline characters.  So if you add more words to the middle of a line it is now too long and gets broken in the middle in the next save/reload.
- But, lines that start with "-" or " " are exempted from the insertion of newlines, so who knows how they appear to teh recipient.
- In lines that start with "-", it is replaced with "--".
- Newlines are sometimes removed; I was not able to figure out the rules that govern this.

I am not a big fan of HTML email so I don't miss it at all, but I want to decide how to format my own plain text, I don't want the program trying to do it for me.  Insertion of newlines is OK, even useful, when the email is finally sent, but doing it in a draft is annoying.

**Comment by BjarniRunar** [comment]
All fair comments, thank you. The composer needs a lot of work.

**Comment by JackDca** [comment]
I've now been using Mailpile for all my email composition for 8 months, including a fair share that are more than a page, and many which are a part of a long conversation, so I could add a lot of additional comments to the above.  Better not to do a revision piecemeal.  Will try to post more.

**Comment by JackDca** [comment]
I have tested 1.0.0rc2 on Debian 9/Firefox 52.4.0, Android 4.4.4/Chromium 62 and Win 10/Edge 40. The scrolling behaviour described in the title does not appear to be present in 1.0.0.0rc2 with these browsers.

The other comments on the message composition window are relevant to  a different issue: #1560.

I am closing this issue.
