### ISSUE TITLE
Automatic eventlog/watch when starting

### ISSUE THREAD

**Issue by Simon-L** [mailpile/Mailpile#1605]
Hello,

I'd like to be able to start Mailpile and have the eventlog being watched automatically.
Maybe through the use of a startup command?
Maybe by using a setting that would specify this?

I try to run `./mp eventlog/watch` alongside just `./mp` but it doesn't seem to work, it does not fail but no logs are displayed.

**Background:** I added mailpile to startup application inside tmux as `tmux new-session -d -s mailpile "/home/user/dev/Mailpile/./mp"` so I have that tmux session started which I can check anytime, if I ever need to go back to it, I'd like to have previous log displayed.

**Comment by BjarniRunar** [comment]
Running two Mailpiles won't accomplish what you want. Quite the opposite, it's a good way to corrupt data and break things, I need to file an issue to prevent that!

You can start your main mailpile with eventlog/watch as you did and that should work fine.
