### ISSUE TITLE
what is passphrase?

### ISSUE THREAD

**Issue by WangYongzhao** [mailpile/Mailpile#1609]
hi,
i am new to this project, i am trying to set up a local version, and block in this step.
http://localhost:33411/auth/login/?_path=%2F

i tried several times but all failed. Any one know what the passphrase is?

![image](https://cloud.githubusercontent.com/assets/19544350/16107775/2634a05e-33d1-11e6-9f60-3ffc87d29e7f.png)

**Comment by lae** [comment]
When you perform setup for Mailpile, it asks you to set a passphrase to use for encryption. You need to enter this password here to unlock your client.
