### ISSUE TITLE
External links opened from HTML emails get script execution blocked

### ISSUE THREAD

**Issue by Simon-L** [mailpile/Mailpile#1611]
When clicking on external links inside HTML emails, the resulting opened tab often just displays a blank window. Confirmed for me on Chrome, Chrome-beta and Firefox, all on Linux.
On Chrome, the exact error message is:
`Blocked script execution in '[link]' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

I do realise this might be a security feature.
Possibly related: #1347 (?)

**Comment by BjarniRunar** [comment]
This is unintended; we wanted to use the browser's sandboxing features to make the displayed HTML "safe", we did not realize that new tabs/windows would inherit the sandbox!

This needs to be fixed, but I'm not yet sure how to do so without disabling the sandbox. Any suggestions would be most appreciated.

**Comment by BjarniRunar** [comment]
This will be fixed next time I push up; however, our current fix relies on browser support for the `allow-popups-to-escape-from-sandbox` attribute on the iframe sandbox. Only the most recent browsers support this: http://blog.dubbelboer.com/2016/01/23/state-of-the-html-iframe-sandbox.html

I am looking into what else can be done. It looks like if we want a decent user experience, we may need to disable the sandbox for at least some browsers. It's dynamically generated (JS), so we do have that option. It just sucks. :-)

**Comment by BjarniRunar** [comment]
This is as fixed as it's going to be, for now at least.

Any browser that supports the allow-popups-to-escape-sandbox attribute on the iframes should now behave better. Unfortunately, that's not many browsers at the moment.

Others who want to live dangerously can: set prefs.html5_sandbox = false
