### ISSUE TITLE
Need to turn on access for less secure apps when using Gmail

### ISSUE THREAD

**Issue by ImagineInfinity** [mailpile/Mailpile#1614]
To use Mailpile I have to turn [this](https://www.google.com/settings/security/lesssecureapps) on.
Google had sent an email saying the following

> [...] Google just blocked someone from signing into your Google Account [my email] from an app that may put your account at risk.

**Comment by kehugter** [comment]
#822 #1371

**Comment by BjarniRunar** [comment]
Closing as a duplicate. Thanks for filing. :-)
