### ISSUE TITLE
Could not upload attachment because: HTTP Error.

### ISSUE THREAD

**Issue by mmni** [mailpile/Mailpile#1619]
I followed the instruction on "Getting started on linux" page in "Wiki", and successfully deployed a copy of Mailpile in a virtual machine, which was specifically used for Mailpile. Receiving mail works perfectly, and so does sending out plain mail, but I found that uploading any attachment will lead to an notification "Could not upload attachment because: HTTP Error."

Anyone experienced a similar thing before? any way to solve it? Thanks.

**Comment by sharifmarat** [comment]
In my case it was due to file size limitations. From nginx logs: "client intended to send too large body".
I just increased the file limit in `/etc/nginx/nginx.conf`:
```
http {
     ...
     client_max_body_size 10M;
}
```

**Comment by BjarniRunar** [comment]
Thanks for filing and thanks for the helpful reply @sharifmarat. I'm closing this as not-a-Mailpile-problem.
