### ISSUE TITLE
Unable to read maildir

### ISSUE THREAD

**Issue by comzeradd** [mailpile/Mailpile#1624]
I'm following the [instructions](https://github.com/mailpile/Mailpile/wiki/Configuring-Linux-to-download-your-email) for getting Mailpile read maildir created by offline imap.

But when I run the add command I get an error:

`add error: Not a mailbox: /Home$/mail`

Similarly, when I try to do this from the web UI instrad of Mailpile recognizing that this is a maildir folder, I get a list with all imap folders inside it.

**Comment by BjarniRunar** [comment]
I think this was fixed in my last big local-mail sprint. Please check HEAD and file a new issue if problems persist. Thanks for filing!
