### ISSUE TITLE
Wiki page with TOR HowTo

### ISSUE THREAD

**Issue by renne** [mailpile/Mailpile#1629]
I've forked Mailpile and created a [Wiki-page with basic instructions for TOR as transport protocol](https://github.com/renne/Mailpile/wiki/SMTP-over-TOR) instead of plain TCP/TLS. It seems Github does not allow pull-requests for Wikis.

How can I 'port' the Wiki page to the Mailpile repository?

**Comment by renne** [comment]
I was able to create a new page at [Mail(pile) TORified](https://github.com/mailpile/Mailpile/wiki/Mail(pile)-TORified). ;-)

**Comment by BjarniRunar** [comment]
Hi @renne! Thank you for doing this!

Could you add some words to the top of that Wiki page explaining what exactly you are doing and why?

It looks like you are configuring Mailpile for access over Tor as a hidden service, but I haven't fully read all the details so I'm not entirely sure.
