### ISSUE TITLE
Selection action: tag message is broken

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1632]
the box does not allow data entry

**Comment by BjarniRunar** [comment]
Yep, it's broken! :-)

To be more clear, what @ferdiga is (probably) reporting is that the tag popup from the selection-action list doesn't currently work. It has been broken for quite some time and needs to be either fixed or removed before 1.0.

**Comment by BjarniRunar** [comment]
Turns out this is basically a dup of #879. That issue has more details, closing this one.
