### ISSUE TITLE
layout problem on mobile devices

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1636]
1.0.0.rc0
after "selecting" a message - the menu bar (New,Trash,..)  overlays the text (Header)

![image](https://cloud.githubusercontent.com/assets/6248560/19016531/1855cac6-881d-11e6-9325-08c2742ca59b.png)

**Comment by ferdiga** [comment]
1.0.0rc0
it happens also on desktop browser after reducing width and height 

![image](https://cloud.githubusercontent.com/assets/6248560/19020865/aca3b372-88b4-11e6-92db-7e35d7b93865.png)

**Comment by BjarniRunar** [comment]
The mobile layout is very early alpha - it's not really expected to work yet.

I'm closing this; not because you're wrong, but because the entire mobile UI is considered broken and making a note of every way it fails would just clutter up the issue database.
