### ISSUE TITLE
save outgoing mail settings hangs

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1639]
1.0.0rc0
wanted to add my signature (with Umlaute)
clicked SAVE
waiting for <my server>
no more actions possible, except logging button shows something running

**Comment by BjarniRunar** [comment]
A appreciate your brevity and your interest, but you haven't provided any details with which we can attempt to figure out why this happened or what went wrong - let alone how to fix it.

I'm closing this since there's nothing I can do about it. :-)
