### ISSUE TITLE
milepile does not pick up state change on IMAP server

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1640]
1.0.0rc0
marking an email as read with another mail client (thunderbird, which I want to use as long the download all attachment function is not implemented) is not reflected in mailpile.
at least not in a reasonable time (probably because it's still busy with initial loading ?)

**Comment by BjarniRunar** [comment]
Mailpile does not currently do any synchronization with the remote server; it just copies mail and acts on it locally. Fixing that (adding a sync feature) is a large undertaking and is tracked elsewhere, e.g. #1017.
