### ISSUE TITLE
moving message to another folder/tag does not set the tag of the new folder

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1642]
1.0.0.rc0
on a gmail account , when I move a message from one subfolder to another, the tag of the target folder is not set

BUT
moving it to the master-Inbox (top of the list) the tag is set

PS:
moved a mail from "all mail" to "inbox"
- many mails are now in the "ALL Mail" instead of the Inbox !?? (1)
  So the mail shows up in
- Master Inbox
- all mails of the account
  but not in the inbox  

PPS: (1)
The mails are again correctly in the Inbox
I assume that the "All Mail"  issue occurs only when checking/downloading the "All Mail" folder - the new mail is checked in the "All Mail" folder before it is discovered in Inbox.

PPPS:
The mails are again in the "All Mail" box
Can not see a pattern.

**Comment by BjarniRunar** [comment]
I don't understand this issue.

It sounds like you're trying to remove messages from "All Mail", which isn't actually possible, since all mail is by definition, all mail. :-)

**Comment by ferdiga** [comment]
right, it's a bit confusing IMO,
currently it's not well or not at all clear on which folder or sub-folder is the focus.
in the search field the internal name is displayed -  
"in:mailbox-001e" or similar - not very helpful.....

suggestion - the active mailbox folder should be clearly highlighted and/or printed on top of the message header list.
