### ISSUE TITLE
notifications should include account/folder name

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1643]
1.0.0rc0
having defined multiple accounts a lot of messages are ambiguous as a lot of folders/tags have the same name in different accounts.
- Sending via smtp.gmail.com
- Copying up to xx e-mails from yyy

**Comment by BjarniRunar** [comment]
Thank you for filing this, sorry about the long silence.

Actually, the ambiguous notifications should probably (mostly) go away, but the details you seek should be exposed in a user-accessible fashion on the event log page.

The user benefits from seeing these popups right after account creation, to confirm things are working, but soon after they just become spammy. Closing as superceded by #2168.
