### ISSUE TITLE
icon - state of "mark read/unread" not to distinguish

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1645]
1.0.0.rc0
The state of the icon (sun?)  switches between gray and dark grey - hardly recognizable - especially on mobile devices in sun light.
IMO it should be adapted also to be readable by visually impaired and should hence change shape. 
sugestion open/closed envelop

**Comment by Epse** [comment]
very related to #1428

**Comment by bioncabond** [comment]
Hello @BjarniRunar, 

Is this still an issue that needs to be resolved?
