### ISSUE TITLE
Add an attachment upload progress dialog

### ISSUE THREAD

**Issue by DaLynX** [mailpile/Mailpile#1646]
I am using mailpile hosted on a remote server and uploading attachments can sometimes take quite long, depending on the quality of my connection, and I have no way of seeing what is going on unless an error comes up and I can see the notification, or the download finishes and I can see the attachment.

So an upload dialog where we could see the progress of files being uploaded - and maybe cancel one if necessary - would come really handy.

**Comment by BjarniRunar** [comment]
Agreed. I'm surprised if we don't have an issue tracking this already!

**Comment by DaLynX** [comment]
Apparently there is some code that is not working:
https://github.com/mailpile/Mailpile/blob/e2e8490aecab6640b99fee66aa9de5d9ef142402/shared-data/default-theme/html/jsapi/compose/attachments.js#L153

When I try to check this in my browser debugger, the selector returns a 0-length object.

**Comment by BjarniRunar** [comment]
It seems PR #1676, which attempts to address this, broke attachments completely. Will be looking into this soon.

**Comment by balping** [comment]
The progress bar is displayed nicely for me

**Comment by BjarniRunar** [comment]
This dialog exists and works, as far as I can tell. That said, it does have bugs. To reduce confusion I am going to close this issue as complete and file separate issues for the bugs I have found.
