### ISSUE TITLE
Mailpile displays no sender, no subject, and not able to reply

### ISSUE THREAD

**Issue by mathiasfriman** [mailpile/Mailpile#1647]
It seems that Mailpile is not able to extract the sender and subject from a POP3 fetched mail.

![mailpile-no-subject](https://cloud.githubusercontent.com/assets/3397596/19119508/429df1e0-8b20-11e6-9ff1-6e5fd638b97d.png)

And after opening the mail, it looks like this, sender and subject circled in green and red:

![mailpile-noone-sending](https://cloud.githubusercontent.com/assets/3397596/19119535/6052f564-8b20-11e6-9afa-62cf31dc906c.png)

When trying to reply to the mail, I get 

```
Message Not Found

We were unable to find the message you requested, perhaps it was deleted?

If you think this is a bug, please file a bug report
```

So I did... Extended error message is:

```
{
 "data": {
  "elapsed": 182, 
  "output": "composer.jhtml!minimal", 
  "ui": "HttpUserInteraction"
 }, 
 "date": "Wed, 05 Oct 2016 15:23:35 -0000", 
 "event_id": "57f51af7-008a9-1442", 
 "flags": "c", 
 "message": "reply: Failed: reply ", 
 "private_data": {
  "data": {
   "_method": "POST", 
   "context": [
    "search:568bfc8149fbc570a224ff22eb8d666e"
   ], 
   "csrf": [
    "57f51acf-uOTIfDNOarz1ipDjtj39flnJCeowzwvKbtSYfEKGnOUNuB1WGp3_FTjpRCaaETVqb5QrSqjmx9n3YrETahnHGQ"
   ], 
   "mid": [
    "6"
   ], 
   "reply_all": [
    "True"
   ]
  }
 }, 
 "source": ".plugins.compose.Reply", 
 "ts": 1475681015.693587
}
```

Not sure if that is helpful, please get back to me if you would like some more information.

**Comment by mathiasfriman** [comment]
Tested the CLI and got the following:

    mailpile> search
      1   (anonymous)          (No Subject)                            (src:34e57f4f27a[SE]19 hours
      2   matte                Testing signing and encrypting 3        (Sent[SE]19 hours
      3   (anonymous)          (No Subject)                            (src:2f757f50481[SE]19 hours
      4   admin                Testing signing and encrypting 2        (Sent[SE]19 hours
      5   admin                Testing signing and encrypting          (Sent)20 hours
      6   (anonymous)          (No Subject)                            (src:b9557f4c8c4)21 hours
      7   (anonymous)          (No Subject)                            (src:b9557f4c8c4)21 hours
      8   admin                testing smtp delivery via mailpi        (Sent[S]22 hours
      9   admin                testing internal delivery               (Sent[S]23 hours

    mailpile> view 1

      1 (anonymous)                      (No Subject)                                                                                    (src:34e57f4f27a[SE]19 hours
     ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Received: from mailpile.local (192.168.1.244:45255 [127.0.0.1])
    From: 
    To: 
    Cc: 
    Bcc: 
    Subject: 
    Encryption: none
    Attach-PGP-Pubkey: 

        by bdsmail (BDSMail-Brain Dead Simple Mail Server 0.1.0) with SMTP
        for <matte@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p>; Wed,  5 Oct 2016 55:34:28 -0000 (UTC)
    MIME-Version: 1.0
    Content-Type: multipart/encrypted;
     boundary="==XDuLmrnZIAGPPXrV2IXELEoc6io5uF==";
     protocol="application/pgp-encrypted"
    Subject: Testing signing and encrypting 3
    From: matte
     <matte@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p>
    Message-Id: <XkLtQSsQ6kHcwuddj6GukMToqBum9ILTAbCV7KWZ215b@mailpile>
    Date: Wed, 05 Oct 2016 15:33:33 -0000
    OpenPGP: id=CD90B01988E2EEE8D628D1C32B7A76EE0E68A87D; preference=sign
    To: admin <admin@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p>

    --==XDuLmrnZIAGPPXrV2IXELEoc6io5uF==
    Content-Type: application/pgp-encrypted
    Content-Disposition: attachment

    Version: 1

    --==XDuLmrnZIAGPPXrV2IXELEoc6io5uF==
    Content-Type: application/octet-stream
    Content-Disposition: attachment; filename="msg.asc"

    -----BEGIN PGP MESSAGE-----
    Version: GnuPG v1

    hQEMA1dM5lsRnEbkAQf+N0M/WnVeDxMO9NWQLve0NrW07OiK6O57gAKFjzBulF3L
    [..]
    yjN7t/pPoP3GPTzoTeYy9dEqIuuBBBqgLgbC
    =cG9t
    -----END PGP MESSAGE-----

    --==XDuLmrnZIAGPPXrV2IXELEoc6io5uF==--
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

So the problem seem to be that even though the information is in the header of the email, mailpile does not pick it up and doesn't display it in the corresponding places. The BDSMail software is at best beta so I'm not sure if the problem is within it or in Mailpile?

**Comment by mathiasfriman** [comment]
When replying in CLI:

    mailpile> r 1
    Traceback (most recent call last):
      File "/var/tmp/Mailpile/mailpile/commands.py", line 579, in _run_sync
        return self._finishing(command(self, *args, **kwargs))
      File "/var/tmp/Mailpile/mailpile/commands.py", line 577, in command
        return self.command(*args, **kwargs)
      File "/var/tmp/Mailpile/mailpile/plugins/compose.py", line 563, in command
        ephemeral=ephemeral)
      File "/var/tmp/Mailpile/mailpile/plugins/compose.py", line 500, in CreateReply
        text = ((_('%s wrote:') % t['headers_lc']['from']) + '\n' +
    KeyError: 'from'

    reply error: Failed: reply 1
    Elapsed: 0.507s (reply: Failed: reply 1)

    No results

No surprises of course, since the **from:** field is not set.

**Comment by BjarniRunar** [comment]
I'd need to have a sample of an actual mailbox created by BDSMail to fix this - it looks like messages are stored in a format which Mailpile is failing to parse. I think we discussed that it was most likely a Maildir, but it appears there's something else going on here.

**Comment by mathiasfriman** [comment]
Sorry, this is a different issue. This one adheres to POP3, not local maildirs, it's in the text but could have been made clearer.

In this particular issue I've tried to telnet to the POP3 port and all commands work nicely, like this:

    user admin
    pass password
    list
    retr 1
    quit

When fetched, the email is there in the folder, but the sender and subject can not be parsed from the email, and therefore, since the object does not have any such properties, the reply fails.

The one we discussed on IRC however, was with local mailboxes. I could make an issue of that too.

**Comment by mathiasfriman** [comment]
Here is the other issue. Short but sweet, with attached mailbox: #1658

**Comment by BjarniRunar** [comment]
So to get this clear - you download the mail using bdsmail, and then Mailpile is configured to re-download it using POP3?

**Comment by mathiasfriman** [comment]
Almost. :) bdsmail (https://github.com/majestrate/bdsmail) is a mail daemon like postfix or sendmail. It offers SMTP and POP3 interfaces (no IMAP4 yet). You use bdsmail to send and route emails in I2P, and also to setup local email accounts. 

    $ ./bin/maild config.lua 
    INFO[0000] Brain Dead Simple Mail Server 0.1.0          
    INFO[0000] loaded config config.lua                     
    INFO[0000] Using user maildir at /home/mathias/source/bdsmail/mail 
    INFO[0000] Using inbound maildir at /home/mathias/source/bdsmail/inbound 
    INFO[0000] using outbond maildir at /home/mathias/source/bdsmail/outbound 
    INFO[0000] Setting mail hostname to localhost           
    INFO[0000] Initialize database localhost.sqlite         
    INFO[0000] Database ready                               
    INFO[0000] binding web ui to 127.0.0.1:8888             
    INFO[0000] binding pop3 server to 127.0.0.1:1110        
    INFO[0000] Starting up I2P connection... hang tight we'll get there 
    INFO[0020] We are 2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p 
    INFO[0020] Starting Up Mail Server                      
    INFO[0020] Serving Web ui                               
    INFO[0020] Server Outbound SMTP Server on 127.0.0.1:2525 
    INFO[0020] Serving Inbound SMTP server                  
    INFO[0020] Outbound mail flusher started                
    INFO[0020] Serving POP3 server                    

So one mail address can be mathias@2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p so to login i do:

    $ telnet 127.0.0.1 1110
    Trying 127.0.0.1...
    Connected to 127.0.0.1.
    Escape character is '^]'.
    +OK POP3 Server Ready
    user mathias
    +OK you may try login as mathias
    pass mathpass
    +OK mathias maildrop logged in, you have 3 messages (4816 octets)
    list
    +OK 3 messages (4816 octets)
    1 1440
    2 1880
    3 1496
    .
    retr 1
    +OK 1440 octets
    Received: from ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p (pbAH6D--s2HMsHg2plzSCTQg0LPwbJtQKziBXjihl8dwdCbYUqIXkPhid~wy88QkJ6B0OxtCzxANxt-7CxLd8hZXRut-$
        by localhost (BDSMail-Brain Dead Simple Mail Server 0.1.0) with SMTP
        for <mathias@2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p>; Wed, 19 Oct 2016 1919:10:40 -0000 (UTC)
    Received: from raspberrypi (127.0.0.1:37706 [127.0.0.1])
        by bdsmail (BDSMail-Brain Dead Simple Mail Server 0.1.0) with SMTP
        for <mathias@2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p>; Wed, 19 Oct 2016 1919:10:28 -0000 (UTC)
    Date: Wed, 19 Oct 2016 07:10:28 +0000
    From: admin@ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    To: mathias <mathias@2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p>
    Subject: Re: Testing delivery from Mailpile
    Message-ID: <20161019071028.GJ8451@raspberrypi>
    References: <YWkvEkTaht2nDbHLz8naKa3VK6JarLs3hMGAabdu2162@mailpile>
    MIME-Version: 1.0
    Content-Type: text/plain; charset=us-ascii
    Content-Disposition: inline
    In-Reply-To: <YWkvEkTaht2nDbHLz8naKa3VK6JarLs3hMGAabdu2162@mailpile>
    User-Agent: Mutt/1.5.23 (2014-03-12)

    On Wed, Oct 19, 2016 at 07:07:25AM -0000, mathias wrote:
    > My testing mail. Please get it.
    >
    > //mathias

    > pub  2048D/7754E383 2016-10-19 mathiasi2p (mathias_i2p)<mathias@2npwlaijs6xcw6nkq5l3agjh7kmspnqj3w5b6kdscxpbdsfqhhta.b32.i2p>
    > sub  2048g/DA72D110 2016-10-19

    Really seems to work great. Sortof..
    //admin
    .
    quit
    +OK k bai
    Connection closed by foreign host.

So, sending via SMTP localhost 2525 (bdsmail) works great from Mailpile, but not fetching and indexing via POP3. POP3 works great via telnet though, so the functionality is there. However, bdsmail is under heavy development, so the problem might be there.

**Comment by BjarniRunar** [comment]
OK, thanks. I'm going to check the state of our POP3 code before I comment further! :)

**Comment by BjarniRunar** [comment]
I found and fixed some bugs in POP3, have updated #1667 as of a few minutes ago. None of the bugs I found/fixed would have caused the problems you're describing above, but it may still be worth checking.

**Comment by mathiasfriman** [comment]
The patch changed things at least, what previously listed as `(anonymous) (No subject)` now shows as

    1   (anonymous)     (processing message ...)                              now
    2   (anonymous)     (processing message ...)                           7 mins
    3   (anonymous)     (processing message ...)                           7 mins
    4   (anonymous)     (processing message ...)                           7 mins
    5   (anonymous)     (processing message ...)                           7 mins

`processing message ...` is a string that is located on line 700 in `mailpile/search.py`

**Comment by BjarniRunar** [comment]
Closing this due to inaction, there's no way for me to follow up on this.
