### ISSUE TITLE
start with ip instead of localhost?

### ISSUE THREAD

**Issue by prankousky** [mailpile/Mailpile#1650]
hi,

i am running mailpile on my headless raspberry pi. i would like keep it running 24/7 and automatically start upon reboot. however, i need to start ./mp, then enter www ip:port in order for mailpile to be reached within my network. otherwise only localhost can reach it.

is there a way to automate this so i can create an @reboot cron to always have mailpile running network-wide? thanks in advance :)

**Comment by DaLynX** [comment]
Hello,

I'm starting mailpile with ./mp and it directly listens on all interfaces. (0.0.0.0:33411)

Anyway if you want to specify an interface or port, I believe you can use the option _--www=_ and specify where exactly you want the web interface to listen.

**Comment by prankousky** [comment]
Thank you.

For some reason, this does not work. When I start sudo ./mp --www=192.168.111.40:33221 I get
OK: Moved the web server to http://192.168.111.40:33221/

However, I cannot access this url.

When I sudo ./mp, then type web 192.168.122.40:33221 , it works.

**Comment by BjarniRunar** [comment]
Strange. I haven't managed to reproduce this. However, why in the world are you running Mailpile with sudo?

It does not need and should not have root privileges to run. Quite the opposite, Mailpile should always run as a normal user.

**Comment by BjarniRunar** [comment]
... of course, now that you've run it as root, that's where the data lives, in root's home directory. Moving the data or starting over as a normal user will fix this, but I'm not sure which is easier for you.
