### ISSUE TITLE
Lock the send button until attachment is uploaded

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1656]
If I start uploading an attachment, and the file is uploading, I still can hit the send button and the message will be sent ; without the attachment (popping briefly an error).

Relates in some way #1646

**Comment by BjarniRunar** [comment]
I think this is a good idea. We want both this and #1646.

**Comment by waseem18** [comment]
Hi,

I'm new to Mailpile and would love to work on this issue.

Thank You.

**Comment by JocelynDelalande** [comment]
@waseem18 go ahead and pull request :-) Feel free to ask for more information if you need some, hanging arround on IRC channel may be a good way to communicate with other devs (and particularly @BjarniRunar ;-) )

**Comment by waseem18** [comment]
Thanks for the response @JocelynDelalande . Currently going through the code. Will keep updated :)

**Comment by broder** [comment]
This looks to have been fixed in #1676

**Comment by BjarniRunar** [comment]
This works! However, unfortuantely I don't think it's actually sufficient; I'll be filing some new issues about attachment UI.
