### ISSUE TITLE
Restarting Mailpile breaks it

### ISSUE THREAD

**Issue by arhue** [mailpile/Mailpile#1657]
Everytime I restart Mailpile it gives out "You have not configured any accounts yet" even when accounts are visible. I can view my mails but can't send any because it complains of "No usable profiles found, click to check your settings!"

**Comment by BjarniRunar** [comment]
I have not witnessed this. If you can provide more details (a lot more details) that would be helpful. Things like:

1. Which version of Mailpile
2. Which OS
3. Which versions of python, gpg, openssl
4. Sample output from Mailpile
5. What you were doing - have you completed the GUI setup? Have you logged in/out?

**Comment by arhue** [comment]
Sorry about not providing enough information.
1. Latest version from the master branch at the time of opening the issue. Fetched with "git clone --recursive https://github.com/mailpile/Mailpile.git" as mentioned in the wiki.
2. Ubuntu 16.04. Fully updated in a LXC container. Host OS is the same as well. Hosting it on a private IP with Nginx as reverse proxy and OpenVPN on host for connectivity from outside.
3. Python 2.7.12, OpenSSL 1.0.2g  1 Mar 2016, gpg (GnuPG) 1.4.20
4. Everytime I restart it it breaks. Tried it 3 times now. Both with running ./mp or via systemd process. Yes fully completed GUI setup and setup accounts. Even mailed and did some encryption/decryption of emails. Restart it or close it and start it again and it breaks.
This image should hopefully make things more clear: https://files.catbox.moe/ipl8b9.png

**Comment by arhue** [comment]
Did a reinstall after pulling the latest code. The issue persists.

**Comment by BjarniRunar** [comment]
Thanks for sharing. If this machine is on the public Internet (or you're willing to launch a pagekite SSH kite), is there any chance I could get SSH access to log on and take a look? I've had reports of this sort of thing a couple of times, but never been able to look for myself to figure out what was going on.

**Comment by arhue** [comment]
Thanks a lot @BjarniRunar it really means a lot when the developer is really personal and helps with bugs which very few people are hitting. I'm running Mailpile with an internal IP using source NAT+OpenVPN. I tried Pagekite but it simply refused to work with my setup. I can do two either one of these two things:
1. Generate OpenVPN config/keys for you to connect and access the internal IP.
2. Do destination NAT(port forwarding) for SSH access and for the WebUI.
Do let me know what you prefer. Option 1 should be easier and better. Please fire a mail through at me@varunpriolkar.com so we can take this forward.

**Comment by BjarniRunar** [comment]
Wow, a month went by. Sorry about not getting in touch. Still interested in debugging this?

**Comment by BjarniRunar** [comment]
I think the trail has gone cold here. Closing, sorry we didn't figure this out!
