### ISSUE TITLE
Mailpile does not work with local mailboxes by i2p-based bdsmail

### ISSUE THREAD

**Issue by mathiasfriman** [mailpile/Mailpile#1658]
Mailpile does not want to process mail from bdsmail mailbox. I've attached a mailbox with 2 mails that at least mutt is able to pick up.

[mailbox.tar.gz](https://github.com/mailpile/Mailpile/files/546482/mailbox.tar.gz)

**Comment by BjarniRunar** [comment]
No, that should be correct, the parent is the Maildir. I'll take a look, thanks for the sample.

**Comment by BjarniRunar** [comment]
OK, using my current (local) tree I was able to both browse the contents of that mailbox and import the messages, using the normal web UI.

So it's at least working for me - I'll hopefully be pushing my latest changes for review later this week, when I do I'll update this issue and you can try pulling the branch to see if it makes a difference.

**Comment by mathiasfriman** [comment]
Great, I'll wait for the changes and see then :)

**Comment by mathiasfriman** [comment]
I applied pull request 1667 ( via `git apply < 1667.patch` ) and that seem to solve this issue. :) Wonderful! I'll just wait for the PR to reach master before closing it.

**Comment by BjarniRunar** [comment]
Thanks for testing that! There are still a bunch of things that need fixing (POP3 is indeed broken as we've discussed elsewhere), but at least I've got some momentum now working on them.

**Comment by mathiasfriman** [comment]
I don't know if this is attributed to local mailboxes, but it seems that encrypting mails is not possible even if I send signed messages and attach the encryption key. It doesn't seem to pick up the key or the signature.

I know it worked in some iteration of my testing before the patch, but not now..

Attach a mail that is not being picked up as signed, and also with an attached encryption key:

[mail.txt](https://github.com/mailpile/Mailpile/files/567071/mail.txt)

**Comment by BjarniRunar** [comment]
Let's try and have one bug per issue if possible... :-)

**Comment by JocelynDelalande** [comment]
@BjarniRunar should be closed, seems fixed.

**Comment by BjarniRunar** [comment]
@JocelynDelalande Right you are, thanks!
