### ISSUE TITLE
Provide more useful feedback when an e-mail cannot be opened

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1662]
1.0.0rc 
the search shows mails in the result listing and can not open these 
"Hrm, We Could Not Find Anything"

I am also pretty sure that these mails do not contain the searched word.

**Comment by BjarniRunar** [comment]
I'm afraid this usually means something got corrupted in the background - possibly the app was shutdown/restarted uncleanly? It may also mean you configured a mail source to not keep local copies of the mail, and the remote server is temporarily unavailable.

There may well be bugs here, but I can't really think of any way for you to provide me with enough details to find them and do something about them.

There IS however one actionable item here - the "Hrm, We Could Not Find Anything" page is ugly and useless. We should improve that page to provide more details about what went wrong (if Mailpile can figure it out) or provide suggestions on how to send actionable bug reports.

I'm going to rename this issue to track the above improvement.

**Comment by JocelynDelalande** [comment]
Just to give a feedback, facing a lot of those, very frustrating. Clearly a 1.0 thing :-)

**Comment by BjarniRunar** [comment]
This issue might be fixed. Will close once I've gotten some feedback...
