### ISSUE TITLE
has bogus HTML.

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1663]
1.0.0rc
I had to re-index the mails I saw a lot of lines like
=268C/WZmsXSEDmfWCy1Lky1HrgL1Egog has bogus HTML.

I used this method to reindex
https://github.com/mailpile/Mailpile/wiki/Troubleshooting

**Comment by BjarniRunar** [comment]
This is not an error, it is just debug output which will be removed before we make a release for the general public. The bogus HTML is in the e-mail, Mailpile can't do much about that except try and make sense of it anyway or complain when it fails (as it is doing here).
