### ISSUE TITLE
Failed to reindex

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1664]
1.0.0.rc

to solve issue
https://github.com/mailpile/Mailpile/issues/1662
I used the process to reindex described here
https://github.com/mailpile/Mailpile/wiki/Troubleshooting

during reindex i get many errors like

Traceback (most recent call last):
  File "/home/mailpile/Mailpile/mailpile/plugins/core.py", line 111, in command
    idx.index_email(self.session, e)
  File "/home/mailpile/Mailpile/mailpile/search.py", line 1022, in index_email
    crypto_state_feedback=False)
  File "/home/mailpile/Mailpile/mailpile/mailutils.py", line 1048, in get_msg
    raise IndexError(_('Message not found?'))
IndexError: Message not found?

probably some mails have been deleted in the source mail boxes?

**Comment by BjarniRunar** [comment]
Your theory is quite plausible, especially if you're reading the same mail with another e-mail app as well. I don't think there is really a bug here, at least not one I can act upon. Thanks for reporting this though!

**Comment by ferdiga** [comment]
Hm, if the message can't be found, it can't be indexed either?
but, how can mailpile find a message which does not exist ?

**Comment by BjarniRunar** [comment]
The reindexing procedure you followed deletes some data, but not all - the metadata index still holds a record of messages which may not exist in your source mailboxes anymore.

**Comment by ferdiga** [comment]
so what happens if the mails are not retained on the server during the read option - will the re-index  issue an error for each message?
IMO it must only re-index local messages.

**Comment by BjarniRunar** [comment]
Please consider that you're complaining about debug output in a development version of unfinished software... that's not entirely reasonable of you. :-)

The software works just fine even if it complains a bit too much sometimes.

Regarding your idea that a manual reindexing process (which is only used by developers and testers) should arbitrarily only reindex some mail and not other mail ... that makes no sense to me. If people choose keep their mail remotely and then need a reindex for some reason, the remote mail is no less important than the local mail.

**Comment by ferdiga** [comment]
well , I make a distinction between re-index and re-download

**Comment by BjarniRunar** [comment]
That distinction is, in some cases, non existent. To be indexed, the message has to be read. To be read, it has to be downloaded (assuming local copies are not made). There's no way around that.

**Comment by ferdiga** [comment]
may be I miss the point,
if a message is already classified in the meta data, it was already read, no need to reread it again from the server (where it might have been deleted by another programm)

**Comment by BjarniRunar** [comment]
Reindexing means "read everything again to rebuild the search index". So by definition, that's what you were asking for. :-)  The metadata index is only metadata, not search keywords.
