### ISSUE TITLE
clear search field - icon / button missing

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1665]
1.0.0rc

currently it is not possible to clear the search field using the mouse (or the finger on a touch screen device)

suggestion: add a "clear" icon like in thunderbird
![image](https://cloud.githubusercontent.com/assets/6248560/19882406/cf0e8cbe-a00d-11e6-9c4e-9e2330a0af35.png)

**Comment by BjarniRunar** [comment]
Just to play devil's advocate: why does this matter? Even if you've cleared the search field you're going to need to use a keyboard to type in the search terms anyway...

To answer my own question: I guess many users don't know how to select-all and then delete with hot-keys?

**Comment by ferdiga** [comment]
well I thought working with a mouse device should be supported - it may have a reason why a lot of UI have this feature.

**Comment by shreab373** [comment]
@ferdiga hello! i'm a complete noob to open source contribution, do you think i should take this up? could you guide me? :)

**Comment by ferdiga** [comment]
sorry can't give advice - not my domain

**Comment by BjarniRunar** [comment]
@shreab373 Welcome!

I think this task has a few parts, some harder than others:

1) You'd want to find or create an appropriate icon. At the simplest, this would be a Unicode character that is available in the standard fonts, medium complexity would be to create a .png icon and add to the project's static resources (`shared-data/default-theme/img/`), most complex would be to draw a new icon and add to our icon font.

2) Update the HTML/CSS to display the icon. The Mailpile HTML/CSS code lives in `shared-data/default-theme/...`

3) Create a small amount of Javascript which clears the search box when the icon is clicked. The main app Javascript is in `shared-data/default-theme/html/jsapi/...`

Does this help? You may also want to join our IRC channel on Freenode (#mailpile) to have live chats with us there.
