### ISSUE TITLE
Gracefully handle Mail Delivery Reports and other errors

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1668]
Mailpile should do the following:

1. Parse any incoming mail delivery reports
2. If they apply to a sent message, somehow (in a user-friendly, clear way) make it clear to the user which message was not delivered and to which recipient, and if possible why
3. Suppress all other mail delivery reports, they're basically spam

No user should ever have to actually *read* a mail delivery report unless they actually want to. But informing users that their mail wasn't delivered is important.

**Comment by DaLynX** [comment]
Interesting idea!

Just one thing: do not just */dev/null* the unwanted reports, at least they should go to *Spam*, because someone operating their filtering at an earlier stage, like on the mail server, could want to know what spam got through to tweak their filters.

**Comment by BjarniRunar** [comment]
Agreed, auto-deleting e-mail is not something Mailpile should ever do. However, sending it straight to "archives" so it's not in your face would most of the time be a clear improvement.
