### ISSUE TITLE
Conversation Tree Start and End not aligned

### ISSUE THREAD

**Issue by lorenzschmid** [mailpile/Mailpile#1671]
The round corners forming the end or beginning of a branch in the conversation tree are not aligned with the straight branch sections
![screen shot 2016-11-07 at 19 12 00](https://cloud.githubusercontent.com/assets/3830671/20069785/49c038b2-a51e-11e6-9686-4d976d922210.png)

**Comment by BjarniRunar** [comment]
Yes. This depends on the font, for some reason some fonts seem to have buggy line-drawing characters (there's no point to shipping line drawing characters if they don't line up, thus my assertion that it's a bug in the font).

We need to somehow identify which fonts are safe to use cross-platform and update our CSS to use only those.

**Comment by lorenzschmid** [comment]
I just looked at web safe fonts and tried a couple of them in Safari and Google Chrome on my Mac. It seems like `Tahoma` would do the trick. Can I just add it to [shared-data/default-theme/less/app/pile.less#L278](https://github.com/mailpile/Mailpile/blob/master/shared-data/default-theme/less/app/pile.less#L278) or do you separate font-families into other stylesheets?

**Comment by BjarniRunar** [comment]
I'm not actually sure, I'm still learning the ropes of the less/CSS side of things myself. I recommend grepping the .less files for things to do with fonts and see if you find a place that fits.
