### ISSUE TITLE
Issues with Inbox Tag (not visible, doesn't sync with Thunderbird)

### ISSUE THREAD

**Issue by lorenzschmid** [mailpile/Mailpile#1672]
I access my emails over different clients but managed that all use the same folders for Inbox, sent messages, trash etc. The problem with Mailpile is that despite having an "inbox" tag which receives all new incoming messages its content never gets updated if I read or delete one of these messages with an external program such as Thunderbird (remains unread or despite being deleted is still in the Mailpile inbox).

I am not entirely sure if it is not just a naming issue (i.e. I might have two different inboxes). So I started to play around with the name of my Mailpile inbox with the result that I cannot see it anymore in the "top of sidebar" but only in the sidebar. If I select the "top of sidebar" option, it disappears completely form the sidebar and is only accessible via search. I tried to log what happens when I change the sidebar option but there is no error shown:
`5820c691-0003a-36c2=ConfigSet:c set: Updated your settings`

**Comment by BjarniRunar** [comment]
Mailpile doesn't yet sync. It just copies. So the behaviour you're seeing is expected, given the current state of things.

The tag disappearing sounds more interesting, I'll see if I can reproduce the issue at my end.

**Comment by lorenzschmid** [comment]
That explains a lot 😄

Let me know if I can be of any help about the disappearing tags. Could also try to reproduce it again if necessary.

**Comment by mrbiber** [comment]
To follow a bug for the syncing part, see #1017 (there's also a bounty attached to that bug)
