### ISSUE TITLE
Autoconfig is broken

### ISSUE THREAD

**Issue by thierryOrdissimo** [mailpile/Mailpile#1686]
### 1) Here is the network activity during the autoconfiguration of test@substantiel.fr
Recent Activity
Here you can see a log of recent network activity, both successful and failed attempts.
You are not using Tor. This may leak your IP address and allow monitoring of which servers you communicate with.
Edit your Privacy Policy.
09:24 Connected to mail.online.net:993 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:24 Connected to mail.online.net:993 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:24 Connected to imap.online.net:993 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to mail.online.net:587 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to mail.online.net:587 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to mail.online.net:587 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to smtp.online.net:587 over the Internet with TLSv1/SSLv3 (256 bit DHE-RSA-AES256-SHA256).
09:24 Connected to mail.online.net:465 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to mail.online.net:465 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:24 Connected to smtp.online.net:465 over the Internet with TLSv1/SSLv3 (256 bit DHE-RSA-AES256-SHA256).
09:24 Connected to mail.online.net:587 over the Internet with no encryption.
09:24 Connected to smtp.online.net:587 over the Internet with no encryption.
09:24 Failed to connect to mail.substantiel.fr:587: [Errno 111] Connection refused
09:24 Failed to connect to smtp.substantiel.fr:587: [Errno 111] Connection refused
09:24 Failed to connect to online.net:465: [Errno 101] Network is unreachable
09:24 Connected to mail.online.net:465 over the Internet with no encryption.
09:24 Connected to smtp.online.net:465 over the Internet with no encryption.
09:24 Failed to connect to mail.substantiel.fr:465: [Errno 111] Connection refused
09:24 Failed to connect to smtp.substantiel.fr:465: [Errno 111] Connection refused
09:24 Connected to mail.online.net:995 over the Internet with no encryption.
09:24 Connected to pop.online.net:995 over the Internet with no encryption.
09:24 Failed to connect to mail.substantiel.fr:995: [Errno 111] Connection refused
09:24 Failed to connect to pop.substantiel.fr:995: [Errno 111] Connection refused
09:24 Failed to connect to online.net:993: [Errno 101] Network is unreachable
09:24 Connected to mail.online.net:993 over the Internet with no encryption.
09:24 Connected to imap.online.net:993 over the Internet with no encryption.
09:24 Failed to connect to mail.substantiel.fr:993: [Errno 111] Connection refused
09:24 Failed to connect to imap.substantiel.fr:993: [Errno 111] Connection refused
09:24 Failed to connect to mx.online.net:80: [Errno 111] Connection refused
09:24 Failed to connect to autoconfig.mx.online.net:80: [Errno -2] Name or service not known
09:24 Failed to connect to mx.online.net:80: [Errno 111] Connection refused
09:24 Connected to substantiel.fr:80 over the Internet with no encryption.
09:24 Failed to connect to autoconfig.mx.online.net:80: [Errno -2] Name or service not known
09:24 Connected to autoconfig.substantiel.fr:80 over the Internet with no encryption.
09:24 Failed to connect to mx.online.net:443: [Errno 111] Connection refused
09:24 Failed to connect to autoconfig.mx.online.net:443: [Errno -2] Name or service not known
09:24 Connected to autoconfig.thunderbird.net:443 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:24 Connected to autoconfig.thunderbird.net:443 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:24 Failed to connect to substantiel.fr:443: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:590)
09:24 Failed to connect to autoconfig.substantiel.fr:443: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:590)

### 2) Here is the network activity during the autoconfiguration of sordissimo@gmail.com
Recent Activity
Here you can see a log of recent network activity, both successful and failed attempts.
You are not using Tor. This may leak your IP address and allow monitoring of which servers you communicate with.
Edit your Privacy Policy.

09:18 Connected to imap.gmail.com:993 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:18 Connected to smtp.gmail.com:465 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:18 Connected to autoconfig.thunderbird.net:443 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:18 Connected to gmail.com:443 over the Internet with TLSv1/SSLv3 (128 bit ECDHE-RSA-AES128-GCM-SHA256).
09:18 Failed to connect to autoconfig.gmail.com:443: [Errno -2] Name or service not known
09:18 Connected to imap.online.net:993 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).
09:17 Connected to imap.online.net:993 over the Internet with TLSv1/SSLv3 (256 bit ECDHE-RSA-AES256-GCM-SHA384).

### My temporary resolution in mailpile/mail_source/pop3.py 
        ussl=False
        if port == 110:
          ussl=False
        elif port == 995:
          ussl=True
        else:
          ussl=('pop3_ssl' in protocol)
        return pop3.MailpileMailbox(host,
                                    port=port,
                                    user=username,
                                    password=password,
                                    use_ssl=ussl, #('ssl' in protocol),
                                    debug=debug)

**Comment by BjarniRunar** [comment]
So, to be 100% clear - autoconfig succeeds and your mail gets downloaded if you make that change?

**Comment by thierryOrdissimo** [comment]
yes

**Comment by BjarniRunar** [comment]
Thanks for reporting this and providing such good details. I have reproduced the problem at my end and will push up a fix soon.
