### ISSUE TITLE
Make sure Mailpile stops safely when out of disk space

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1696]
If Mailpile runs out of disk space, it should notify the user and prevent any further actions (tagging, mail downloading, etc.) until more space is available. This applies both to the back-end processes and the user interface.

This is critical so users don't experience data loss when they run out of disk space.

**Comment by BjarniRunar** [comment]
Note: I'm working on this...

**Comment by JocelynDelalande** [comment]
I have been recently out of space (disk wal filled by another app, while mp was running). 

As a result, MP continued to run but lost a part of the stored messages (lot of «« Message canot be found » errors while opening emails ). I got no warning in the interface.

So I am wondering how the warn & stop feature is supposed to work ? Is the health check occuring only on startup ?

**Comment by BjarniRunar** [comment]
@JocelynDelalande, can you give more details? OS? Is it possible that Mailpile is checking free space on the wrong volume/partition in your case?

**Comment by JocelynDelalande** [comment]
> @JocelynDelalande, can you give more details? OS? 

Debian stretch. Ext4 partition.

> Is it possible that Mailpile is checking free space on the wrong volume/partition in your case?

Only one partion. So it is unlinkely. I also thought about the reserved space for root. But the space checking (available space vs free space) seems done properly, taking this into account.

What I did not got is when the space check is done exactly on startup or periodicaly ?

**Comment by BjarniRunar** [comment]
It's checked in a few places, before (and during) operations which are likely to consume a lot of disk space. Maybe I missed a spot? How is your mail downloaded?

**Comment by JocelynDelalande** [comment]
via imap

**Comment by JocelynDelalande** [comment]
@BjarniRunar side note : I'm getting recurrent issues with « message not found », that time it seemed correlated with a full disk. But not every time. So maybe I am not be the ideal person to troubleshoot with (my « minimal failing case » is not very minimal nor reproducible :-/).

One sure thing is my disk was full and Mailpile interface said nothing to me and did not stop (but seemed to miss some data write at some point).

**Comment by BjarniRunar** [comment]
I've been testing this, and as far as I can tell, it works. So I'm going to close this issue; the feature exists and works - if it's buggy in some environments or on some platforms, I think we should file specific issues for tracking those down.
