### ISSUE TITLE
Assigning signatures to emails by being "Context Aware"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#170]
Current functionality of written signatures (name, email, phone, etc...) in most email clients has the following sort of options to appending:

* 1 Global signature
* X Differing global signatures 
* X Differing signatures for each name@email.com sending account

The goal of this feature is to minimize the amount of selecting a signature for an email. 
Issue #88 brings up the idea of a "Context Aware" feature. A context is anything like "Work, Friends, Family, Strangers" whereby different behaviors happen for a given context- this is a big enough topic that it needs to be handled / discussed on its own. 

How this type of feature applies to email signatures is cases like this, where using only 1 email address, e.g. brennan@myemail.com the following happens:

* When sending emails to "Family" context never append a signature
* When sending emails to "Work" context append signature "Normal Work" 
* When sending emails to "Strangers" context signature "Work Inquiries"

I imagine this "Context Aware" feature  will be useful in other aspects of Mailpile, but not now this is one concrete use case!

**Comment by BjarniRunar** [comment]
This exists; you can have multiple accounts and each account can have its own signature. There are bugs in the UI, but those should be tracked separately.
