### ISSUE TITLE
Clean up inline Styles

### ISSUE THREAD

**Issue by Epse** [mailpile/Mailpile#1708]
There are a lot of what could be considered "UI hacks" in the HTML. Lots of `style=`, a bunch of `width="100%"` and some other things. This should really be cleaned up and moved into the CSS/LESS. 
This would also improve code reuse. 
In general, we'd need someone with a solid front-end background to refactor that stuff. It would take quite a bit of work, but it isn't that difficult.

**Comment by BjarniRunar** [comment]
This isn't a bug. This is a matter of taste. :-)

That said, I welcome pull requests that improve the situation!
