### ISSUE TITLE
Use a proper key derivation function to protect the master key

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1711]
According to feedback from Kai of the GnuPG project (see discussion on #1684), the way we currently protect the internal mailpile master key is insecure.

Instead of sending the user's Mailpile password directly to GnuPG, we need to run it through a strong key derivation function first.

**Comment by flanfly** [comment]
For the record: The key derivation in GnuPG isn't broken, we just have better means deriving keys from password now then 2007 when the OpenPGP standard was written.

**Comment by BjarniRunar** [comment]
Progress: I've got working code in my local tree that uses PDKDF2 or Scrypt (preferred), depending on the capabilities of the local crypto libraries.
