### ISSUE TITLE
Recognize and handle multipart/related

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1712]
Currently, Mailpile ignores the multipart/related container.

This is a mistake; the multipart/related container is used to group together different parts, most commonly used to link HTML mail with in-line images. This is immediately useful in two ways:

1. This signal will allow us to better decide which message parts to display as attachments, and which parts to hide in the UI. It would probably be nice to still be able to expand to "all attachments" or even "all parts", but by default things within a multipart/related container should be hidden from view.

2. Since most HTML mail is marketing, this gives us a pretty clear signal for differentiating between "interesting" attachments and boring ones (another such signal might be file size). Paying attention to this signal would allow us to make Mailpile's attachment- and photo searches much more relevant, since they wouldn't give results for HTML boilerplate images anymore.

**Comment by AndreHeinecke** [comment]
> Since most HTML mail is marketing ...

I disagree with that point. Working on GpgOL / Outlook the default is to send multipart/alternative html mails and there is a prominent option to add images to mails. I often receive mails from customers in various projects (unrelated to crypto) where they send screenshots of error states in software as embedded images in mails.

My point is that in my opinion, for Outlook users it's common to embed images.

**Comment by BjarniRunar** [comment]
Thanks for clarifying (and bringing this to my attention in the first place). More logic will be needed - which is sort of what I meant by pointing out that another signal might be size, but I should probably have been more clear.

**Comment by Arnaudv6** [comment]
Same here: I'm a claws-mail user, wanted to view my html mails without resorting to CM html plugins.
Tried mailpipe but it fails there yet.
