### ISSUE TITLE
Permanently delete mail button

### ISSUE THREAD

**Issue by aaronthj16** [mailpile/Mailpile#1715]
There doesn't seem to be an obvious way of permanently deleting mail in the GUI, I think it might help to have a button that can delete mail (maybe in trash) rather than untagging it. It also might be useful to add a feature that deletes mail in trash after an amount of time (this can be set by the user) similar to what gmail does when there is mail in the trash after 30 days.

**Comment by BjarniRunar** [comment]
This isn't just "a button". This is an entire subsystem, which is being tracked here: #129 

The ability to take actions after a certain time has been implemented, actual deletion is partially implemented. Once the basics work, we can consider adding a button as well, but right now the infrastructure isn't in place and this issue isn't really one people can act upon.

Closing for that reason - it's not good to have an issue tracker full of issues people can't actually work on.
