### ISSUE TITLE
Give better feedback when unable to encrypt a message

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1719]
Mailpile currently doesn't do anything helpful when it fails to encrypt a message. Reasons it may fail to encrypt include:

1. The recipient key is about to expire or is expired
2. The user has chosen sign+encrypt, but hasn't yet unlocked their key for signing

There may be others; we need to parse the error messages from GnuPG and give the user better feedback.

**Comment by BjarniRunar** [comment]
Relates to #912

**Comment by mathiasfriman** [comment]
Just some feedback regarding issue **2**: 

I have a passphrase protected key, and the default behaviour when _only_ signing (not encrypting) a message and not yet having unlocked the key is to show this popup below. That, IMHO, should be the default behaviour also when encrypting+signing.  But perhaps that is what you mean by "give the user better feedback", I hope so. :)

![unlock_encryption_key_mailpile-red](https://cloud.githubusercontent.com/assets/3397596/20978750/5938860c-bcaa-11e6-8357-5bfe1d47f6d0.png)

Just my 2 cents.

**Comment by BjarniRunar** [comment]
@mathiasfriman That would fix some of the common cases, but wouldn't help the user if encrypting is impossible because the key they want to encrypt to is expired. Quite the opposite, it'd not only be confusing and unhelpful, it'd be wasting the user's time.

So yes, if popping up that dialog is the right thing to do, then we should pop the dialog! The problem is, sometimes it's not. :-)

**Comment by JocelynDelalande** [comment]
relates #1727

**Comment by BjarniRunar** [comment]
Case 2. is resolved, case 1 (unusable recipient key) remains... I think!
