### ISSUE TITLE
TOFU: Automatically import keys

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1725]
To complete our TOFU flow (as per the 1.0 security roadmap), we need to automatically import recipient PGP keys. We don't want to just blindly import all keys, as that opens up the keychain for nasty spam-based DoS. So...

1. The "trigger" for automatically importing a key, is sending e-mail to someone
2. We should only import a key if we've seen it used in a reasonable number of signatures

This implies that when we begin composing an e-mail to someone, a background process does the following:

1. Check if we have seen N signed messages from them
2. Extract the key ID (fingerprint) from the signed messages
3. Search for a key matching that ID

The search is an interesting point; we should prefer keys that have been mailed to us, but if they're not available then hitting the keyservers should be safe since we have pretty precise criteria for which key to download. This will leak information about the fact that we're e-mailing that person to people listening in on the network and/or keyserver operators though - unless the request is routed over Tor.

**Comment by BjarniRunar** [comment]
Relates to #733.

**Comment by BjarniRunar** [comment]
First draft of this is pushed! Closing, new issues will be filed as bugs are found...

**Comment by JackDca** [comment]
Hello Bjarni,

What is "N" in the above scheme?

I've set up two new Mailpile instances, using two new gmail accounts, one for Alice and one for Bob.

Alice sent Bob a signed email attaching her public key. Bob replied with a signed email attaching his public key. They've gone back and forth three times (each has received three signed emails with keys attached from the other) and still the message "No encryption keys found"is coming up.

Is there a way to make this work?

Thanks.
