### ISSUE TITLE
"Could not encrypt" error instead of passphrase prompt.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1727]
## Expected behaviour

1. Start mailpile
2. Log-in
3. Write a message (encrypt icon checked)
4.  send it
5. MP prompts for passphrase to unlock key
6. Mail take off !

## Current behaviour

1. Start mailpile
2. Log-in
3. Write a message (encrypt icon checked)
4.  send it
5. « Could not encrypt » error (no passphrase prompt)

## Workaround

First send a signed-only message (the passphrase is prompted as expected, and once the key is unlocked, it works well for encrypting further messages).

**Comment by TheCapsLock** [comment]
confirmed

**Comment by BjarniRunar** [comment]
Should be fixed now.

**Comment by JocelynDelalande** [comment]
@BjarniRunar I confirm, thanks :-)
