### ISSUE TITLE
Setup fails when Mailpile detects insufficient disk space

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1730]
The setup process fails to create the default tags and such things if Mailpile detects that it doesn't have enough disk space to download mail. This makes the app launch in a weird wonky state that it won't recover from automatically, even if the user frees up disk space.

Proposed fix: The setup process (which lives in `mailpile/plugins/setup_magic.py`) should temporarily set `sys.minfree_mb` to a very low value, and reset it back to the default when it finishes.

Workaround: If you're bitten by this, the following steps on the Mailpile CLI will fix it;

    mailpile> set sys.minfree_mb = 10
    ...
    mailpile> setup
    ...
    mailpile> unset sys.minfree_mb

(or if you're sure you want to run Mailpile with less than 1GB of free space for mail and indexes, set `sys.minfree_mb` to whatever value you are comfortable with instead of unsetting it.)

**Comment by MikeinRealLife** [comment]
I will attempt to do this.

**Comment by BjarniRunar** [comment]
I've verified this is fixed. Thanks @smari !
