### ISSUE TITLE
Files are not being attached

### ISSUE THREAD

**Issue by maysara** [mailpile/Mailpile#1732]
Greetings,

I've did git pull today (last commit 0fd9f7dc90525223200d85c8d9ec0c33a8b0cb34); I'm unable to attach files, I've tried to attach files to encrypted emails, signed emails or neither; in all cases when email is sent the attachment is not included.

**Comment by BjarniRunar** [comment]
Thanks for reporting this. I am working on it, PR expected after a few more tests. :)

**Comment by JocelynDelalande** [comment]
I can confirm this bug is still around as of db939d820a7df09158d4c9d40d4a7d0fe970f174

**Comment by BjarniRunar** [comment]
That's expected, the fixing PR hasn't been merged. :-)
