### ISSUE TITLE
New password won't work on initial setup with master

### ISSUE THREAD

**Issue by kode54** [mailpile/Mailpile#1740]
As of current master, I had to wipe my setup completely, as it was crashing repeatedly on the data that was initially imported and created with 0.5.2. Now no matter what I set as the password during the initial setup wizard, it won't accept that password to log in.

It also reports errors in the console when setting the initial password:

```
[Error] Failed to load resource: the server responded with a status of 403 (OK) (as.js, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (OK) (app.js, line 0)
[Error] Did not parse stylesheet at 'http://10.0.0.69:33411/jsapi/as.css?ts=1.0.0rc0-1482557310' because non CSS MIME types are not allowed in strict mode.
[Error] ReferenceError: Can't find variable: Mailpile
	(anonymous function) (password:33)
	k (libraries.min.js:2:3538)
	fireWith (libraries.min.js:2:4346)
	ready (libraries.min.js:2:6152)
	g (libraries.min.js:1:968)
```

**Comment by cbz20** [comment]
can confirm, this must have happened in the latest batch of commits (after Dec 10, 2016, was working fine before then).

**Comment by kode54** [comment]
Narrowed this down to PR#1722.

**Comment by kode54** [comment]
Traced it to not having the Python cryptography package installed when creating the password. So it looks like the old system fallback no longer works with #1722 applied.

Adding py-cryptography to my mailpile Docker container, along with py-pbr and py-pillow.

**Comment by BjarniRunar** [comment]
I am looking into this. It should have falled back, but cryptography is a requirement now. Thanks for reporting this and digging into it.

**Comment by BjarniRunar** [comment]
A few people have reported this. I've traced things to the following:

   * It looks like Debian might be shipping a broken Python Cryptography library? :-(
   * Cryptography will fail in a way that breaks Mailpile's new password stretch / key save code
   * Mailpile's fallback logic is broken

Incoming PR to deal with both problems. The workaround in the meantime is:

    pip install 'setuptools>=11.3'
    pip install 'cryptography>=1.3.4'

The latter is only needed if you don't already have cryptography installed; the former fixes cryptography's requirements so it actually works (the Debian issue).
