### ISSUE TITLE
Use GPGME - or not?

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1742]
This is a discussion bug, to capture the pros- and cons of dropping our GPG wrapper in favour of something based on GPGME, most likely the GnuPG team's official SWIG bindings.

Relates to #733.

**Comment by BjarniRunar** [comment]
I am not currently in favour of moving to GPGME, for the following reasons:

1. I would like to keep Mailpile's external dependencies to a minimum, and make sure that the dependencies we do have are either widely available on Mac OS X, Linux distributions and Windows, and/or from the Python Package Index. If a simple `apt-get install` and/or `pip install` isn't enough to get up and running, then I'm not comfortable with adding the dependency. The official bindings for GPGME have not reached this point *yet*; pip install doesn't work and you cannot apt-get install unless you pull in the Debian testing repository.

2. I don't like GPGME from a design/security point of view. It is a large amount of C code which is doing pretty much the same thing as our Python wrapper, only in a more complex way. Given the choice between logic in a memory-safe language (Python) and equivalent logic written in C, I prefer the Python code.

3. We will still have to wrap the GPGME bindings with our own code to translate to our own internal data structures, Kai's initial port (#1621) was not noticeably smaller than our original wrapper.

**Comment by BjarniRunar** [comment]
Devil's advocate; the benefits of switching to GPGME:

1. GPGME is the preferred interface as recommended by the GnuPG team. They know what they're doing.

2. GPGME may make it easier for us to support S/MIME at some point in the future.

3. GPGME is documented and used by other projects. This may lower the barrier to entry for some new contributors to Mailpile, in particular for the GnuPG team itself.

**Comment by loidor** [comment]
Just need to put this somewhere - Debian Stretch will ship with gpg 2.1.

**Comment by BjarniRunar** [comment]
@loidor yep, we are aware and this is being tracked in #1133. I've started work on 2.1 support in my local tree.
