### ISSUE TITLE
HTML Viewer messes up image URIs

### ISSUE THREAD

**Issue by JoEiner** [mailpile/Mailpile#1744]
The HTML viewer changes image URIs so that image resources are fetched through the http_proxy command. In that process, the HTML viewer messes up the all but trivial URIs.

An example from my inbox:
https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-misc.s3.amazonaws.com/emails/coursera_logo.png?w=150&amp;h=22&amp;fit=scale

Is transformed into:
http://localhost:33411/api/0/http_proxy/?csrf=XXXX&url=https%3A//d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https%3A//coursera-misc.s3.amazonaws.com/emails/coursera_logo.png%3Fw%3D150%26h%3D22%26fit%3Dscale

When arriving in the HTTP proxy, this turns into
https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https%3A//coursera-misc.s3.amazonaws.com/emails/coursera_logo.png%3Fw%3D150%26h%3D22%26fit%3Dscale
which is a different URI than what we started with.

**Back to the example URI and how the HTML viewer transforms it:**
I didn't look at the javascript sources and I did not manage to figure out what the encoding/transformation of URIs actually does. It for some reasons removes the &amp; and replaces it by %26 which is just & url-encoded... Wouldn't it be meaningful to just url-encode the whole url string, turning it into  `https%3A%2F%2Fd3njjcbhbojbot.cloudfront.net%2Fapi%2Futilities%2Fv1%2Fimageproxy%2Fhttps%3A%2F%2Fcoursera-misc.s3.amazonaws.com%2Femails%2Fcoursera_logo.png%3Fw%3D150%26amp%3Bh%3D22%26amp%3Bfit%3Dscale`?

Another, not entirely url-encoded version would be 
`https%3A//d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https%3A//coursera-misc.s3.amazonaws.com/emails/coursera_logo.png%3Fw%3D150%26amp%3Bh%3D22%26amp%3Bfit%3Dscale`

Both these encodings provide a correct url variable in line 140 of html_magic.py when used in the following way: http://localhost:33411/api/0/http_proxy/?csrf=XXXX&url=ENCODEDURI

I suggest that the HTML viewer should simply use javascript's encodeURIComponent when it modifies the URIs of images.

**Comment by BjarniRunar** [comment]
Thank you for reporting this; I'm sure you're right and we have some bugs there!
