### ISSUE TITLE
Can't tag mails in GUI

### ISSUE THREAD

**Issue by loidor** [mailpile/Mailpile#1751]
Whenever I try to tag a mail, I get the tag chooser window, but it's filled with the html that I'm supposed to use to select tag. See image. I couldn't see an open issue, but I guess this is well known.

![mailtag](https://cloud.githubusercontent.com/assets/9845638/21577961/6df76c80-cf6e-11e6-86cc-d9fa15e7f58f.png)

**Comment by BjarniRunar** [comment]
This is a duplicate of #879 :-)  Thanks for filing!

In the meantime, you can tag by dragging/dropping messages to tags (that is a "move" which removes the tags you are looking at and assigns the tags you dropped on) or dragging tags to messages (just assigns the tag).
