### ISSUE TITLE
Attachments don't get stored or sent to recipients

### ISSUE THREAD

**Issue by matthewbloch** [mailpile/Mailpile#1753]
I've got an up-to-date Mailpile install, and attachments get silently removed when the message is stored. i.e. it's as simple as

1. Compose new email
2. Upload a new attachments (gets shown in preview)
3. Save message to Drafts
4. Click on Drafts folder
5. Message body appears, attachment is gone.

I noticed this after a couple of people said they didn't receive attachments I swore I'd sent! I retried with and without encryption FWIW.

**Comment by BjarniRunar** [comment]
This is a known issue, which should be fixed when #1737 gets merged. See also #1732. Thanks for a clear, good bug report though! :-)
