### ISSUE TITLE
Epiphany browser does not load

### ISSUE THREAD

**Issue by marxistvegan** [mailpile/Mailpile#1757]
Hey folks,

Trying the latest version out and I use at the moment Web (aka epiphany) on Debian test/stretch. When I run ./mp it tries to open the page but fails to succeed. I can use the address and successfully open it in Chromium. 

I am not quite sure how to debug this as Inspector does not give any output and the browser just says it is 'loading'

Thoughts?

**Comment by loidor** [comment]
What happens if you run ./mp and try to manually write http://localhost:33411 in the address bar of Epiphany? Same error?

**Comment by marxistvegan** [comment]
@loidor yep...trying to figure out how i can get some output on why it wont load.

**Comment by BjarniRunar** [comment]
We just use the Python webbrowser module. If the python webbrowser module doesn't work on Debian test/stretch, that's probably a bugreport someone within the Debian ecosystem would be interested in. I don't think this qualifies as a Mailpile bug....

**Comment by marxistvegan** [comment]
@BjarniRunar before i close this, can anyone that is reads this test it out to make sure it is not just me running into this, if it is more than just me I will file a bug report with debian.

**Comment by BjarniRunar** [comment]
One thing to check is the environment you're running Mailpile in. If you're running it from within a terminal in your GUI session, and it doesn't work, you can try this to see if it's a problem with python:

    $ python
    Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import webbrowser
    >>> webbrowser.open('https://www.mailpile.is/')
    True
    >>> 

If that works and launches a browser window/tap, then Mailpile should work in the same environment (run from the same shell). However, if the above doesn't work either the webbrowser module isn't working right OR your environment is broken. I'd check the environment for a DISPLAY variable?

    $ echo $DISPLAY
    :0
    $ 

That's what I see. If you don't see `:0` or `:1` or something, then the webbrowser module will probably fail.

A trivial wail to get things to fail, is to e.g. `ssh localhost` and then try to run Mailpile. The SSH session won't have a DISPLAY variable that works unless you have X11 forwarding over SSH enabled. Or you could alt-f1 and launch Mailpile on the text console - again, that won't launch the browser. There are many ways to contrive an environment where Mailpile/Python can't launch a browser, whether your case is a bug or not will requires a fair bit of digging to ascertain.

**Comment by marxistvegan** [comment]
I will try to test what i can.
`$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> webbrowser.open('https://www.mailpile.is/')
True
>>> `

This resulted is expected it opened the browser, which is what happens with the ./mp command it just never loads. I am going to try to gather more information from the browser on what is happening or failing to happen.

**Comment by BjarniRunar** [comment]
Ah - opens the browser but never loads is a very different problem, I had misunderstood! Interesting.

**Comment by kwill** [comment]
I have similar "endless loading" issues trying to access http://localhost:33411 with GNOME Web / Epiphany. The browser says "Loading localhost" in the corner, but no actual page is loaded or rendered. (This is after using another browser to actually set up Mailpile, bypassing #1909 )

A direct attempt to load http://localhost:33411/auth/login/ worked once - I entered my Mailpile password and again encountered endless loading. Attempts at the same URL after that failed. I found that http://localhost:33411/setup/password/ could load.

By contrast, other Firefox-based browsers work as expected, and `wget http://localhost:33411` succeeds.

**Comment by kwill** [comment]
Interesting event. If I launch Mailpile in a Firefox-based browser and login, and then visit http://localhost:33411/in/inbox/ in GNOME Web, my inbox loads and I can use Mailpile (receive and send email). If I then visit http://localhost:33411 in GNOME Web I get "endless loading".
