### ISSUE TITLE
Weird imap errors

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1770]
We tried to dig into #1762 with @BjarniRunar (thanks a lot !).

One bug leads to another, so, the error on startup seemed harmless, but there are strange imap errors which happen then, they might be the actual issue preventing from fetching new emails.

First, I was getting an error because python *imaplib* was considering the imap response body too big :

```
Traceback (most recent call last):
  File "/home/jocelyn/Mailpile/mailpile/mail_source/__init__.py", line 961, in run
    self.sync_mail()
  File "/home/jocelyn/Mailpile/mailpile/mail_source/__init__.py", line 284, in sync_mail
    elif (self._has_mailbox_changed(mbx_cfg, state) or
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 832, in _has_mailbox_changed
    uv = state['uv'] = src.mailbox_info('UIDVALIDITY', ['0'])[0]
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 373, in mailbox_info
    imap.select(self.path)
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 208, in select
    rv = self._conn.select(mailbox='"%s"' % mailbox, readonly=readonly)
  File "/usr/lib/python2.7/imaplib.py", line 661, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 1087, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 913, in _command_complete
    raise self.error('command: %s => %s' % (name, val))
error: command: EXAMINE => got more than 10000 bytes
```

So, as this issue [got fixed](https://github.com/python/cpython/commit/97c874d2) in recent python versions, I monkey-patched to reproducte the patched value from recent python versions, adding in mail_source/imap.py the following :

```
# Monkeypatching to same value as recent CPython versions
# See https://github.com/python/cpython/commit/97c874d2
import imaplib; imaplib._MAXLINE = 1000000
```
The previous crash disapears, but another appears instead :

```
"traceback": "Traceback (most recent call last):
  File "/home/jocelyn/Mailpile/mailpile/mail_source/__init__.py", line 961, in run
    self.sync_mail()
  File "/home/jocelyn/Mailpile/mailpile/mail_source/__init__.py", line 284, in sync_mail
    elif (self._has_mailbox_changed(mbx_cfg, state) or
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 833, in _has_mailbox_changed
    uv = state['uv'] = src.mailbox_info('UIDVALIDITY', ['0'])[0]
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 374, in mailbox_info
    imap.select(self.path)
  File "/home/jocelyn/Mailpile/mailpile/mail_source/imap.py", line 209, in select
    rv = self._conn.select(mailbox='"%s"' % mailbox, readonly=readonly)
  File "/usr/lib/python2.7/imaplib.py", line 661, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib/python2.7/imaplib.py", line 1087, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 911, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
abort: command: EXAMINE => unexpected response: '35210 35210 [... snip, realy huge list of IDs] 47435'
```
I'm a bit stuck in my debugging from here, my MP is still in a state where it works but cannot fetch new emails from imap server.

Any ideas ? :-)

**Comment by BjarniRunar** [comment]
Great work! As a workaround, I suggest you raise _MAXLINE even further.

Rationale:

EXAMINE shouldn't get back a list of IDs - I am pretty sure that list of IDs is the leftovers of a previous command which failed.

As written (based in my local copy), imaplib will put itself into a broken state if any line is longer than _MAXLINE - it will read up to _MAXLINE bytes, throw an error, but leave the rest of the line still in the OS buffers for next call to readline() to find, so the next command will usually fail or in some pathological edge cases, return corrupt and invalid data.

One potential workaround in Mailpile would be to try and catch these errors specifically, reset the connection to work around imaplib's broken internal state, and incrementally monkey-patch the _MAXLINE value higher and higher. Oh joy! :-)

**Comment by BjarniRunar** [comment]
For the record, there is a Mailpile bug here too. The documentation for imaplib says we should reset the connection when imaplib raises "abort", and we're not doing so.

**Comment by BjarniRunar** [comment]
To sum up:

1. imaplib's _MAXLINE default limit is too low in some versions of Python... or all?
2. Mailpile doesn't correctly reset the connection when it gets fatal errors from imaplib
3. It looks like imaplib raises imaplib.error() on overlong lines, which isn't supposed to be fatal for the connection - but it still leaves imaplib in a broken internal state, so it actually is.

Point 3 argues for overriding imaplib's default readline method, because it's buggy. The question remains whether to implement explicit line-length limits at all or rely on the IMAP logic's timeouts to protect us against OOM states.

Will sleep on it and then propose a PR.

**Comment by JocelynDelalande** [comment]
I can confirm this bug as closed, works like a charm, thanks :-)
