### ISSUE TITLE
Mailpile Command Is Not Found

### ISSUE THREAD

**Issue by Starz0r** [mailpile/Mailpile#1772]
I installed all the dependencies and followed the guide that is listed on the Github wiki, but there seems to be this issue where running the final command does not work for some reason. I tried chmod, chown, and logging in as a root shell, but nothing seems to be able to find this command or is able to run "./mp". I searched around and it seems no one else seems to have this issue so I decided to open one to hopefully get this resolved.

Operating System: Ubuntu 16.04.1
Mailpile: 0.5.2 Beta

**Comment by JocelynDelalande** [comment]
@Starz0r In which folder are you when running the command ?

**Comment by BjarniRunar** [comment]
Please don't run 0.5.2 Beta. It's completely obsolete and horribly buggy.

Please follow the development guidelines.

**Comment by BjarniRunar** [comment]
Please disregard this comment if you had planned to hack on the code.

I mean this in the nicest possible way, but if you are looking for an e-mail client for daily use and you're not able to get Mailpile running, then Mailpile probably isn't ready for you.

There are still some serious bugs and issues that require Python development skills to resolve and cope with - if you don't want your e-mail held hostage while you learn how to debug Python applications, you might want to wait a bit. :-)

**Comment by Starz0r** [comment]
@JocelynDelalande Root Folder of where I extracted Mailpile.

@BjarniRunar I don't mind using software that isn't fully ready for daily use, and I'm really only using this for Gmail for now, so it really can't hold my emails hostage. Even if it's just for finding bugs, or experiencing them, at least I'd be able to report them to hopefully get them fixed.

**Comment by JocelynDelalande** [comment]
@Starz0r I second what Bjarni says : dont actually expect something 
working. MP will fail at some point (as it's early-early-beta at the moment) and may loose your data.

Anyway, as you seem aware of that, I'd suggest that you use latest master from git rather than the released archive you are speaking about.

**Comment by Starz0r** [comment]
@JocelynDelalande I still have the same problem when I setup Mailpile from the Master Branch, but this time the permission to access the command is completely denied. Regardless of being in a root shell, or chown the folder.

**Comment by BjarniRunar** [comment]
Did you follow these instructions? https://github.com/mailpile/Mailpile/wiki/Getting-started-on-linux

If so, it sounds like you might have missed a step and forgotten to activate the virtualenv. But I'm just guessing here, you haven't exactly given us many details to work with. Please remember that we can't see your screen (or read your mind), so if you want to report problems or ask for help you will need to provide enough details that we can understand what is actually going on.

Have you considered joining our IRC channel, to discuss things with people there?

**Comment by Starz0r** [comment]
@JocelynDelalande I followed the instructions step-by-step. I'm not exactly sure what else I should be doing. I'll check in with IRC though and see if anyone can help.

**Comment by BjarniRunar** [comment]
I think this was resolved on IRC; although the root cause wasn't discovered, Starz0r's installation of Mailpile was corrupted in some way. Reinstalling fixed the issue and let us move on to other problems instead. :-)
