### ISSUE TITLE
(trivial) tooltip on send still shows "signing" when signing disabled

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1773]
Clicked the "signing" icon to turn it off, and noticed that the tooltip on the Send button still says that it will be signing the mail.  See attached image.

![mailpile-201702-signing-not-signing-tooltips](https://cloud.githubusercontent.com/assets/127907/22688343/b9b27cdc-ed23-11e6-9411-d74e95fdc9c5.png)

**Comment by BjarniRunar** [comment]
Good catch. The tooltip should be changed when the state of the toggles is changed.

**Comment by Mandrizzy** [comment]
I an currently new to github and open source projects but i have looked at your software I would like to be apart of the development team and contribute in whatever way I can

**Comment by BjarniRunar** [comment]
Hi @Mandrizzy! As a first step, I recommend installing Mailpile and playing with it. If you've got it up and running, please join our IRC channel (#mailpile on Freenode) and chat with us there. Also, take a look at our contributor guidelines: https://github.com/mailpile/Mailpile/blob/master/CONTRIBUTING.md

That said - in the future, please file a separate issue if you would like to discuss something technical, or chat with us on IRC. Adding off-topic comments to existing issues is considered impolite. Thanks, and welcome!
