### ISSUE TITLE
Imap folder removal/deconfiguration.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1774]
In the past, I used to have ~100 folders on my imap account.

But that was before I use mailpile, now, I barely use 4 (drafts, inbox, sent, trash, junk), and handle their content via mailpile tagging (which is greate).

So at first, I configured mailpile to look for emails in ~100 folders.

But… Removing the folders from the imap server does not tell mailpile to stop checking them. So mailpile is spending its time failing to list inexisting folders content:

```
IMAP_IOError: Failed to list mailbox contents
```

Which is logical. But I lack a way to **delete/deconfigure folders from the imap account** (on mailpile side).

**Comment by BjarniRunar** [comment]
This issue is closely related to #1173 - it's a subset of the same problem: cleanly deleting the configuration relating to downloaded e-mail.
