### ISSUE TITLE
Problem while sending message with key attached

### ISSUE THREAD

**Issue by marciomr** [mailpile/Mailpile#1777]
While trying to send an email with key attached nothing happened and I get the following error message in the terminal:

File`` "(...)/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "(...)/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "(...)/mailpile/crypto/streamer.py", line 820, in _read_data
    return process(None)
  File "(...)/mailpile/crypto/streamer.py", line 810, in process
    % self.name)
IOError: EventLog/DS(589d3b8c-05577-54d1): Bad data, failed to decode

**Comment by BjarniRunar** [comment]
Thanks for reporting! Sadly, that error message is not at all related to the problem you describe.

You say nothing happened - no notification popped up, no reaction from the UI at all?

If you are familiar with browser dev tools, could you use those to see if anything is sent to the backend or a JS error is thrown? If a request is going to the back-end, the following commands might help find some clues:

    mailpile> set sys.debug = log http
    ...
    mailpile> eventlog/watch

(Press ctrl-C to abort the log watching if you want your CLI back)

**Comment by marciomr** [comment]
You are write, the message appear when I start the program. When I try to send a message with key attached to someone that don't have PGP keys, the message is not sent, I don't get any notification in the browser, and I get the following in Google Chrome Console:

Uncaught TypeError: Cannot read property 'locked_keys' of undefined
    at Object.success (app.js?ts=1.0.0rc0-1486787958:1578)
    at k (libraries.min.js?ts=1.0.0rc0:2)
    at Object.fireWith [as resolveWith] (libraries.min.js?ts=1.0.0rc0:2)
    at c (libraries.min.js?ts=1.0.0rc0:3)
    at XMLHttpRequest.<anonymous> (libraries.min.js?ts=1.0.0rc0:3)

On the eventlog that you suggested  I got the following:

bg/log(20): Elapsed: 0.000s (output: Set output mode to: json)
as/Mailpile/mailpile/mailutils/__init__.py", line 343, in PrepareMessage
    config, sender, rcpts, msg)
  File "/home/marciomr/Programas/Mailpile/mailpile/plugins/__init__.py", line 546, in outgoing_email_content_transform
    return self._txf_out(self.OUTGOING_EMAIL_CONTENT, cfg, s, r, m, kwa)
  File "/home/marciomr/Programas/Mailpile/mailpile/plugins/__init__.py", line 532, in _txf_out
    s, r, msg, match, cont = txf.TransformOutgoing(s, r, msg, **kwa)
  File "/home/marciomr/Programas/Mailpile/mailpile/plugins/crypto_gnupg.py", line 128, in TransformOutgoing
    encoders.encode_base64(att)
  File "/usr/lib/python2.7/email/encoders.py", line 45, in encode_base64
    encdata = _bencode(orig)
  File "/usr/lib/python2.7/email/encoders.py", line 32, in _bencode
    value = base64.encodestring(s)
  File "/usr/lib/python2.7/base64.py", line 315, in encodestring
    pieces.append(binascii.b2a_base64(chunk))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 36: ordinal not in range(128)

bg/log(10): mail error: Failed: mail 
589f45c8-000c1-82b=UpdateAndSendit:c mail: Failed: mail 
bg/log(20): Elapsed: 0.067s (mail: Failed: mail )

**Comment by BjarniRunar** [comment]
Excellent reporting, thanks again. That should help me (or someone) track this down.

**Comment by BjarniRunar** [comment]
Oh, also, to disable the debugging (which slows many things down):

    mailpile> unset sys.debug

 :-)

**Comment by ktpx** [comment]
Same issue here after startup, now it wont read new emails.

**Comment by BjarniRunar** [comment]
@ktpx That's not the same issue at all. Note the stack-trace in the original report has nothing to do with the issue being discussed here (that was a red herring). Please file a separate issue and provide more details there if you can.

**Comment by ktpx** [comment]
Ok, will look into it tomorrow.

**Comment by BjarniRunar** [comment]
@marciomr Hello, I was taking a look at this issue and I couldn't reproduce or even find a plausible explanation for why this was happening. Do you still have the setup which triggered the problem?

**Comment by BjarniRunar** [comment]
Woops take it back. I think I know what's going on! :-)

**Comment by marciomr** [comment]
Great. As soon as I have some time to test I'll let you know.
