### ISSUE TITLE
Consider unpoly.com instead of our own autoajax

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1781]
Looks like http://unpoly.com/ implements many or most of the concepts we hoped to accomplish with our autoajax (incremental JS-ification). It might be worth dropping our own hacks and using UnPoly instead.

**Comment by triskweline** [comment]
Unpoly maintainer here. I like what you're trying to accomplish with Mailpile. If I can help you get started with Unpoly, or debug the occasional issue, I'm happy to help.

**Comment by BjarniRunar** [comment]
Hi @triskweline! Thanks for the generous offer, that's really cool.

I don't think we're going to attempt this in the super-near future (want to get other things working first), but I think this should probably be on our longer-term roadmap to reduce the amount of stuff we maintain ourselves.
