### ISSUE TITLE
Problems generating keys in Docker

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1785]
Reported by @cesarandreslopez on #1746:

Just tried on latest commited version. When trying to generate PGP KEY Seeing

Traceback (most recent call last): File "/Mailpile/mailpile/crypto/gpgi.py", line 1562, in run gpg.chat(self.gpg_args(), self.run_script, self.main_script) File "/Mailpile/mailpile/crypto/gpgi.py", line 1347, in chat return callback(proc, *args, **kwargs) File "/Mailpile/mailpile/crypto/gpgi.py", line 1548, in run_script self.expect_exact(proc, exp, timeout=tmo) File "/Mailpile/mailpile/crypto/gpgi.py", line 1536, in expect_exact if RunTimed(timeout, self._expecter, proc, exp, timebox): File "/Mailpile/mailpile/util.py", line 1010, in RunTimed RunTimedThread(func.__name__, work).run_timed(timeout) File "/Mailpile/mailpile/util.py", line 999, in run_timed raise TimedOut('Timed out: %s' % self.name) TimedOut: Timed out: _expecter

On GnuPG 2.1 AND also when rolling back to GnuPG 1.4

Using the latest Dockerfile to build (as Feb 16)

**Comment by BjarniRunar** [comment]
This has been reported by others as well; I don't think this relates to the GnuPG 2.1 changes, I think this is something docker-specific. When run with `sys.debug = log gnupg` and GnuPG 2.1, the debug output will report that the command used to generate the key is:

    gpg --utf8-strings --pinentry-mode=loopback --no-tty --command-fd=0 --status-fd=1 --yes --full-generate-key

And the reported error from the GnuPG interface in the other case was:

    Timed out
    Boo! GET_LINE keygen.algo not found in

... this is the first thing the GnuPG interaction code looks for in the output from gpg, so most likely the command is returning an error or failing in some other way. If you (or some other Docker user) could log into the docker environment and run the gpg command by hand, and report what the output is, that would be helpful.

**Comment by askielboe** [comment]
Tried this on a built of 523c971.

Running the following command in the container:

    gpg --utf8-strings --pinentry-mode=loopback --no-tty --command-fd=0 --status-fd=1 --yes --full-gen-key

Gives me the output:

    gpg: WARNING: unsafe permissions on homedir '/mailpile-data/.gnupg'
    gpg (GnuPG) 2.1.15; Copyright (C) 2016 Free Software Foundation, Inc.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    [GNUPG:] GET_LINE keygen.algo

Continuing through the key generation manually works fine.

**Comment by askielboe** [comment]
The issue is with the command you posted. If you change `--full-generate-key` to `--full-gen-key` it works.

Found another issue with the key generation through: If for some reason you enter your name as a single word the key generation will fail with:

    Boo! GET_LINE keygen.email not found in
    [GNUPG:] GOT_IT
    [GNUPG:] GET_LINE keygen.name

For some reason it won't accept a single word for the name, and instead ask for the name again, which fails the check.. So the user should probably get a warning if trying to add a mail account using a single-word name.

**Comment by askielboe** [comment]
I can make a pull request if you want, but I'm not sure if this change can break older GPG versions or something like that..

https://github.com/askielboe/Mailpile/commit/b8d0c17675deec8c68f8cdca44623ddd8dbd6b44

**Comment by BjarniRunar** [comment]
@askielboe Thanks for this!

Great finds, both of them. And you are right, there may be version conflicts - I'm going to be doing a fair bit of hacking this weekend, I'll see if I can get this sorted out then.

**Comment by BjarniRunar** [comment]
I've done a quick check, --full-gen-key is the "old" flag, the longer form one appears to have been added later but both are accepted by more recent versions. So if you'd like to snag the credit (rightfully so) for this, feel free to file a PR.

And I think a separate issue for the name thing is the right thing to do, I'm not sure what the best fix is, but I am pretty sure bugging the user isn't the answer.

**Comment by askielboe** [comment]
Done! I'll create a new issue for the single-word-name-bug.
