### ISSUE TITLE
Mbox Local Folders imported emails lost - Spurious "From "

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1786]
Some issues were encountered when attempting to import and index about 39,000 emails dating back to 2001 from a Thunderbird "Local Folders" mbox format directory structure.  This is the first issue.

In the mbox format, multiple emails are stored in each file.  Each email is prefixed by a blank line followed by a line that begins with "From ". Any lines in the email headers or body that begin with "From ", regardless of whether they are preceded by a blank line, are mangled by inserting ">" before "From ".

About 2% of the emails imported, up to 10% in some files, included extra mangled "From " lines near the start of the message, e.g.  
 
   [<<<<blank line]
 From - Thu Feb 05 22:34:43 2009  [<<<< start message - "From " after blank.]
 X-Mozilla-Status: 0011
 X-Mozilla-Status2: 00000000
 X-Mozilla-Keys:                                                                                 
 \>From - Mon Jan 26 17:20:56 2009 [<<<< Extra mangled "From " line.]
 X-Mozilla-Status: 0001
 X-Mozilla-Status2: 00000000
 Return-Path:  .... etcetera

The extra "From " lines occurred mostly in messages dated 2009-2012. It is not clear if they are intentional or due to a bug.

The Python 2.7 email.parser class handles a non-continuation header line NOT containing ":" as an error UNLESS it starts with "From " (feedparser.py l.226: if not headerRE.match(line):).  When it encounters an error all remaining headers are thrown into the email body. The extra ">From " lines in our emails are treated as errors. As a result the subsequent headers are not parsed.

These emails are lost to Mailpile.

Preferred solutions (require library mods - not happening soon):
- Modify feedparser.py so that header lines not containing ":" do not cause subsequent headers to be ignored.  e.g. parse as a blank key with the entire contents of the line being the value; and/or
- Modify mailbox.py so that it can take an option to unmangle ">From " as per the reversible mboxrd format (see reference below) since inspection of emails shows that Thunderbird actually used mboxrd mangling, not the original mboxo mangling.

Quick solution in Mailpile code:
- Perform mboxrd unmangling in the Mailpile code mailpile/mailboxes/mbox.py l.209 get_bytes().  This will result in ">From " being unmangled to "From " so it will then be ignored by email.parser instead of causing an error.

I will push a PR for this three line fix.

Reference:
"mbox" is a family of several mutually incompatible mailbox formats.
https://jdebp.eu/FGA/mail-mbox-formats.html

**Comment by BjarniRunar** [comment]
Hmm. I have some reservations. Please at least make sure that you don't change the length of the returned data - that might have unfortunate side-effects elsewhere - try to replace `>From ` with something of equal length, and be sure you include the preceding newline, so `\n>From ` would be thes string to replace.

Possibly just something that looks like a header? We can't use the obvious `\nFrom: `, but `\nX-EF: ` (as in x-escaped-from) is the same length. Ugly, but most of the time it'll be invisible.

**Comment by JackDca** [comment]
OK, let me look at this again.

Remember that this does not change get_bytes for all mailbox types - only mbox.  But if mbox is used as an ongoing mail source, rather than an archive that is imported just once, maybe there's an issue.  Does anyone do that?

**Comment by BjarniRunar** [comment]
1. Everyone who uses the Unix default of delivering to an mbox in /var/spool/mail/. :-)
2. mbox is the format where lengths being correct matter most
3. get_bytes() isn't being used anyway, changing THAT will effects *all* mailbox types

 :-)

It may still be an appropriate fix, but it's important to think it through and get it right.
