### ISSUE TITLE
Key generation fails if len(name) < 5

### ISSUE THREAD

**Issue by askielboe** [mailpile/Mailpile#1796]
#### Symptom:
When adding a new email account, If you use a name with less than 5 characters (including spaces), GPG key generation fails.

Mailpile produces the following error:

    Boo! GET_LINE keygen.email not found in
    [GNUPG:] GOT_IT
    [GNUPG:] GET_LINE keygen.name

#### Cause:
GPG does not accept `keygen.name`s shorter than 5 characters. If supplied with one, GPG simply asks for a name again. This raises an error in [`mailpile/crypto/gpgi.py`](https://github.com/mailpile/Mailpile/blob/master/mailpile/crypto/gpgi.py).

#### Setup:
Running latest master (b59a7493910ffec7b4847b0cec811fd59812a042) in docker.

**Comment by askielboe** [comment]
Originally discovered when working on this issue: #1785.

**Comment by BjarniRunar** [comment]
I've got code that fixes this in my local tree. The solution: Unicode Zero Width Spaces.

Not pushing up just yet, maybe there's a less evil solution. But I absolutely don't want to enforce the minimum length limit, people named π or X or whatever shouldn't have to put up with an app rejecting their identity.

**Comment by BjarniRunar** [comment]
A better solution: passing --allow-freeform-uid to GnuPG. Testing locally.
