### ISSUE TITLE
Make CLI accessible from the web UI

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1805]
For debugging and support, we will need to be able to issue CLI commands from the web UI - sending users to the terminal is unrealistic in many cases.

This doesn't need to be a full blown terminal, and it could even use the HTML renderings when available, but we need to be able to type in commands and see their output.

This is probably a requirement for 1.0, but could be bumped if we find terminal-based solutions on all platforms.

**Comment by BjarniRunar** [comment]
Note: One quick'n'dirty way to make this work, would be to hijack the search box, possibly using / as prefix, like IRC commands. So if you type "print sys.prefs" in the search box it will search for those terms, but if you type "/print sys.prefs" instead, it will run that command as if were typed on the CLI and display the output.

**Comment by grekko** [comment]
I'll have a look at that one :)

**Comment by BjarniRunar** [comment]
Having looked at this in more detail with @grekko , I've removed the low-hanging-fruit tag. This requires coordination with the back-end and we need to take special care with the access control and session concepts, neither of which are particularly easy.

**Comment by smari** [comment]
I have done some work on this; it's not perfect, but it moves us in the right direction, I think enough for the uttermost basics required for 1.0 purposes. There is a near infinity of things that one could add to this of course. See PR.

**Comment by BjarniRunar** [comment]
Hey @smari ! Thanks for your work on this so far, this is awesome.

A few nits I encountered, some of which we'd discussed, others not:

   * The initial view is a bit small, since many commands assume "a 24x80 terminal" worth of space.
   * The gpg command does not work at all (this is hard to fix without breaking other things)
   * The alt+t keybinding does not work on my Firefox/Linux, it just opens up the Tools menu.
   * There is no (obvious) way to close the terminal w/o the keybinding. Moar buttons!
   * Rather than having "big" and "little" keybindings, the user should just be able to resize

Of these, the gpg issue is both the most difficult and the most important - the purpose of providing a terminal at all is for troubleshooting and debugging, and being able to interact with GnuPG directly is very important for that. Unfortunately, that's also a hard problem to solve, since gpg will sometimes try to solicit input from the terminal. Supporting interactive gpg commands would entail implementing a full psuedo-tty, which is probably very hard in a cross-platform (including Windows) way. But we probably want to support at least the non-interactive ones, somehow? As I said, this is hard...

**Comment by BjarniRunar** [comment]
Closing this, what we have is now good enough. There are always a million things that we could do better; we can file separate issues for them (or just PRs).
