### ISSUE TITLE
Attachments: Prevent aborted/partial uploads

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1811]
Currently, the Mailpile UI will allow the user to navigate away from the page where an attachment upload is still in progress.

We prevented premature sending in #1656, but that's only a fix for the most embarrassing failure mode (where a message is sent without its attachment), there are quite a few other ways where this can go wrong:

1. In cases where the navigation is "autoajax" enhanced (partial page updates), this doesn't actually interrupt the upload but there remains no user-visible indication that an upload is still in progress. The progress bar from #1646 should probably be moved to a notification element so it persists even if the user navigates away (see also issue #1813).

2. In the case where the user triggers a full-page refresh, the upload itself will be aborted. We need to detect that this is about to happen, warn the user and give them the choice whether to continue (and abort the upload) or wait a bit longer.

The attachment Javascript logic is (for the most part) in `shared-data/default-theme/html/jsapi/compose/attachments.js`.

**Comment by BjarniRunar** [comment]
Note: Putting this issue in the 1.0 milestone - but it's a "nice to have", I don't consider it a blocking issue for a release.

**Comment by grekko** [comment]
> In cases where the navigation is "autoajax" enhanced (partial page updates), this doesn't actually interrupt the upload but there remains no user-visible indication that an upload is still in progress.

I tried to validate that but noticed that the upload is actually being canceled, at least in Google Chrome 57 on Mac OS X.

![](https://giant.gfycat.com/FlamboyantAltruisticGemsbuck.gif)

I checked the current behavior of Gmail for "navigating away" while uploading attachments. For Gmail the XHR upload does not cancel and I can navigate back to my E-Mail draft and after the XHR upload is done, I can successfully access the file/send the email.

Although I noticed that while the XHR upload is still in progress, Gmail does not re-open the Compose view for the E-Mail draft (which still has a pending upload). Not sure if thats a bug/feature.

@BjarniRunar Can you verify that the upload is indeed canceled or describe how to keep the upload "alive" while navigation to a different view?

**Comment by grekko** [comment]
I dont know how important it is for people to be able to leave the compose page while uploading attachments but I would argue that it is OK to force people to stay on the current page and wait for the upload to finish.

What would be missing right now is some UI feedback for the user that informs about the fact that leaving the site would cancel the upload and asks her wether she wants to continue and cancel or wait for the upload to finish.

**Comment by BjarniRunar** [comment]
You are observing the full-page-refresh behaviour; there the upload is canceled without warning which is a problem both because not warning the user is bad and because the backend is buggy and will attach a partial file.

If you want to see the autoajax-enabled partial-refresh behaviour which exhibits the other problematic behaviour (continues uploading in the background), try replying to a message and attach a file to the composer that is inline with search results.

**Comment by BjarniRunar** [comment]
I agree it's not super important to support navigating around. But if it works, it's a nice-to-have.

If we intend to disable all other use of the app while uploads are happening, then file uploads should be a modal dialogue IMO. Displaying progress inline as we do now implies that the user can continue doing other things, without any hints about what the limits are (and there are some pretty strict limits!).

**Comment by grekko** [comment]
> You are observing the full-page-refresh behaviour

🤦‍♂️  Ah.. I just assumed that navigating is always done via autoajax – which is the case when a user is currently viewing the inbox, but not so much when viewing the compose-page.

> If you want to see the autoajax-enabled partial-refresh behaviour which exhibits the other problematic behaviour (continues uploading in the background) […].

Alright! Following that instruction I am able to observe the XHR upload request being continued after navigating to a different view (e.g. "Sent").

While playing around with the UI, I discovered a third way that allows composing a new email that allows uploading an attachment and navigating to e.g. "Sent" without canceling the XHR upload request.

![](https://dl.dropboxusercontent.com/s/xeqzxotm6mf6nv4/2017-04-06%20at%2020.39.png)

When the compose-view is accessed this way navigating using the sidebar does not force a full-page-refresh behavior:

![](https://fat.gfycat.com/FlawedRemorsefulGoa.gif)

When accessing the compose-view via the <kbd>C</kbd> shortcut, navigating using the sidebar leads to that full-page-refresh behavior.

With having observed that I would like to discuss:
1. **Unifying the behavior of the sidebar navigation**: I dont see (conceptually) a good reason (maybe you can clarify that?) why navigating via the sidebar should behave different (meaning: full-page-refresh vs. autoajax-enabled partial refresh) when accessing the Compose-View via <kbd>C</kbd> vs. replying to a message vs. accessing the Compose-View via the "Compose a message"-Button. My proposal is to have autoajax-behavior for all views.

With a unified behavior a user will be able to navigate via the sidebar (and keyboard shortcuts) w/o interrupting the upload.

2. **Implement the `onbeforeunload`-event**: There are be still cases where a user unloads the document, e.g. through the browser UI (or e.g. <kbd>CMD</kbd>+<kbd>R</kbd> for Chrome on OS X). Therefore the native [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload)-event can be implemented, which results on Chrome OS X in the following dialog:

![](https://giant.gfycat.com/ChillyThisBushsqueaker.gif)

The JS would need to keep track wether there are currently still any XHR uploads (maybe even other XHR requests?) active and provide that information to the `onbeforeunload`-event handler.

**Comment by BjarniRunar** [comment]
Cool! I mostly agree with your analysis.

We should implement onbeforeunload for sure, that sounds like very low hanging fruit that will help in some cases (even if it doesn't help in all).

I still think my original proposal of moving the upload progrss bar to a notification popup is the right solution for the autoajax-navigation case. This matches what GMail does (using Mailpile UI metaphors) and is more flexible; in particular it will allow us to have more than one progress bar visible at once if multiple uploads are in progress.

Regarding unifying how Autoajax behaves; what you are seeing is an artefact of "progressive enhancement" - autoajax is enabled for a few links and activities (and on certain pages) where it is known to work. The full composer view simply isn't on the list of things known to work, although probably by now it could be. This also relates to issue #1702, removing the old thread view in favour of the new in-result message/composer display. When the composer is rendered in-line as part of a search result (which could be done on the drafts page), autoajax is active. When it is rendered on a page of its own (full-thread-view style) it is not. I don't think we want to spend much time fixing/improving/enhancing the views that are scheduled for removal.

**Comment by grekko** [comment]
> We should implement onbeforeunload for sure, that sounds like very low hanging fruit that will help in some cases (even if it doesn't help in all).

👍 Agreed. I'll work on a proposal for that one.

> I still think my original proposal of moving the upload progrss bar to a notification popup is the right solution for the autoajax-navigation case.

Yup. Sounds reasonable.

> I don't think we want to spend much time fixing/improving/enhancing the views that are scheduled for removal.

Also agreed. What about changing the <kbd>C</kbd> shortcut to instead navigate to the progressively enhanced compose-view?
