### ISSUE TITLE
Attachments: Detect aborted uploads

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1812]
It appears that in at least some cases, interrupting the upload of a large attachment will result in a truncated file being attached to the message. This needs to be fixed.

The API method is defined by the Attach class in `mailpile/plugins/compose.py`, but the problem might be in the HTTP daemon itself `mailpile/httpd.py` which shouldn't really pass incomplete requests on for processing.

**Comment by mayurpate** [comment]
Hi @BjarniRunar , can I work on this?

**Comment by BjarniRunar** [comment]
@mayurpate Of course, please do!

**Comment by Luckerdog** [comment]
Is this fixed and merged upstream?

**Comment by BjarniRunar** [comment]
@Luckerdog, No, this issue is still open.

**Comment by gregg00** [comment]
How does one abort an upload?  I pressed "x" for the upload in the notifications window, but the upload still attached/did not effect whether part of file or entire file was attached.   The "send" "save" buttons also go gray while file is being uploaded.  Maybe it has been resolved?

**Comment by kawara417** [comment]
@BjarniRunar could I take this issue?
