### ISSUE TITLE
Delete a draft from a thread returns to full message list (eg: Inbox)

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1817]
I happen (often) to start a draft on a thread, and then changing I "delete" it. That works. But it then redirects me to the full message list. It would be more friendly to leave me on the thread view from where I removed my draft.

**Comment by BjarniRunar** [comment]
Agreed.

**Comment by hmuhammadazeem** [comment]
How can I take this up and start fixing? Contributing first time.
