### ISSUE TITLE
Notify users of Important Things after some time has passed

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1818]
It would be nice to have a mechanism for notifying the user of Important Things after some time has passed or some other criteria has been met.

Examples:

   - Prompt user to enable backups
   - Provide "hints" now and then on advanced features of the app

There should also be a way to view the timeline and "skip the queue" or revisit old hints/prompts.

**Comment by BjarniRunar** [comment]
Note: I've started working on this as part of #129.

**Comment by BjarniRunar** [comment]
The scaffolding for this now exists. We just need to add relevant notifications... which makes this low hanging fruit. See `shared-data/contrib/hints`!

**Comment by garoller** [comment]
I've added Hints for Spam and Autotagging. Just to clarify, the back end implementation for the Hints to appear as Notifications is already in place, correct?

**Comment by BjarniRunar** [comment]
That is correct, yes! For pure documentation hints, you shouldn't need to change anything outside `shared-data/contrib/hints/`.

I look forward to seeing your work!
