### ISSUE TITLE
CLI : do not display tag list in `help` output.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1822]
It was ok with 4/5 tags and when MP didn't expose its internal tags `mp_*`, but with ~60 "real" tags (hidden ones are displayed) + ~60 automatic MP tags, this is IMHO flooding the output.

Maybe a simple message could be included in `help` output like : 

> tags can also be typed as a command, issue `tags` to list them.

**Comment by BjarniRunar** [comment]
How about keeping it as it is, but suppressing tags from the list using roughly the same criteria as is used for the web GUI?

**Comment by JocelynDelalande** [comment]
> How about keeping it as it is, but suppressing tags from the list using roughly the same criteria as is used for the web GUI?

If you mean displaying in the CLI what is displayed in left sidebar, it looks good to me :).

**Comment by BjarniRunar** [comment]
Is this good? Do we not want to list the other tags at all? Maybe not in help?

**Comment by BjarniRunar** [comment]
Relates to #1942.
