### ISSUE TITLE
Fix counts on "home" page to not include spam/trash

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1840]
@loidor wrote (on #516):

> Correct me if I'm wrong, but as I've understood it there's one tag for inbox and another one for unread. As of today, I get an unread number hovering the spam piggy, but it also shows up in the total unread number on the start page.
>
> What bugs me is that total unread number - I expect it to be zero when not having unread mail in my inbox and the more spam I get, the further away from zero I get. I think it's a bit weird to having to go to my spam box and mark everything unread in order to get to that zero. My suggestion is therefore to change it from total number unread to number unread in inbox.
>
> What do you think?
>
> I think it would be a win situation to change that total unread

I agree, we should fix the numbers on the home page to not include spam/trash counts.

**Comment by BotQ** [comment]
Any hint where I should search for code connected with that issue?

**Comment by aalon2** [comment]
Is this issue is still relevant?
I see in my Home page: 17 new when my inbox contains 17 mail, the trash 1 and the spam 1.
so looks like it's OK already.

**Comment by BjarniRunar** [comment]
Thanks @aalon2, you are correct - this is fixed. There may still be some confusion because of the mismatch between "message counts" and "conversation counts" in the UI, but the orginal issue has been resolved.
