### ISSUE TITLE
Inbox doesn't show read messages

### ISSUE THREAD

**Issue by lstandish** [mailpile/Mailpile#1842]
After clicking the "All" button, read messages in Inbox are not shown.  Read messages can only be located with a search. (Mailpile snapshot of May 14.)

Expected behavior when clicking "All" button: All Inbox messages, including read messages, should appear. Actual result: Only unread (boldfaced) messages are shown, the same as when the "New" button is clicked.

(This problem does not appear for "local mail" folders.)

System is Debian 8.

**Comment by BjarniRunar** [comment]
I am pretty sure you are confused by the default ordering ("Freshness") which by prioritises unread messages. The read message are there, but if you have a lot of unread mail then they may be pushed far enough down in the result list that you don't see them.

If you want plain chronological order, click "Order" and make your selection! :-)

**Comment by largestprime** [comment]
is it possible to make the setting 'stick'? so I don't have to click 'newest first' every time? I can't be the only person in the world who habitually leaves lots of messages unread.

--
Daniel Yeow
+49 173 722 8769
http://www.danielyeow.com
http://darkroom.danielyeow.com

"To save the world requires faith and courage: faith in reason, and courage to proclaim what reason shows to be true."  ~ Bertrand Russell

**Comment by BjarniRunar** [comment]
@largestprime yes, from the CLI:

    mailpile> set prefs.default_order = rev-date

... should do the trick.
