### ISSUE TITLE
Font cut off below baseline in Firefox

### ISSUE THREAD

**Issue by balping** [mailpile/Mailpile#1844]
This is a really minor issue. In Firefox characters having parts below baseline like like g and j  aren't displayed correctly in the searchbar, as shown below:

![diff](https://cloud.githubusercontent.com/assets/5840038/26521118/83a25b52-42d8-11e7-94c0-d285bab6393f.png)

I tried, but I couldn't find the source of the issue. Some CSS expert might be able to easily fix this.

I have a high-DPI screen, that could mess things up. It would be nice if someone could test this on a normal screen.

**Comment by BjarniRunar** [comment]
Thank you for the report and the screen shots. It would be great if someone could figure this out!

**Comment by psyonara** [comment]
I think I may have a solution. Will give it a go.
