### ISSUE TITLE
Enable proper message deletion support for GMail accounts

### ISSUE THREAD

**Issue by ut3** [mailpile/Mailpile#1847]
If the documentation I am requesting exists, I apologize, but I was not able to find it. 

Gmail's implementation of imap is nonstandard in that most folders therein are implemented as labels, with all mail actually being stored in a folder "All mail." Deleting a message from any folder will not fully remove that message from Google's servers if that message continues to exist in the "All mail" folder.

If a Mailpile has the means to work with the "All mail" folder and ensure that downloaded mail is fully removed from Google's servers, documentation as such would be beneficial. 

In case the behavior I am seeing is an error in my local setup, I am including details of my setup. For my Gmail imap source in Mailpile: (1) "Leave mail on server" is unchecked, (2) "Copy all mail and add to search engine" is checked, (3) The mail source is of course enabled.  For my Gmail account's settings, I have "When I mark a message in IMAP as deleted" == "Auto-Expunge on - Immediately update the server. (default)."

**Comment by BjarniRunar** [comment]
Thanks for reporting this!

This isn't a documentation issue, we would need to add explicit support for such GMail deletion to our IMAP code. Renaming issue for that reason.

**Comment by BjarniRunar** [comment]
Labeling this as a privacy/security issue, because deletion is necessary for privacy.
