### ISSUE TITLE
SSL Cert for Demo Has Expired

### ISSUE THREAD

**Issue by rgant** [mailpile/Mailpile#1853]
> demo.mailpile.is uses an invalid security certificate. The certificate expired on April 18, 2017 at 9:17 AM. The current time is June 23, 2017 at 11:11 AM. 

<img width="891" alt="screen shot 2017-06-23 at 11 12 24" src="https://user-images.githubusercontent.com/710553/27488460-1b60447c-5805-11e7-81af-11f3b1d1d1d1.png">

**Comment by BjarniRunar** [comment]
We know! Thanks for reporting, I'll get to it as soon as I can. Closing this, as it's not a bug in the mailpile codebase itself, it's an admin thing.
