### ISSUE TITLE
« Hide from sidebar » does not work for sidebar child items

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1860]
## Steps to reproduce

1. Create a saved search
2. Create another saved search, and set its parent to be the first saved search
3. *Edit* the second saved search, tick « Hide from sidebar » and save.

## Expected result

The second saved search disappears from the sidebar

## Actual result

The second saved search remains in the sidebar

**Comment by Kabouik** [comment]
Similar issue here. I have an empty folder on the remote mail server, it has been detected by Mailpile and added to the left bar, and it still shows up even after I click on "Organize", click on the gear next to the account name, go in "Technical settings", go in the settings of the corresponding subtag, and select "Hide from sidebar". For this account, my actions in the settings seem not to be taken into account even though they are saved (if I do it again, "Hide from sidebar" is still selected).

Weirdly enough, the subtags for this account are always collapsed by default: if I manually extend them and reload Mailpile, they will be collapsed again. I don't think the same thing happens with other accounts.
