### ISSUE TITLE
The GUI field for adding a signature to your emails will eat your brain (and your account)

### ISSUE THREAD

**Issue by Kabouik** [mailpile/Mailpile#1863]
I wasted hours today trying to set up a fresh Mailpile configuration and inevitably losing one of my accounts after restarting Mailpile, regardless of what I tried. It did not contain a duplicate email address and could not be retrieved or added again. The corresponding source was still listed in `print -flat sources`, but `print sources` showed that most of the information was missing in it. Feel free to add any extra details from my reports on IRC today if you think any is relevant to the issue @BjarniRunar.

I thought the issue was related to connection settings since I sometimes barely configured anything when it happened, plus the account was my only Exchange account in all those that I set up, and coincidentally the only one causing issues. However, the account did not readily disappear at the first Mailpile restart all the time, which made troubleshooting and replicating the issue a pain. I think I finally identified that the GUI field for specifying an email signature was the issue.

It took me ages to realize that the account did not only differ from the others from its connection settings/server type, but also by the presence of a signature (old fashioned email signature, not talking about GPG here) added when setting it up.

Steps to reproduce (last Mailpile version from git):
- Add a new account and set a plain-text signature using the GUI.
- Send emails, note that it works and be enthusiastic. 
- Ctrl+D or `q` in Mail[ile CLI, relaunch Mailpile.
- Throw yourself on the walls in despair: the account is gone.

As a comparison: 
- Add a new account and set the same plain-text signature using `vcards/addlines` command.
- Send emails, note that it works and be enthusiastic. 
- Ctrl+D or `q` in Mail[ile CLI, relaunch Mailpile.
- The account is still here.

By the way, it seems that I have to manually add the signature using `vcards/addlines` command everytime another account is added in Mailpile, or the signature will never show up in replies. Additionally, when only the account with a signature is set up, the signature will shop up automatically in Compose and Reply views, but if you add other accounts and then have to select that with an associated signature in either Compose or Reply views, the signature will not show up. It only appears when the corresponding account is selected by default.

**Comment by BjarniRunar** [comment]
Thank you very much for digging in and reporting this! Adding as a 1.0 blocker, disappearing accounts is a bad bug.

**Comment by Kabouik** [comment]
I would feel more comfortable if someone more experienced with Mailpile could try to reproduce the bug and test whether it is related to the signature GUI field only, or whether it's caused by the GUI field combined with something else.

**Comment by BjarniRunar** [comment]
I will probably look into this during my next sprint. :-)

**Comment by loidor** [comment]
I'll test it right away, since I've been looking for an easy way to remove an account :)

**Comment by BjarniRunar** [comment]
I have found and fixed a bug in how Mailpile saved/loaded VCards from disk; basically if a data field included carriage-return (\r) characters, that could cause data corruption.

Since profiles are stored as VCards, and since signatures often contain \r characters, this is a plausible explanation for the disappearing account problem.

**Comment by Kabouik** [comment]
Excellent, thanks. Indeed, I had distinct lines in my signature (using `\n`). Out of curiosity, does your commit also fixes the couple issues mentioned in the last paragraph of my message (I don't have my Mailpile here to try myself)?

**Comment by BjarniRunar** [comment]
@Kabouik, no I have not fully addressed the fact that sometimes signatures are added to messages and sometimes not. I think I'll file another issue describing the limitations of how we currently handle signatures. Thanks for reminding me.
