### ISSUE TITLE
Error running ./mp on MacOS

### ISSUE THREAD

**Issue by ovnicraft** [mailpile/Mailpile#1865]
1. clone repo
2. pip install requirements
3. run ./mp 

Got this error: https://gist.github.com/ovnicraft/4eeaa9afaa9785849e9c29beaa09d640

**Comment by BjarniRunar** [comment]
I suspect that means you don't have GnuPG installed. GnuPG is not a requirement that can be installed using PIP.

**Comment by ovnicraft** [comment]
I confirm solution for this issue.
`$ brew install gnupg`

In another hand, @BjarniRunar would be possible add a raise about gnupg, i can work on PR.

**Comment by BjarniRunar** [comment]
Agreed, it would definitely be better to give a human-readable error message!

**Comment by ovnicraft** [comment]
Ok, so will work

**Comment by BjarniRunar** [comment]
Thank you! If you need any guidance, I'll try and be on IRC later this evening (#mailpile on Freenode), and definitely on Thursday and Friday.
