### ISSUE TITLE
E-mail signatures (non-cryptographic) limitations

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1866]
The way we currently handle signatures (custom text at the bottom of e-mails) is a bit lame at the moment and needs to be rethought.

Currently, signatures are simply treated as part of the message text and Mailpile will add them automatically to the blank template when it can. Unfortunately, because sometimes a message is generated for editing *before* the user has chosen which account they are sending as, Mailpile doesn't know which signature (if any) to use until too late. The composer does not automatically inject (or remove) signatures when the user chooses/changes sending accounts. So sometimes the signature is missing.

There are two possible ways to fix this:

1. Add the signature during PrepareMessage, when the e-mail is finalized for sending. This means the signature will not be part of the editable message text. In this case, it would be nice if the composer Javascript would display which signature is in use, but not give the user the option to edit it.

2. Enhance the composer to add/remove signatures on the fly, when the user chooses/changes sending accounts. This will still allow the user to edit the signature itself (is that a bug or a feature?), and the injection logic would need to take that into account so it doesn't accidentally inject two signatures, or accidentally undo edits the user has made.

Of these, I think option 1. is a cleaner solution, especially since it can be done incrementally (the in-composer display can be omitted from the first draft). It also has the benefit of being compatible with non-JS composition workflows.

I am assigning this to the 1.0 milestone: since this feature is currently half-broken, we need to decide whether to ship it as-is with 1.0, disable it or fix it.

**Comment by BjarniRunar** [comment]
(Relates to #1863 )

**Comment by BjarniRunar** [comment]
I've implemented strategy 1. above, but there's no feedback to the user (no signature display) yet. This is enough to clear 1.0 I think, bumping to 1.1.

**Comment by Kabouik** [comment]
Thanks for addressing this. I admit I prefer solution 2 over 1 and do not see many advantages for 1 (from a user's perspective, not a dev). This was for instance the behavior in Nylas Mail before it died (there is [hope](https://github.com/nylas-mail-lives/nylas-mail) though) and it felt very natural and trivial to use.

Having feedback on what the signature will look like is in my opinion a must (especially as Mailpile is under active development, so letting the user control what his final email will look like without any black box seems like a good idea), and on-the-fly editing of signatures can be very useful as well in some situations. In general, I believe a mail composer should always let the sender preview his final email, and therefore display its editable form as close as the message will actually be sent (this includes automatic wrapping as well), and hopefully be received (although it depends on the recipient's client as well). Adding formatting or content like signatures in an automatic way without letting the user control it seems risky and from my personal use, which may not be a good example, I see more cons than pros in this. Emails cannot be unsent.

I am glad that you did not decide on removing signatures for 1.0 though, as I still prefer a system that is not fully-functional over no system at all for signatures (this would force me to remember the name of my work institution in scandic, which I'm incapable of!).

**Comment by BjarniRunar** [comment]
You can remove the signature by removing it from the account. Being able to do it on a per-message basis is a luxury, IMO, not a required feature. Definitely a nice-to-have, but not a show-stopper by any means.

**Comment by BjarniRunar** [comment]
Also, as a counterpoint - as a user, assuming I've chosen a signature I want, it is definitely a feature that I don't have to worry about accidentally deleting it during editing. I tend to do things like select-all+paste-over, and that nukes the signature by accident. This also makes signatures on outgoing mail accidentally inconsistent, which is exactly the bug I was trying to fix here. :-)

**Comment by BjarniRunar** [comment]
Implemented previews as a warm-up this morning...

**Comment by Kabouik** [comment]
I really like the previews! But that's more solution 2 than 1 in the end, or was I confused with what you meant with solution 1? In any case, it's trivial, flexible and easy to use, thanks!

**Comment by BjarniRunar** [comment]
Solution 2 lets you edit the signatures by injecting them into the textarea itself. This is just a preview. Glad you like it!
