### ISSUE TITLE
Create a Hint about the side-bar Organize mode

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1874]
The user can customize their sidebar by clicking the Organize button at the bottom of the sidebar. The organizing happens mostly by dragging tags up and down, so they end up in different places.

The fact that you can drag/drop things and move them around is non-obvious and needs explaining. The current mechanism we have for such explaining is the Hints plugin, in `shared-data/contrib/hints/` - adding some explanations there would be a good first step.

Longer term, it might make sense for the "Organize" mode to actually gray out the search result area and replace it with helpful text or images. That's a bigger task, obviously.

(thanks to @karlp for the feedback and discussion)

**Comment by BjarniRunar** [comment]
Also, this would be NICE TO HAVE for 1.0, but isn't a blocker. Just sayin'. :-)

**Comment by Coronon** [comment]
Should be closed

**Comment by BjarniRunar** [comment]
@Coronon Correct, thank you very much for the reminder.
