### ISSUE TITLE
Create a Hint telling the user about Gravatar

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1876]
Mailpile currently relies (mostly) on Gravatar (https://secure.gravatar.com/) for thumbnails identifying people. Although we'd like to decentralize that a bit more (and have some code in that direction), in the near term this is the only feasible way for people to make their icons visible.

We should tell people about this, using a Hint sometime within the first couple of weeks of use. The hint should at the very least tell people that Gravatar exists, how we use it, and mention the privacy implications (people who know your e-mail address can see your picture).

Hints are here: `shared-data/contrib/hints/`.

This would be NICE TO HAVE for 1.0, but isn't a blocker.

**Comment by gerroon** [comment]
Any word on this? I still see trying to connect to gravatar. Do not get me wrong but you tell us this is a secure app then you query my and my friends names and users namaes from a shithole. I had no idea that that is what it was going until I checked the logs :(

**Comment by BjarniRunar** [comment]
@gerroon Uh, just turn it off if you don't like it. It's on the privacy settings page. If that setting isn't working, then please file a bug.

And maybe be polite about it? Comments like "shithole" and "well helllooo" are absolutely uncalled for. Everybody is doing their best here, so please appreciate that and show some respect.

Regarding the issue itself, the hint has been created and works, so this issue can be closed.
