### ISSUE TITLE
Mailpile creates a large number of temporary files

### ISSUE THREAD

**Issue by browserinput** [mailpile/Mailpile#1878]
Operating Environment: Raspberry Pi 3 running Arch Linux for ARM

Running Mailpile with five accounts totalling around four thousand e-mails for three days results in over 2.5 million files in the tmp directory. Shutting Mailpile down and restarting it at this point causes an IO jam that crashes the entire operating system as it attempts to first read the name of every file in the tmp directory, shuffle that list, and then delete each file.

While I realize that my particular circumstances are a little extreme, I think Mailpile's behaviour is significiantly more extreme. Can't Mailpile clean-up temporary files as it is done with them as opposed to leaving that all up to the next run?

**Comment by BjarniRunar** [comment]
Wow, that's exciting. Thanks for reporting this. That's way more I/O than seems justified (4000 e-mails is nothing). I'll look into this to see what's going on.

**Comment by BjarniRunar** [comment]
Actually, could you clarify *which* tmp directory?

**Comment by browserinput** [comment]
Of course, I probably should have said that to begin with. It's the directory that under non-Windows and non-OSX environments evaluates to $HOME/.local/share/Mailpile/default/tmp; I've can't remember off hand what the method/variable name is in code.

**Comment by BjarniRunar** [comment]
I'm not managing to replicate this, at all, I think something must be broken in your setup.

In my case (admittedly, not on a raspberry pi), indexing lots of mail doesn't leave any temp files lying around at all - in fact I don't think it's creating any, which is the desired situation.

Did you customize your data encryption settings? Are there any errors or tracebacks on the CLI? Do you see anything interesting if you run the following commands?

     mailpile> set sys.debug = log
     ...
     mailpile> eventlog/watch
     ...

(press ctrl+c to break out of the log watcher)

**Comment by loidor** [comment]
Just adding that I've run Mailpile on a pi 24/7 for half a year or something, with my largest inbox containing 40k mails, and I don't have any tmp files problems either. 

However, it can be a bit iffy to setup on a pi. Some of the python packages doesn't install through Jessie's pip, for some reason. I don't know if that's Jessie or if it's ARM. What I'm getting at is that it might be worth to manually go through requirements.txt and check that everything is properly installed.

**Comment by BjarniRunar** [comment]
Thanks @loidor, that's good advice. Hopefully this will all become a bit easier once we've got our own repository of .deb packages that people can apt-get install.

In this case, it does sound like Mailpile might be having difficulty encrypting data, so checking to see if the Python cryptography module installed correctly would be the first thing I'd check.

**Comment by Kabouik** [comment]
Off-topic, but just jumping on the opportunity (sorry):

> Hopefully this will all become a bit easier once we've got our own repository of .deb packages that people can apt-get install.

When that time comes, please consider other package formats as well. While Debian and Ubuntu-like distributions are horses you can surely bet on if you want to be visible, I feel (on my crystal ball, yes) that some people are getting increasingly annoyed by Ubuntu, Mint and other similar distributions. That was my case. Of course they still satisfy most people, but please do support alternatives (arch, eopkg, rpm, flatpak...).

**Comment by browserinput** [comment]
Well, in order to make my life more interesting, the issue has vanished. Perhaps there was a problem with one of the Arch python packages or maybe one of the recent commits fixed my issue by accident. In any case, if I experience it again, I'll try to track down where it is happening more conclusively and then re-open the issue. Until then, I'll close this. Thanks!
