### ISSUE TITLE
Login using API (SSO) ?

### ISSUE THREAD

**Issue by Yamakasi** [mailpile/Mailpile#1879]
Is it possible to login to Mailpile using an API so you can login to your own app and call the API of Mailpile so the user is loggedin there as well ?

**Comment by smari** [comment]
Currently Mailpile doesn't support anything like SAML. A pull request for SAML support would be welcome. It is however currently possible to feed login credentials over the API as a CGI. Check `shared-data/multiple/mailpile-admin.py` for an example of how to do this. Beware that this isn't very heavily tested yet. Some assembly may be necessary.

**Comment by BjarniRunar** [comment]
There may be some difficulties using SSO, depending on how it is implemented.

Note that when you are logging on to Mailpile (the first time), you are unlocking the master key which keeps all the Mailpile data encrypted.

So this isn't just about "granting access"; this is actually about decrypting critical data, and for that to work Mailpile needs the user to enter their passphrase - an authentication token from some shared auth system won't suffice.

After the initial login has taken place and everything has been unlocked, it would be possible to support SSO semantics (or alternate logins/passwords, per-device passwords and all sorts of other useful things).

But for the first login after starting the app, the user needs to enter their passphrase.
