### ISSUE TITLE
Drag-drop resizes/crops image attachments

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1883]
According to reports on IRC (thanks Kabouik), Mailpile is cropping / resizing png images to squares when they are drag/dropped onto a message. This is probably a mistake in how we handle drops, we should investigate and disable that silliness.

**Comment by Kabouik** [comment]
Ok so as a test, I tried attaching 4 pictures to an email: 
1. a png of 4274 × 3307 pixels 
2. a jpg of 4274 × 3307 pixels
3. a png of 1920 × 1486 pixels
4. a jpg of 1920 × 1486 pixels

They ended up like that in the received email:
1. a png of 3600 × 3307 pixels 
2. a jpg of 3600 × 3307 pixels 
3. a png of 1920 × 1486 pixels
4. a jpg of 1920 × 1486 pixels

So there is no effect of the image type. They are not exactly squares (I spoke too fast when I said that, should have checked the actual resolutions). Only the long side was cropped (both side) on the larger images, the smaller were fine.

Followed by another test:
1. a png of 3601 × 3307 pixels 
2. a png of 3599 × 3307 pixels
3. a png of 3307 × 3601 pixels
4. a jpg of 3307 × 3599 pixels

They ended up like that:
1. a png of 3600 × 3307 pixels 
2. a png of 3599 × 3307 pixels
3. a png of 3307 × 3600 pixels
4. a jpg of 3307 × 3599 pixels

So the hard cap is at 3600 pixels, and it doesn't matter if it's in Y or X axis.

(I did this with drag and drops, but it seems from the comments above that attaching pictures with the button is not different.)
