### ISSUE TITLE
Messages can be sent before all attachments are uploaded

### ISSUE THREAD

**Issue by Kabouik** [mailpile/Mailpile#1884]
Sending a message before all attachments are uploaded is possible, and the message will be sent with only those already uploaded. I believe the composer should wait until all attachments are up, or at least warn the user that his email will be sent without the other attachments in queue.

**Comment by BjarniRunar** [comment]
Hm, I thought we'd fixed (mitigated) that by disabling the Send button! It sounds like you are uploading multiple attachments, is that correct?

We might be using a boolean when we need a counter. Thank you for filing this.

**Comment by Kabouik** [comment]
Yes, that was with several attachments, I have not tried with only one.
