### ISSUE TITLE
GMail OAuth "expires"

### ISSUE THREAD

**Issue by paolosg** [mailpile/Mailpile#1893]
After I gant Mailpile access to my GMail account (using OAuth) it works well, but after a few hours it stops working and asks me to grant it again. It has many email to download.
I don't know what other relevant information I should provide, in case just tell me.

**Comment by BjarniRunar** [comment]
Thanks for reporting this. Mailpile should renew its access tokens automatically; it sounds like this may need more testing. Had you restarted Mailpile at all in the meantime?

**Comment by BjarniRunar** [comment]
... or, if you are running on a laptop, did it expire after the laptop went to sleep for a while? If the laptop is asleep the token renewal won't happen.

**Comment by largestprime** [comment]
I currently run mailpile on a banana pi which is always on, and I
also have this problem. I last restarted and updated my mailpile
this morning.

-- 
Daniel Yeow
+49 173 722 8769
http://www.danielyeow.com
http://darkroom.danielyeow.com

"To save the world requires faith and courage: faith in reason, and
courage to proclaim what reason shows to be true."   ~ Bertrand Russell

**Comment by BjarniRunar** [comment]
@largestprime Thanks. Time to double-check the OAuth key refresh code then.

**Comment by paolosg** [comment]
I am in fact on a laptop so I wanted to check before replying: it does not expires only after sleeping (which it does), but also after 1-2 hours of uninterrupted running.

**Comment by BjarniRunar** [comment]
By my tests, this is fixed (I saw my OAuth token get refreshed) by PR #1893.
