### ISSUE TITLE
RC1: Add Account button does nothing

### ISSUE THREAD

**Issue by mabkenar** [mailpile/Mailpile#1904]
I just installed mailpile (the desktop version) on my Ubuntu 16.04 using the "release" channel of the Debian repositories. It loads on my browser, and I can set my password and review my privacy settings. But I cannot add any accounts. When I press on the button "Add Account", a pop shows up saying "Working..." and it disappears without anything happening. I have recorded the event in the following animated GIF.

![mailpile_add_account_bug1](https://user-images.githubusercontent.com/3006332/29167978-21db84cc-7dcd-11e7-8737-4a85f2976521.gif)

Any ideas? 

I am happy to test and send more information if you want me to.

**Comment by BjarniRunar** [comment]
Thanks for filing! I am going to see if I can reproduce this at my end and will get back to you.

**Comment by BjarniRunar** [comment]
I have tested this on a fresh install of Ubuntu 16.04 LTS, using both Firefox and Chromium and have been unable to reproduce. Can you give any more details?

If you know how to use the browser debugging console, do you see any error messages there? Are you double-clicking by accident?

You can try running the following at the `mailpile>` prompt and see if any debugging messages show up on the terminal:

    mailpile> set sys.debug = log http
    ...
    mailpile> eventlog/watch
    ...

(press CTRL+C to stop watching the log)

**Comment by mabkenar** [comment]
Hi Bjarni, sorry for the late response. After 6 days, I tested mailpile again, trying to enable logging as you instructed me to do. Strangely (and fortunately of course) I cannot reproduce the bug anymore. 

But I'm still wondering what was causing the bug in the first place. If there is still value in sending you logs, I would happily do.

**Comment by BjarniRunar** [comment]
Thanks for reporting back. I'm not sure what logs to request... so I guess this remains a heisenbug for now. We'll find it eventually....
