### ISSUE TITLE
How can I change my email password?

### ISSUE THREAD

**Issue by mabkenar** [mailpile/Mailpile#1907]
Finally, I have been able to play with mailpile. It is really featureful and has great UI design! I was particularly impressed by the address book integration. It pulled contact addresses both from my email server and also from local addresses in my GnuPG key store. I haven't seen any other email client doing this. Very nice work, Bjarni and other contributors!

Now I have a little problem with mailpile: I have accidentally entered a wrong password before sending my first email from mailpile. Ineed, I entered mailpile password instead of my SMTP password since I got confused which password it is asking for.

Now I get the error `Could not send mail to xxxx@xxx.xxx (Invalid username or password)`. But I cannot find the UI part where I can correct the password. How can I change the SMTP password associated with my email address?

![selection_397](https://user-images.githubusercontent.com/3006332/29350389-ae60df7e-825e-11e7-8b3f-b3fdb14a6374.png)

**Comment by Kabouik** [comment]
You have to go in the /privacy/ page by clicking on the cog at the top left when looking at your profiles, or on "privacy" below the e-mail list. From there, click on the portrait icon, and you'll be able to select all accounts/credentials Mailpile knows and select the an below (in your case, Forget, and then Unlock).

I don't know why you are not getting a link in your notifications, I seem to remember I was getting one when I entered wrong credentials.

**Comment by BjarniRunar** [comment]
@Kabouik  No, no, no... that's the main Mailpile password! :-)

There is a tool for managing stored passwords. Click on either the privacy settings or the word "notifications" in the popup, to access the settings section of the app. In the activity list there is a little user avatar between "TLS Certs" and the key icon. That pops up the Account Password Management tool.

**Comment by BjarniRunar** [comment]
Oh, oops, I misread. @Kabouik was saying the same thing I was. Sorry!
