### ISSUE TITLE
"Failed to decrypt configuration, please log in"

### ISSUE THREAD

**Issue by deviratechllc** [mailpile/Mailpile#1915]
I cannot seem to get this to install on a fresh Ubuntu 14.04 server on top of mailinabox. When it says "please log in" what username and password is it expecting? Or what exactly am I doing wrong here? I can't find this documented anywhere so any help would be much appreciated.

> (mailpile-env)root@box:/opt/Mailpile# ./mp
Metadata index not found: /root/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.041s (Loaded metadata, 0 messages)
Elapsed: 0.003s (health: We are healthy!)
**load error: Failed to decrypt configuration, please log in!**
Elapsed: 0.002s (load: Failed to decrypt configuration, please log in!)
Elapsed: 0.000s (motd: )
=============================================================================
Mailpile.py              a tool             Copyright 2013-2017, Mailpile ehf
 v1.0.0rc1         for searching and               <https://www.mailpile.is/>
               organizing piles of e-mail
>This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation. See the file COPYING.md for details.
The Web interface is disabled, type `www` to turn it on.
   Type `help` for instructions or `quit` to quit.
   Long running operations can be aborted by pressing: <CTRL-C>
mailpile> www
*args, **kwargs)
  File "/opt/Mailpile/mailpile/config/manager.py", line 1332, in _unlocked_prepare_workers
    start_httpd(httpd_spec)
  File "/opt/Mailpile/mailpile/config/manager.py", line 1296, in start_httpd
    config.http_worker = HttpWorker(config.background, sspec)
  File "/opt/Mailpile/mailpile/httpd.py", line 571, in __init__
    self.httpd = HttpServer(session, sspec, HttpRequestHandler)
  File "/opt/Mailpile/mailpile/httpd.py", line 529, in __init__
    SimpleXMLRPCServer.__init__(self, sspec[:2], handler)
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 593, in __init__
    SocketServer.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
www error: Failed: www
Elapsed: 0.004s (www: Failed: www )
Failed: Failed: www
          Interrupted. Press CTRL-D or type `quit` to quit.
mailpile> quit
Elapsed: 0.004s (quit: Shutting down...)
OK: Shutting down...
Elapsed: 0.000s (interact: Ran interactive shell)
Elapsed: 0.001s (cleanup: Performed shutdown tasks)
OK: Performed shutdown tasks

**Comment by BjarniRunar** [comment]
Sorry this never got a timely reply. It looks like you had another Mailpile instance already running (or some other port conflict), so the second one was unable to launch the built in web-server.

During the app setup, you configure a password. That is what it was asking for. Maybe you hadn't even run setup, it sounds like you didn't get very far. Sorry this was a disappointing experience!
