### ISSUE TITLE
Installation fails on Ubuntu 14  due to python-cryptography dependency

### ISSUE THREAD

**Issue by TentativeConvert** [mailpile/Mailpile#1918]
Is Mailpile expected to support pre-16.04 versions of Ubuntu?  

My system is running Ubuntu 14.04.  After following the instructions on the download page up to `$ sudo apt-get update && sudo apt-get install mailpile`, I get the following error message:

    The following packages have unmet dependencies:
     mailpile : Depends: python-cryptography but it is not installable
            Recommends: tor but it is not going to be installed
            Recommends: wamerican-small but it is not going to be installed
            Recommends: gnupg-curl

I gather from [this thread](https://github.com/ansible/ansible/issues/26305) that a work-around for this particular package dependency is known, but I don't understand the details.

**Comment by BjarniRunar** [comment]
We have to draw the line somewhere, I'm afraid. Cryptography is not an optional requirement anymore; if you can find packages for Ubuntu 14.04 it might work? Or you can pip install cryptography and force-install the package (ignoring the dependencies), but I think that may leave your apt in a sad state.

Closing as not-a-bug, sorry about the inconvenience! :-)

**Comment by TentativeConvert** [comment]
My understading is that python-cryptography is not available for Ubuntu 14.  But no worries.  The installation page explicitly states that things have only been tested on Ubuntu 16.  You may now add that on Ubuntu 14 the installation is known to fail.
