### ISSUE TITLE
Can it be used for service providers?

### ISSUE THREAD

**Issue by faphdev** [mailpile/Mailpile#1922]
Hello,

I see that you mention that Mailpile can be used locally on a desktop machine or on a PERSONAL remote server.
Can it be used for service providers to provide access to customers?

Thanks, it looks great :)

**Comment by JocelynDelalande** [comment]
@faphdev Hello !

>  Can it be used for service providers to provide access to customers?

No. That is not the current goal/priority.

Someone might develop something toward this direction one day, but we are quite far from allowing mass-deployment nowadays. That is a personal mail client that *could* be installed on personal server, and there is a nice hack allowing pseudo multi-user install, but « scalability » is not in current goals.

@BjarniRunar explicits that in the video at SHA2017 https://www.mailpile.is/blog/2017-08-13_SHA2017.html

(issue can be closed IMHO)

**Comment by BjarniRunar** [comment]
Yes, I'm going to close this. Although technically a service provider could use Mailpile to provide service to their customers, this isn't a use-case we are currently aiming to support.

Our target audience is small multi-user setups (families, small businesses/organizations) or single-user setups. Mass deployment at the ISP level (or equivalent) is out of scope and our current design doesn't make it easy to do.
