### ISSUE TITLE
Attachment size limit differs from server limit

### ISSUE THREAD

**Issue by Kabouik** [mailpile/Mailpile#1923]
I have not been able to pinpoint the exact maximal file size allowed for attachments in Mailpile, but is most definitely lower than the size allowed by the e-mail server itself if using another client of the webclient from the provider. I think Mailpile should only use the same limits as the server for a given e-mail account.

This is true for single attachments at least, but may be true for the total size of all attachments as well (not tested). You get `Could not upload attachment because: HTTP Error.` when trying to upload a file bigger than Mailpile allows.

**Comment by BjarniRunar** [comment]
AFAIK, Maipile has no way of knowing what the remote server supports. And even if it did, Mailpile has no idea what the receiving mail server supports (which can be different again). Your request is reasonable, but it's not solvable using existing Internet protocols. Closing for that reason. :-)

**Comment by Kabouik** [comment]
Is there a way to make the default editable with `set prefs`? I know that 75% of the files I have to send are smaller than my my server's limits or the recipient server's limits, and yet cabnot be used to send them. Therefore the only way to send them is to use another client/webmail or to upload the files to a third-party service, it kind of beat the point and prevents full migration to Mailpile (while Mailpile is intended for full migration since it does not sync with the server, and is even meant to decentralize e-mails from the server). Having a conservative default value makes sense, but it would be great if a user who knows what he is doing when trying to send bigger files could bypass the default limitation.

Also, if the files is bigger than the recipient server allows, would the sender not receive a mail-delivery error giving the details?

**Comment by BjarniRunar** [comment]
Making this configurable is a cop-out, if our defaults are bad we should fix them. And also make it configurable, I guess, but that's a last-resort kind of thing.

Mail delivery errors are not intelligible to most humans.

**Comment by Kabouik** [comment]
Thanks @BjarniRunar for reopening this issue.

I just got the issue again with a 2.9 MB PDF file (I mostly had gotten it with image files so far). 2.9 MB is far below the limit of my e-mail provider, and I assume it would be lower than the destination server as well (< 5 MB limits are getting rare nowadays, except for particular situations). What is the hard cap currently in Mailpile?

I'm curious as to how this issue is dealt with in other e-mail clients. Do you know if they manage to communicate with the server to get the attachment size limit for outgoing e-mails, or if they take any file without any prior limitation but just fail when trying to send it? Or anything else?

As long as there is a feedback to the user (either an error or the message not being sent), I think it's better not to impose an arbitrary limit that does not match the actual limit of the outgoing server (or set one limit but make it configurable for people who know the actual limit is less conservative than Mailpile's default; I wouldn't see it as bad solution but maybe I'm missing something).

As for errors on the receiving server side, I agree that Mail delivery errors are messy, but they clearly mention attachment errors when this is the cause. They also ring a bell and warn the sender that something wrong happened between him and his contact: the sender is immediately notified that his e-mail has not been delivered and read even though it was correctly sent, and whether this user wants to try understanding the specific error or not, this information is already something significant (but I believe Mailpile users would quickly understand the error from a Mail delivery report).

**Comment by Kabouik** [comment]
As a complement, I've just received an e-mail with a 19 MB attachment from a colleague who is using the same e-mail server, but Thunderbird. Not sure how Thunderbird deals with attachments and their size, but there seem to be not a priori limit (or it is a lot less conservative than Mailpile's).

**Comment by Kabouik** [comment]
It turned out that this issue was not related to Mailpile, but to the settings of my VPS. Sorry for opening this thread.

For reference, in cases others use Mailpile on a VPS with Nginx:
add `client_max_body_size 20M;` (or any value of your choice) in the "{server}' block of the Nginx configuration file for the Mailpile subdomain, and change `upload_max_filesize = 20M` accordingly in /etc/php5/fpm/php.ini. Then 'sudo systemctl restart nginx` and `sudo systemctl restart php5-fpm`. Now you should be able to upload attachments up to 20M.
