### ISSUE TITLE
Untranslated string. "You're about to experience email like never before!"

### ISSUE THREAD

**Issue by comradekingu** [mailpile/Mailpile#1928]
Can't see why it doesn't work. Other than it being unescaped, but that shouldn't matter.

https://github.com/mailpile/Mailpile/blob/74d1eea99bdb892555b0cf191b612b9340df1c48/shared-data/locale/mailpile.pot#L6801

https://github.com/mailpile/Mailpile/blob/88ae8e5831dddc628c827c44224166dbdbed91f1/shared-data/default-theme/html/setup/welcome/index.html#L20

Norwegian Bokmål shown here nb_NO:

![butwhy](https://user-images.githubusercontent.com/13802408/30174878-d2c81242-93fc-11e7-972a-25df7489dbdc.png)

Snooky snooks indeed. But it isn't language specific:

It also happens with other locales, here with Spanish es_ES:
![captura de pantalla - 070917 - 17 46 50](https://user-images.githubusercontent.com/13802408/30174787-85f399fa-93fc-11e7-97be-45fdbfcd8b44.png)

Edit: My best guess is the tx push script hasnt been called in a while, or something broke along those lines.
Which would explain strings that are not up for translation, whereas this one is not happening either, so maybe tx pull isnt working either.

**Comment by comradekingu** [comment]
Getting closer. Last time strings were updated is January 2016. Which would correspond with this
https://github.com/mailpile/Mailpile/commit/e2e8490aecab6640b99fee66aa9de5d9ef142402

**Comment by BjarniRunar** [comment]
I could replicate this if the string was translated, but marked fuzzy. Our message compiler skips fuzzy translations. I think this is the right thing to do, since a wrong translation is often worse than no translation. Thanks for reporting this!
