### ISSUE TITLE
Export passphrase not the same as login passphrase?!

### ISSUE THREAD

**Issue by basketas** [mailpile/Mailpile#1937]
I wish to export my key, and when I type in
gpg --armor --export-secret-key my@mail.com
it asks for passphrase but it doesn't accept the passphrase I use to login into the mailpile..

So how do I find this password or otherwise export my private key?!

**Comment by BjarniRunar** [comment]
I assume you are talking about a key Mailpile created for you?

If you click on any of the settings/debug links in Mailpile (Privacy settings, Notifications, ...) you should see in the toolbar near the top of the page a bunch of options. One of them is secret key management, which has the icon of a key. For keys which are created/managed by Mailpile, this tool will give you the option to display the key's internal passphrase.
