### ISSUE TITLE
Your Mailpile may not be running

### ISSUE THREAD

**Issue by fakeid30** [mailpile/Mailpile#1938]
I installed mailpile on Amazon EC2 ubuntu 16.04 following this guide : https://www.mailpile.is/download/linux.html

I have all the ports open for testing purpose, so that should not be a problem, I also installed mailpile-apache2 . 

When I start mailpile from terminal it starts fine but when I go to the web address I see an error 
![screenshot_20170926_190758](https://user-images.githubusercontent.com/26362832/30861911-bcaf14ba-a2bb-11e7-95a7-5bfca529944e.png)

No matter what I input I can't login and proceed further, what am I doing wrong?

**Comment by cbz20** [comment]
Same problem here. Installed mailpile-apache2 (using the official repository) on my raspberry pi (running Raspbian Stretch Lite). 

Related question @BjarniRunar: I have run the setup flow, but it only asked for a password. What is the corresponding (default) username? How do I add a user? (Can I add a user?)

Relates to #1538

**Comment by BjarniRunar** [comment]
@fakeid30 The Apache form is asking for the username and password of a Unix account on that machine. Have you created one? It may also be broken, in which case if you can figure out why that would be great! ;-)

@cbz20 You misunderstand. A user, such as "joe" or "root" runs Mailpile. The setup then applies to their mailpile, not mailpile belonging to other users. Thus there is no need to ask for a username. Just like Thunderbird, Firefox and vim don't ask you your username. You can add e-mail accounts within the app, but that's different. If multiple users want to run Mailpile, each of them runs it himself (or launches via. the Apache integration tool).

**Comment by fakeid30** [comment]
@BjarniRunar I added a new account and gave it sudo privilage, I even tried starting mailpile with sudo just to test, I inputted my main root password too, but no matter what I do I end up being back in the scree. I also setup SSL thinking maybe my browser is force closing the connection. 

![screenshot_20170927_155111](https://user-images.githubusercontent.com/26362832/30907357-f4af2612-a369-11e7-9fab-e273de6f3117.png)
![screenshot_20170927_155123](https://user-images.githubusercontent.com/26362832/30907362-f6b4eb5e-a369-11e7-8476-d3da47c752be.png)

I have noticed that if I input a bad password it instantly comes back to the login page, but a good password makes it do stuff.

**Comment by BjarniRunar** [comment]
@fakeid30  Wow, don't do that. Mailpile should not run as root, and if you do run it at root you run the risk of it creating files as root which the actual owner (normal user) will then not be able to modify.

You may need to nuke the Mailpile data folder and start over: `sudo rm -rf /home/user/.local/share/Mailpile` (you will need sudo for that, since root now owns the files)

**Comment by cbz20** [comment]
@BjarniRunar Thanks a lot, now I understand...and it works! Yuhey! [Now, I just need a certificate to access mailpile securely, but that is a different problem; my ISP seems to block all ports relevant for certbot to work.]

**Comment by BjarniRunar** [comment]
@fakeid30 I am not sure how to guide you through troubleshooting this, so if you're not comfortable diagnosing yourself then exploring other options may make sense. I would love to get to the bottom of this, but I'm not sure where to start. Last time I had problems like you describe, it's because one of the tools the Apache integrated launcher relies on wasn't installed (the package dependency list was missing something).

Mailpile's just a normal HTTP server, but the trick is of course that something needs to launch it and ideally you'd put it behind some sort of proxy that takes cafe of SSL encryption. How you solve that is entirely up to you!

**Comment by fakeid30** [comment]
@BjarniRunar I sort of fixed it by uninstalling the dev version and building the github version with nginx instead of apache. 

![screenshot_20170927_221300](https://user-images.githubusercontent.com/26362832/30924585-be591566-a39e-11e7-8a4e-67155f7dbd29.png)

It's still very slow, is it a known bug?

**Comment by donkikhot** [comment]
i have too this problem in ubuntu16.04 apache2,
Your Mailpile may not be running

**Comment by mahmoudgad94** [comment]
Same problem Debian 9

**Comment by gerroon** [comment]
Same, Debian Testing. It keeps telling me mailpile is not running, entering creds (one the one running mailpile) does nothing

**Comment by BjarniRunar** [comment]
The current Apache integration package is really buggy, please accept my apologies. I think a different approach may be necessary.

**Comment by j-hui** [comment]
@BjarniRunar , as in #1908 , i also have an nginx server already setup. Since it's just an HTTP server, is there any way to run it headlessly (without it trying to pop open the browser window etc.) so that I can proxy nginx over to it?

**Comment by BjarniRunar** [comment]
It won't try and open the browser if the DISPLAY environment variable is unset (it is usually unset on servers). I recommend running Mailpile in a screen session so you can connect to the CLI and work with it. For examples of how such sessions can be launched to automatically go to the background, grep the `contrib/mailpile-gui/mailpile-gui.py` script for the word `screen`.

**Comment by einicher** [comment]
I ran into this with Ubuntu 18.04 and repo right now. Since its Python i guess the problem is the apache proxy configuration?
