### ISSUE TITLE
Replace apache with caddy in multipile

### ISSUE THREAD

**Issue by fakeid30** [mailpile/Mailpile#1939]
If you replace apache2 with [caddy ](https://caddyserver.com/) that'll take care of ssl termination automatically, also HTTP/2 enabled by default, in future QUIC too. 

What is your opinion on this, @BjarniRunar ?

**Comment by BjarniRunar** [comment]
Replace, no. Add support for caddy? That would be cool.

**Comment by sachk** [comment]
What's the reason for using Apache aside from it being reliable and very popular?

**Comment by BjarniRunar** [comment]
@sachk Those are the reasons. It's reliable and very popular. :grin:
