### ISSUE TITLE
 Message not found?

### ISSUE THREAD

**Issue by cbz20** [mailpile/Mailpile#1944]
I have the following problem, which sounds similar to #972, but is probably unrelated, not least because #972 was opened over 3 years ago.

**Problem:** I have a message sitting in my draft folder, although it has definitely been sent. (I have checked, I can see it directly in the inbox of the mail server.) Furthermore, I get an error message when I try to open the message, see details below. The message is part of an email conversation and it appears in the left-hand column of that conversation. I can open all messages in that conversation except that latest one.

**Question 1:** How can I recover the message?
**Question 2:** What can I do to find out what caused this issue?

**Details:** I am running mailpile-apache2 on my Raspberry Pi (Raspian Stretch Lite) and was accessing it over the internet from work. I sent the email shortly before I shut down my laptop and went home, where I then noticed the issue. 

Here is the error message:
```
    Traceback (most recent call last):
      File ".../plugins/search.py", line 358, in _message
        msg = email.get_msg(pgpmime=False)
      File ".../mailutils/__init__.py", line 953, in get_msg
        raise IndexError(_('Message not found?'))
    IndexError: Message not found?
    
    Message MID = ATK
    Error = Message not found?
    Details = Failed to open message d3cf3d041f, message not found in mailbox.
    Data = [
     {
      "mail_desc": "message not found in mailbox", 
      "mail_key": "d3cf3d041f", 
      "mbox_desc": "Mailpile mailbox at .../default/mail", 
      "mbox_key": "0000", 
      "msg_ptr": "0000d3cf3d041f"
     }
    ]
```

**Comment by cbz20** [comment]
**Update:** The next day, mailpile did find the message, but kept the draft tag (even though I could no longer edit the message, as it was already sent). I have now removed the draft tag manually, so the message thread looks normal.

However, the two questions above remain.

**Comment by BjarniRunar** [comment]
There were bugs in Mailpile which would cause drafts to get deleted (replaced by newer content in a new filename), but the metadata index changes didn't get flushed to disk immediately. If Mailpile was then shut down hastily (or even normally depending on how unlucky you were), this could cause drafts to disappear. This was not an easily recoverable state.

The underlying bug has however been fixed.
