### ISSUE TITLE
Option to pick name for "X's mailpile" page title

### ISSUE THREAD

**Issue by lofidevops** [mailpile/Mailpile#1945]
**Steps to reproduce:**

* Add two email accounts called "Alice" (alice@example.com, alice@example.io)
* Add on email account called "Bob" (bob@example.com)

**What should happen:**

I can pick whether the page title is "Alice's mailpile v1.0.0rc1" or "Bob's mailpile v1.0.0rc1". (Or something else?)

**What happens instead:**

The page title is "Bob's mailpile v1.0.0rc1", with no way to change it.

**Comment by BjarniRunar** [comment]
Hmm, I think what you want is for the title to accurately reflect which account the user is looking at (if any), instead of just always saying the same thing? Good catch.
