### ISSUE TITLE
[ux] Better explain when "Missing key" is caused by a keychain delay

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1947]
I regularly get the "Missing key" message (#675) after starting Mailpile (for messages I could previously read, both to and from me). It turns out this is just a loading delay (#1370) and after a while the messages are readable again.

**Suggested solutions:**

* Would it be possible to provide a different message for this scenario? Something like "We are still syncing your keychain. Once we are done this message will be readable."
* Or, when logging in, keep the "loading" animation running until the keychain is synced.

**Comment by BjarniRunar** [comment]
Thank you for reporting this!

I am pretty sure this is not the same loading delay discussed in #1370, and I'm not sure what is going on here... can you describe (including the URL paths you visit) exactly the steps to reproduce this?

The only loading delay I can think of is the time it takes to load the VCards which include your profiles and the details of your accounts and keys. But I'm not sure you can access the UI at all until those have loaded, so I'm surprised. Are you directly hitting /in/inbox/ or directly loading a message after logging in again?

**Comment by kwill** [comment]
I've overhauled my system since reporting this, and haven't yet reinstalled Mailpile to check again. I'll close this, and if anyone experiences this issue again they can reopen/reference this ticket.
