### ISSUE TITLE
[query] Switching from mailpile to mailpile-apache2

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1949]
**Steps to reproduce:**
* Install mailpile package
* Set up and configure this (launching mailpile from the command line)
* Later, install mailpile-apache2
* Confirm apache2 service has started
* Open http://localhost/mailpile/
* Enter POSIX username and password

**What should happen:**
* Previously configured mailpile opens (preferable)
* OR a brand new mailpile opens and needs to be reconfigured

**What happens instead?**
* Loading screen appears
* After a while the following error message appears:

"Your Mailpile may not be running To launch the app please enter your account details above or use a terminal (ssh) to start Mailpile manually."

**Notes:**

* Starting mailpile from the command (as usual), closing the http://localhost:33411 browser tab and opening http://localhost/mailpile/ results in the same behaviour

Should I be able to switch like this? If not is there something I need to delete before switching (I don't mind reconfiguring my mailpile)?

**Comment by BjarniRunar** [comment]
This doesn't work well at the moment. Thanks for filing this issue to track it - I have been meaning to do another round of work on the Apache integration and this is part of it.

At the very least we need to document (in a discoverable place) how users can add their existing Mailpiles to the Apache setup.

**Comment by BjarniRunar** [comment]
I've reworked the Multipile stuff a bit, including making sure this is possible and documenting it. As long as the user only creates one Mailpile this way (avoiding port clashes), this should be relatively smooth sailing now.

**Comment by BjarniRunar** [comment]
Forgot to mention, docs are now here: https://github.com/mailpile/Mailpile/tree/master/shared-data/multipile
