### ISSUE TITLE
Subject line is always "Encrypted Message" (for recipients)

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1950]
**User story:** I don't use Mailpile but my friend does. When they send me an message I want to see the subject line, so I can distinguish between their messages.

**Steps to reproduce:**

* Send encrypted email from Mailpile
* Recipient opens Evolution (for example)
* Recipient receives email

**What should happen:**

* Subject line is visible

**What happens instead:**

* Subject is always "Encrypted Message"
* On opening, the original subject line is visible

**Notes / queries:**
* Mailpile handles this. Subject lines are visible in Mailpile.
* ~~I'm guessing the other email client needs to implement a PGP feature: what feature is it so I can add it to their issues list :) (and a relevant link would be great)~~ Memory hole (link below)
* ~~In the meantime, is it possible to disable this completely (or preferably selectively per recipient)?~~ #1953

**Comment by goatsi** [comment]
Sounds like [memory hole](https://github.com/autocrypt/memoryhole) is enabled.  [Here is an explanation of the mailpile implementation](https://github.com/mailpile/Mailpile/issues/156#issuecomment-279998595).

**Comment by kwill** [comment]
That seems to be it, thanks! Now just looking for a way to disable it...

**Comment by kwill** [comment]
#156 raises some usability concerns when dealing with a MUA that doesn't implement memory hole. Here's some more (new issues? or should I raise them at https://github.com/autocrypt/memoryhole/issues ?):

* Replies now have the header "Encrypted Message". When recipients respond to me (the Mailpile user), the new subject line is "Encrypted Message". I'm supposed to be annoying *them* with my crypto-wizardy!

* Unencrypted, unsigned replies still have the subject line "Encrypted Message". Now we can send unencrypted messages backwards and forwards believing them to be encrypted. Perhaps "No subject" would be better? (I considered "Embedded Message" but that's also false.)

**Comment by JocelynDelalande** [comment]
> Replies now have the header "Encrypted Message". When recipients respond to me (the Mailpile user), the new subject line is "Encrypted Message". I'm supposed to be annoying them with my crypto-wizardy!

Do not report it to memoryhole project, as current recommandations from memoryhole is *not* to enable it by default yet on outgoing messages.

> Unencrypted, unsigned replies still have the subject line "Encrypted Message". Now we can send unencrypted messages backwards and forwards believing them to be encrypted. Perhaps "No subject" would be better? (I considered "Embedded Message" but that's also false.)

The subject content is not supposed to be a guarantee of anything. Anyway you make a point, we could have something less confused like "Stripped subject". I wonder if the "Encrypted message" string usage is part of the memory hole standard.

**Comment by kwill** [comment]
Thanks for the info. Created #1953 and #1954 about those issues,
