### ISSUE TITLE
Snooze Feature like gmail

### ISSUE THREAD

**Issue by guettli** [mailpile/Mailpile#1951]
It would be great, if you could "snooze" mails in your inbox.

Gmail has this feature: https://support.google.com/inbox/answer/6067583?hl=en

Without this, I would not be able too clean my inbox regularly.

With the ability to move mails away for some days I can keep my inbox (which is my todo-list) clean.

Are there any plans to support this?

**Comment by guettli** [comment]
How could this be implemented?

**Comment by BjarniRunar** [comment]
This can be implemented by the user today, using tag automation. Like so:

1. Create a new tag and open for editing
2. Under "Technical Settings", tick "Display in toolbar" and "Behave as category"
3. Under "Tag Settings", choose a nice icon and color so you recognize it in the toolbar
4. Under "Automation", under "Untagging", select the time you prefer and "Move to Inbox" as an action

Does that do what you want?

**Comment by imthenachoman** [comment]
Is there documentation or screenshots showing what options there are under Automation? I don't have Mailpile installed and I want to make sure it does what I'm looking for before I go through all the motions to install it.

**Comment by BjarniRunar** [comment]
@imthenachoman No. We need this, but we don't have it yet. Sorry.

**Comment by guettli** [comment]
Since I can't code this. Is there a way to pay someone to implement an easy to use snooze feature?

**Comment by BjarniRunar** [comment]
@guettli Might I suggest you actually try the software before trying to hire someone to change it? I posted a recipe (that uses existing features and the existing UI - no new code required) for doing what you want above. Maybe the recipe isn't good enough, but you won't know until you try.

**Comment by BjarniRunar** [comment]
Oh sorry, I confused your comments with @imthenachoman 's statement that he hadn't installed the software. Have you installed it? Did you try my suggestion?
