### ISSUE TITLE
[query] Can I disable memory hole?

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1953]
[Memory hole](#156) is a great idea, but I am currently experiencing too many UX issues when interacting with non-Mailpile users. Can I disable it?

I already have "Minimize metadata (may make mail unreadable)" unticked.

**Comment by BjarniRunar** [comment]
Sorry about the late reply.

At the `mailpile>` prompt, type: `set prefs.encrypt_subject = false`

That doesn't disable memory hole (which will still protect key headers with a signature), but it does disable the subject hiding which I think is what is bugging you the most.
