### ISSUE TITLE
Mailbox corruption

### ISSUE THREAD

**Issue by GitHubGeek** [mailpile/Mailpile#1955]
Hello Team Mailpile!

Would like some help with repairing the mailboxes. All messages are inaccessible with an error like this:

```
Message not found?

Failed to load and parse message data. Message may be corrupt!

Traceback (most recent call last):
  File "/home/githubgeek/Mailpile/mailpile/plugins/search.py", line 358, in _message
    msg = email.get_msg(pgpmime=False)
  File "/home/githubgeek/Mailpile/mailpile/mailutils/__init__.py", line 953, in get_msg
    raise IndexError(_('Message not found?'))
IndexError: Message not found?

Message MID = 53H
Error = Message not found?
Details = Failed to load and parse message data. Message may be corrupt!
Data = []
```

This happened after I mass-deleted a few hundred messages. New messages are not affected.

Is there a way to repair the mailboxes?

Also, getting a weird error during login:

```
Traceback (most recent call last):
  File "/home/githubgeek/Mailpile/mailpile/plugins/__init__.py", line 206, in _load
    self._import(full_name, path)
  File "/home/githubgeek/Mailpile/mailpile/plugins/__init__.py", line 176, in _import
    exec mfd.read() in sys.modules[full_name].__dict__
  File "<string>", line 10, in <module>
ImportError: cannot import name Quit
FIXME: Loading mailpile.plugins.gui failed, tell user!
```

Your help is greatly appreciated!

**Comment by RISHAV98** [comment]
Is there any Databases error that lead to Mail corruption

**Comment by BjarniRunar** [comment]
Hi @GitHubGeek! Sorry about the late reply.

Mailpile should rebuild it's internal idea of the mailbox automatically at some point. I assume these are mbox files? Deletion doesn't currently trigger the rebuild as it should, unfortunately. But by now, since it took me so long to reply it should have recovered already.

If not you can help Mailpile detect it needs to rebuild by running "touch /path/to/file.mbx" in a shell and then "rescan sources" from the Mailpile CLI.

Let me know!

**Comment by GitHubGeek** [comment]
Hi guys,

Appreciate the replies. I'm using `~/Maildir/` for incoming mails. Mailpile didn't seem to rebuild the old mails.

The mass-delete took a very long time to run. Pretty sure I gave it time to run and didn't kill the mailpile process

Would `rescan sources` rescan the 10k+ old mails some of them several years old? Thanks.

**Comment by BjarniRunar** [comment]
Hi! Happy New Year to you too!

Interesting, from your description of the problem I expected you were using mbox - I am not sure how this happens with a Maildir.

Rescan sources just triggers a rescan, Mailpile has internal logic which will try to save time and not re-index a message it has already seen. So it shouldn't take forever. But I'm not sure it will help in this case - my previous message assumed mbox. Hmm.

**Comment by GitHubGeek** [comment]
Is there a way to delete the existing database / indexes and then re-read all messages?
