### ISSUE TITLE
How are translations integrated  ?

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1957]
https://github.com/mailpile/Mailpile/wiki/Translations

Says 

> Most of the translation work is happening on Transifex, at https://www.transifex.com/otf/mailpile/

But I don't get how and when hose translations get integrated into mailpile.

Any hints ?

**Comment by BotQ** [comment]
Translations get integrated into Mailpile by Transifex client. In the Makefile file there is a command to download all the translation which are made in minimum 50 percent.
`tx pull -a --minimum-perc=50`
After it all the translations are stored in shared-data/locale. But to let specific language appear in setup list you have to type command (in folder with specific language, for example shared-data/pl/LC_MESSAGES):
`msgfmt -o mailpile.mo mailpile.po`
This will 'compile' language file to binary file that Mailpile uses.

**Comment by JocelynDelalande** [comment]
@BotQ Thanks for your explanations, it led me to write some documentation on how to use translations:

https://github.com/mailpile/Mailpile/wiki/Translations

**Comment by JocelynDelalande** [comment]
FYI something was broken, in auto-importing of the .pot in TX and is now back functioning :)

See https://www.transifex.com/otf/mailpile/announcements/8103/

Thanks @BjarniRunar
