### ISSUE TITLE
Web browser is not launched under wayland

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1961]
Using wayland (Debian/Gnome 3), when I run `./mp` command, the browser does not fire up like when using xorg. I get the following error instead :

> Unable to init server: Impossible de se connecter : Connexion refusée          
> Error: cannot open display: :1

(not sure it's mp's fault, but anyway, here is the result :-)

**Comment by BjarniRunar** [comment]
This is not Mailpile's fault. We're using the Python webbrowser module, if it doesn't work then that's the fault of the distro breaking things.

But I'm leaving this open anyway, as we will probably want to work around this somehow anyway.
