### ISSUE TITLE
Improve Windows installer build script

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1967]
## **Updated Windows Installer - Notes**

PR #1966 updates the Windows installer packaging code from the Beta release.

I wanted a fast and automatic method to makes mods to Mailpile on Debian and test them on Windows. That project took on a life of its own. Bjarni Runar mentioned the need for Windows packaging in his 2017-01-30 blog post, so this is a start. It seems to mostly work but with some rough edges, so the purpose of the PR is to let others test and comment.

An installer and source archive, built with this code, is posted at https://cyberspirit.dyndns.org/mailpile.  The resulting Windows install should be treated as possibly unreliable for now!!! But hopefully others will try it and makes suggestions. Again, treat with caution!

The SHA256 checksum of the above mentioned installer Mailpile-0.99.1++-Installer.exe is
982b243e44cb49c1715237e94f01c6791503260d66c1a33554137fa08b1f92f9

The SHA256 checksum for the recently added Mailpile-v1.0.0rc2-Installer.exe is
7dbb6c2dec19719edbfeec966669c3b5e189e161e73cb497ebad0135808d0d9b
[edited 2018-02-16]

The SHA256 checksum for Mailpile-0.99.2~processlockfix201803091151-Installer.exe (added 2018-03-09) is 
699e3c4dab8a44876168ab4437a3ac72eb71f412431ffe05ccb792dce94b0a04
This is commit b0a5051 dated 2018-03-06 from master (not long after 1.0.0rc2), but with PR #2016 merged into it.
[edited 2018-03-08]

### Goals and comments

The goal is to save developers work in the future by making the creation of a Windows installer a one-step process, including creation of a source code archive that can be posted to meet copyleft licence requirements and provide traceability back to authenticated source code for security purposes. For Windows, it is necessary to include all the third party code (e.g. Python, GnuPG and OpenSSL) in the installer. So, the script downloads specified versions of the third party package source from their "official" project websites and automatically cross-builds them on Debian using the projects' own build procedures. Note that OpenSSL does not publish "official" binaries at all, so building from source is inescapable. Python is not built from source - the python.org distro is considered authoritative and secure. Wasted download/rebuild time is avoided by saving third party package build results for subsequent installer builds.

If a new version of either Mailpile or a third party package is wanted, just a few configuration strings at the start of the packages/windows/repackage-linux.sh script need to be changed. That assumes that upstream does not change the build _procedure_ for a package.

To eliminate the need for hacking the Python package installs, this installer includes the Python .MSI installer and runs it on the target computer (an "administrative install" that does not set Start menu items and registry variables so it is unknown except to Mailpile). For additional Python packages, the Python distribution files are included in the installer, then installed by pip.

There are still some rough edges:
- In testing the Windows installation it appears that when Mailpile is stopped, its state is sometimes not fully captured. e.g. a recently received email will disappear and will have to be downloaded a second time from the IMAP server when Mailpile is started again.
- It's not clear to me that the GnuPG Windows integration is done right. e.g. you can't explicitly import a key that a Mailpile on another machine has attached because it is wrapped in HTML so the browser wants to open it in another Firefox window; and the way I've installed GnuPG, there could be some additonal problems.
- The installer should be signed so that casual users aren't presented with a scary "Do you want to allow the following program from an unknown publisher to make changes to this computer" message. Mailpile ehf could invest in an Authenticode code signing certificate. The cheapest I've seen is US$72/year at https://cheapsslsecurity.com/comodo/codesigningcertificate.html
- It's not clear that pip does file integrity checking (other than https) when downloading packages. The GnuPG builder downloads 3rd party source archives from gnupg.org, and it's not clear that it does file integrity checking. Also, Python uses MD5 and gnupg.org uses SHA1, which is not up to current standards.
- When the installer run pip to install Python packages, Windows command windows pop up. It would  be better if the messages from pip could be redirected to the installer window.
- Internet Explorer on Win7 does not render Mailpile correctly because it defaults to a legacy rendering engine. It needs the Edge engine. (This can be corrected with changes to the headers served to the browser by Mailpile.) Workaround: use Firefox. Win10 renders Mailpile OK.
- SpamBayes and GnuPG directories are created in C:/Users/user/AppData/Roaming. It would be preferable to keep all the 3rd party package data files in the Mailpile user's directory.
- MailpileLauncher apparently must be built using Microsoft Visual Studio. It would be preferable to develop a version that can be built with free (as in speech) software tools.
- The installer is bloated (41 MB), in part because the complete binary packages of GnuPG and OpenSSL are included in the installer, though Mailpile only uses a subset.

The installer has been minimally tested on Windows 7 and 10 virtual machines. The installer build script has been tested on Debian Stretch.

### Executive summary

The script `repackage-linux.sh` can rebuild the Mailpile installer for
Windows when run on Gnu-Linux. Run it, yay!

repackage-linux.sh [--local] [_branch_]

 --local causes the Mailpile code that is packaged to be cloned from the local
        git repository from which the repackage-linux.sh script was checked
        out. Default is to clone from https://github.com/mailpile/Mailpile.git.
        
 _branch_ is the branch of the Mailpile git repository that will be checked out.
        The default is "master".

 ... or read on to learn about bits and pieces.
 
### Windows details

When run, the installer creates a start menu section Mailpile with entries
     Open Mailpile
     Start Mailpile
     Uninstall Mailpile
     
When Mailpile is run, it creates a System Tray icon. Right-clicking on that
icon pops up a menu with entries
    Open Mailpile
    Donate
    Debug
    Quit

### What it builds and where

It builds the Windows installer in /tmp/mailpile-winbuild. In addition, the
installed image, a collection of source archive files and (if third party
packages are rebuilt) the build directories for the third party packages are
left in /tmp/mailpile-winbuild.

The specific archives to be used in building the installer are configured by
shell variable settings at the beginning of the script. As new versions of
third party packages are released by the upstream developers, these can be
modified (or not) as required.

A complete build takes 15 minutes on my 2011 vintage AMD 8 core 2.8 GHz system.

### Mailpile code

The Mailpile code is checked out from either the local repository or github.

An archive of the Mailpile code image, identified by its commit id, is saved in
 /tmp/mailpile-winbuild/SourceArchive.

### Python

The Python Windows (.msi) installer and package files for all needed Python 
modules are downloaded from python.org to PythonDistFiles in the local git
working copy, then PythonDistFiles is copied to the install image. The Python
installer and pip are run on the target Windows computer to install all the
needed Python code. Subsequent builds in the same git working copy use the 
already downloaded files.

    Caution: The file requirements-with-deps.txt must list all the Python
            packages that will be required including indirect dependencies. 
            That file must be committed - the version used is the one checked 
            out from the repository.
            
    Note: After installing on Windows, check the file 
            C:\Program Files (x86)\Mailpile ehf\Mailpile\Python27\check.txt .
            to determine if any dependencies are missing. Also the pip log
            can be checked if there are problems. It is saved at
            C:\Program Files (x86)\Mailpile ehf\Mailpile\Python27\install.txt .
            
### Other third party packages

Third party packages (e.g. GnuPG, OpenSSL) are built from source archives
downloaded from each project's home web site to SourceArchive in the local git
working copy, using the unique build system of each project. The packages are
built in subdirectories of /tmp/mailpile-winbuild. Once built, needed files are
copied to subdirectories of the script directory (e.g. packages/windows/GnuPG).
Those subdirectories are then copied to the install image. The SourceArchive
directory is copied to /tmp/mailpile-winbuild so that all the source is
available to publish for licence compliance purposes.

Subsequent builds will use the needed files stored in the script directory so
avoid unnecessary rebuilding of the third party packages.

The MailpileLauncher package is downloaded in binary form from
https://www.mailpile.is/files/build/MailpileLauncher.zip
It appears to require MS Visual Studio to build. Possibly in the future
a free version could be substituted.

### File integrity

Some downloaded files are checked for integrity against checksums hardcoded
into the script. This includes the Python installer, GnuPG and OpenPG.

**Comment by BjarniRunar** [comment]
Wow. So sorry I haven't responded to this, but I always want to review and understand things and I just haven't had the time. I still haven't had time to do a deep dive, but this looks fantastic. As it doesn't appear to touch much outside the Windows packager, I'm going to merge it without a full review. I think it's a clear improvement either way.

**Comment by JackDca** [comment]
Thanks for merging this! No apology necessary, I knew that an updated Windows Installer was near the end of your schedule of preparations for 1.0, so didn't expect quick action. Hope it lives up to your positive comments and in any case, reports from others would be most welcome.

**Comment by BjarniRunar** [comment]
Note: this issue will be the starting point for packaging efforts by the "Mailpile Windows Person", assuming we manage to hire one (<https://www.mailpile.is/jobs/>). @JackDca, I just want to encourage you to apply for that position if you are at all interested!

**Comment by JackDca** [comment]
The SHA256 checksum listed in the first post of this issue is for
https://cyberspirit.dyndns.org/mailpile/Mailpile-0.99.1++-Installer.exe and it is
982b243e44cb49c1715237e94f01c6791503260d66c1a33554137fa08b1f92f9

The SHA256 checksum for the recently added
https://cyberspirit.dyndns.org/mailpile/Mailpile-v1.0.0rc2-Installer.exe is
7dbb6c2dec19719edbfeec966669c3b5e189e161e73cb497ebad0135808d0d9b

**Comment by JackDca** [comment]
As noted above, "Internet Explorer on Win7 does not render Mailpile correctly because it defaults to a legacy rendering engine. It needs the Edge engine. (This can be corrected with changes to the headers served to the browser by Mailpile.)"

My HTML skills are non-existent. I believe that the correct header is:
` <meta http-equiv="X-UA-Compatible" content="IE=Edge" />`
but someone more qualified than I should
- determine this is the correct header
- determine it won't affect rendering in Chrome or Firefox, which already work fine.
- make the needed update to mailpile/httpd.py

The (completely unrelated) issue #2006 makes reference to adding to the standard HTML headers served by Mailpile - perhaps this change could be piggybacked on that one.

Given the necessary code updates I can test the effect on Win7 - IE8.

**Comment by JackDca** [comment]
More on Windows7 IE8 issue.

I've tested the current master on Windows7 with Internet Explorer 8. This includes the change to add the X-UA-Compatible IE=Edge header (BjarniRunar's commit fabf8fb, httpd.py line 183 - thanks!). The rendering is still incorrect :(

The UI is partially functional, but the icons don't render at all, and some buttons (e.g. the ones in Settings and Tools) don't respond when clicked.

To do the test I ran a new Mailpile using Firefox for the UI and used it to create one profile that connected to a test gmail account. Then I logged out from the Firefox session and connected with IE8. I logged in successfully and went to Inbox successfully. A screen capture and a copy of the Mailpile console output is attached.
![mp-ie-v1 0 0rc2](https://user-images.githubusercontent.com/15818803/37104773-8ba01864-21fb-11e8-99a3-bcfda14bdd40.png)
[MP-IE-v1.0.0RC2+.txt](https://github.com/mailpile/Mailpile/files/1789965/MP-IE-v1.0.0RC2.txt)

**Comment by BjarniRunar** [comment]
Regarding IE8 - I am not sure we care, here. If I understand the Internet correctly, Microsoft are no longer providing support for it. That means it's no longer getting security updates and should be considered insecure. Arguably, the right thing to do if we detect IE8 would be to refuse to run and tell the user to install a properly maintained browser. Yes? No?

**Comment by BjarniRunar** [comment]
AFAICT Firefox is available for Windows 7. Is Chrome as well? If people are downloading Mailpile, they can also download a decent browser. This isn't really a barrier IMO - or at least, it's not a barrier that the user hasn't already proven they can and are willing to surmount!

I agree it would be excessive to block the UI from working in IE8, but displaying a warning and encouraging the user to download something more modern would still be appropriate. Spending time on getting IE8 to work well seems much less appropriate. However, I will raise this with our newly hired Windows guy (Alex!) and see if he also wants to convince me otherwise. :+1:

**Comment by JackDca** [comment]
Agreed on all points. IE8 support is only worth doing if it is very easy.

Excellent that Mailpile has a Windows guy now. Go, Alex, go!

**Comment by JackDca** [comment]
Of course it is a waste of resources to maintain two build systems.

But, one request. At present it [appears](https://www.mailpile.is/download/&) that mailpile.is does not have Windows packages available for download. This means that, in order to test Mailpile's Windows installer, the user must set up the Windows build system on a Windows machine (not a trivial effort) and build the installer themself. I suspect that few users have done that, which means that the Windows installer is getting little or no beta testing. Beta testing is especially important under Windows since there is a wide range of Windows versions in use and because Windows does not have a global package management system. ([One source](https://www.techrepublic.com/article/windows-10-hits-dramatic-market-share-drop-as-windows-7-use-increases/) reports that Windows 7 still has 40% market share!)

For the old Linux-built Windows installer, I posted an installer on the web myself. I think a few people tried it - not a lot, but still valuable testing. How about providing a test version (better still, a nightly build) on mailpile.is so the builder gets some mileage before 1.0?

**Comment by BjarniRunar** [comment]
Absolutely agreed, this has been near the top of my TODO list for a while - I'm making an automated build robot for Windows and the Mac, just like we currently have for Debian packages. This should happen quite soon; I've got a blog post drafted that should explain in further detail. It should go public either later today or Saturday.
