### ISSUE TITLE
can't add directory starting with a dot

### ISSUE THREAD

**Issue by marcb1** [mailpile/Mailpile#1969]
I use getmail to fetch pop3 e-mails, which are downloaded to a directory that starts with dot.
i.e /home/marc/.getmail/mail/gmail

> ls /home/marc/.getmail/mail/gmail
> cur/  new/  tmp/
> 

When I use the browse tool, to browse my e-mails in MailPile I am unable to locate any folders that start with a dot.

Is there a way to view my e-mails in Mailpile?

**Comment by BjarniRunar** [comment]
In the browse tool, you may be able to just hand-edit the path in the URL. Does that work?

Alternately, you can create a symlink which has a non-dot name that Mailpile can then see and work with.

**Comment by marcb1** [comment]
hand editing the path works, thanks.
