### ISSUE TITLE
Bad data error, when trying to log in

### ISSUE THREAD

**Issue by steelstrings** [mailpile/Mailpile#1972]
I upgraded my Fedora system from version 25 to 27 and after that a user on my system can't get past the logging in animation anymore. After entering the passphrase, mailpile expels this error message:

```
Traceback (most recent call last):
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 195, in run
    self._copy_loop()
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 182, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 819, in _read_data
    return process(None)
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 809, in process
    % self.name)
IOError: EventLog/DS(5a148f61-0001d-3815): Bad data, failed to decode
Traceback (most recent call last):
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 195, in run
    self._copy_loop()
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 182, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 819, in _read_data
    return process(None)
  File "/home/karlwalch/Packages/mailpile_latest/Mailpile/mailpile/crypto/streamer.py", line 809, in process
    % self.name)
IOError: EventLog/DS(5a171d08-0001d-2f36): Bad data, failed to decode
```

Followed by an infinite login animation, it basically hangs there. It doesn't even shut down with `<Ctrl>+<D>` or `<Ctrl>+<C>`.
Whereas I haven't got a problem with mailpile on my user account and it's working properly.
Tested with the release version 1.0 and the most recent from the master branch.

**Comment by BjarniRunar** [comment]
These error messages are harmless.

Something else is going on here if the user is unable to log in and use Mailpile. I have however had another report from a friend, of similar problems after a recent upgrade and will be exploring with him during the next few days - he can give me access to the raw data, which makes a huge difference when debugging such things. Stay tuned!

**Comment by BjarniRunar** [comment]
Sorry about the slow response. My friend's difficulty turned out to be caused by NoScript and Firefox upgrades. Could that be the case here as well?

**Comment by BjarniRunar** [comment]
(Basically, NoScript rules needed to be reminded to allow Mailpile traffic)

**Comment by steelstrings** [comment]
I'm getting the error `Corrupt data in metadata index! Trying to cope...` when trying to login in, on the mailpile command line, with the most recent version.

**Comment by BjarniRunar** [comment]
@steelstrings That on the other hand can be indicative of a more serious problem. This shouldn't happen unless Mailpile is shutdown uncleanly (machine powered off, kill -9) or you are experiencing disk corruption.

If it's only the metadata index that is corrupted, then Mailpile should recover and should let you log on anyway, but you may have lost some of your metadata and Mailpile will need to rediscover those messages and you will need to retag them.

**Comment by steelstrings** [comment]
How can mailpile rediscover those messages?

And how am I going to retag them?

**Comment by BjarniRunar** [comment]
The messages aren't lost, just the metadata about them is. Unless you experienced more disk corruption than you reported above.

When Mailpile re-scans the mailboxes that contain them (which it does every few minutes), it will rediscover the messages as if they were new.

You re-tag them the same way you tagged them in the first place, by hand - unless they were autotagged or filtered, in which case that should again happen automatically, since to Mailpile they are effectively new messages.

**Comment by steelstrings** [comment]
No login doesn't work, it basically hangs and does seemingly nothing.

So I can't even rescan messages manually.

What I didn't mention before is, that the system upgrade didn't went well, so I skipped a version. Can't say for sure if data corruption happened though.

So this basically means this configuration is broken?

Thanks for your help anyways.

**Comment by BjarniRunar** [comment]
@steelstrings, there may be more than one thing going on here. I would be curious what happens if you just use the CLI only and just run these commands:

1. mailpile> login (type in your password)
2. mailpile> search (enter)

If 1 completes and 2 shows mail, then the fact that you aren't able to log in to the web interface suggests a problem with your browser.  If 1 never completes, or 2 shows no mail, then yes, it sounds like things are badly broken.

**Comment by steelstrings** [comment]
Yes it never completes on command line too!

That's one of the reasons I haven't been able to rescan messages manually.

**Comment by BjarniRunar** [comment]
Sadly, that does sound like things are hopelessly broken. I don't have any suggestions here that wouldn't involve giving me access to your machine (or at least the data) to poke around and explore. Since e-mail tends to be rather sensitive data I don't think that's realistic. I'm sorry :(

**Comment by steelstrings** [comment]
Well, I reconfigured my mailpile install two weeks ago. But thanks for your help anyways.
