### ISSUE TITLE
Mailpile forgets data on system restart

### ISSUE THREAD

**Issue by cbz20** [mailpile/Mailpile#1973]
I am testing mailpile on a raspberry pi (raspian stretch lite) via apache. 

**Steps to reproduce the bug:**
1) Start mailpile
2) Write an email, send it and wait until it has left the outbox
3) Log out
4) Reboot the system
5) Restart mailpile

**Result:** Mailpile has forgotten all changes since the previous fresh start. (In this example, it is just a single email; however, the above has happened to me already several times and I lost a week worth of emails. Luckily, mailpile could simply refetch them from the servers, so no harm done; just annoying, as I had to sort them again.)

**Random toughts:** I have noticed that mailpile does not stop running when I log out. (This seems counter-intuitive to me, since the logout button looks like a switch off button.) If I tell mailpile to quit via the mailpile terminal ("t") in the browser, the problem above does not occur.  

So maybe, as a temporary solution, one could add a quit button to the logout screen, with a message that one should not restart the system until mailpile has stopped running. However, I do not really understand why mailpile just forgets data. I can **reproduce the same error** as above even if I call "cleanup" before step 3. Mailpile still forgets the email it just sent.

**Comment by BjarniRunar** [comment]
If you are uncleanly shutting down your computer, you can expect all sorts of data loss. If you perform a clean shutdown Mailpile should get a kill signal which will instruct it to save to disk and shutdown cleanly... should. :)

**Comment by cbz20** [comment]
I am shutting down via "sudo shutdown -r now". Isn't this what one is supposed to do?

**Comment by cbz20** [comment]
@BjarniRunar: I disagree with your comment about data loss and other applications. E.g. if I modify a text document in any decent text editor and press "save", changes are written to the disk immediately, so I am always able to recover that version of the document, even after an unclean shutdown. 

Admittedly, mailpile is a bit more than just a text editor :-), but I would expect a similar behaviour: Once I have finished modifying an email (saved a draft, sent an email, downloaded an email from the server, etc.), I would expect mailpile to save these changes to the disk. But apparently that does not happen. (Or maybe it does, but something else fails.) 

We had a power cut this morning, and again, emails that I had sent since the previous startup had disappeared. I consider this a serious bug, as power cuts do happen from time to time. 

So I guess, there are two slightly different issues here: 
- Avoid **any** data loss on clean shutdown ("sudo shutdown -r now")
- Minimize data loss on unclean shutdown (e.g. power cut)

I currently do not understand how mailpile stores data and I am unable to find this in the wiki. Could you point me to where I can learn about this? I am happy to do some further testing.

**Comment by BjarniRunar** [comment]
Mailpile does write things to disk almost constantly, and it does save to disk in all the cases you have described. I am not entirely sure what is going on here.

**Comment by cbz20** [comment]
Ok, thank you, that is reassuring! 

I have made a few more tests, varying step 2 in my first post:
- Step 2': Save a draft. 
- Step 2'': Change mailbox configuration (e.g. change outgoing server name)

My conclusions: Mailpile remembers changes to the mailbox configuration. However, mailpile forgets drafts like sent messages. While sent messages reappear after a while in the inbox (albeit as new/unread and without the "sent" tag), drafts do not reappear. Furthermore, sent messages do not reappear, if the mailbox has been disabled (by changing the server name). So I guess this means that mailpile simply finds sent messages on the mail server and downloads them. 

Can other people reproduce the issue?

**Comment by BjarniRunar** [comment]
I found, and fixed, bugs that may have been causing these problems. I would be interested to know whether you can still reproduce the problem. Thank you again for reporting this, it took a few reports for me to realize what was going on...

**Comment by cbz20** [comment]
Thanks a lot! I have not been able to reproduce the issue after upgrading to rc2. 

However, I did experience one minor data loss similar to the one above under rc2. Only, I do not know if it was actually related to the issue above, as I have not managed to reproduce it. Did you fix those bugs before or after rc2? I would be interested to know what those bugs were that you have found.

**Comment by BjarniRunar** [comment]
Saving drafts wasn't correctly triggering a save of the related metadata. So unless you did something else that triggered a metadata save, you could end up losing drafts if there was an unclean shutdown (of Mailpile). I'm going to close this issue, as it sounds like it's been resolved. Please feel free to reopen or open a new one if you find more problems.

Thanks for your help on this!
