### ISSUE TITLE
Sidebar subtags not displaying for IMAP email generated tag

### ISSUE THREAD

**Issue by eauchat** [mailpile/Mailpile#1979]
I just installed Mailpile 1.0 and configured my email using IMAP, there are many folders in my account. At first the folders appeared as subtags under the main tag of that email address, then they disappeared. I looked in the tags settings, and here are all the folders, listed as subtags, "Show in sidebar" is ticked for all of them, and for the parent email box.

If I change the parent folder to "none" or another tag, then they are properly displayed under that other tag.
However, they never show if the parent is that email address's tag.

**Comment by BjarniRunar** [comment]
Is the tag just collapsed? Sounds like you may be experiencing #1875. 

You didn't say how you installed, but if you are using the Debian package then you're going to have to wait until I build and push updated packages. I'm thinking I should do that soon.

**Comment by eauchat** [comment]
Yes, it seems like it could be same issue than #1875. Sorry I hadn't seen it before posting this issue.
I'll confirm that it's solved after I get the next Debian package update.

**Comment by BjarniRunar** [comment]
I'm going to assume this is fixed. :)

**Comment by eauchat** [comment]
After updating just now, I confirm it's fixed :)
