### ISSUE TITLE
intrusive message from transifex.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1980]
Here is an email I received from transifex (I guess it is an automatic one).

I think this is intrusive (I don't want to fill a google doc) and misbehaving (an explicit form of the data vs service usual GAFAM blackmail).

I specially dislike the « If you do not respond to the following questionnaire or this email, we will not add you to the translation team ». (which is odd because I already started to translate strings in MP).

So, is it a phishing of some form or is this real ?

If this is real, is it decided by mailpile comunity or transifex ?

If this comes from mailpile community, I suggest we stop doing that.

```
Subject: French language coordinator sent you a message on Transifex
From: Transifex Notifications <notifications@transifex.com>
Date: Thu, 21 Dec 2017 20:37:59 -0000
'French language coordinator'[1] sent you a message

'French language coordinator'[1] said:

## Mailpile

Hello,

Thank you for your interest in joining the Mailpile French team and the Localization Lab community! The Localization Lab is a global community of volunteer translators who support the translation and localization of Internet freedom tools like the one you’ve requested to contribute to. To learn more about our work and the projects we support, visit localizationlab.org.

Before you begin translating, we would like to know more about you so that we can best integrate your efforts into the project and community. ***If you do not respond to the following questionnaire or this email, we will not add you to the translation team*** When you have a moment, please fill out the following Contributor Questionnaire and read through the Contributor Roles &amp; Guidelines. Once you have filled the questionnaire, your request will be taken in consideration.

Contributor Questionnaire:
https://docs.google.com/forms/d/e/1FA...

Contributor Roles &amp; Guidelines :
http://www.localizationlab.org/roles-...
You need to familiarize yourself with our roles and guidelines before contributing.

Meet the Projects!
A complete list of the Internet freedom tools and training materials that we support is available here : https://www.transifex.com/otf/public/.

Join the Discussion!
There are several ways for you to keep in touch with Localization Lab staff, the developers and project managers of the tools you translate, as well as fellow translators and activists. Please feel free to use any of the following methods to pose questions, begin discussion or request assistance related to localization and all things Internet freedom.

- Mattermost: internetfreedomfestival.org/... (Join the Localization Lab channel after signing up)
- Google Group and Mailing List: https://groups.google.com/forum/#!for...
- IRC Channel: https://kiwiirc.com/client/irc.freeno...
- Email: french.coordinator@rbox.me

Welcome, and thank you again for your interest in contributing to the Localization Lab projects!

Best Regards,

Alain-Olivier
French language coordinator
localizationlab.org |transifex.com/organization/otf

[ Reply https://www.transifex.com/user/messag... ]

[1] https://www.transifex.com/user/profil...
```

**Comment by BjarniRunar** [comment]
Pretty sure this is real.

> If this is real, is it decided by mailpile comunity or transifex ?

Neither, this is from the OTF Localization Lab, which Mailpile is part of. The benefit we (supposedly) get is they do some coordination stuff and promotion to encourage folks to translate Mailpile (and other Localization Lab projects). Obviously that turns sour if they scare a lot of people off with things like this, but I suspect you're being a little more sensitive than most right now.

I have a fair bit of sympathy with the plight of non-technical coordinators trying to do their job here - I don't think use of a Google Docs survey is entirely unreasonable in this case. There aren't a lot of tools out there that are better fits for this sort of thing.

**Comment by JocelynDelalande** [comment]
Thanks for the information.

> I have a fair bit of sympathy with the plight of non-technical coordinators trying to do their job here - I don't think use of a Google Docs survey is entirely unreasonable in this case. There aren't a lot of tools out there that are better fits for this sort of thing.

Those are two fair points. (sadly for gdocs alternatives, but that is not our topic right here).

But still, « we won't let you in if you don't fill the google form » is realy bad :-/.

**Comment by BjarniRunar** [comment]
Thanks for bringing this to my attention.

I'm closing this as a "WONTFIX" - I don't feel strongly enough about this one way or another to complain to the people responsible. :-)

**Comment by d9h20f** [comment]
@JocelynDelalande you can always reply to the message saying you can't subject yourself to Google but are willing to answer any important questions the Localization Lab might have. I don't think filling in the document is really required.
