### ISSUE TITLE
No signature on first email sent to new address.

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1982]
It appears that the first email sent to a previously unknown email address is not signed, even though the green check icon in the lower right of the compose window is present and "Always digitally sign outgoing mail" is selected for the sending email address.

The next email sent to the same receiving email address is properly signed.

I've confirmed this with my regular "production" Mailpile setup using commit 072b9d1 from 2017-09-14 and with a development version which is commit d4eec099 plus some experimental mods which should not affect crypto (they are in PR1976). Attached two raw emails from the development version tests.

[SigningBug2018-01-10.txt](https://github.com/mailpile/Mailpile/files/1620108/SigningBug2018-01-10.txt)

**Comment by BjarniRunar** [comment]
Thank you for filing this! This is very strange.

Can you tell me what the security settings are for that account?

**Comment by BjarniRunar** [comment]
I can confirm I have reproduced this. Still investigating.

**Comment by JackDca** [comment]
Not sure if you still need the security settings. They are essentially the defaults. I've dumped mailpile.cfg and attached it. This is a test account so there should be nothing sensitive in it but just to be sure I've edited out anything that looks like a secret.

[mailpile.cfg.txt](https://github.com/mailpile/Mailpile/files/1623166/mailpile.cfg.txt)
