### ISSUE TITLE
sidebar unread message counts are not updated on new email

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1987]
## Expected behavior

When a new email arrive (from IMAP source) inside a sidebar « folder », the message count is udpated.

## Current behavior

When a new email arrive inside a sidebar « folder », the message count is not udpated, even when clicking links (switching to other search views or individual message views).

## Workaround

Manually refresh the whole page (F5), the unread message counts gets updated.

## Hints

It seems that the ajax-stuff is not made in a way that updates the sidebar unread counts.

**Comment by BjarniRunar** [comment]
It does update, but only eventually. Something is missing in the internal cache invalidation logic to more promptly recognize that the data needs updating.
