### ISSUE TITLE
Command browse_or_launch is obsolete, should be removed

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1993]
The idea of the browse_or_launch command appears to be to check if another Mailpile is running on the same pile; if not, then launch this Mailpile normally; if so, then start the OS's browser (to allow the user to interact with the other Mailpile) and terminate this Mailpile.

This is important, especially if as per #877 there are multiple Mailpile data sets ("piles") and/or processes on one machine and/or if port numbers are assigned randomly, since the user may not know the port number in any of those situations.

Processlock PR #1976 breaks browse_or_launch since running two Mailpiles on one pile will cause immediate termination of the second Mailpile when it detects that the pile is already locked, before reading the configuration files, so it can't start the browser.

However it appears that browse_or_launch was already broken before PR #1976. The attached file shows results in three different situations, and the browser is not started in any of them.

A decision should be made as to whether to just abandon or fix browse_or_launch.

Fixing it involves some complications since it implies that, even with the pile locked by another process, Mailpile would have to read the public configuration file mailpile.rc to determine the port on which to launch the browser.  PR #1976 does anticipate another process reading the mailpile.rc, but allowing the second Mailpile to continue executing to read it and start the browser, while guaranteeing that it does not write anything to the pile, is not straightforward.

[BrowseOrLaunchLog.txt](https://github.com/mailpile/Mailpile/files/1682276/BrowseOrLaunchLog.txt)

**Comment by BjarniRunar** [comment]
I think this API command is obsolete and should just be removed. The desktop integration work has taken a path which doesn't use it. Renaming issue to match.

**Comment by noahhaasis** [comment]
Can I do this commit?

**Comment by BjarniRunar** [comment]
Go for it!

**Comment by Jagroop-Singh** [comment]
Is this open or closed? It sounds like noahhaasis has already solved the issue and closed it, and somehow it reopened?

**Comment by Jagroop-Singh** [comment]
@BjarniRunar
