### ISSUE TITLE
Message-ID duplication when using GMail and Yahoo SMTP

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1997]
When sending emails from Mailpile, it appears that the GMail SMTP server smtp.gmail.com and the Yahoo SMTP server smtp.mail.yahoo.com adopt the Message-ID provided by Mailpile.

As a result, the BCC to the sending email address, which is generated by Mailpile, is never indexed and never appears in the Inbox. The outgoing email is tagged Sent and is indexed. When the BCC arrives from the incoming IMAP server it is treated as a duplicated message because it has the same Message-ID as the copy in the Sent folder and is not indexed. In the cases that I have checked, both the sent and the BCC emails are present in the Mailpile mail subdirectory; but the latter does not appear in any search results.

Other SMTP servers that I have tested provide their own Message-ID, including smtp.hushmail.com, mail.messagingengine.com (FastMail), and smtp-mail.outlook.com.

When GMail or Yahoo is not used, there can also be some unexpected behavior. If a pile has two incoming email addresses and the user sends an email from one address to the other, both the BCC and the Sent copy may have the same MessageID, so the one that arrives later is not indexed. This is probabaly a good thing since having two copies in the Inbox is pointless.

**Comment by BjarniRunar** [comment]
What you are describing as unexpected, is expected.

What you are expecting, is unfortunate and I'd consider a bug at the mail provider level. SMTP servers shouldn't mess with the message-ID... that potentially breaks all sorts of things!

**Comment by BjarniRunar** [comment]
(actually, I'm not sure from your description which you feel is unexpected... a little confused here)

But in any case, there is (or will be after one of my next pushes, I'm confused), a new settings on the preference page for disabling the bcc-to-self thing.

**Comment by JackDca** [comment]
I expected BCC to self to always work, since it worked with all the providers I had used. Didn't realize the changed Message-ID was a quirk - thanks for educating me. You're right, logically the Message-ID should not change. 

Is BCC to self ever useful?

It is handy if you access the IMAP server directly (no Mailpile) on some devices, since (on those devices) without it you can't see "Sent" emails composed with Mailpile.

**Comment by BjarniRunar** [comment]
Exactly! The entire purpose of this, is to make sure sent messages appear in other e-mail clients, until Mailpile learns how to upload things to the IMAP Sent folder.

I'm going to close this as working-as-intended. Thanks for raising the issue!

**Comment by JackDca** [comment]
Thanks - sorry for taking your time on this - at least I learned something.
