### ISSUE TITLE
Fix the UX of the Welcome Home page

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1999]
As reported/discussed in #1926, the "Welcome Home" page does not auto-update as new mail is downloaded. This should either be fixed, or we should avoid displaying numbers at all since people will expect them to stay valid.

The Welcome Home page is also horribly broken on mobile.

I would be quite happy with a fix is purely cosmetic: remove the numbers and fix the mobile experience.

Later iterations can then add back more functionality...

**Comment by noahsburroughs** [comment]
Is this an issue that's still in need of assistance?
