### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by Davy1992** [mailpile/Mailpile#2000]
The demo [page](https://demo.mailpile.is/in/inbox/) returns the "Template error" message.
Is this a known bug, and if so is it on a todo list?
I would like to test the client before installing it on my machine.

Thanks.

**Comment by Davy1992** [comment]
2000 you guys have come a long way 🥇

I just installed Mailpile on **WSL** (Windows Subsystem for Linux) and it's working flawlessly.
Thanks for the quick update.

**Comment by BjarniRunar** [comment]
I should warn you, that there were discussions on our IRC channel, where folks were having some troubles with WSL. Some things were definitely not working as expected, so first impressions may be deceiving you. Until we've got proper Windows packages built, I recommend Linux in a VM.
