### ISSUE TITLE
httpd.py: Include Content-Length on 302 Redirects

### ISSUE THREAD

**Issue by jvilk** [mailpile/Mailpile#2011]
My [automatic memory leak debugger](https://github.com/plasma-umass/bleak) for the client-side of web applications uses [MITMProxy](https://mitmproxy.org/) to instrument JavaScript/HTML to locate memory leaks. This is how I found all of those memory leaks I reported earlier; I simply ran BLeak on your demo site w/ a script that ran it in a loop, and it pinpointed code that caused memory leaks. :-)

I noticed that MITMProxy doesn't work on a local installation of Mailpile, however; it hangs (doesn't finish intercepting a request) when Mailpile redirects the web browser (e.g to the login page). I traced it back to [your code for 302 redirects](https://github.com/mailpile/Mailpile/blob/master/mailpile/httpd.py#L149), which fails to terminate the HTTP response -- either implicitly with a `Content-Length` or by closing the connection. From what [the Internet says](https://stackoverflow.com/a/15995101), one or the other must happen, so MITMProxy continues to wait for data that will never come.

This isn't a problem in browsers themselves, which seem to follow the redirect w/o waiting for a full response body.

I was able to fix the issue with the following change (if it's not idiomatic Python, I apologize; Python isn't my 'native language' :) ):

```python
        body = ('<h1><a href="%s">Please look here!</a></h1>\n') % (destination)
        self.wfile.write(('Location: %s\r\nContent-Length: %s\r\n\r\n') % (destination, len(body.encode('utf-8'))))
        self.wfile.write(body)
```

(PS: Your demo site is broken, but you might be aware of that?)

**Comment by BjarniRunar** [comment]
Thank you! I'll get this fixed in my local tree and push up with my next batch.

And yes, I broke the demo site the other day, haven't yet found time to fix it... soon, soon.
