### ISSUE TITLE
Header text overlap

### ISSUE THREAD

**Issue by largestprime** [mailpile/Mailpile#2019]
On certain screen resolutions (around the crossover point between mobile/tablet and regular desktop) the "report bugs" text clashes with the search box and causes the whole upper section to expand slightly, but enough to cover whatever is at the top of the left column (in my case - inbox)

**Comment by BjarniRunar** [comment]
This is pretty much the same as #2046, except that issue has screenshots. :)  Thanks for filing, closing as a dup!

**Comment by BjarniRunar** [comment]
Ooops, I meant #2045. But it's all related.
