### ISSUE TITLE
Update Dockerfile to use our Debian repo

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2021]
The current Dockerfile is doing things "its own way."

I don't user Docker and I'm usually alone on the core team - so this virtually guarantees that the Dockerfile becomes obsolete over time. And no, I'm busy, expecting me to just learn Docker and add this to my workload already isn't going to happen. :grin: 

It would be awesome if someone could rework the Dockerfile to use a minimal Debian image, add our Debian repository and install from packages that are actually maintained.

The package should by default track the release repo, but an option to use nightly would make sense. If Dockerfiles have options, otherwise just another Dockerfile. See: https://www.mailpile.is/download/linux.html

**Comment by BjarniRunar** [comment]
Thanks @rgarrigue for working on this!

First, I agree with your comments from the PR that with this pattern, an official Docker does indeed start to make sense. Since this is (aside from the sandboxing and special user account) following roughly the same patterns as our non-Dockerified linux setups, it shouldn't increase our support burden or complicate things too much.

Regarding that, I do have a couple of questions:

   * How do Docker installs like this get updated? What procedure should we recommend?
   * I notice you create VOLUMEs for the data directories, can you explain to a Docker newbie what that means? I assume this is part of not losing all your data if/when you rebuilt the container?

**Comment by BjarniRunar** [comment]
And also:

    * Can the Dockerfile be parametrized to pull in the nightly repo somehow?

**Comment by rgarrigue** [comment]
I guess some will help. Shortly for now

- Update is docker stop, docker pull (updates image), docker start. The app (mailpile) gotta be able to detect old version data and update it if required.

- Mounting volume is persisting data. Otherwise a container is just a process, all in memory. Kill or stop it and data is lost. The relevant folders to be mounted are usually declared with VOLUME instruction in Dockerfile.

- hub.docker.com can make a tag by git branch, and will trigger a build on a github push via webhook. Fixing a version in Dockerfile might not be necessary. But you can do it.

**Comment by BjarniRunar** [comment]
Thank you! Mailpile's normal update strategy is like that of any other Debian app - updates from the repo. Is that "incompatible" with The Docker Way?

**Comment by rgarrigue** [comment]
Well, to paraphrase you, Docker app's normal update strategy is is like that of any other app - updates from the repo ;-)

Don't think about docker like you'ld think about a VM. The Docker Way is

- One app by container, fix version with tag
- Update by pulling a new docker image, built around the new app version.

To think about this, have a look at for example https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml. This docker-compose.yml specify multiples services  : postgres database, redis cache, gitlab app. If you want to update gitlab version, edit `image: sameersbn/gitlab:10.6.0` with say `image: sameersbn/gitlab:11.2.1`, then just `docker-compose up`. That'll pull the new image, replace the running gitlab container with a new one based on the new image. Starting in the brand new container, Gitlab app will see the data in postgres and files in `/srv/docker/gitlab/gitlab:/home/git/data:Z` volume being from 10.6.0 version and migrate/update it. I did this multiples times as part of my previous job, it works very well, it's almost as good as running `apt install nginx` to specificaly update nginx package to a new version from the repo. The almost being, there's a downtime while gitlab restart, when nginx will boot new updated threads to replace old ones.

**Comment by BjarniRunar** [comment]
Hmm, I think that's a roundabout way of saying it is totally incompatible with the way we (and Debian) do updates. We need to provide a docker repo and make sure it gets updated as well, or people will be stuck on old versions?

**Comment by rgarrigue** [comment]
Yes. But there shouldn't be much work here.

As I said, Docker Hub uses Github WebHooks to trigger builds on new changes, on chosen git branch/tag. So if you tag v1.0.1 in github, that will build docker image tagged as mailpile/mailpile:v1.0.1. If at the time the version installed by "apt install mailpile" is v1.0.1, this will be all good and well. If the version in the repo is still v1.0.0, there's a mismatch. So here are some solutions
- If you've the .deb somewhere in the repository, you go for a `ADD mailpile.deb /` and `RUN apt install /mailpile.deb` 
- You don't have it and rely on repository, it's `ENV VERSION=1.0.1` and `RUN apt install mailpile=$VERSION`. Or `RUN apt install mailpile=$(cat VERSION.txt)` or alike.

**Comment by BjarniRunar** [comment]
@rgarrigue Thanks! That is helpful. I am going to close this issue as resolved, but open another one referencing it as a reminder to get the Docker Hub thing sorted out. It seems worth doing, now that we're this close to parity with our other preferred installation options.
