### ISSUE TITLE
Help new users who don't visit the web UI

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2025]
So this guide here, has a somewhat scary word of warning: https://www.digitalocean.com/community/tutorials/how-to-install-mailpile-on-ubuntu-14-04

> A word of warning: Mailpile will not save your settings after it stops. So, before you spend time configuring it, you may want to complete the optional next step of running it like a service.

At first I thought that was insane and obsolete, but it is actually true if the user hasn't gone through the basic setup first - either by running `setup` on the CLI or using the web interface. We should modify the CLI prompt so it constantly tells the user to do one of those things if the app is still unconfigured.

This is probably most easily done by making a minor change to `mailpile.app.Interact`, so an admonishion to "run setup or visit the web UI" is printed before each call to `threaded_raw_input()`, if the app is unconfigured (see `mailpile/plugins/gui.py` for examples of how to check if the app is unconfigured).

**Comment by wymillerlinux** [comment]
In my recent testing of the master branch, this issue can be closed. The master branch solved what @BjarniRunar was explaining in the OP.

**Comment by BjarniRunar** [comment]
@wymillerlinux indeed! Thanks for pinging the thread.
