### ISSUE TITLE
Add Mailpile to Docker Hub

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2028]
See comments on #2021 - we should be able to have an auto-built, auto-updated docker image that uses the packages from our Debian repo. Since this is more or less the same setup as we are recommending, this shouldn't be hard to support.

(This is an issue for the Mailpile core team, the community doesn't have enough access to do this. But if people want to chime in with hints and tips beyond what was in #2021 that's most welcome.)

**Comment by chrislaing** [comment]
Hi @BjarniRunar, has any progress been made on this issue in the past two years?

**Comment by BjarniRunar** [comment]
To facilitate running Mailpile v1 on modern operating systems, I've put together and published and documented "official" Mailpile docker images. See: https://github.com/mailpile/Mailpile-v1-Docker
