### ISSUE TITLE
Best effort: encrypt/sign e-mail feature always enforce signed key attach

### ISSUE THREAD

**Issue by danger89** [mailpile/Mailpile#2030]
Hi,

Using the latest Mailpile version: v1.0.0rc2.

When I enable the "Best effort: encrypt and/or sign mail whenever possible" (which is checked by default?). 
All receivers, including receivers who **never** received my public key, will get my signed key attached...?

Meaning this 'best effort' feature has a bug. 

**Expected behavior:** The signed checkbox is ONLY marked for people who already received the public key.

**Actual behavior:** The moment I select a random person from my contact lists (who never received my public key), the following signed checkbox is marked in all cases. Which is not wanted:

![image](https://user-images.githubusercontent.com/628926/38319125-570f9498-3831-11e8-9a06-6a36c8973e64.png)

Regards,
Melroy van den Berg

**Comment by JackDca** [comment]
There are good reasons for signing every email that you send.

- The recipient may have received your public key from a keyserver or from a third party.

- If the recipient does receive your public key at a later date, any messages that were previously received can then be verified. This email history is evidence that your public key is authentic.

- If the recipient knows nothing about end-to-end email encryption, they may ask you to explain what the signature is all about. You can then explain about data mining, government surveillance, and the awesome qualities of Mailpile, thereby contributing to this project and a better future for humankind.

**Comment by BjarniRunar** [comment]
This is working as intended, @JackDca explained it well. Thanks for filing though, and I really appreciate the detail of the bug report!

**Comment by danger89** [comment]
@JackDca OK fair enough. Maybe remove the "best effort" for this setting option, since I was expecting some more advanced logic behind this option (like again only sign e-mails to people who received my public key). While in practice it's just adding my signing to every e-mail in all cases, without any logic.

@BjarniRunar  Thanks.

**Comment by BjarniRunar** [comment]
@danger89 No, it is working as intended. Just because you read "best effort" as one thing and we implemented another doesn't mean our way is wrong. Like everything else, it could probably be improved in various ways, but for now it is working as intended. Have you read our security roadmap? It explains much of the rationale behind these things.

In any case, I'm going to repeat my request from another thread - until you've spent a bit more time with the app (this is what, your 2nd day using it?) maybe refrain from passing judgement so quickly.

**Comment by danger89** [comment]
Sorry I didn't fully understand the feature. And I will check-out the roadmap.
