### ISSUE TITLE
Implement "Factory Reset" for user tags

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2031]
Sometimes users move tags around and they get lost. This is disconcerting and can be hard to recover from for people not deeply familiar with the innards of the app.

Rather than make it harder to customize the UI, I think it might make sense to add a "Factory Reset" feature to the sidebar, which reverts all of the tags that are initially configured on setup to their original icons, colors, positions, etc. etc.

How I would do this:

   1) Add a `reset/tags` API method to `mailpile.plugins.setup_magic` - some refactoring will be required
   2) Expose this method to the user as a subtle option when they click `Organize` in the sidebar.

Regarding 2, we don't want people to accidentally revert their tag settings, so there should definitely be a warning popup that asks the user to confirm. A javascript `confirm()` would probably suffice.

(A more fancy implementation would allow the user to select exactly which of the standard tags get reset, but that's a lot of extra work which may not be justified at this point in time.)

**Comment by SushantGahlot** [comment]
Hi, I am new to contributing to OSS and I'd like to work on this if nobody has started working on it?

**Comment by BjarniRunar** [comment]
Hi @SushantGahlot and welcome! However, @kolibrik7 had already start working on this issue. You can see the pull request linked above your comment; unless they have given up on completing that it would probably be best to find something else to work on.
