### ISSUE TITLE
Tag info pop-up ignores tag settings

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2032]
The tooltip that appears when you hover over a tag in the search result allows the user edit the tag or remove it.

The edit op is fine, but the removal op should only be present for tags that can be modified - the tags which represent remote mailboxes and folders are supposed to be immutable (and the remove op will fail if attempted).

We shouldn't be showing the user options that don't work!

Fixing this requires exploring how the popups are generated (somewhere in `shared-data/html/jsapi/`) and tweaking things appropriately. It will probably require adding some information to the HTML template that defines the tag icon so the popup JS knows what to do (`shared-data/default-theme/html/partials/search_item.html`). I apologize in advance for the spaghetti code.

**Comment by meda123** [comment]
Hi - may I please work on this issue?

**Comment by BjarniRunar** [comment]
@meda123 Sorry about the late reply - yes of course, that would be great! I try to hang out on #mailpille on Freenode (IRC). I recommend chatting with me there as you work on this, so you don't get stuck or lost in the code.
