### ISSUE TITLE
Wrong email shown in "Grant Access" after an aborted add-account attempt.

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#2033]
Software Version: v1.0.0rc2 commit c7b1c89b2efd8677b5d6f8f2a888cc80e35d8247, hosted on FreeBSD 11.1-RELEASE.

On a clean install, I began the process of adding petur@ingi.dk (gmail hosted)  as an email account but aborted in the Security and Privacy tab.
Again, I began the process of adding an account, this time using peturingi@mailpile.is. Once through the four steps, I was presented with the following grant access request.
![screen shot 2018-04-06 at 09 31 30](https://user-images.githubusercontent.com/1230353/38408320-4c231210-397d-11e8-9ee7-5fb9315cc99e.png)

Note that the grant access request is for petur@ingi.dk, the address used during the aborted attempt.

I pressed Cancel on the access request screen. The following screenshots depicts my screen after pressing cancel. 
![screen shot 2018-04-06 at 09 35 51](https://user-images.githubusercontent.com/1230353/38408481-0e4265ee-397e-11e8-9df6-38d0010fa676.png)

The above screenshot shows that I have successfully added peturingi@mailpile.is as an account. Note the notification in the bottom right corner; the notification shows that access was denied by mail server for petur@ingi.dk, the email entered during the aborted attempt.

**Comment by peturingi** [comment]
Update: I clicked "grant access" on the notification and gate it a google key. Mailpile proceeded to download emails for petur@ingi.dk, adding them under the account peturingi@mailpile.is.

**Comment by BjarniRunar** [comment]
That's pretty wild!

At first I thought you must have changed the e-mail address after creating the account (in which case this would be expected and normal, since the IMAP credentials may differ from the e-mail identity you use for composing), but it looks like that was not the case.

I wonder if your browser was auto-filling the hidden form fields with petur@ingi.dk settings? If you didn't click the save button, nothing should have been written to Mailpile's configuration.

I'll see if I can replicate this.

**Comment by peturingi** [comment]
I do indeed use auto-filling. Will try again this evening with auto-filling disabled.

**Comment by BjarniRunar** [comment]
09:40 <@BjarniRunar> PeturIngi: in the wrong-email issue, when you say 
                     "aborted", did you close the modal, or go back to the 
                     first section and fill in new data?
    09:55 < PeturIngi> I dont remember that well enough to give a confident answer. 
                   I might have closed the modal, clicked in the top left 
                   corner to reload the page, then tried again to add an 
                   account.
    09:55 < PeturIngi> Or I might have simply clicked the first step and change the 
                   email. I am not sure...
    09:56 < PeturIngi> "Again, I began the process of adding an account" looks like 
                   something I would write to mean that I did indeed close the 
                   modal.
    10:29 <@BjarniRunar> OK. Well, short of auto-fill, I don't see hwo a fresh 
                     modal could cause that behaviour.
    10:29 <@BjarniRunar> However, clicking back to the first step could very easily 
                     have those results.
    10:29 <@BjarniRunar> And that's something that users might do now and then, so 
                     adding a warning to the first step if the e-mail doesn't 
                     match the source settings would be helpful.
