### ISSUE TITLE
mailpile-admin Causes Unclean Shutdown

### ISSUE THREAD

**Issue by dominic-p** [mailpile/Mailpile#2039]
I recently ran into an issue where running `./scripts/mailpile-admin --stop` caused several emails in my inbox to disappear. Fortunately, mailpile automatically recovered (seriously cool), but ideally, this shouldn't happen.

It seems like this is an issue with the mailpile-admin script causing an unclean shutdown.

For completeness, I ran into this because I use systemd to manage mailpile. I was getting timeouts and strange behavior, so I thought I would try restarting mailpile (thus causing the unclean shutdown). I know the "run mailpile as a service" discussion has come up a number of time, but I thought I would throw my unit file out there to see if anyone sees any obvious issues with it.

```
[Unit]
Description=mailpile webmail server

[Service]
Type=oneshot
RemainAfterExit=true
User=mailpile
Group=mailpile

# If you change the port here you need to update the reverse proxy config
ExecStart=/usr/local/share/Mailpile/scripts/mailpile-admin --start --port 42431 --webroot /
ExecStop=/usr/local/share/Mailpile/scripts/mailpile-admin --stop

[Install]
WantedBy=multi-user.target
```

**Comment by BjarniRunar** [comment]
Thank you for filing this! There are two things that I need to do here:

   1) Make sure mailpile-admin.py is giving Mailpile enough of a grace period to shut down
   2) Make sure Mailpile flushes metadata index changes to disk early in the shutdown process

**Comment by BjarniRunar** [comment]
I've double-checked things, and `mailpile-admin.py` gives a 30 second grace period before running `kill -9` to shut down Mailpile forcefully. Metadata index saves are also one of the first things Mailpile does during shutdown.

So I think the things I talked about above are already in good shape - 30 seconds should be enough unless something else is broken - and the fact that you were getting timeouts suggests that may indeed have been the case.

Do you remember, did the stop command take a over 30 seconds? Or is it possible that systemd is more impatient and kills things itself early?

**Comment by dominic-p** [comment]
It's possible that systemd got impatient. The actual command I ran was: `systemctl restart mailpile` which just runs the stop command followed by the start. I'm not sure what logic systemd uses to determine when the ExecStop command has finished. I don't remember the restart taking very long at all though.

I'd be happy to provide some more debugging info if it would help. Maybe some journald logs for the unit?

**Comment by dominic-p** [comment]
Btw, I ran the restart because I was seeing two issues consistently. I'm not sure if these are related.

1. Timeouts when opening longer emails
2. GPG key generation hangs forever (constant notification about either generating key or waiting to generate key for weeks)

I think the second issue was due to my system being low on entropy which I'm pretty sure I worked around (i.e. I was able to successfully generate a key in Mailpile). I also haven't encountered the first issue since restarting.

**Comment by BjarniRunar** [comment]
Having reviewed the code in question, I think the blame is most likely systemd or the way the unit file is written. I'm closing this, but please feel free to re-open or open another issue if you find evidence that I'm wrong about that.

**Comment by dominic-p** [comment]
Thanks for taking a look at this. A quick question so I can tweak the unit file appropriately: It [looks like](https://github.com/systemd/systemd/issues/2616#issuecomment-184272163) systemd assumes that the command executed in ExecStop "waits synchronously for the service to shut down on its own" can you confirm if `mailpile-admin --stop` does this?

**Comment by BjarniRunar** [comment]
It should be synchronous, yes. Or a poor approximation thereof - `mailpile-admin --stop` shouldn't exit unless Mailpile has been shut down, gently or otherwise. The logic could use some improvement though.

**Comment by dominic-p** [comment]
Thanks for the confirmation. I appreciate that.

**Comment by dominic-p** [comment]
As a follow up here. I'm not sure if this related to the original issue, but I noticed the following errors in my systemd logs for mailpile. This happens every time I start/stop the mailpile service.

```
Apr 14 23:24:11 capture.blue systemd[1]: Starting mailpile webmail server...
Apr 14 23:24:11 capture.blue mailpile-admin[17136]: WARNING: [Errno 2] No such file or directory: '/var/lib/mailpile/apache/usermap.txt'
Apr 14 23:24:11 capture.blue systemd[1]: Started mailpile webmail server.
Apr 14 23:56:23 capture.blue systemd[1]: Stopping mailpile webmail server...
Apr 14 23:56:34 capture.blue mailpile-admin[17453]: sh: line 0: kill: (17141) - No such process
Apr 14 23:56:34 capture.blue mailpile-admin[17453]: ==> kill "17141" || (rm -f "/var/lib/mailpile/pids/mailpile.pid"; false)
Apr 14 23:56:34 capture.blue systemd[1]: Stopped mailpile webmail server.
```

**Comment by BjarniRunar** [comment]
Thanks! Those all look pretty normal. But I should probably make the admin less noisy.
