### ISSUE TITLE
Multiple tags per mail (like gmail or thunderbird)

### ISSUE THREAD

**Issue by Sigmun** [mailpile/Mailpile#2041]
I was wondering if there is any way I can assign mail unique mail to several tags. I think this is very useful for classification. For example, I wish I am able to assign "Archive" but also "Images" so I can find my email in both.

**Comment by BjarniRunar** [comment]
Uh, this is one of the basic features of Mailpile.

Could it be you are posting issues without having even installed the app or tested it? Please don't do that, you're spamming me.

**Comment by Sigmun** [comment]
eh... calm down!
I am using this app from the git repository on linux. It works well but I cannot find any documentation on how to set multiple tags manually. I may be stupid, but it does not appears obvious to me.
Can you show me the documentation on that ?
