### ISSUE TITLE
Index of new mail source vulnerable to unclean shutdown

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#2044]
When a newly created Mailpile instance is set up, including a profile with an IMAP account, all the messages in the IMAP acount are indexed. This takes on the order of 1-2 s per message (e.g. a few minutes for 250 messages), and Mailpile does the indexing in batches (e.g. 10-100 messages). If there is no other activity (e.g. quit command, new mail on the IMAP account, user actions on the UI), the metadata index is not written to the `mailpile.idx` file after completion of the indexing, even after a wait of many hours. An unclean shutdown while in this state will result in a pile (workdir) with no `mailpile.idx` file. Nevertheless the keyword index file `kw-journal.dat` is written out.

When Mailpile is run a second time, the indexing operation is eventually repeated, apparently as a result of rescans of the mailbox, but it may be hours before all the messages are indexed so that they appear in the UI. Since `kw-journal.dat` has been written, ghost entries are created in the internal metadata index for all the `msg_mid`s that were created in the first run and new `msg_mid`s are created in the second indexing operation.

(This information verified using a shell script that records each change to the size or modification time of `mailpile.idx`.)

It is possible that similar behaviour occurs when a new profile with an IMAP account or other mail source is added to an existing Mailpile instance - this has not been tested.

It would be better if `mailpile.idx` could be updated as the messages from a new IMAP account (or any mail source) are indexed. However, if an append to `mailpile.idx` were done after each message, the result would be wasteful of space in `mailpile.idx` and also likely of CPU time. It appears that each append to mailpile.idx has an overhead of 300 - 400 bytes in the encrypted file and the CPU cost of handling multiple encrypted segments may be significant. In addition, after `MAX_INCREMENTAL_SAVES = 25` appends, Mailpile forces a complete rewrite of `mailpile.idx`. If a new IMAP account with hundreds of messages is added to an existing Mailpile with a large `mailpile.idx` then multiple complete rewrites of `mailpile.idx` will take place which is  expensive. A more efficient solution would be to append to `mailpile.idx` after completing each batch of messages.

**Comment by BjarniRunar** [comment]
I think we need to expect tens of thousands of messages, not hundreds.

Hmm, I know you've done a bunch of testing. I'm surprised we don't write out for hours, I agree that is excessive. 

A better way to think about this might be in terms of time. Making sure there are never more than 5-10 minutes worth of metadata index changes accumulated might make sense. This is very easy to implement, there are already various periodic jobs that run every few minutes. Making sure one of them flushes changes to the metadata index would be a one-line addition.

**Comment by JackDca** [comment]
I'll look into that approach.

**Comment by BjarniRunar** [comment]
The obvious job to piggy-back on is the periodic rescan job.

It runs every 15 minutes by default, which definitely puts a more reasonable upper bound on how long we let things accumulate in RAM. That's still going to be completely rewriting the metadata index at least four times a day (assuming there is a relatively steady stream of incoming mail over the course of the day), which seems like a lot.

Maybe raise the rewrite threshold from 25 to 100 to compensate?

**Comment by JackDca** [comment]
If mailpile.idx is already really big, the "cost" of a complete rewrite is high but relative effect of a lot of appends is small. e.g. if  the overhead of each append is comparable to an extra 1 kB of data, mailpile.idx is 10 MB, and you want to limit the extra overhead to 5% of the total, that's 500 appends. Maybe the threshold should go up as the size of the metadata index increases.

It will take me a while to grok the rescan job, which I have never looked at, but I will do so.

**Comment by BjarniRunar** [comment]
Making it relative to size is an excellent idea. Like!

The rescan job lives in `mailpile.plugins.core.Rescan`. It is a bit of a mess, sorry.

**Comment by JackDca** [comment]
Having studied the code, I have a concern about implementing changes which would result in a large number of modified entries being written at one time.
 
Most of the calls to `mailpile.search.save_changes()` are made by threads launched by `mailpile.commands.Command._background_save()`. That method **does not** hold `MailIndex._lock()` while it copies data from `MailIndex.INDEX` to the output file (see `mailpile.search.py` line 275 in the current master). Unless I am missing something (please correct me if I have!), there is potential for another thread to write data to `INDEX` while it is being copied.  (The method does hold `MailIndex._save_lock()` , but that only prevents two saves from happening at the same time, it does not prevent another thread from modifying `INDEX`.) I think the code works at present because most of the calls to `_background_save()` are part of a user interaction so that they affect only one or a small number of items in `INDEX` and they happen slowly in a sequence which avoids conflict.  But, if a worker asynchronously writes out a large number of changes wholesale, conflicts are more likely to occur.

The simple way to fix this is to hold `MailIndex._lock()` for from beginning to end of `save_changes()` but that could potentially affect response time of the UI. (There may even be some history which resulted in the code being the way it is.)

One way to make the code bulletproof is to limit the appends to `mailpile.idx` to some maximum number N of changed records, holding `_lock()` while that is done, releasing `lock()` pausing, then repeating for the next N modified records, until all modified records are done. With that change, save_changes() could safely be called anytime.

A similar approach could be taken when doing a full save of a new copy of mailpile.idx as in `mailpile.search.save_changes()`. Of course this would result in more sections in the encrypted file, but as discussed earlier, that may be acceptable. Or, INDEX could be accessed in several small pieces to build one larger section to be appended, repeating until the entire index is written.

Comments would be appreciated.

**Comment by BjarniRunar** [comment]
Yes, people can keep changing the index even as it is being saved. That's deliberate, otherwise things would grind to a halt when saves are being written out.

The reason this works, if you look in the save() function, is this snippet here:

            # In a locked section, check what needs to be done!
            with self._lock:
                mods, self.MODIFIED = self.MODIFIED, set()

That, in a locked section, stores the current set of modifications and sets up a stable "work plan" for this batch. From that point onwards, any subsequent modifications will add themselves to `MODIFIED` and get picked up by a later invocation of `save()`. (This pattern is used in a few places in the app.)

Due to the way this data is used (and thanks to Pythons GIL), the odds that save() will write out an individual record that is corrupt because it is being modified, are actually extremely low. Not quite zero, but very low. And even if we do get really unlucky, the damage will be corrected on the next `save()` because the changed entry will definitely be in `MODIFIED`.

**Comment by JackDca** [comment]
OK. I got what you were doing with the statement you quoted, but found it a bit scary that INDEX was not protected.

**Comment by JackDca** [comment]
Thank you for drawing my attention to the Python GIL. So, when code updates one item in INDEX, it generates a new line and then writes a pointer to it into the INDEX list. If the write of the pointer is atomic, and if the old line is not immediately overwritten, then the operation is safe, even if another thread is in the middle of reading the old line. Similarly, if two threads are writing lines into the same INDEX item, then as long as the writes of the pointers are atomic, the first will overwrite the second and the operation is safe. Since the code is executed by one interpreter running in one CPU, we can be reasonably sure that the writes are atomic.

Pardon me for obsessing about this. I'm just an old C programmer who spent a lot of time trying to find mysterious bugs in embedded RTOS systems.

**Comment by BjarniRunar** [comment]
Very interesting!

It's been a while since I measured those things, and that's a different methodology from mine. But it does support my reluctance to append too often.

I stopped obsessing over this at one point, because I came to the conclusion that I wanted to rip the whole thing out and replace it with an encrypted random-access record store. I've got the code written, but it's such a fundamental change that it's sitting in the inventory until we've shipped something to a broader audience and are moving past "1.0".

**Comment by JackDca** [comment]
PR #2063 addresses this issue.

- A full rewrite is **never** performed at shutdown, minimizing the exposure to a timeout in the shutdown process.
- A full rewrite is performed if the number of appends in the file exceeds 1/200 of the number of lines in the file. Since the time overhead for an append is on the order of 20x the time required to read or write an entry, the increased time to read or write a file with that number of appends is only about 10% more than a fully rewritten file.
- A full rewrite is performed if the size of the file has increased by 1/10 due to multiple duplicated lines pertaining to the same contact or message entry. Again, the time/space penalty of using appends is no more than 10%.
- The threshold number of appends or duplicates is held at 25 or 500 respectively when the file is small.
- The file is written every 15 minutes if there's anything to write. That's a maximum of 96 times per day. For a 50,000 line file the threshold number of appends is 50,000/200 = 250, so saving at 15 minute intervals would result in a full rewrite every 2-1/2 days.

The rescan code already looked rather tangled, so this PR creates a new cron task for the 15 minute rewrites of the metadata.

One issue remains, which is the time required to do a full rewrite of a large mailpile.idx, that could conceivably cause problems. One solution is a random access file as mentioned above. Since the metadata index records are variable length, that will require attention to defragmentation, not a trivial problem. An alternative is to do full rewrites in a background thread, a few hundred lines at a time, allowing appends to continue in the foreground whenever required.  A set `MODIFIED_FULL` could be added to the internal index to keep track of all records appended to the file during the background full rewrite, then  do a single append to the rewritten file, based on `MODIFIED_FULL`.
