### ISSUE TITLE
Hamburger menu does not get rendered on top on other UI elements.

### ISSUE THREAD

**Issue by peturingi** [mailpile/Mailpile#2046]
The following screenshot shows the effect of clicking the hamburger menu icon in the top right (depicted in red). Namely, that the menu does not get rendered on top of other UI elements. As such, only the menu's top frame gets rendered.

![screen shot 2018-04-16 at 09 32 04](https://user-images.githubusercontent.com/1230353/38796104-a71e21fc-415a-11e8-9164-26d33e8b8bba.png)

**Comment by BjarniRunar** [comment]
Thanks for reporting. It seems we have a bunch of Safari rendering bugs.
