### ISSUE TITLE
Improper alert box when requesting logout: "Are you sure you want to leave this page?"

### ISSUE THREAD

**Issue by peturingi** [mailpile/Mailpile#2048]
On macOS 10.13.4, using Safari 11.1:
Clicking the top right logout button displays an alert box which reads "From "localhost": Are you sure you want to leave this page?"

Performing the same action using Chrome, does not cause the alert box to be shown.

The following screenshots clarifies:
<img width="1051" alt="screen shot 2018-04-16 at 09 57 38" src="https://user-images.githubusercontent.com/1230353/38796858-050b76dc-415d-11e8-8205-f9429b9edb2b.png">

_Note that I have been presented with that very alert box when performing other tasks in Mailpile._

**Comment by BjarniRunar** [comment]
Leave this page questions should pretty much never pop up. I don't know what is causing this, but it's a bug.

**Comment by BjarniRunar** [comment]
Incidentally, I think I have also seen spurious "leave this page" popups on Windows IE. This isn't just Safari.

**Comment by BjarniRunar** [comment]
I think this was fixed in 66a8c9ff0625783a7e3a581ea2122aaa7aa92ba4. Please reopen if I am wrong-o!
