### ISSUE TITLE
Mailpile custom GnuPG keychain and gpg.conf

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2061]
One of the decisions from the little Mailpile dev summit last week, was that on Desktops, Mailpile should probably (by default) use a private keychain, rather than the shared OS keychain.

There is currently an option for this, but it is incomplete in that we will still be using the shared GnuPG configuration. Mailpile should use its own GnuPG configuration file.

Another issue we found, was that at build time, GnuPG 2.2.x on Mac seems to compile in the paths to dirmngr and gnupg-agent and other helper utilities. When the MacOS .app bundle gets moved around, these paths break and GnuPG stops working. I am pretty sure this could also be resolved by Mailpile shipping its own gpg.conf file.

Fractal complexitiy - this balloons to four possibilities:

   1. Shared GnuPG keychain, shared GnuPG config
   2. Shared GnuPG keychain, private GnuPG config
   3. Private GnuPG keychain, shared GnuPG config
   4. Private GnuPG keychain, private GnuPG config

Of these options, I see strong use-cases for 1. and 4. - case 2. may be required for the Mac bundle to work. I see no use for case 3.

If we can eliminate case 2, this becomes much simpler. That would imply requiring that IF the user wants a shared keychain, they must also provide a shared GnuPG installation that Mailpile can use instead of the one bundled in the .app. That makes shared keychains an expert-level setting. This needs a little more thought.

**Comment by JackDca** [comment]
I agree with these comments. "Casual users" should use "case 4" by default so they don't have to understand the interaction between Mailpile and an external GnuPG. "Expert users" should be able to enable "case 1" if they wish.

The Windows installer build script in the current master installs the executables of GnuPG in a subdirectory of the Mailpile program directory: `C:\Program Files (x86)\Mailpile ehf\Mailpile|\GnuPG` on WIn7. The thinking was that (since standard Windows does not have a package manager) casual users should not be asked to manually install additional packages; the Mailpile install should be just one operation; and putting Mailpile's GnuPG executables in that location would prevent conflict with another GnuPG if it were installed. However, the installer by default still leaves the GnuPG data at a public location, `C:\Users\[username]\AppData\Roaming\gnupg` on Win7, which creates the possibility for conflict. The private location should be the default.

**Comment by JackDca** [comment]
Re the comment: "Mailpile should use its own GnuPG configuration file."

I think this is already covered. According to the gpg manpage, if the command is
`gpg --homedir [path] ...`   then gpg looks for it configuration file at
`[path]/gpg.conf` , **ignoring** (e.g. on Debian)`~/.gnupg/gpg.conf`.

This can be verified by creating a new Mailpile workdir, setting _Use shared GnuPG keychain for PGP encryption keys_ to _Off_, then creating a profile with a new key, so the key is stored in `[workdir]/pubring.gpg`. Then the command
`gpg --homedir [workdir] --list-public-keys`
lists the key that was just created. The listing format changes if a file [workdir]/gpg.conf is created containing the option `keyid-format 0xlong`. Adding that same option to the global `~/.gnupg/gpg.conf `has no effect (with or without the local `[workdir]/pubring.gpg` present).

Also gpg-agent accepts the --homedir option. (But is it OK to have multiple active instances of gpg-agent??)

It seems messy to have all the gnupg files sprinkled among the Mailpile files in workdir. Would it be better to have a directory `[workdir]/gnupg`??

**Comment by BjarniRunar** [comment]
Note that @AlexanderHaase's work is probably changing how we build the installer. I don't know how much when it comes to GnuPG.

This issue could be more accurately read as: "Mailpile needs to create a gpg.conf file that has useful and helpful contents" - we don't currently do so.

I am pretty sure you can have multiple gnupg agents, at least on Linux and the Mac, since the communication happens over named pipes. I don't know if the Windows implementation is different in this regard.

**Comment by AlexanderHaase** [comment]
@BjarniRunar, I haven't tested that, but I'll add it to my backlog. Using explicit options via gpg.conf also potentially insulates mailpile from compile-time defaults--potentially useful future proofing.

**Comment by JackDca** [comment]
Testing on Debian - when a new pile is created, Mailpile reads the global public keyring and makes VCards containing email addresses from the key user ids. In my case, I have 38 public keys on the global keyring. Mailpile creates 18 VCards. Not sure of the selection criteria.

This happens before the user is prompted for a password, so the user has not yet been given the opportunity to select global/local keyring. If global is the default and they select local, there's already VCard data present from the global keyring.

This seems like a bug - comments?

**Comment by JackDca** [comment]
More testing on Debian - setting up a new pile with a local GnuPG homedir and a 3072 bit key pair being generated by Mailpile. If another instance of Mailpile is running at the same time, gpg frequently appears to crash and the new key is never generated. Running` ps -Af |grep gpg` shows the gpg process as "defunct". This happens with (so far) 100% certainty if I try to create two new piles and both instances of Mailpile are running a gpg key generation process at the same time.

**Comment by BjarniRunar** [comment]
I can confirm the vcard creation issue - I've drafted a patch that changes that which I'll push up soon. Interesting about the gpg misbehaviour, but I don't think it's going to be common enough for me to worry. That honestly sounds like a GnuPG issue.

**Comment by BjarniRunar** [comment]
Now the packaging work is complete, it turns out this isn't necessary. We don't currently have a need for a gpg.conf (or dirmngr.conf or, ...), so I am closing this. We can reopen later if necessary.

**Comment by BjarniRunar** [comment]
Clarification: The custom keychain was implemented and the defaults changed; it's jsut the gpg.conf we didn't end up needing.

**Comment by BjarniRunar** [comment]
Testing has shown we needed it after all. Reopening, have started working on this in my tree.
