### ISSUE TITLE
Polish up mailpile-gui

### ISSUE THREAD

**Issue by AlexanderHaase** [mailpile/Mailpile#2067]
Currently mailpile allows multiple-gui instances to attach to the same mailpile instance. This can be a bit confusing since it appears there are multiple instances of mailpile running where there is only one. It is also confusing in that all of them have linked behavior--pressing shutdown in one closes them all.

There are several potential use cases: mailpile-gui on remote devices, concurrent mailpile instances, etc--mailpile should have a user-friendly model for how it interacts with multiple gui instances.

**Comment by BjarniRunar** [comment]
Renaming this, here's a short checklist of things that I want to do:

   * [ ] Rethink the duplicates as discussed above
   * [ ] Investigate why the Mailpile GUI often fails to connect "the first time", but succeeds the second

**Comment by BjarniRunar** [comment]
The connection issue was resolved in https://github.com/mailpile/gui-o-matic/commit/e743d62ece5b5c4a76894cc193a400e9a385c753
