### ISSUE TITLE
Sandbox GnuPG, openssl and other external apps

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2072]
In light of [today's PGP scare](https://www.mailpile.is/blog/2018-05-14_PGP_Security_Alert.html), it is probably worth exploring whether we can sandbox GnuPG, OpenSSL, and other external tools invoked by Mailpile. Most of the time, we do not want these tools making any network requests and preventing them from doing so would be good proactive security.

A very simplistic way to do this on Linux, would be to use LD_PRELOAD, and a library that causes network related requests to fail. Better would be kernel-supported containerization of some sort. Research would be needed to understand how/whether we can do this on other platforms.

Relates to #733.

**Comment by lanodan** [comment]
I think you can reuse Gentoo’s sandbox for that, it does filesystem and network sandboxing by using LD_PRELOAD.
Project Page: https://wiki.gentoo.org/wiki/Project:Sandbox

**Comment by vezult** [comment]
I'm not familiar with gentoo's sandbox, it doesn't seem like something that's going to be widely available. Firejail is probably something that would be more commonly included in Linux distributions. Using that, we could do: `firejail –-net=none gpg ...`, if we discover firejail is available on the local host.

python-seccomp: Not available in stable Debian or backports, if that matters (mailpile is available as a deb, right?)

More generally, we could build an apparmor profile for mailpile, or a firejail profile.

**Comment by vezult** [comment]
OK, so [gaol](https://github.com/servo/gaol) does not appear to have windows support yet. Anyway, if we have to provide our own sandboxing for some reason, that seems like it might be safer/better/more ergonomic option than writing something in C. Seems like just targeting linux w/firejail may be the easiest thing at the moment.

**Comment by BjarniRunar** [comment]
Writing our own is a bigger task than we can handle; doing this sort of thing well requires low-level knowledge of OS specifics and we're spread pretty thin already.

I really like the idea of detecting and using firejail if it's available, and whatever is available and native on other platforms. I see firejail is available on my Ubuntu 18.04, so if it were a package dependency it'd just work! Putting the jail-specific-logic in `mailpile.platforms` would be appropriate (if it's small); that's where OS-specific stuff goes. Otherwise, `mailpile.sandbox` and `mailpile.sandbox.firejail` modules, if there is a large-ish amount of boilerplate.

The natural integration point would be `mailpile.safe_popen`, with sane (restrictive) defaults and new arguments to allow extra permissions (such as network access for Tor, or if/when we want GnuPG to contact key servers).

**Comment by vezult** [comment]
I'm working on this, FWIW

**Comment by vezult** [comment]
While I'm currently focusing on Firejail, the [bubblewrap](https://github.com/projectatomic/bubblewrap) project provides a comparison of several sandbox projects and the tradeoffs involved in each.
