### ISSUE TITLE
Allow the MOTD to trigger a notification

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2074]
When we need to inform our users of critical security news (like this: 
https://www.mailpile.is/blog/2018-05-14_PGP_Security_Alert.html), it would probably be good if the MOTD mechanism were able to trigger a popup notification. Just updating the text on the Home page is not really sufficient, after a while people stop looking at that.

Adding a "alert: URL" variable to the MOTD JSON would probably suffice; if that's present we should pop a notification.

**Comment by DanielPolatajko** [comment]
Could I try and take this on? It would be my first open source contribution so I might benefit from a bit of guidance but I'd love to have a crack.

**Comment by BjarniRunar** [comment]
@DanielPolatajko Sorry about the late reply, but yes, absolutely! If you have any questions, feel free to post them here or ask in the #mailpile channel on Freenode IRC - I'm mostly done with moving countries and summer holidays, so I should respond more promptly.

**Comment by zzulanas** [comment]
is this issue still open? looking to get started with contributing and this looks doable
