### ISSUE TITLE
[Question:] Ok, it's running, but what next...

### ISSUE THREAD

**Issue by aanno** [mailpile/Mailpile#2076]
Hello, 

cloning github and running Mailpile in the lines of https://github.com/mailpile/Mailpile/wiki/Getting-started-on-Linux was straight forward. I can use the command line and the browser. But now I tucked: What I'm expecting is some way to configure the IMAP and SMTP server to use.

Is there a way to do that? Or, I'm running in the wrong direction? What I'm supposed to do after I get the programm running?

Kind regards,

aanno

**Comment by BjarniRunar** [comment]
Once you have configured the app in your browser, you should be asked to review the privacy settings and then be presented with a big button for adding accounts. Did that not happen?

**Comment by gerroon** [comment]
Press home icon and use add account.

**Comment by aanno** [comment]
Well, when I first tried, nothing happened when pressing the 'privacy settings'. I now updated to 89a606b and this version works like a charm. BTW, is there a way to import a GPG key? So far, I was only asked to create a new one...

**Comment by BjarniRunar** [comment]
You should be able to import a key using standard GnuPG tools. On Linux, the default is for the keyring to be shared (this may change in the future though).
