### ISSUE TITLE
Display HTML formatted... button out of order

### ISSUE THREAD

**Issue by loidor** [mailpile/Mailpile#2085]
I just noticed the "Display HTML formatted message content" button doesn't work any longer. I don't use it that much, so I don't know really when it last worked, but not too long ago. A couple of weeks, at top a month.

I'm running mp on debian stretch on a raspberry pi that's been up for about a year now.

**Comment by BjarniRunar** [comment]
I need more details. Browser? What version of Mailpile (as in, when did you last update, and from where)?

It's working for me, I was testing HTML stuff half an hour ago.

In the unlikely event you were hoping to display HTML content from PGP-encrypted mail, that has been disabled for security reasons.

**Comment by loidor** [comment]
I've tested it on firefox and chrome on android. I just pulled from git before posting, in case something had updated.

No PGP, just plain things.

I'll checkout some older commits to see if I can spot what made it. Oh! Have you updated the requirements lately? It's been quite a while since I updated the python packages. I'll have a look at that too.

**Comment by loidor** [comment]
Updated python, problem was still there. Checked out 30 April, that worked fine. Worked my way forward, and now everything works on current as well. Really weird, but it's apparently solved. So I'm closing this now.

**Comment by TmCTux** [comment]
I'm experiencing the same issue, I can't get a display of mail in html (don't know if it comes from the button though :-)). For sure the mail is not encrypted, I'm using rc3 with firefox ESR under debian, clicking on the button doesn't do a thing.
