### ISSUE TITLE
Failed to build pycrypto

### ISSUE THREAD

**Issue by noahhaasis** [mailpile/Mailpile#2086]
On my machine installing the requirements-dev.txt failes with the following message:
`Command "C:\Python27\python2.7.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\leinw\\appdata\\local\\temp\\pip-install-gtxyuy\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\leinw\appdata\local\temp\pip-record-uli19y\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\leinw\appdata\local\temp\pip-install-gtxyuy\pycrypto\`

This problem can be resolved with the following command:
`easy_install http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py2.7.exe`

**Comment by BjarniRunar** [comment]
This isn't really a Mailpile issue, but thank you for reporting it so other developers can find your advice.
