### ISSUE TITLE
FR: Sorting support for local Mail folders

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2092]
Hi

I can browse my local maildir folders fine but the emailsa re all unsorted or somethign like that. it would be nice if there is support for sorting those local maildir (downloaded by another app) emails. 

There is not ui item for sorting like the regular account folders have.

thanks

**Comment by BjarniRunar** [comment]
I am not sure sorting will help much. Sorting is a way to facilitate "human search", and it only works well if you can quickly and accurately navigate the list of results. Our current UI doesn't do that very well, so sorting will become a lottery: if you're lucky, the stuff you wanted will bubble to the top, if you're not, well, nothing is gained.

That said, improvements to the local mail browser are all well on topic (and I would accept pull requests for this), but they're relatively low priority compared with a bunch of other things that need to be done. This won't happen any time soon unless someone from the community steps up.
