### ISSUE TITLE
FR: Indicate the mail folder/tag

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2095]
Hi

The one issue I have with Mailpile is that it does not tell me what email I am looking at unless I try to dig around the email adresses, headers etc.

It would be very very nice if there is some kind of bold indication of where an email belongs to and which folder it originates from.

For instance go up to your home window, then use the search bar to search for an email. Click on one of the found results, try to click on a result that was fetched from an email that came from deep imap folders like "INBOX/Work/Design". Now once you open the email you will never know where it belongs to. You might guess it belongs to this or that email address but you wont know the original category or the tagging.

thanks

**Comment by BjarniRunar** [comment]
Thanks, this is a good suggestion.

The default message view should include metadata such as tags, but in a way that doesn't overload the user with information.

This also relates to #1791 - the user should have access to technical details of a message, including details about where the e-mail is stored on disk (or online), and details about "hidden" or Mailpile-internal tags.

Deciding where the cut-off is: which details to display by default and which to relegate to a technical details page, will be a bit of a balancing act (and we'll never manage to please everyone).

**Comment by gerroon** [comment]
Hi

Thanks for considering it. I hope this is first implemeted among other FRs I put out there. This seems to me the most needed, at least that is my take as a user.

thanks
