### ISSUE TITLE
FR: Reverse the chat direction

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2097]
HI

The current chat direction feels awkward at least to me, the reason is that the last message is shown at the top which is the general opposite of how we used to chatting via text. Generally when a text conversation happens the latest reply will always be at the bottom not at the top.

thanks

**Comment by BjarniRunar** [comment]
Hello, thank you for your comment!

I am not sure it would be any less confusing if Mailpile sometimes showed the most recent message at the top, and at other times showed the oldest message. Different things confuse different people!

However, giving people control over this (by selecting a sort order) is something we already do for search results and it should be possible to do the same for message/thread views.

This relates to #1702 - removing the old thread view and replacing it with a view based on the same templates as the search results is mostly done already, so bringing back features like sort ordering should be relatively straightforward.

**Comment by gerroon** [comment]
Thanks for considering.
