### ISSUE TITLE
"Too many mailboxes found! Raise limits to continue.", 

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2098]
Hi

Yes I probably have too many mailboxes in my local archive which I added today. 

I have been getting this in the log, that is cool but how do I raise the limits? I cant find it in the docs and I could not find a usable web search about it.

thanks

**Comment by gerroon** [comment]
@JackDca 
Thanks I will try it. 

Would not make sense that this is also increased in the actual source as well?

**Comment by BjarniRunar** [comment]
Thanks for the report and discussion guys!

There are some "hostile" (or just old) IMAP servers out there that will spam us with a massive amount of mailboxes, thus filling the configuration and user interface with crap. This limit is supposed to prevent things from going nuts when we encounter such a server.

The notification which offers to raise the limits for you seems to be broken. Fixing it is IMO the correct solution to this problem.

**Comment by BjarniRunar** [comment]
Update: I did some work on this during the last few days. Fixes will be pushed this weekend once I've completed a few more tests.

**Comment by gerroon** [comment]
thanks

**Comment by BjarniRunar** [comment]
I've just pushed up a bunch of fixes to this code; it was broken in a few interesting ways and the UX was bad in some others. I'd be interested to hear from you whether current master (or tomorrow's nightly deb package) improves things for you.

**Comment by JackDca** [comment]
If  I can find the old mbox structure that raised this issue for me, I'll try importing it (to a new test pile, not my production instance).

Could take a while.
