### ISSUE TITLE
Support nested tag trees (avoid flattening IMAP folder structure)

### ISSUE THREAD

**Issue by zeigerpuppy** [mailpile/Mailpile#2099]
I am using an IMAP server (Dovecot) with maildirs and my mail is organised with subdirs, e.g.:

```
.
├── work
├── work.finance
├── work.meetings
├── work.people
│   ├── work.people.ann
│   └── work.people.jim
└── work.tax
```

However, Mailpile treats these all as independent mailboxes (which I guess technically they are!)
So the folders are shown as:

```
.
├── work
├── work.finance
├── work.meetings
├── work.people
├── work.people.ann
├── work.people.jim
└── work.tax
```

Is it possible for Mailpile to read a directory structure of IMAP folders and to display them as a collapsible tree?

**Comment by BjarniRunar** [comment]
Hello!

Unfortunately, Mailpile currently only supports one level of nesting in the user interface, and so to avoid confusion, the backend code which creates tags doesn't nest things any further. The tag structure itself allows deeper nesting, but if anyone takes advantage of it, the UI will break.

Fixing this requires enhancing the UI and then reworking the logic in `.../mailpile/mail_source/*` to create more deeply nested tags.
