### ISSUE TITLE
Quoted Text in PGP Email Replies Should Be Off by Default (opt-in)

### ISSUE THREAD

**Issue by uktu** [mailpile/Mailpile#210]
"Quoted Text" in email replies actually presents a security hazard, and 
should be off by default (opt-in) during PGP mode. This problem has not 
yet been mitigated in major PGP-supporting email clients, and it would 
be good to see mailpile rectify this. If Bob's private key is revealed, 
a passive attacker can use quoted text to read Bob's mails to Alice as 
well. This is unnecessary. Automated threading (gmail-like conversation 
view) should be used for keeping track of conversation flow instead of 
quoted text. This practice also reduces redundancy.

For
1. the threat model and security hazard of quoted text @smari 
2. the mitigation: using conversation view instead for UX @brennannovak 
3. how to implement this using existing or novel headers @BjarniRunar 
a whitepaper is available at
https://github.com/uktu/blog/blob/master/security-quotedtext

**Comment by BjarniRunar** [comment]
Closing this, as I think breaking e-mail traditions and context is the wrong solution to the problem. Making sure people encrypt (issue #1305) is the right solution. :-)
