### ISSUE TITLE
Index error in gpgi.py

### ISSUE THREAD

**Issue by noahhaasis** [mailpile/Mailpile#2100]
I want to give a quick update on my build after fixing the GnuPG and SSL issue. Maybe that's useful for the rework. If I now run `start .\mp.cmd` I get the following output:
`Elapsed: 0.491s (Loaded metadata, 0 messages)
Traceback (most recent call last):
  File "scripts\mailpile", line 14, in <module>
    Main(sys.argv[1:])
  File "C:\Projects\python\Mailpile\mailpile\app.py", line 216, in Main
    config.load(session)
  File "C:\Projects\python\Mailpile\mailpile\config\manager.py", line 321, in load
    self.gnupghome = GnuPG(self).gnupghome()
  File "C:\Projects\python\Mailpile\mailpile\crypto\gpgi.py", line 590, in gnupghome
    rv = self.run(["--version"], novercheck=True)[1]["stdout"][0]
IndexError: list index out of range`

The last index is out of range, because the second thing self.run returns is self.outputbuffers, which is set to `self.outputbuffers = dict([(x, []) for x in self.outputfds])`. self.outputfds is always `["stdout", "stderr", "status"]`. So self.outputbuffers is set to `{'status': [], 'stderr': [], 'stdout': []}`.
So the last line of the traceback could be rewritten to `{'stdout': [], 'stderr': [], 'status': []}["stdout"][0]`.
I don't see a case where this line can succeed but I would be happy if you proof me wrong.

**Comment by BjarniRunar** [comment]
If this were so fundamentally broken for everyone, we would have noticed. The StreamReader thread initialized in the run() function fills that array with data.

The only way for "stdout" to be empty, is if running `gpg --version` returns no output or if subprocess.Popen itself is broken - either of which is a pretty sure sign that your setup is broken. As I recall, you're trying to do this in the Windows Linux subsystem, so the latter would not surprise me.
