### ISSUE TITLE
Issues in CentOS: metadata index not found and GPG version error

### ISSUE THREAD

**Issue by j-hui** [mailpile/Mailpile#2102]
**What were you doing?**

I'm trying to see if this will work on my CentOS webserver. Following the instructions, I tried building it from source.

**What did you expect would happen?**

I expected it to work. That is, install all the system dependencies (which were pretty minimal, thankfully), setup virtualenv, run `./mp`, and commence further bushwhacking to get it behind my haproxy/nginx setup.

**What actually happened?**

When I ran `./mp`, I encountered the following error(s):

```
(mp-virtualenv) $ ./mp
Creating: /home/j-hui/.local/share/Mailpile/default                            
Metadata index not found: /home/j-hui/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.021s (Loaded metadata, 0 messages)                                  
Elapsed: 0.004s (health: We are healthy!)                                      
Traceback (most recent call last):
  File "/home/j-hui/Mailpile/mailpile/commands.py", line 584, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/j-hui/Mailpile/mailpile/commands.py", line 582, in command
    return self.command(*args, **kwargs)
  File "/home/j-hui/Mailpile/mailpile/app.py", line 166, in command
    self._gnupg().common_args(will_send_passphrase=True)
  File "/home/j-hui/Mailpile/mailpile/crypto/gpgi.py", line 630, in common_args
    raise ImportError('Mailpile requires GnuPG 1.4.x or 2.1.12+ !')
ImportError: Mailpile requires GnuPG 1.4.x or 2.1.12+ !

interact error: Failed: interact 
Elapsed: 0.007s (interact: Failed: interact )
Elapsed: 0.000s (cleanup: Performed shutdown tasks)
OK: Performed shutdown tasks
```

So there seemed to be two problems:

1. The index file was missing (`~/.local/share/Mailpile/default/mailpile.idx`)
2. Wrong GnuPG version (see below for GPG version).

Problem 1 seemed to have been "fixed" (as in, the error message no longer appears) by just running `touch ~/.local/share/Mailpile/default/mailpile.idx`, but problem 2 persists.

**Operating system? GnuPG version? Mailpile version?**

Operating system: CentOS 7, a choice which I am regretting more day by day
GnuPG version: 2.0.22 (yum does not appear to have a later version available) with libgcrypt 1.5.3
Mailpile: 0.4.1 (according to `package.json`)

**Comment by BjarniRunar** [comment]
Thank you for reporting this!

However, this is not a bug: Mailpile will not work with GnuPG 2.0.22.

Your distro almost certainly has GnuPG 1.4 available (since 2.0.x was unsuitable for a variety of tasks that people needed done), if you install it and configure Mailpile to use it things might work.

Regarding the index file - that's not a bug, that's a warning message and it's expected on first run, since Mailpile hasn't yet created an index.
