### ISSUE TITLE
multiple FROM accounts

### ISSUE THREAD

**Issue by cypriotxx** [mailpile/Mailpile#2114]
hi there , 
i cant seem to be able to add more than one from account when replying to emails to send from , how do i achieve this pls ?

**Comment by JocelynDelalande** [comment]
Thanks for taking the time to report.

@cypriotxx could you detail what you want to do exactly ?

**Comment by cypriotxx** [comment]
I would like to create multiple identities so i can send emails from
different identities like on roundcube for example .

Thank you so much
Regards

**Comment by JocelynDelalande** [comment]
on mailpile home, your account(s) should be listed, you then have a button, near screen top. with a « add an account » button.

![image](https://user-images.githubusercontent.com/429633/42379543-3ef9d074-812b-11e8-9f3d-bbaa6072eb16.png)

Does it work for you ?

**Comment by BjarniRunar** [comment]
I don't see a bug here... creating accounts works. The only lesson I can derive from this is that our UI would benefit from a tutorial of some sort. But that deserves its own issue (if it doesn't exist already, I know the idea has come up before).

Thanks @JocelynDelalande for chiming in!
