### ISSUE TITLE
Internal error with POP3 (?)

### ISSUE THREAD

**Issue by darklamp** [mailpile/Mailpile#2118]
Hi,
today I tried setting up an account which uses POP and SMTP both on TLS. I checked the settings three times and they are correct. However, Mailpile cannot retrieve the account's mail, throwing this error log. I'm running on Ubuntu 18.04 fully updated and on latest firefox, using pyhton virtualenv.

{
 "data": {
  "connection": {
   "error": [
    false, 
    "Nothing is wrong"
   ], 
   "live": false
  }, 
  "counters": {
   "copied_messages": 0, 
   "indexed_messages": 0, 
   "unknown_policies": 0
  }, 
  "enabled": true, 
  "have_unknown": false, 
  "id": "(removed)", 
  "mailbox_state": {}, 
  "name": "(myemail)", 
  "plan": [
   [
    "0001", 
    "Internal error: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)", 
    "Inbox"
   ]
  ], 
  "profile_id": "88c5b4de3c2", 
  "traceback": "Traceback (most recent call last):\n  File \"/home/me/Mailpile/mailpile/mail_source/__init__.py\", line 1042, in run\n    self.sync_mail()\n  File \"/home/me/Mailpile/mailpile/mail_source/__init__.py\", line 298, in sync_mail\n    elif (self._has_mailbox_changed(mbx_cfg, state) or\n  File \"/home/me/Mailpile/mailpile/mail_source/pop3.py\", line 115, in _has_mailbox_changed\n    prefer_local=False)\n  File \"/home/me/Mailpile/mailpile/config/manager.py\", line 902, in open_mailbox\n    mbox = msrc.open_mailbox(mbx_id, mfn.raw_fp) if msrc else None\n  File \"/home/me/Mailpile/mailpile/mail_source/pop3.py\", line 138, in open_mailbox\n    throw=POP3_IOError)\n  File \"/home/me/Mailpile/mailpile/mail_source/pop3.py\", line 47, in _open_pop3_mailbox\n    debug=debug)\n  File \"/home/me/Mailpile/mailpile/mailboxes/__init__.py\", line 68, in __init__\n    parent.__init__(self, *args, **kwargs)\n  File \"/home/me/Mailpile/mailpile/mailboxes/pop3.py\", line 65, in __init__\n    self._connect()\n  File \"/home/me/Mailpile/mailpile/mailboxes/pop3.py\", line 113, in _connect\n    self._pop3.pass_(self.password)\n  File \"/usr/lib/python2.7/poplib.py\", line 197, in pass_\n    return self._shortcmd('PASS %s' % pswd)\n  File \"/usr/lib/python2.7/poplib.py\", line 159, in _shortcmd\n    self._putcmd(line)\n  File \"/usr/lib/python2.7/poplib.py\", line 104, in _putcmd\n    self._putline(line)\n  File \"/usr/lib/python2.7/poplib.py\", line 395, in _putline\n    sent = self.sslobj.write(line)\n  File \"/usr/lib/python2.7/ssl.py\", line 677, in write\n    return self._sslobj.write(data)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)\n"
 }, 
 "date": "Tue, 17 Jul 2018 13:17:26 -0000", 
 "event_id": "5b4de3cb-00077-3074", 
 "flags": "R", 
 "message": "Internal error!  Sleeping...", 
 "private_data": {}, 
 "source": ".mail_source.pop3.Pop3MailSource", 
 "ts": 1531833446.996618
}

**Comment by BjarniRunar** [comment]
Thank you for reporting this. It looks like your password has non-ascii characters in it, and Mailpile is failing to correctly encode those. Is that possible?

**Comment by BjarniRunar** [comment]
I have reproduced this at my end. Will fix soon, thanks again for the report!

**Comment by BjarniRunar** [comment]
Potential fix pushed. It would be fantastic to know whether it works! :grin:

**Comment by darklamp** [comment]
That's most probably the case! Trying the fix asap :)

**Comment by darklamp** [comment]
Fix working flawlessly! Nice jobbb

**Comment by BjarniRunar** [comment]
Great! Thank you so much for confirming!
