### ISSUE TITLE
How to set a breakpoint for a URL handler?

### ISSUE THREAD

**Issue by littlehome-eugene** [mailpile/Mailpile#2119]
For instance, when a user hits his inbox, I'd like to set a breakpoint to see the code.

it's hard to step if I run `./mp` since pdb line is mangled with ./mp command line

I'm tying to use `./mp --wait www` or sort just to run the web without command line interface.

./mp  --wait www
Elapsed: 0.003s (health: We are healthy!)
Mailpile.py              a tool             Copyright 2013-2018, Mailpile ehf
 v1.0.0rc3         for searching and               <https://www.mailpile.is/>
               organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation. See the file COPYING.md for details.

The Web interface is disabled, type `www` to turn it on.

**Comment by BjarniRunar** [comment]
I don't know, sorry. I don't think anyone does!

If you figure it out, maybe add something to our wiki?
