### ISSUE TITLE
Fix the "three dot" signature/quote/forward suppression

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2130]
As discussed in #633, Mailpile is currently too aggressive about hiding content from view in the UI.

The "three dots" are currently suppressing forwarded content and quoted replies, whether the recipient has seen it before or not. The intention was to only suppress content that has already been seen by the user, and we need to do better here.

A quick fix which would improve things a great deal, would be to disable content suppression on the first message in a thread. We should do this ASAP.

(A more advanced fix would require keeping track of which paragraphs have appeared before in e-mail, and suppress paragraphs that are "duplicates." The search engine could do this and there might be some additional cool features that could be built on top of such an index... but it would also bloat the search index and is a more invasive change. So that's a "maybe in the future" kind of thing.)

-----

Marking this as low hanging fruit; if anyone wants to pick this up, it's going to be Jinja templating work in `.../shared-data/default-theme/html/partials/pile_message.html`, adjusting the logic that decides which paragraphs to mark as hidden.

If nobody volunteers within the next couple of weeks I'll probably do this myself. :grin:

**Comment by AnOxfordDev** [comment]
I'll give it a go! :)

**Comment by AnOxfordDev** [comment]
@BjarniRunar - I have followed the build documentation a few times, but I keep running into this error once I start the app. I've installed jinja2 and retrying etc, just wondering if its a common issue or something local to my machine? 

`(mp-virtualenv) C:\Users\Grumpy\Documents\Github\Mailpile>Traceback (most recent call last):
  File "scripts\mailpile", line 11, in <module>
    from mailpile.app import Main
  File "C:\Users\Grumpy\Documents\Github\Mailpile\mailpile\__init__.py", line 1, in <module>
    from mailpile.i18n import gettext as _
  File "C:\Users\Grumpy\Documents\Github\Mailpile\mailpile\i18n.py", line 5, in <module>
    from jinja2 import Environment, BaseLoader, TemplateNotFound
ImportError: No module named jinja2`

**Comment by BjarniRunar** [comment]
I only ever develop on Linux, so I don't know if Windows has any quirks. Sorry! Jinja2 and any dependencies (probably?) need to have been installed into the virtualenv, I can't tell from your comment whether you installed it globally or in the venv? Globally might also work, but mixing global and virtualenv is more error prone in general.

**Comment by R-K07** [comment]
I would like to do this.

**Comment by lee7670** [comment]
One thing that has worked for me while working on windows is running mailpile on Windows Subsystem for linux on Ubuntu. This worked flawlessly for me using the instructions from the wiki at https://github.com/mailpile/Mailpile/wiki/Getting-started-on-Linux.
