### ISSUE TITLE
able to send HTML email?

### ISSUE THREAD

**Issue by littlehome-eugene** [mailpile/Mailpile#2131]
I'd like to send an html email (including tables)

I guess there are two possibilities and wonder if its doable so I can pursue further

1. attach an editor (such as froala.com) and edit html in the composing window

2. write up html outside of mailpile and give the html message and recepient to mailpile at `/api/0/message/update/send/` endpoint as data.

Are these two plausible?

**Comment by BjarniRunar** [comment]
Are you using GET or POST? Mailpile's API follows the "standard" HTTP semantics of GET requests only being accepted for things that don't change state, POST is required for anything that is actually making changes - writing, editing, changing settings and yes, sending mail.

(We mostly don't bother with the other HTTP verbs, such as PUT or UPDATE, but we do respect the difference between GET and POST.)

As implied by the dev FAQ, you definitely want to `set sys.debug = log http` (at least) and then use `eventlog/watch` to watch for error messages while you're developing. It will make a lot of things clearer.

**Comment by pcompassion** [comment]
By the way, I was able to do this.
