### ISSUE TITLE
Mailpile is trying to use a revoked key when setting up a new account

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/Mailpile#2142]
I am trying to add an account.  I've set the preference `Use shared GnuPG keychain for PGP encryption keys.` to "on".  When I get to the Encryption Key step, I see a pull down with my old (revoked) 1024 bit DSA key, but not my current one.   I've verified that the revocation certificate is in my gpg1 keychain, `~/.gnupg/pubring.gpg`. The current unrevoked key is also in my gpg1 keychain.  This is running on Debian unstable on amd64.

**Comment by bjmgeek** [comment]
I noticed #1133, so I should mention that I first tested mailpile without gnupg1 installed, so `gpg` was version 2.2.10.  I then tried installing gnupg1, but got the same result.

**Comment by JackDca** [comment]
PR #2142 should stop the use of disabled, revoked, or expired keys.

There is still the separate issue, that only one key is offered to the user, even though more than one suitable existing key is available. This is a separate issue.

bjmgeek - if it is not too difficult, it would be good if you could test this in the configuration that produced your original issue.

**Comment by bjmgeek** [comment]
That pull request didn't work for me.  When I tried it, I cleared out my ~/.local/share/Mailpile directory, so I'd have a clean slate.  I started mailpile, and it asked me for a password, but then never progressed past that point.  I pulled the master and it worked.  I guess it might be related to https://github.com/mailpile/Mailpile/issues/1133

**Comment by JackDca** [comment]
Hmmm. Were you using GnuPG 1.4 or 2.1? I've always used 2.1 with no problem, and I've seen 1.4 do some strange things.

**Comment by JackDca** [comment]
The updated PR should now work.

**Comment by bjmgeek** [comment]
I was using 2.1

**Comment by bjmgeek** [comment]
That worked.  I was able to select my current key.

**Comment by JackDca** [comment]
Thanks for taking the time to test it!

**Comment by BjarniRunar** [comment]
Thanks both of you for your work on this. I've merged @JackDca 's fix and am closing this issue - please feel free to reopen or file a new one if the problem resurfaces.
