### ISSUE TITLE
feature request: use DNS CERT records to retrieve keys

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/Mailpile#2144]
Similar to #2117, another way to retrieve a public key from an email address is the CERT record, as defined in [RFC 4398](https://tools.ietf.org/html/rfc4398).  As an example, GnuPG supports retrieving keys using this mechanism.

**Comment by BjarniRunar** [comment]
Agreed, I don't think we should bother with DNS CERT. DNS records are in general a much less accessible, and much less secure mechanism than HTTPS. WKD is just better.
