### ISSUE TITLE
total number of messages does not add up

### ISSUE THREAD

**Issue by cbz20** [mailpile/Mailpile#2162]
I am using four different e-mail accounts in mailpile: gmail, posteo, my current university e-mail account and an old disabled university account. The total number of messages (conversations) is as follows:

gmail: 13k (5430)
posteo: 650 (291)
disabled uni account: 538 (243)
current uni account: 110 (84)

The "all mail" folder/tag contains about 6200 conversations, so the number of conversations (roughly) adds up. However, the total number of messages is shown as 26821 at the bottom of each search page ("Searched %n messages in %s seconds"). This is about twice the size I would expect. 

**Question:** Where could this discrepancy come from? Are there any "hidden" mailboxes in mailpile?

I am not sure if this is related, but I have also noticed the following: My trash folder is configured to delete e-mails after one day. When I move e-mails to trash, the total number of messages for the relevant account decreases, as I would expect. The total number of messages, however, does not decrease, even if I wait 24 hours. 

**Setup info:** I have been using mailpile for almost a year as my main mail client. I am running mailpile on a raspberry pi, using the latest stable release candidate. The mail sources are configured to delete emails on servers, so the email servers do not contain any emails. I am happy to provide more info, if that is helpful.

**Comment by BjarniRunar** [comment]
Hello! Thanks for your report.

The total message count almost certainly includes all your deleted messages; it's just measuring the length of the index file, and that includes all the tombstones for deleted messages. Given your setup, would you agree that probably explains [most of] the discrepancy?

We should probably try to change that, this is obviously confusing.

**Comment by cbz20** [comment]
Thanks for the quick reply! I think that would explain it. 

Nonetheless, I suspect that the e-mails that I put in trash are not deleted properly. From time to time, emails that I deleted months ago keep re-appearing as new in my mailboxes, even though the mail servers are completely empty. Also, the total size of the mailpile mail directory is 19 GB. This would translate to an average mail size of more than 1 MB per e-mail, which I don't think is right. That was the motivation for my second question. 

My mail directory contains about 50-60 subfolders named by seemingly random 5-digit hexadecimals; the size of these folder varies from 4KB to several GB. Is this supposed to be like that? I had expected these folders to correspond to my different accounts. If some of those are "hidden" accounts, that would also explain the issue.

**Comment by BjarniRunar** [comment]
As a fail-safe, there is a global setting determining whether deletion is allowed or not, on the privacy settings page.

Mailpile prompts you to change it to "allowed" after a couple of weeks of use (on the assumption that if you're using it after two weeks you like Mailpile and deletion should start happening), but if you dismissed the notification without acting on it, deletion may not be happening yet.

**Comment by BjarniRunar** [comment]
Since All Mail and Sent Mail are very likely to both contain many of the same messages, and Mailpile only counts each message once no matter how often it is found in a mailbox, the actual message-in-mailbox count will almost never match Mailpile's total.

As far as I can tell, this is working as intended. Furthermore, I'm actually of the opinion now that there's not much we can do to reduce the confusion either - de-duplication will always confuse people who dig too deep (but not quite deep enough). Since GMail's folders aren't really folders (they're tags), almost any amount of weirdness is expected on that front.

**Comment by cbz20** [comment]
Sorry keep nagging about this. I agree that getting those individual numbers add up correctly might be hard and not particularly important. But you said in your first reply:
> The total message count almost certainly includes all your deleted messages; it's just measuring the length of the index file, and that includes all the tombstones for deleted messages. [...] We should probably try to change that, this is obviously confusing.

Don't you still agree with that? I find it rather weird that the total message count does not go down if I permanently delete emails.

**Comment by BjarniRunar** [comment]
Friendly discussion doesn't count as nagging! :grin: 

I guess I just don't consider it particularly important, I see it as mostly ornamental - and yet it's still valid information: how many e-mails has this Mailpile processed.

Of course, if people expect it to mean something else, they'll be confused like you were. And I agree that's unfortunate. I guess one constructive thing we could do here, is turn this discussion on its head; current implementation aside, which metrics would people want to see (and why?), which things should we track and count and present?
