### ISSUE TITLE
How to hard-reset and re-setup

### ISSUE THREAD

**Issue by jamestomasino** [mailpile/Mailpile#2163]
I must have installed mailpile a long time ago and have some remnants somewhere. When I run the latest build I'm prompted for a password, which I don't remember ever setting. I'd like to wipe local settings and start again.

I looked at old issue logs and they suggested removing files in ~/.mailpile ~/.share/local/Mailpile etc, but none of those locations exist on my system (linux). I'm assuming the configuration files were migrated with gpg updates or something, but I can't find a reference to their current location in the wiki.

Can someone provide assistance on how to:

1) reset mailpile so I can run setup again
2) or let me know where the files are that need to be deleted to restart
3) or let me know where the docs are that I should be referring to

Thanks

**Comment by BjarniRunar** [comment]
Those are the locations. Unless you're on a Mac or Windows! :grin:

Uninstallation docs are here: https://github.com/mailpile/Mailpile/wiki/Uninstalling-Mailpile
