### ISSUE TITLE
FR: Please add a way to disable notifications popups

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2166]
Hi

It would be nice if there is a way to disable the notifications that show up at the right bottom constantly, I personally find them to be super distracting, totally against the distraction free email consumption idea. 

The messages there are mostly useless, talking about some stuff that is no help to me whatsoever. Even worse this gets worse on the mobile ui as if I have alot of space to spare on my phone's screen.

I click on "x" to close it, it shows up again.

thanks

**Comment by BjarniRunar** [comment]
Thank you for the suggestion, but no.

The notifications are an absolutely critical part of the UI. That's where we communicate about configuration problems, that's where the undo links show up for reverting tagging accidents, that's where we communicate about problems sending mail, etc. etc. etc.

I would happily consider an alternate implementation but until we have such a thing, notifications absolutely have to be there. Designing and implementing an alternative is not a trivial task.

I would also welcome improvements to reduce noise (there is some spam there). But just disabling... no.

**Comment by gerroon** [comment]
I am not advicing to remove them, asking a way to disable per user's requests. I have seen thousands of Mailpile popups and there was no single popup useful to me, I am user not a dev.

**Comment by BjarniRunar** [comment]
That is the same thing. You're asking me to remove the side view mirrors from the car because they stick out and annoy you. :smile: 

I agree that reducing spam in the notifications is important, but allowing the user to just make them go away forever is not going to happen.

**Comment by gerroon** [comment]
It is interesting to me that you are defending a feature that pollutes the screen space (which offers no value), which is worse on the mobile screen, half of the screen of my phone is occupied by continuous chatty pop up screen about totally irrelevant activity.

It is your desicion for sure, but from the user experience side, not so useful at least to me as a daily user. At least it should stay at rest and be activated when the user clicks on it.

**Comment by BjarniRunar** [comment]
I've already explained myself. Locking this thread, thanks.
