### ISSUE TITLE
Publish snap package

### ISSUE THREAD

**Issue by vvug** [mailpile/Mailpile#2167]
It would be very nice to have v1.0 distributed as a snap package on https://snapcraft.io/. Great way to reach many distributions.

**Comment by BjarniRunar** [comment]
Agreed, it would be nice. But unless someone contributes the necessary packaging scripts, it's not going to happen - I am not going to delay the release while I learn how to do this.

**Comment by jeroen7s** [comment]
currently using the mailspring snap
it says version 1.5.6
not sure is that outdated?
