### ISSUE TITLE
Improve Mailpile's notifications and event log

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2168]
The Mailpile notifications are too noisy/spammy, and there is some low-hanging fruit that could also make them more useful. A few things which should be done to improve this:

   * [ ] Suppress mail-source notifications more aggressively
   * [x] Find and fix the cause of superfluous time-outs at the API level
   * [ ] Improve the event log page to allow undo from there
   * [ ] Improve the event log page to give more useful details (instead of raw JSON blobs)

The notifications communicate extremely important information much of the time, but the spam is reducing the visibility of these messages and annoying users (to the point that people demand the feature be disabled entirely, #2166, which remains a hard no until someone proposes an alternate UI that accomplishes the same things).

The mail source notifications in particular are tricky; the information presented is extremely useful right after account setup, but quickly becomes distracting spam after that. The current (weak) workaround is these notifications reappear if you visit the account overview page, but if dismissed on any other page (search results etc.) they stay dismissed. They should at the very least auto-dismiss themselves after a while, but it's likely that an even better solution could be found (possibly not involving notification popups at all).

Marking this as Low Hanging Fruit, because it should be easy to make progress on individual components of this, even if the entire task is quite large.

**Comment by BjarniRunar** [comment]
Hello @derekyyyan !

Thanks for choosing Mailpile for your project! I look forward to your contributions and will do my best to give helpful feedback.

Note that the tasks on the list above vary a great deal in size/complexity. The first two will probably be nearly one-line changes, but may require a fair bit of investigation to figure out what needs to be done. The latter two are more straightforward "just add new code to do new stuff" tasks.

In general, please note that it's much easier for me to review and merge if pull requests are small in scope - the first three issues would probably justify one pull request each, but the fourth point (implementing the notifications UI) would probably best be broken up into multiple changes, one for each type of notification that is being improved.

Good luck with your work, and thanks again! If you have any questions, our IRC channel (#mailpile on Freenode) is a good place to chat and get quick answers (assuming I'm awake and online). And the contributing guidelines (https://github.com/mailpile/Mailpile/blob/master/CONTRIBUTING.md) and the DEV FAQ should also be helpful.

**Comment by BjarniRunar** [comment]
Addendum: In my last comment I probably overstated how small the a code change would be needed to address the first item on the list. Sorry! Please don't take my estimates too literally, they're just to give you an idea of what to expect - and one should also always expect surprises and wrong estimates. :wink:

**Comment by lee7670** [comment]
Hi, I'm one of the students who's working on the timeout issue. I've identified the issue as the ajax request sent by eventlog.js polling from the client having the same timeout as the maximum wait time in the server to look for new events given in the request. If there are no new events then the server waits for the whole 30 seconds before sending the ajax response. Since the ajax timeout is exactly 30000ms, due to the server overhead, the actual time to response is slightly more than 30000ms. I've fixed the timeouts entirely by adding a 1 second buffer to the _timeout override in eventlog.js. If that seems reasonable I'll clean it up and submit a pull request.

**Comment by BjarniRunar** [comment]
@lee7670 That does sound very reasonable and plausible. I'd suggest adding a bit more of a buffer (maybe 5 seconds), but aside from that this sounds great! Thanks!

**Comment by lee7670** [comment]
Changed the buffer to 5s, PR here(#2187 )

**Comment by karnation22** [comment]
Clarification question - for the notifications sub-task issue, should we limit the number of notifications on the screen at any given time (i.e keep at most the recent 4 notifications), dismiss after some fixed amount of time but keep on accounts page? Something else?

**Comment by lee7670** [comment]
PR for undo for tag events here #2190
