### ISSUE TITLE
Gmail using SAML2 auth is not available under sending accounts

### ISSUE THREAD

**Issue by JosephKiranBabu** [mailpile/Mailpile#2174]
# Background

## Setup
I am using a locally installed mailpile on Debian testing with amd64 architecture. I launch it directly from the git repository using the executable file called `mp`. My repository is up-to-date and pointing to the master branch.

## Things leading to the issue
- My SAML2 provider forced me to change my password as they usually do once in a while. 
- I changed the password.
- Mailpile detected that it was unable to fetch emails and prompted me to reauthenticate
- I was presented with a popup for the login and subsequently the Gmail permissions screen in which I remember allowing all the listed permissions. 

# Issue
Mailpile is able to fetch the emails from Gmail but doesn't allow me to send any emails from the Gmail account. In the *Compose* view, the Gmail account doesn't appear in the menu called "Choose Sending Account"

**Comment by JosephKiranBabu** [comment]
Thanks for the reply.

Yes, it's a Google Apps aka GSuite account. 

Mailpile doesn't even list this account in the Email Accounts section (/profiles). But it does show the INBOX of the Gmail account

Is there a way to remove and add this account? Hopefully, without downloading all the email once again.

**Comment by BjarniRunar** [comment]
Oh, weird. The account being gone is a bad sign, that really shouldn't happen unless you explicitly deleted it.

If you're on the cli and you type `print -flat sources` or `print -flat routes`, you will be able to see whether the IMAP settings still persist even if the account itself is gone. If they do, it's possible (using some magic incantations which I'll have to research for you) to link the old mail source with a new account so things look normal again. If the IMAP settings (the mail source) are gone, then you won't have any choice but to re-download the mail.

**Comment by BjarniRunar** [comment]
Clarification: `print -flat routes` won't tell you anything about the IMAP settings. But it's worth checking all the same, as a clue to what happened to the account.
