### ISSUE TITLE
how to send a mail with attachments using APIs

### ISSUE THREAD

**Issue by futurecrew** [mailpile/Mailpile#2179]
Hi,
I'm trying to send a mail with attachments using APIs.
I can send mails with text attachments using '/api/0/message/attach/' and '/api/0/message/send/'.
But no luck with binary attachments.

I read attachment binary files and set the file contents in the file-data fields as the following guide.

/api/0/message/attach/    <messages>/[<path/to/file>]/
... POST only: file-data=[file data]&mid=[metadata-ID]&name=[(ignored)]

The following is the snippet of my code to set the attachment contents.

```
file_content_list = []
with open(xls_path, 'rb') as fp:
  file_content = fp.read()
  file_content_list.append(file_content)

  data = {
    'mid': mid,
    'file-data': file_content_list
  }
  # Call /api/0/message/attach/ with data structure.
```

This code works fine for text attachments.
But for binary files such as excel files, there is an exception while decoding the attachments in Mailpile.

UnicodeDecodeError: 'utf8' codec can't decode bytes in position 10-11: invalid continuation byte
urlmap.py
data[var] = [d.decode('utf-8') for d in sdata]

How can i call /api/0/message/attach/ with binary files?

Thank you.

**Comment by BjarniRunar** [comment]
File uploads are encoded differently from "normal" GET and POST requests. You need to figure out what browsers do and emulate that. If you look in `mailpile/plugins/compose.py` the `Attach` command class is what handles the uploads, but the HTTP data parsing happens in `mailpile/urlmap.py`.

Sorry this is vague, but I don't remember the details off-hand and you can Google for answers just as well as I can. :grin:
