### ISSUE TITLE
First use with existing email address and existing PGP keys

### ISSUE THREAD

**Issue by halfshavedyaks** [mailpile/Mailpile#2183]
I'm trying mailpile for the first time and I want to use an existing email account with existing PGP keys. I would expect to do something like export my keys from enigmail then import them to mailpile.

There is no option to import existing keys when creating an account in mailpile I can either create a new one or use it unencrypted.

Seems to me that this is a common use case. 

Am I missing something?

**Comment by BjarniRunar** [comment]
It's only as common as use of GnuPG itself... which isn't very! :laughing:

But kidding aside, if Mailpile didn't detect your ~/.gnupg (or you didn't have one, or you chose not to use it on the initial privacy settings page), then you can just use standard GPG commands to import your keys.

The Mailpile command line interface has a `gpg` command that just shells out to GnuPG (with the right environment variables set so keys end up in Mailpile's keychain). So you should be able to consult any documentation about how to import/export keys into GnuPG and just follow those instructions.

**Comment by halfshavedyaks** [comment]
sorry to go on about this but I still don't get it - I think there is some critical context I am not getting.

if I have a key in .asc format and import it with "gpg --import mykey.asc" from the mailpile cli should that import the key to mailpiles own gpg instance? Assuming I get the path right and so on. 

The gpg commands do not give helpful feedback. I tried this and the key did not show up in the mailpile keys window.

when I  do "gpg --somecommand argument" from the mailpile cli am I accessing mailpile's own instance of gpg separate from the system one? (Assuming i first set up mailpile not to use the system one)

**Comment by BjarniRunar** [comment]
Yes to all of those. It sounds like you did get it. :grin: 

The gpg commands give the gpg feedback. Manually managing keys is expert level stuff, so you need to know how gpg works, Mailpile isn't trying to simplify that for you.

If you didn't tell Mailpile to use the shared system keychain, it uses its own. Just because something is on the keychain though, doesn't mean Mailpile will use it for outgoing mail - you link keys with accounts when you create or edit the accounts. Mailpile will list existing keys as options for such linking if they have a UID that matches the e-mail of the account itself.

**Comment by halfshavedyaks** [comment]
I just tried gpg --list-keys from the mailpile cli and it showed me all the keys in my system keychain even though mailpile is set not to use a shared keychain and no keys show up in the keys popup in the settings tab.

so either I'm really misunderstanding or there's a bug or some sort of settings corruption.

if using gpg from the mailpile cli is supposed to be accessing mailpile's own keychain it shouldnt be able to see all my system level keys.

**Comment by BjarniRunar** [comment]
This bug was present in some older versions of Mailpile. Sounds like you're not running the latest and greatest...

**Comment by halfshavedyaks** [comment]
I installed from the repo... do I need to change to nightly repo?

**Comment by halfshavedyaks** [comment]
mailpile reports version 1.0.0rc4

**Comment by BjarniRunar** [comment]
It might only be in nightly, yes.

**Comment by halfshavedyaks** [comment]
Updated to nightly and it worked. Strangely the version reported in Mailpile is still the same 1.0.0rc4

I still didn't get the verbose confirmation I get in my system terminal, but the key showed up in the mailpile window so all is fine there so far.

My 2c worth ( and I guess it isn't urgent) is that importing a key from a file should be an option in the intial setup gui. I accept that it is probably an uncommon thing to do for the general public, but mailpile users are self selecting towards a group much more likely to already have gpg keys. In any case there is a way to do it, and now it is documented here.

Sorry that most of my posts are essentially support requests, but until the forum is up there is nowhere else to ask.

**Comment by elvirolo** [comment]
I've set mailpile to use the system keyring, and my key is detected in the "Keys" settings dialog, but I can't link it to my email account. The account settings dialog only offers to create a new key. Is there are way around that?
