### ISSUE TITLE
Sending email fails

### ISSUE THREAD

**Issue by jimlei** [mailpile/Mailpile#2194]
I have had mailpile set up for a while. After some update a while back I was no longer able to send email. Incoming email, inbox, indexing, searching etc all still work as expected

Request:
```json
{
 "command": "mail", 
 "elapsed": "0.010", 
 "event_id": "5c1620c2-0090d-1", 
 "message": "Failed: mail ", 
 "result": false, 
 "state": {
  "cache_id": "", 
  "command_url": "/message/update/send/", 
  "context": "", 
  "context_url": "/message/update/send/", 
  "csrf_token": "5c1620c2-dVQhKVEn6LcCsSL_73OWymT1kJtfPujwgDp-S0L82QfBr_vYK8nyq9v7ml29g56FPUIgYlriNUQgZcLfdrXj5w", 
  "query_args": {
   "end": [], 
   "order": [
    "rev-date"
   ], 
   "parent": "", 
   "q": [], 
   "qr": [], 
   "start": [], 
   "view": []
  }
 }, 
 "status": "error"
}
```

Not sure how to get any further. Unsure where people get stack traces and if I try to run the cli I get "Another Mailpile or program is using the profile directory"

**Comment by JackDca** [comment]
Re running the CLI, it looks as if you are trying to run a second instance of Mailpile in a command window.
Instead, click on the gear icon (upper right), then click on the CLI button. That gives you a CLI window in the web interface.
Or, you could quit the instance that is running, then run a new instance in a command window.
After that, read Development Guide in the wiki. You can turn on some additional debugging.
It might help to turn off encryption of log files (temporarily!) so you can read the files in the subdirectory log of the Mailpile work directory.
Hope this helps.

**Comment by jimlei** [comment]
Thank you for responding! Trying to run the CLI in the web ui throws this in the browser console:

```
Uncaught TypeError: Mailpile.API.terminal_session_new_post is not a function
    at Object.Mailpile.Terminal.session_start (as.js?ts=1.0.0rc4-1545028828:3224)
    at Object.Mailpile.Terminal.toggle (as.js?ts=1.0.0rc4-1545028828:3182)
    at HTMLAnchorElement.onclick ((index):484)
```

Will try the other things you mention later on today

**Comment by BjarniRunar** [comment]
Any news?
