### ISSUE TITLE
Importing a PGP key with multiple user ids causes strangeness

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#2195]
Importing a key with multiple PGP UserIDs can give results that are not desirable and which depend on the order and timing of events. The tests described were done with the current master, commit `a6e9008`.

Example:

1. Alice Mailer and Bob Mailer each set up an account on an IMAP server(`mptestalice@gmail.com` and `mptestbob@gmail.com`) and clear the contents of the server.

2. Alice and Bob each set up Mailpile using their respective names and email addresses (`Alice Mailer <mptestalice@gmail.com>` and `Bob Mailer <mptestbob@gmail.com>`), each generating a new key, using defaults including local keychains for each pile.

3. Alice quits Mailpile, then uses CLI gpg to add a second userid (`Alice Alterego <alterego@fastmail.fm>`) to her existing PGP key, then runs Mailpile again.

4. Alice sends Bob an email with her key attached.

5. Bob receives the email from Alice, composes an encrypted reply (by clicking on the lock icon in the lower right, importing the key that was received from Alice, and clicking again on the lock icon), and sends the reply.

6. Bob starts to compose a new email to Alice, typing `alice` in the `To` window. Mailpile offers two options:
`Alice Alterego <mptestalice@gmail.com>`
`Alice Alterego <alterego@fastmail.fm>`

The "name" part `Alice Alterego` is used on both of these addresses, although the name in the PGP UserID for the `mptestalice@gmail.com` address is `Alice Mailer`. This is confusing to Bob, who has never heard of `Alice Alterego` before. The reason it happens is that when importing the key, Mailpile has added the name and the email address from the second user id to the VCard for `mptestalice@gmail.com`.

```
mailpile> vcards --lines alice
Elapsed: 0.003s (vcards: Listed 1/1 results)

  0       version: 4.0
  3       clientpidmap: 1;urn:uuid:mp-gpg-5c17bd5b-0/D02599B2F928C31CB0C4B4A05C36AAFA391C3140
  2       clientpidmap: 991;priority
  1       clientpidmap: 990;default
  5 1.1   email: mptestalice@gmail.com
  4 1.1   email: alterego@fastmail.fm
  6 1.1   fn: Alice Alterego
  7 1.1   fn: Alice Mailer
  8 1.1   key: data:application/x-pgp-fingerprint,D02599B2F928C31CB0C4B4A05C36AAFA391C3140 (keytype=RSA, creation=2018-11-28, keysize=3072)
  9 1.1   x-gpg-mrgid: D02599B2F928C31CB0C4B4A05C36AAFA391C3140
 12 990.1 x-mailpile-history: s-PJVZRV-1
 13 990.2 x-mailpile-prefer-profile: 7775bfeae52 (address=mptestalice@gmail.com)
 10       x-mailpile-rid: 7f45c17bd52

```

But, things come out differently if Bob sends emails to each of the Alices _before receiving Alice's key_. Start over with steps 1 - 3 above, then:

4. Bob composes and sends an email to each of the two Alice name and email addresses.

5. Alice Mailer replies to Bob with her key attached.

6. Bob receives the email from Alice, composes an encrypted reply (by clicking on the lock icon in the lower right, importing the key that was received from Alice, and clicking again on the lock icon), and sends the reply.

7. Bob starts to compose a new email to Alice, typing `alice` in the To window. Now Mailpile offers these options:
`Alice Mailer <mptestalice@gmail.com>`
`Alice Mailer <alterego@fastmail.fm>`

This time, the name from the _first_ user id has been attached to both email addresses. Also, _two VCards have been created instead of one_, but both VCards contain both names and both email addresses, though the order is reversed:

```
mailpile> vcards --lines alice
Elapsed: 0.004s (vcards: Listed 2/2 results)

  0       version: 4.0
 10       clientpidmap: 1;urn:uuid:mp-gpg-5c17c327-0/D02599B2F928C31CB0C4B4A05C36AAFA391C3140
  5       clientpidmap: 991;priority
  1       clientpidmap: 990;default
  2 1.1,9 email: alterego@fastmail.fm (type=pref)
 11 1.1   email: mptestalice@gmail.com
  3 1.1,9 fn: Alice Alterego
 12 1.1   fn: Alice Mailer
 13 1.1   key: data:application/x-pgp-fingerprint,D02599B2F928C31CB0C4B4A05C36AAFA391C3140 (keytype=RSA, creation=2018-11-28, keysize=3072)
  4 990.1 kind: internal
 14 1.1   x-gpg-mrgid: D02599B2F928C31CB0C4B4A05C36AAFA391C3140
  8 990.2 x-mailpile-history: s-PJW0P8-1
  9 990.3 x-mailpile-prefer-profile: 7775bfeae52 (address=alterego@fastmail.fm)
  6       x-mailpile-rid: d2b5c17c252

  0       version: 4.0
 10       clientpidmap: 1;urn:uuid:mp-gpg-5c17c327-0/D02599B2F928C31CB0C4B4A05C36AAFA391C3140
  5       clientpidmap: 991;priority
  1       clientpidmap: 990;default
  2 1.1,9 email: mptestalice@gmail.com (type=pref)
 11 1.1   email: alterego@fastmail.fm
  3 1.1,9 fn: Alice Mailer
 12 1.1   fn: Alice Alterego
 13 1.1   key: data:application/x-pgp-fingerprint,D02599B2F928C31CB0C4B4A05C36AAFA391C3140 (keytype=RSA, creation=2018-11-28, keysize=3072)
  4 990.1 kind: internal
 15 990.4 note:  (pref=None)
 14 1.1   x-gpg-mrgid: D02599B2F928C31CB0C4B4A05C36AAFA391C3140
  8 990.2 x-mailpile-history: s-PJW0MQ-0,s-PJW0U9-4
  9 990.3 x-mailpile-prefer-profile: 7775bfeae52 (address=mptestalice@gmail.com)
  6       x-mailpile-rid: 3aa5c17c221
```

Conclusions:

- Importing a PGP key with more than one User ID causes confusing behaviour.
- Perhaps Mailpile should require that each VCard has exactly one `email:` line.

**Comment by BjarniRunar** [comment]
Honestly, I think we need to just stop creating VCards based on what we find on the user's GnuPG keychain. There's no way to do it in a sane way, since PGP keys can contain an unbounded amount of potentially hostile UIDs.

Which means we'll need to rethink a bunch of other things to do with contacts and keys.

**Comment by BjarniRunar** [comment]
This is at least in part resolved by my latest merge/push: Mailpile will now only import the UIDs matching the e-mail address you were interested in when you searched for a key. So if someone uses one key with 6 different e-mails, you'll have to import it 6 times for Mailpile to see the whole picture.

The way Mailpile converts keys with multiple UIDs to vcards is still problematic, but we should see much, much less of that now.
