### ISSUE TITLE
Please add a way to disable (or at least dramatically reduce) notifications popups

### ISSUE THREAD

**Issue by armandoaleon** [mailpile/Mailpile#2197]
Hello,

[This](https://github.com/mailpile/Mailpile/issues/2166) thread was locked, but I'd like to ask you to keep this one open or otherwise allow people to publicly comment on this request so that you can allow yourself to remain open to feedback from people who might have differing points of view.

I agree with the poster from the above-linked issue that I have seen few if any notifications that I feel are useful enough to merit constance pop-ups.  I acknowledge that you did agree that a decrease in "spam" notifications would be useful.  But I'd like to propose something dramatically less obtrusive -- perhaps an icon that appears in a prominent color that you could mouseover to see what the message is?  Or something at the top of the screen that isn't constantly moving?

Thank you!
A.L. in San Francisco

**Comment by BjarniRunar** [comment]
Thanks the interest, but if I locked a thread that's a pretty clear sign that I don't want to continue the discussion. Please respect that.

I'm aware of the problem, more people commenting isn't going to magically make MORE aware, nor is it magically going to give me more time or more money or more developers. Thanks.
