### ISSUE TITLE
Switch to python3

### ISSUE THREAD

**Issue by wahrwolf** [mailpile/Mailpile#2202]
Hi there,
I just stumbled across this awesome project, but could find no information on if or when you want to switch python 3?

**Comment by JackDca** [comment]
I, too, think Mailpile is awesome.

Python 3 is discussed in Issue #160.

It is listed in the Post 1.0 Roadmap milestone.

**Comment by BjarniRunar** [comment]
Closing as a duplicate. Thanks for filing!
