### ISSUE TITLE
Multiuser GPG/PGP different private keys

### ISSUE THREAD

**Issue by buelentgit** [mailpile/Mailpile#2203]
Hi!

As i read in https://github.com/mailpile/Mailpile/issues/1022#issuecomment-57821022

> Mailpile uses the standard GPG keychain on your machine

My Mailpile instance is running as user "mailpile".
My standard GPG keychain ist in my ~/.gnupg/ Folder

How can i use my existing GPG keys?

And how does it work in multi-user Mailpile installations?

So long

**Comment by BjarniRunar** [comment]
On a modern OS, there is no such thing as a single-user installation.

Your Mailpile instance should run as YOU. That's how Unix multiuser works. Mailpile is no different from any other desktop app (Firefox, Evolution, Thunderbird, LibreOffice) in that respect.

If it runs as some other user, it uses that other user's GnuPG keychain. If that other user is also "you", Mailpile has no way of knowing that or connecting the two.
