### ISSUE TITLE
Treat certain URLs as attachments in the UI

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2204]
It is becoming increasingly common for people to send around attachments as URLs instead of attaching files. It would be nice if Mailpile recognized such things and presented in a friendly way in the UI. The groundwork for this feature was laid in ac03b658c1a50672102dccd205e49739f709177e, but it is incomplete.

Progress and proposed tasks:

   * [x] Change the `attachments` search result view to include "URL attachments"
   * [ ] In `mailpile.search`, scan text parts for URLs (there is a FIXME)
   * [x] In `mailpile.search`, scan HTML parts for URLs
   * [ ] Compile a list of trusted, known file sharing site URL regexps (Google Drive, etc)
   * [ ] Set sane `prefs.attachment_urls` defaults in `mailpile.plugins.setup_magic`
   * [ ] Consider whether the UI of message display also needs changing
   * [ ] Add a UI behaviour allowing a user to click on a link and say "treat URLs like this as attachments" to add to the `prefs.attachment_urls` list.

**Comment by BjarniRunar** [comment]
Anyone who wants to add examples of well-known, trusted file sharing site URLs in the comments here is encourage to do so. Google Drive? DropBox? Do things like OwnCloud have a pattern we can recognize?

**Comment by BjarniRunar** [comment]
Note: Before anyone requests Mailpile go and download such things in the background, rather than delegate to the user's browser; I don't think that is possible. These URLs usually lead to a human-friendly web interface of some sort, they are rarely a direct download link. The UI may also require the user authenticate or log in. The best we can do is recognize and improve the presentation of these URLs (and make them searchable).

**Comment by byaka** [comment]
think Github also can be trusted URL

**Comment by RS357** [comment]
Hey, I'd like to work on the second tick box task - scanning text parts for URLs. Should we have a chat on IRC about how to go ahead with this? Cheers!

**Comment by byaka** [comment]
> Hey, I'd like to work on the second tick box task - scanning text parts for URLs. Should we have a chat on IRC about how to go ahead with this? Cheers!

Think u can make one in discord or something and just link here :)

**Comment by BjarniRunar** [comment]
@RS357 Sure! Just join #mailpile and if I'm around we'll chat. But I must warn you, I'm often busy elsewhere so it may take a little while for us to sync up. If you leave your client connected you'll see my replies even if we don't manage to be online at the same time.

**Comment by qxtaiba** [comment]
Is this issue still unresolved? Happy to work on it!

**Comment by pybash1** [comment]
@BjarniRunar Can I start work on task 4 of this issue?

Task 4:
>  Compile a list of trusted, known file sharing site URL regexps (Google Drive, etc)
