### ISSUE TITLE
how to rebuild mailpile.idx file

### ISSUE THREAD

**Issue by futurecrew** [mailpile/Mailpile#2206]
I deleted mailpile.idx and previous five mailpile.idx.? files by mistake.

Is there any way to rebuild the mailpile.idx file from the files in the 'default/mail' directory?

**Comment by BjarniRunar** [comment]
If you've deleted all the mailpile.idx files, then Mailpile will just have to rediscover all your mail.

You will also have lost any information about tags you have assigned, and your search index will contain garbage - you will want to `rm -rf ~/.local/share/Mailpile/default/search` before you rebuild your indexes to avoid having completely broken search results.

If you are running the latest code from Github our our Debian nightly package, the `rescan` CLI command can be used to force a rescan of a specific mailbox.

An example:

    mailpile> print sys.mailbox
    {
        "sys.mailbox": {
            "0000": "/home/bre/.local/share/Mailpile/Dogfood/mail",
            "0001": "/var/spool/mail/bre",
    ...

    mailpile> rescan mailbox:0001

Note that unless you have downloaded (or deleted from the server) a very large quantity of mail, it may be best to just delete all Mailpile's data and start from scratch. And even if you need to re-read the downloaded mail, IF you are using the current defaults of not encrypting downloaded mail (you'll want to check Mailpile's privacy settings), you can copy Mailpile's existing mailboxes to another location, start from scratch and then use the local mailbox support to read the old mailboxes that way. That will also probably be easier than trying to get this broken Mailpile fixed.

Hope this helps!

**Comment by futurecrew** [comment]
Thanks a lot. 
That worked!!
