### ISSUE TITLE
Access Denied - api/0/rescan/ - i need the CSRF

### ISSUE THREAD

**Issue by max1404** [mailpile/Mailpile#2210]
Hello Community,

i want to use the API, once a night, to retrieve all new emails without calling the web interface.

Get Cookie: 
`curl http://192.168.1.10:33411/api/0/auth/login/ -H 'Content-Type: application/x-www-form-urlencoded' --verbose 2>&1 | grep Set-Cookie`

Login: 
`curl -X POST http://192.168.1.10:33411/api/0/auth/login/ -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: 6JTGtFfEVaAG=9hz6ZgZZARxphftFpoQ53fn5QxLNnYy3' --data 'pass=MYPASSWORD' --verbose 2>&1`

Show Profiles (check-only): 
`curl http://192.168.1.10:33411/api/0/profiles/ -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: 6JTGtFfEVaAG=9hz6ZgZZARxphftFpoQ53fn5QxLNnYy3' `

Trigger for new emails: 
`curl 'http://192.168.1.10:33411/api/0/rescan/' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Cookie: 6JTGtFfEVaAG=9hz6ZgZZARxphftFpoQ53fn5QxLNnYy3' --data 'which=sources' --compressed`

Here I get an "**Access Denied**" because the rescan without csrf in "data" is not possible (`which=sources&csrf=abcdef12345'`). But how do I get csrf through the API?

Can someone help me?

**Comment by BjarniRunar** [comment]
Hi Max!

Please take discussions like this to https://community.mailpile.is/ in the future. GitHub Issues are not the right place for discussions or support requests.

That said, the answer is in the JSON of every single API call - there is a `state` section that has a valid CSRF variable. You're already checking the `/profiles/` endpoint, you just need to parse the CSRF out of the output.
