### ISSUE TITLE
skip or ignore binaries

### ISSUE THREAD

**Issue by gpatel-fr** [mailpile/Mailpile#2213]
Hello, trying out Mailpile; when starting it without Tor installed, it displays
Required binary missing or unusable: Tor not found
(...you can set...)
 MAILPILE_SKIP_BINARIES="Tor"

This is a help message mistake, the correct name for this environment variable is
MAILPILE_IGNORE_BINARIES="Tor"

using github version downloaded less than one hour before this issue.

**Comment by gpatel-fr** [comment]
was fixed by https://github.com/mailpile/Mailpile/commit/8165336fabc41906646bb4598f9b8f20270154c4

**Comment by BjarniRunar** [comment]
Thank you for reporting this, and sorry about the lack of replies!

**Comment by gerroon** [comment]
How do I ignore multiple binaries like tor and gnupg at the same time?

**Comment by gpatel-fr** [comment]
err, you should know better than used a closed issue as a forum thread...
anyway, app binaries names are supposed to be separated by a space, so if you want to ignore 2 binaries one of them being 'burp' and the other 'Tor' (case matters), you would go about something like
export MAILPILE_IGNORE_BINARIES="burp Tor"
and no I'm not going to uninstall gnupg out of my computer to find out what value you'd need to use instead of 'burp'. Not using Tor is no great matter IMO, not using Gnupg is not sane if you care about privacy.

**Comment by gerroon** [comment]
thanks
