### ISSUE TITLE
Tor Dependancy Missing

### ISSUE THREAD

**Issue by scouseman** [mailpile/Mailpile#2214]
I am having a few issues with my Mailpile installation on Ubuntu 16,04
I am getting the error: Required binary missing or unusable: Tor not found
I have googled this but can't find a solution on how to resolve instaling this missing dependancy.
Any hints would be most appreciated.

**Comment by scouseman** [comment]
apt install tor

**Comment by h3artbl33d** [comment]
Did you install Mailpile through a package, or manually by the code? Depending on this, Mailpile made `tor` a soft dependency, so it _should_ no longer fail if `tor` isn't installed on your system.

Generic speaking: Tor is best installed through the package manager of your OS. This can be achieved with:

**Debian / Ubuntu / Deratives**
`apt install tor`
**Arch** 
`pacman -S tor`
**OpenSuSE**
`zypper install tor`
**FreeBSD / HardenedBSD**
`pkg install tor`
**OpenBSD**
`pkg_add tor`
