### ISSUE TITLE
Cannot add maildir

### ISSUE THREAD

**Issue by mokawi** [mailpile/Mailpile#2221]
I have the same issue as #1624 : I cannot add my maildir folder from offlineimap (as requested, issuing new ticket). Attempting it gives this response:

`add error: Not a mailbox: ~/Sync/.maildir/Gmail`

Mailpile version is v1.0.0rc5.
My .offlineimaprc file:

```
[general]
accounts = Gmail

[Account Gmail]
localrepository = GmailLocal
remoterepository = GmailRemote
maxage = 100

[Repository GmailLocal]
type = Maildir
localfolders = ~/Sync/.maildir/Gmail/

[Repository GmailRemote]
type = Gmail
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = [my email]
createfolders = true
remotepasseval = [my password]
holdconnectionopen = true
keepalive = 60
sync_deletes = no
folderfilter = lambda folder: folder not in ['[Gmail].Brouillons',]
```

**Comment by h3artbl33d** [comment]
What does `ls -la ~/Sync/.maildir/Gmail/` return?

**Comment by mokawi** [comment]
I used "add ~/Sync/.maildir/Gmail" in the Mailpile prompt.

`ls -la` returns:

```
total 232
drwx------ 58 mok mok 4096 jun 15 00:40 .
drwx------  3 mok mok 4096 jun 14 22:07 ..
drwx------  5 mok mok 4096 jun 15 00:40 aair
drwx------  5 mok mok 4096 jun 14 22:16 aair.ai
drwx------  5 mok mok 4096 jun 15 00:40 academia
drwx------  5 mok mok 4096 jun 14 22:16 academia.edu
drwx------  5 mok mok 4096 jun 14 22:16 AFEMMS-L
drwx------  5 mok mok 4096 jun 14 22:16 Arc
drwx------  5 mok mok 4096 jun 14 22:16 Asana
drwx------  5 mok mok 4096 jun 14 22:16 Atrium-Philopolis
drwx------  5 mok mok 4096 jun 14 22:16 Brouillons
drwx------  5 mok mok 4096 jun 14 22:16 Calcul Qu&AOk-bec
drwx------  5 mok mok 4096 jun 14 22:16 Calcul Qu&AOk-bec.Briar&AOk-e
drwx------  5 mok mok 4096 jun 14 22:16 Commercial
drwx------  5 mok mok 4096 jun 14 22:16 Commercial.CheapOAir
drwx------  5 mok mok 4096 jun 14 22:16 Commercial.Dreamhost
drwx------  5 mok mok 4096 jun 14 22:16 Commercial.LinkedIn
drwx------  5 mok mok 4096 jun 14 22:16 Commercial.UOttawa
drwx------  5 mok mok 4096 jun 14 22:16 Corbeille
drwx------  5 mok mok 4096 jun 14 22:16 Courriel UQAM
drwx------  5 mok mok 4096 jun 14 22:16 DH
drwx------  5 mok mok 4096 jun 14 22:16 DH.eclassiques
drwx------  5 mok mok 4096 jun 14 22:16 DH.Humanist
drwx------  5 mok mok 4096 jun 14 22:16 DH.liste dh
drwx------  5 mok mok 4096 jun 14 22:16 DH.list ln
drwx------  5 mok mok 4096 jun 14 22:16 Drafts
drwx------  5 mok mok 4096 jun 14 22:15 Envoy&AOk-s
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Brouillons
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Corbeille
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Corbeille.soccer Jean-de-Br&AOk-beuf
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Facebook
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Favoris
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Importants
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Importants.podio
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Messages envoy&AOk-s
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Pourriel
drwx------  5 mok mok 4096 jun 14 22:16 [Gmail].Tous les messages
drwx------  5 mok mok 4096 jun 14 22:16 INBOX
drwx------  5 mok mok 4096 jun 14 22:16 INBOX.Philopolis - volunteers to contact
drwx------  5 mok mok 4096 jun 14 22:16 legal
drwx------  5 mok mok 4096 jun 14 22:16 legal.grp-atelier-legal
drwx------  5 mok mok 4096 jun 14 22:16 legal.Outrage au tribunal
drwx------  5 mok mok 4096 jun 14 22:15 Liste ISC - UQAM
drwx------  5 mok mok 4096 jun 14 22:16 NCF Pop
drwx------  5 mok mok 4096 jun 15 00:40 philopolis
drwx------  5 mok mok 4096 jun 14 22:16 philopolis.net
drwx------  5 mok mok 4096 jun 14 22:16 philopolis.net.daily report
drwx------  5 mok mok 4096 jun 14 22:16 phi-nix
drwx------  5 mok mok 4096 jun 14 22:16 phinyx-site
drwx------  5 mok mok 4096 jun 15 00:40 pitt
drwx------  5 mok mok 4096 jun 14 22:16 pitt.edu
drwx------  5 mok mok 4096 jun 14 22:16 Pourriels
drwx------  5 mok mok 4096 jun 14 22:16 Queue
drwx------  5 mok mok 4096 jun 14 22:16 Sent
drwx------  5 mok mok 4096 jun 14 22:16 Slack
drwx------  5 mok mok 4096 jun 14 22:16 Templates
drwx------  5 mok mok 4096 jun 14 22:16 Trash
drwx------  5 mok mok 4096 jun 14 22:15 trello
```
so only folders (which are the ones in my account).

**Comment by mokawi** [comment]
Been reading a bit to figure it out. There is something weird about offlineimap (cf. [here](https://github.com/OfflineIMAP/offlineimap/issues/589#issuecomment-450877528)). The "cur", "new" and "tmp" are within each folder. This said, `add ~/Sync/.maildir/INBOX` has the same result, even though this folder has "cur", "new" and "tmp" subfolders.

**Comment by h3artbl33d** [comment]
The permissions seem okay. You are running Mailpile from the `mok` account?

Does the fix from pierrebeaucamp work? [See here](https://github.com/OfflineIMAP/offlineimap/issues/589#issuecomment-455922624).

**Comment by mokawi** [comment]
Yes, I'm running it from mok. The fix from pierrebeaucamp doesn't work... I even tried syncing it to a new (blank) directory, to no avail.

**Comment by h3artbl33d** [comment]
Are you implying that you (re)synched from the IMAP server to a newly created Maildir? If that assumption is _true_, could you enlighten me as to why you are using Mailpile in conjunction with offlineimap?

If false, two things come to mind:

1. offlineimap also supports the `type = GmailMaildir`, but as I am not familiar with offlineimap, it might make no difference at all or perhaps even be a worse call.
2. could you rerun offlineimap without the `folderfilter` option and move out the folders starting with `[Gmail]` (to a temporary folder, as long as it's not in a subfolder of the new Maildir)?

**Comment by mokawi** [comment]
Hi h3artbl33d,

Sorry for the delay, I was out of town, with a different computer.

I did resync to a new directory. The idea of using offlineimap is that I want to back up my imap on a directory in a syncthing folder, so I can free up space on Gmail (I also like the idea that I'd keep my correspondance for myself) while sharing it on various computers. I might be using different clients (e.g. cli-based clients are more convenient for some uses), so it makes sense to have a separate program manage syncing with the server. But I chose Mailpile because most of the time, I like having a complete, gmail-like interface for writing emails.

None of the two things seem to work... GmailMailDir seems to simply be a renaming scheme for `[Gmail]` folders.

I wonder if there might be an encoding thing? Some folder names have weird equivalents for accents (e.g. "&AOk-" for "é").

**Comment by h3artbl33d** [comment]
Hi mokawi,

Now I have to apologize for my late reply ;) The Github notifications weren't sent out - setting flipped back to _no notifications_.

Your scenario seems solid and thought through. Before I switched to Mailpile, I had a comparable setup; I thought it was madness to leave the entire archive with the mail provider - no matter which one. Hence, I configured a local IMAP server and synchronized to that.

I ditched that setup as I felt comforable with Mailpile. Started with Mailpile on the local network (reverse proxy with TLS through nginx), but put Mailpile on my local PC without any form of LAN access as time passed. I use the CLI interface of Mailpile most of the time.

Back to your issue: the encoding might be one of the (possible) root causes, yeah. Though I do not know how likely this is, as the Mailpile project origins from Iceland - where they have accents as well. Perhaps @BjarniRunar is in the position to state whether this might be true or false?

Could you create a new/empty Gmail account, sent a mail to it from a different account and see whether that can be synced to a Maildir and imported in Mailpile?

**Comment by mokawi** [comment]
Hi,

I tried again and realized I wasn't doing the right thing. I assumed that the `add` command on the command line was what I needed to begin making a new account; it turns out it was in the ui (hidden to me because I hadn't caught that I needed to save settings first).

I'm sorry for the confusion! I suggest we close the issue.
