### ISSUE TITLE
Language strategy, moving to Hosted Weblate

### ISSUE THREAD

**Issue by comradekingu** [mailpile/Mailpile#2227]
Branching out from #2223

For the upstream strings in Mailpile, the English stringbase, I think the preferable solution to management is to have two (or more) different people working at it, and asking Bjarni to explain things if needed.
Making both the task of getting a handle on the upstream strings easier, as-well as translation thereof, ideally done in unison, it would help greatly in that regard to move the translation effort onto https://weblate.org/hosting where I can help administrate things.

The current translation platform is closed source, spies on the users, does not allow one to look at things without an account, and is extremely broken for any sort of sensible approach to translation.
It also does not handle fuzzy strings, so any change upstream, inherently means potentially good translations are invalidated.

Moreover, it does not allow anyone under 18 to participate, and it non-sensibly costs the LocLab a lot to have it on there. The terms changed so that gratis hosting is no longer offered to projects if they have a venue of commercialization, (which Mailpile does). That is non-commercial, and therefore even actively antithetical to the principles of the Mailpile license.

In (the copylefted libre software) Weblate, working on upstream strings is much easier, as there are links to each corresponding file in the version control system. One can even turn on direct editing, so that everyone can "translate" English to English, as with any other translation. By default everyone can edit any language, which works great. There are also a lot of built in checks, improving quality overall.

**Comment by h3artbl33d** [comment]
Damn. I have not read up enough on Transifex - I use it currently to contribute translations (Mailpile, NextCloud and others). The downsides are enormous - especially when there is a much better alternative.

So I second this idea!

**Comment by BjarniRunar** [comment]
Makes sense. You have a green light from me to start working on the migration to Weblate; no release is imminent, so it's fine if this stuff is in a transitional state for a while.

To clarify further, what did you envision the two people working on this, working on? I can think of a bunch of i18n-related work that needs doing, but I'm curious what you had in mind.

**Comment by BjarniRunar** [comment]
Oh, and regarding the move - what do you need from me? Let me know!

**Comment by BjarniRunar** [comment]
Closing. This remains a good idea, but after some offline discussion, we'd need someone else to lead the effort.

We can open a new issue if/when someone else is interested in working on this (or any other strategy to invigorate our i18n work).
