### ISSUE TITLE
Make IMAP (and maybe other mail sources) stop polling gone mailboxes

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2229]
Mailpile should automatically stop trying to re-check a mailbox/folder which has been deleted from the source/server.

This should be done in such a way that if the mailbox reappears, polling starts again. This should be relatively straightforward, mostly we need to make sure that each individual mailbox type communicates clearly that it's "gone" (not just temporarily unavailable) and the master mail source polling logic should watch for that state and reconfigure itself accordingly.

The mailbox discovery logic also needs to recognize that if a mailbox we've seen before, but is in the "gone" state has reappeared, reconfiguring is also justified. Care needs to be taken that if a user *manually* disables a mailbox, that the discovery logic doesn't re-enable it.

**Comment by RenatoViana01** [comment]
Can I work on this?

**Comment by BjarniRunar** [comment]
@RenatoViana01 If you're still interested, of course! I recommend finding me on IRC (#mailpile, Freenode) so we can chat about this, there are some subtleties in how all this stuff fits together and our dev docs are not detailed enough to cover them.

**Comment by chapagaiashim** [comment]
How can I make that imap server?
