### ISSUE TITLE
Account creation is painful

### ISSUE THREAD

**Issue by mardy** [mailpile/Mailpile#2230]
Hi all!
  I have an e-mail account on my domain, hosted at dreamhost. I installed Mailpile, and tried added an account. I first used autodetection, and that seemed to find all the endpoints (POP3, IMAP, SMTP), but then when I went to the "Receiving emails" and "Sending emails" tabs, the configuration was missing.

I then tried manual account configuration. It failed; I guess it's because I didn't specify the port numbers (the third time I tried adding the account, I entered the right port numbers and it worked). If my guess is correct (that it failed because of missing port numbers), then these fields should be set as mandatory.

In general, if the account creation fails, it's painful to re-enter all the information again: ideally, the page should stay open and close only if the account was created successfully.

I'm willing to try implementing some improvements, if you agree with what I wrote above :-)

**Comment by BjarniRunar** [comment]
Thanks @mardy for the valuable feedback and sorry about the very late response. I agree this could all be improved as you describe.
