### ISSUE TITLE
Make translations more accessible to developers

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2234]
Currently our translations happen in Transifex.

One of the downsides of this, is people need a tool and an account (I think!) with Transifex to download the .po files (translation catalogs). We are currently checking these .po files in to the `release/1.0` branch along with each tagged release, but the master branch has no i18n content which makes it hard for people to test related functionality.

This should be addressed in some way; possibly by offering an alternate (unauthenticated) location for downloading translations and building that into our tooling somehow. Just putting the .po files in Github is not a great idea though, because then people inevitably start filing pull requests which then conflict with what we get from Transifex.

I'm not sure how best to handle this, suggestions are welcome.

**Comment by leojlin** [comment]
Can we make i18n of Mailpile a separate project on GitHub so that people can download .po or .mo files based on their locale?

**Comment by bronger** [comment]
Isn’t it even much worse? You don’t only need a Transifex account, you need a membership in the Mailpile team at Transifex.  The translations are locked away currently.

**Comment by bronger** [comment]
I think the best solution is to copy the po files into the source tree, eventually using an automated process. The trouble that this may cause can be dealt with. This is what I know from other projects.
