### ISSUE TITLE
Unable to run mailpile in background

### ISSUE THREAD

**Issue by r3db3rry** [mailpile/Mailpile#2237]
Hi, I'm trying to run mailpile as a service and, first of all, I'm trying to run mailpile in the background.

I tryed this command `nohup mailpile >mailpile.out 2>mailpile.err &` but I got an error and the program won't start:

Elapsed: 0.004s (health: We are healthy!)
Elapsed: 0.000s (motd: )

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 44, in reader
    line = raw_input(prompt).decode('utf-8').strip()
IOError: [Errno 9] Bad file descriptor

Elapsed: 0.146s (interact: Ran interactive shell)
Elapsed: 0.000s (cleanup: Performed shutdown tasks)

I installed mailpile via Debian repository.

Can you help me plz?

Is it possible to run the program in non interactive mode???

**Comment by JackDca** [comment]
Hi @r3db3rry,

I have run mailpile using screen which works well (Debian 9).

I'm not experienced with nohup.

But, the error traceback suggests that Mailpile is trying to read from the console, and I don't see a redirected sysin file specified in the nohup command.

**Comment by BjarniRunar** [comment]
Thanks for the bug report and the script, @r3db3rry  :-)

Running in screen is our "official" solution, that is what both our own Apache integration and desktop wrappers use.
