### ISSUE TITLE
FR: Show extra time information

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2241]
Hi

It would be so nice if the user can see extra time/clock information about the sent or received emails. At the moment all I can see is day names or truncated dates which is not much precise if you will. I realize one can take a look at the source to see some extra info but that is not convenient when trying to judge the order of events and replies.

thanks

**Comment by BjarniRunar** [comment]
Have you noticed that when you hover the mouse pointer over the "friendly time" the full time is in the tooltip? I'd rather not clutter up the search result view any further, so I think that will have to do until someone convinces me otherwise. :-)

I do agree that we should be showing the full time more prominently when you are reading a message though. Thank you for bringing this up!

**Comment by gerroon** [comment]
The tooltips are helpful for sure. I guess my point was more about being able to get a better idea about  the email chain as in the frequency of replies etc. That kind of thing is hard to grasp atm, we need a way to see all the time frequencies together. But I see your point about the UI.

**Comment by BjarniRunar** [comment]
Interesting, I understand better what you want now. Thanks for clarifying. I am not sure what a UI that communicates that would look like! If you have concrete proposals I'm happy to consider them.

Especially your interest in the timing of an entire conversation... we don't really have any view today that is dedicated to an overview over a conversation, so I think we'd need such a view before we could even start to work on this.

**Comment by BjarniRunar** [comment]
Adding a user preference to disable the "friendly dates" and use a bit more space for a full date + time would be a very minor change to the code. Would that cover it?

**Comment by gerroon** [comment]
Hi

I just tested it and it seems to work, thanks for the addition.
