### ISSUE TITLE
Too much disk activity, over 30gb of reading in couple hours

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2245]
Hi
I am using git version under virtualenv on debian. I am very happy with this except that I see alot of cpu and disk activity.

I installed Mailpile last year and I have close to 6 gb of data inside the Mailpile user folder. I ran `iotop` for maybe 2 hours and I see that it read about 30 gb of data. Does not this sound wrong a bit? i mean it seems like it read the whole data over and over under couple of hours.

My mail activity is very little like couple emails a day, but I have thousands of email in the storage , some from local email backups and some from online email accounts that were downloaded (and deleted from the server)

`/usr/sbin/iotop -aoP`

`33.76 G    289.83 M  0.00 %  0.68 % python2.7 /opt/Mailpile/mp --www= --wait`

Maybe this is ok, not sure. I guess I am wondering if this sounds right to the devs too. Could this be a bug?

Mailpile is definetely a SSD killer for sure :)

**Comment by BjarniRunar** [comment]
This is unsual, I think. I would be interested to know which files it is reading. You can also get a sense for what Mailpile is doing, by using the CLI (in a terminal, the web browser CLI is less functional still) and run the following:

    mailpile> set sys.debug = log
    mailpile> eventlog/watch
    ...

This will show a fair bit of output on the terminal, what sort of activities Mailpile is performing.

It is normal for Mailpile to do a fair bit of periodic housekeeping (retraining the spam filter, optimizing the search index, things like that). But it shouldn't be constant.

**Comment by gerroon** [comment]
Hi

THanks for the reply. I will check the logs and report back. 

I also have alot of "local" emails in Mailpile. I am suspecting that it keeps going back to those.

**Comment by gerroon** [comment]
https://paste.debian.net/hidden/fc91ea38/

It seems to keep repeating those steps. 

I let Iotop to log for an hour and it read about 3.5 gb and it was going up when I stopped Iotop.

**Comment by raspher** [comment]
@gerroon paste removed, can you upload it to pastebin like service, without removing after some time?

// not found on archive.org

**Comment by gerroon** [comment]
@raspher 

Sorry the paste is gone, I will try it again. I think I found the issue. Mailpile constantly scans the local emails (local emails from the file system ) And I have alot of archieved emails, I think that Mailpile keeps reading through those emails unnecesarily. Maybe it should stop indexing those once it has inspected them?
