### ISSUE TITLE
Failed to connect 587 and 995 (pop3s)

### ISSUE THREAD

**Issue by Danissss** [mailpile/Mailpile#2250]
Hi, thanks for the great program. I was trying to setup the mailbox, but the autoconfig can't connect to SMTP at 587 and pop3s at 995.

```
17:25 Failed to connect to mail.sample.ca:587: [Errno 111] Connection refused
17:25 Failed to connect to mail.sample.ca:995: [Errno 111] Connection refused
```

Here is nmap status
```
Not shown: 994 filtered ports
PORT     STATE  SERVICE
22/tcp   open   ssh
80/tcp   open   http
443/tcp  open   https
587/tcp  closed submission
995/tcp  closed pop3s
3306/tcp closed mysql
```

I am not sure whether it is caused by not running as root so mailpile can't start to listen port 587 and 995.

How do I configure Mailpile to listen these two ports (as non-root)?
 
OS: ubuntu 18.04
User: non-root
Web server: nginx
Python: 2.7

**Comment by Danissss** [comment]
I just realized that I need root to setup the mailpile.

**Comment by JackDca** [comment]
Hi Danisss,

It appears that you are expecting Mailpile to act as an SMTP/POP3 server. Mailpile is a client, not a server. It does not listen on port 587 or 995. Its function is to be a client, receiving incoming mail via an IMAP or POP3 server and sending outgoing mail via an SMTP server, while providing all the necessary composition, display, indexing, encryption and decryption. Hope that explains it.

**Comment by Danissss** [comment]
Thanks for clarification!
