### ISSUE TITLE
Installers

### ISSUE THREAD

**Issue by hudojnick** [mailpile/Mailpile#2253]
Hello! When can I approximately download the installer other than Linux?

**Comment by p073** [comment]
Installers for Windows and macOS are being worked on. No ETA as of now. But if you'd like to try Mailpile in the meantime, it isn't very hard to install it yourself and get it up and running :)

Are you using Windows, macOS or something different?

**Comment by hudojnick** [comment]
I have both macos and windows.

вт, 5 мая 2020 г., 00:09 p073 <notifications@github.com>:

**Comment by p073** [comment]
This should work for Windows, haven't been able to test it myself due to the lack of a Windows machine: https://github.com/mailpile/Mailpile/wiki/Getting-started-on-Windows

**Comment by hudojnick** [comment]
As I understand it, installers for ordinary people will not appear soon?)

**Comment by p073** [comment]
I can't answer that question as I am not a project member - just a user seeking to help other users. But in general, it is always wise to expect a "_it's done when it's done_" with open source projects. And heck, even beyond that ;)
