### ISSUE TITLE
Oauth2 for Gmail is broken

### ISSUE THREAD

**Issue by Lerrrtaste** [mailpile/Mailpile#2259]
The popup window says that the login is temporarily disabled. The option to allow insecure apps has been recently removed by Google.

Logging in via App-Password does work though.

**Comment by odysseus654** [comment]
In case you haven't heard from other places by now, it looks like Google has been heavily restricting use of OAuth to apps they have explicitly reviewed and approved.  In addition, it's extremely unlikely an open-source project would be permitted access; if nothing more the need to embed the approving signature somewhere has disqualified other projects from participating.

So yes, app-specific passwords thankfully still work for me too.

- a comment from someone not involved but have read a large number of frustrations from multiple projects trying to work with Google.

**Comment by BjarniRunar** [comment]
Mailpile v1 is no longer being developed, so at this point this probably won't get fixed.

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
