### ISSUE TITLE
Mailpile isn't python-3 compatible, and python-2.7 is EOLed and is being removed

### ISSUE THREAD

**Issue by yurivict** [mailpile/Mailpile#2263]
The FreeBSD port has this notice in it:
```
DEPRECATED=	Uses deprecated version of python
EXPIRATION_DATE=	2020-08-15
```

The port is going to be removed because of this.

**Comment by zzeroo** [comment]
See: https://github.com/mailpile/Mailpile/issues/160

**Comment by BjarniRunar** [comment]
To facilitate running Mailpile v1 on modern operating systems, I've put together and published and documented "official" Mailpile docker images. See: https://github.com/mailpile/Mailpile-v1-Docker

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
