### ISSUE TITLE
Create a plugin that allows encrypted Facebook Messages

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#227]
This is something I've LONG wanted to exist. I know, I could use Admium or any other Jabber client, but I want this data correlated with emails as I use both in very similar ways. 
### Jabber Library

This seems to be a pretty well supported XMPP library for Python https://github.com/fritzy/SleekXMPP

And here is a decent post about using it work with the Facebook Messages http://philsturgeon.co.uk/blog/2013/06/facebook-message-with-xmpp-access-tokens-python

Facebook Message API documentation https://developers.facebook.com/docs/reference/api/message/
### Encrypted Chats

We should also add encryption so that two Mailpile users can communicate over Facebook API in a fully encrypted chat. This will have the benefit of allowing a user to toggle seamlessly between conversations of their contacts- so of which will be encrypted, some won't- which is a gain to everyone. 

Not exactly sure how key exchange would work, but perhaps something like when starting a chat pop up a message (in the chat) like: 
- "Want be having an truly private conversation"
- "Communicate securely & privately with Mailpile.is"
- "To communicate securely with John Symthe [send your key]"

**Comment by BjarniRunar** [comment]
I don't think this is ever happening. Or at least, it doesn't need to be on our issue list - if someone from the community does this, awesome!
