### ISSUE TITLE
IMAP. Needing a second email to arrive into the remote inbox with Mailpile running, for the first pre-existent email to also show up in Mailpile

### ISSUE THREAD

**Issue by JazzTp** [mailpile/Mailpile#2272]
Mailpile 1.0 rc6, Ubuntu Linux 18.04.5

IMAP, totally empty remote inbox folder.

- With Mailpile _not_ running:
    + I launch Thunderbird
    + I send one email to that address, and in a few seconds it appears in Thunderbird's remote inbox folder.  
       
       Both the following points seem to be irrelevant:
    + I don't click on it, meaning it remains unread
    + I close Thunderbird  
  
- I launch Mailpile and wait for it to check that account... that email doesn't show up.
- With Mailpile running, I launch Thunderbird again
    + I send a second email to that address => **very quickly, *both* emails appear in Mailpile**

(Possibly, although I believe unlikely, related with https://github.com/mailpile/Mailpile/issues/1610)

**Comment by JazzTp** [comment]
> Just popping to my mind... could that be only a mistyped test, maybe in the GUI Inbox visualization code?
> 
> Something like
> 
> if numberOfEmails > 1
> 
> instead of
> 
> if numberOfEmails > 0
> 
> ?

Nope, minutes ago it was happening with 2 messages in the remote inbox, Mailpile was not showing them, Thunderbird was.

I sent an email to that inbox (this time from Mailpile but before opening this issue I had done it from Thunderbird) and immediately Mailpile was showing the 3 messages.

**Comment by JazzTp** [comment]
I see that it's not always happening, sometimes Mailpile shows just the same messages that Thunderbird sees in the remote folder, but I can't figure out what might change when it's OK vs. when it's not.

Always, so far, when Mailpile was not showing the new emails arrived into the remote inbox, the arrival of a new one made it show them all.

**Comment by JackDca** [comment]
My Mailpile instance connects to and checks each IMAP server only at 5 minute intervals. This is set by the config parameter `interval` (`sources/-source id--/interval`) which defaults to 300 s. There's also a `keepalive` parameter which (in my Mailpile version) defaults to `false`. The `keepalive` parameter allows Mailpile to keep a connection open to the IMAP server so the server can push emails to Mailpile, which would get around the delay of up to 5 minutes. I haven't used the `keepalive` parameter so I'm accustomed to having to wait up to 5 minutes for a new email to show up in Mailpile.

It sounds as if you have `keepalive` enabled but perhaps there are some quirks in its implementation in Mailpile (or in the server).

I'd expect an incoming email to show up in Mailpile within 5 minutes even if no subsequent emails arrive.

Hope this helps.

**Comment by JazzTp** [comment]
@JackDca 

Thank you a lot for all the information.

I'm using v1.0.0rc6 on Ubuntu Linux 18.04.5, I didn't modify the interval or keepalive.

I'm vigilant but the issue hasn't happened in days. (I've realized that when it was happening I should have checked the Network log and the all events log, I'm starting to think that it might have triggered an error on the server side which they might have fixed, although Thunderbird was not having that issue.)

Actually, I've also added a GMail account with years of emails, it has already fetched over 7GB and over 11k emails, yet the search engine gives answers in 0.002-0.3 sec on this old computer, with full search index encryption set. **Gorgeous piece of software!**

BTW:

> (sources/-source id--/interval)

**How do you access and modify the interval and keepalive settings?**

**Comment by JackDca** [comment]
--- How do you access and modify the interval and keepalive settings? ---

I put some comments at

https://community.mailpile.is/t/hints-for-developers/562

**Comment by JazzTp** [comment]
Thank you!

It's happening right now.
Thunderbird is showing me an email that is not showing up in Mailpile.

No interesting info in the Event Log or Network Activity, I only see lines like these:
```
hh:mm No new mail at hh:mm

hh:mm Connected to imap.vivaldi.net:993 over the Internet with TLSv1.3 (256 bit TLS_AES_256_GCM_SHA384).
```

Again, I've tried using in Mailpile the older settings which Vivaldi autoconfig server was giving, port 143 instead of 993, same problem.

With both port numbers:

Instead of IMAP/TLS, I've tried IMAP and  "Require STARTTLS encryption", same problem.

This is the only account giving this problem of the three I have at the moment configured in Mailpile.

**The only difference I can think of is that the username before @vivaldi.net is shorter in this account.**

I wouldn't mind sending you an encrypted message with user and password if you want to check that out, as long as you don't change the password to lock me out LOL. (It's blogs and other newsletters on various subjects what I get in that account.)

The problem is that with the next incoming mail Mailpile will fetch them all and I'll have to wait for the next time this happens.

**Comment by JazzTp** [comment]
> --- How do you access and modify the interval and keepalive settings? ---
> 
> I put some comments at
> 
> https://community.mailpile.is/t/hints-for-developers/562

I've used your page (great).

I've checked the dumped config file, by default the lines with keepalive = False and interval = 300 are - I believe - commented out with ';' and a note says:

```
;interval = 300              ; (default) How frequently to check for mail
;keepalive = False           ; (default) Keep server connections alive
```

For that account, I set keepalive = False and interval = 300, then dumped the config file again and verified the changes had been saved, then logged out shut down and restarted and logged in.

Unfortunately, there's no change, that email is still not showing up in Mailpile (and of course it's still in the remote folder, and just to be sure I'had marked it as unread after opening it accidentally in Thunderbird after the problem had already shown up again, anyway).

**Comment by JazzTp** [comment]
And voilà two other mails arrived into that account and the three of them now appear in Mailpile.

**Comment by JazzTp** [comment]
@JackDca 
> For that account, I've set keepalive = False and interval = 300

Actually, surprisingly, now every 7-16 seconds I was reading in the notifications "Checking for new mailboxes"... "Processed 1 mailboxes", and occasionally after the first notification I read something like: "Copying up to 112 emails" but no new emails appeared, and/or "Updating search engine for Trash.accountname".

I guess I could have used the unset command to reset those two settings to their defaults, but that wouldn't have solved the original issue.

I've removed the account and added it again, I'll see how it goes in the next days.

**Comment by JazzTp** [comment]
I also retook the Mailpile folder copy from before removing that account, and _instead_ I added a second source to it, disabling the first one. So, if/when the issue happens again, I'll have different Mailpile folders to test (kind of chasing butterflies admittedly).

(Actually, in both cases the new source appears in the sidebar as a new tag named same@account.name.2, but I do not lose the previous one from the sidebar, although I could always _search_ for the previous tag name... apparently moving emails from the previous to the new tag wouldn't work, untagging and tagging from the CLI _with this kind of tags_ doesn't seem to work.)

-----

**About your page** https://community.mailpile.is/t/hints-for-developers/562
I forgot to mention:

instead of
`pipe > /Mailpile$/mailpile.cfg.txt -- cat /Mailpile$/mailpile.cfg`

I do
`pipe > mailpile.cfg.txt -- cat /Mailpile$/mailpile.cfg`

and find the result in my home folder.
**Where is the result stored with the first command?**

**Comment by JackDca** [comment]
Sorry, I can't make sense of these symptoms. I will say that in my installation, the "Checking for new mailboxes" shows up only once for each mail source in each 300 second `interval` and the "copying up to nnn emails" only happens when new (previously unseen) email(s) are present. Could it be that some kind of error condition is happening so that Mailpile is aborting its attempt to access the IMAP server and then retrying repeatedly. See the community topic re the location of the dumped file.

**Comment by JazzTp** [comment]
> Sorry, I can't make sense of these symptoms. I will say that in my installation, the "Checking for new mailboxes" shows up only once for each mail source in each 300 second `interval` and the "copying up to nnn emails" only happens when new (previously unseen) email(s) are present. Could it be that some kind of error condition is happening so that Mailpile is aborting its attempt to access the IMAP server and then retrying repeatedly. See the community topic re the location of the dumped file.

@JackDca 
Thank you, no problem, I'm checking out what happens with this second source activated instead of the first one, all right so far.

**Please check out the question at the bottom of my previous message**, I don't need an answer but you might want to review your note for developers.

**Comment by JazzTp** [comment]
> [...] I'm checking out what happens with this second source activated instead of the first one, all right so far.

Apparently, creating the new source and disabling the previous one solved the problem.

I see that settings for the two sources are identical, except of course:

- enabled = False or True
- the two settings that I had modified in the first source, to check if that would solve the issue:
    + interval = 300
    + keepalive = False

As I wouldn't be able to replicate the creation of a malfunctioning source, I'm closing this issue.

**Comment by JazzTp** [comment]
P.S.: @JackDca  Thank you again.

**Comment by JazzTp** [comment]
It has happened again, same account.

(Right when I was finally overall happy, yesterday I unchecked "Leave mail on server" and "send BCC to myself", I was going to definitely encrypt and compress the Thunderbird tree. It's the single _real_ issue to me.)

**Comment by JazzTp** [comment]
On second thought: that account is by far the one where I receive most e-mails with that provider, it could be the only reason why I had the issue on it and not on others.

**Comment by JazzTp** [comment]
## POSSIBLY A WORKAROUND

Reminder:

- Sometimes I'm seeing via Thunderbird that I have new incoming emails in the remote inbox folder which are not appearing in Mailpile.
- I posted 16 days ago that I added a second source in Mailpile for that account, disabling the first one.

Now, when I see no new emails into that account:

- I edit its settings in Mailpile
  - I disable the source which is currently active
  - I enable the other one.
- Then of course I let Mailpile connect to the server again.

So far, provided that there were actually new emails on the server, they have always appeared in Mailpile with this workaround (I recently started with it though, used it three times only, I'll have more cases in the future).
