### ISSUE TITLE
should biplist be listed as dependency 

### ISSUE THREAD

**Issue by suliuzh** [mailpile/Mailpile#2275]
Hi
I am wondering if biplist should be listed in setup.py or requirements,txt?
As we can see, **biplist** is used in packages/macos/dmgbuild-settings.py as a must. So should biplist be listed as dependency?
![image](https://user-images.githubusercontent.com/27858725/98772217-29e00500-2421-11eb-95b6-0cb498914803.png)

**Comment by ooojpeg** [comment]
@suliuzh I've added this to the dev requirements.txt as it looks like this is a dependency only used when building packages not for production.

**Comment by suliuzh** [comment]
Thanks for  your nice reply.
It seems that there are other requirements that are not declared?

- PySide
https://github.com/mailpile/Mailpile/blob/c9bd0018e7ef16bbc2e417f54e4ff3624767c5e6/scripts/mailpile-pyside.py#L8

- email
https://github.com/mailpile/Mailpile/blob/c9bd0018e7ef16bbc2e417f54e4ff3624767c5e6/mailpile/plugins/compose.py#L2
