### ISSUE TITLE
Unable to install on Ubuntu 20 

### ISSUE THREAD

**Issue by sudheerds** [mailpile/Mailpile#2285]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mailpile : Depends: spambayes but it is not installable
            Depends: python-appdirs but it is not installable
            Depends: python-dns but it is not installable
            Depends: python-pgpdump but it is not installable
            Recommends: tor but it is not going to be installed
            Recommends: pagekite but it is not going to be installed
            Recommends: python-stem but it is not installable
            Recommends: wamerican-small but it is not going to be installed
            Recommends: gnupg-curl but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Oymate** [comment]
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 mailpile : Depends: spambayes but it is not installable
            Depends: python-lxml but it is not installable
            Depends: python-appdirs but it is not installable
            Depends: python-cryptography but it is not installable
            Depends: python-dns but it is not installable
            Depends: python-fasteners but it is not going to be installed
            Depends: python-imgsize but it is not going to be installed
            Depends: python-pgpdump but it is not installable
            Depends: python-icalendar but it is not going to be installed
            Recommends: pagekite but it is not going to be installed
            Recommends: python-stem but it is not installable
            Recommends: wamerican-small but it is not going to be installed
            Recommends: gnupg-curl but it is not installable
E: Unable to correct problems, you have held broken packages.
`
I actually had a few more uninstallable dependency PopOS 20.10

**Comment by pisn** [comment]
I have just installed in Ubuntu 20.04 LTS using the requirements-dev.txt requirements and it is working normally. Only problem I had during setup was with PyCrypto, but I could solve installing these packages:

sudo apt-get install build-essential libssl-dev libffi-dev python-dev

(Only for the record, solved it by following the instructions from these StackOverflow answer: https://stackoverflow.com/a/58415632)

**Comment by angerangel** [comment]
I confirm mailpile can't Install on Linux Mint 20  (It's Ubuntu focal).
I get the same error:

```
I seguenti pacchetti hanno dipendenze non soddisfatte:
 mailpile : Dipende: spambayes ma non è installabile
            Dipende: python-appdirs ma non è installabile
            Dipende: python-dns ma non è installabile
            Dipende: python-pgpdump ma non è installabile
            Raccomanda: python-stem ma non è installabile
            Raccomanda: gnupg-curl ma non è installabile
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

```

**Comment by angerangel** [comment]
Why don't you create a snap package? It's indipendent from distribution and version and it would resolve all Python 2 dependencies.

**Comment by angerangel** [comment]
ok works! Thank you!

**Comment by Oymate** [comment]
@pisn Will you make a PR based on those steps

**Comment by pisn** [comment]
Hello @Oymate ! I am not sure this is necessary, since the steps are already described at [Getting Started on Linux](https://github.com/mailpile/Mailpile/wiki/Getting-started-on-Linux) session on the project wiki.

**Comment by BjarniRunar** [comment]
To facilitate running Mailpile v1 on modern operating systems, I've put together and published and documented "official" Mailpile docker images. See: https://github.com/mailpile/Mailpile-v1-Docker

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
