### ISSUE TITLE
Gmail blocks Mailpile

### ISSUE THREAD

**Issue by Mydherin** [mailpile/Mailpile#2294]
Hi everyone,

I am really interested on using mailpile but i can not introduce my gmail account on MailPile. 

I am using Mailpile 1.0.0rc6.

My Gmail configs:

![2](https://user-images.githubusercontent.com/88291577/131737203-6decc3b0-5437-467e-9247-7b5408cde96b.PNG)

![3](https://user-images.githubusercontent.com/88291577/131737275-5bc5f028-9c83-4d51-be21-56252bb3864d.PNG)

Finally, I need to authorize Mailpile access from Gmail popup from this dialog:

![4](https://user-images.githubusercontent.com/88291577/131737302-574ea15f-4798-4e99-9928-b5887d4f5638.PNG)

![captura](https://user-images.githubusercontent.com/88291577/131738716-36edf631-76da-467e-9d90-a95b38b13f35.PNG)

After pressing authorize button i get that error. I have enabled not secure apps from Gmail so I do not understand what it is not working fine here.

Any suggestions? Thanks. And my apologise if this topic is duplicated i have done a quick search and i have not found this error (I have found others errors about Gmail connection but not this).

**Comment by pisn** [comment]
Hello Mydherin!

I started to debug mailpile using a gmail account no more than two weeks ago. I had the same problem you had and could not manage to make it work using OAuth2 authentication. Only way it worked was generating an app password and using Password authentication.

This page teaches you how to generate the password: https://support.google.com/mail/answer/185833?hl=en

**Comment by Mydherin** [comment]
Thanks pisn, it works for me. I do not know why OAuth2 authentication is not working. I will close this issue.
