### ISSUE TITLE
Tor cannot be enabled

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#2297]
**Security and Privacy Settings > Networking Privacy > Enable Tor** gives "Failed: setup/tor" error
**Troubleshoot recent Network Activity** shows successful connection to 127.0.0.1:9050, with the error:
"Failed to connect to clgs64523yi2bkhz.onion:80: Tor error, general SOCKS server failure" showing next

clgs64523yi2bkhz.onion is a Tor v2 onion service and v2 onion services are now deprecated and are no longer supported. Tor Project recommends onion service administrators migrate to a Tor v3 onion service.
[https://support.torproject.org/onionservices/v2-deprecation/](url) should be helpful with the migration.

**Comment by BjarniRunar** [comment]
Mailpile v1 is no longer being developed, so at this point this probably won't get fixed.

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
