### ISSUE TITLE
Improve output of terminal commands

### ISSUE THREAD

**Issue by ArthurHDRodrigues** [mailpile/Mailpile#2299]
I didn't find any issue addressing this, I noticed that some commands return raw json instead of a nice formatted text. I tested all the commands listed using `help` and found out `health` and `eventlog` do this. (Is there any other that I could have missed?)

So I guess that improving their output would improve the terminal user's experience.

I intend to work on it

**Comment by BjarniRunar** [comment]
Mailpile v1 is no longer being developed, so at this point this probably won't get fixed.

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
