### ISSUE TITLE
More than 14 email accounts -cannot select "Choose sending account" 

### ISSUE THREAD

**Issue by bai-yi-bai** [mailpile/Mailpile#2303]
I discovered today that I cannot select the "top" or first account alphabetically from the compose message/draft screen. I have more than 20 email accounts defined, but only 14 will display. There is no way to scroll up, the only way I was able to select the email account I wanted to send a message from was to use the HTML inspector and delete a bunch of nodes before I could click on one. This is not ideal. Sorry, a better email address picker is needed.

**Comment by BjarniRunar** [comment]
Mailpile v1 is no longer being developed, so at this point this probably won't get fixed.

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
