### ISSUE TITLE
Upgrade to Debian 11 Bullseye broke Mailpile

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#2309]
I recently upgraded my OS to Debian 11 Bullseye. This broke Mailpile. It appears that, due to the end of upstream support for Python 2.7, the Debian packages providing a number of Python2 modules have been removed from Bullseye, e.g. python-icalendar, python-appdirs, python-cryptography, python-lxml ... . Also, python-pip (for 2.7) has been removed.  It is present in Debian testing but has a number of serious bug reports.

After considerable hacking (e.g. attempting to install pip from testing and other packages from oldstable) with no success I decided to remove Debian Python2 packages completely from my Bullseye system and to do a "local" Python2 install (i.e. by a non-privileged user without using root). Then it was possible to use pip to install the needed Python packages. I still do not have virtualenv working, so I am not using it. Mailpile now works as before.

Of course this  is not a long term solution since there's no longer support upstream for Python 2.7 and it could result in security vulnerabilities. It works for now!

Here's an outline of the process, after upgrading to Bullseye.

- With Synaptic, as root, purge python2.7, python2.7-minimal, libpython2.7-minimal, libpython2.7-stdlib.
- Following advice [here](https://www.devdungeon.com/content/how-build-python-source) (see ** below) with apt, as root,
`apt install libncurses-dev libgdbm-dev libz-dev tk-dev libsqlite3-dev libreadline-dev liblzma-dev libffi-dev libssl-dev
`
- As unprivileged user (`jack` in this example), download [https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz](https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz)
- Calculate and check the MD5 hash of the downloaded file which is [here](https://www.python.org/downloads/release/python-2718/)
```
md5sum Python-2.7.18.tgz
38c84292658ed4456157195f1c9bcbe1  Python-2.7.18.tgz
```
- Extract the above and cd to the extracted directory, then
```
make clean
./configure --prefix="/home/jack/.local" --with-ensurepip=install
make
make install
```
- Go to the Mailpile program directory and install required Python packages using pip:
```
export PATH=/home/jack/.local/bin:$PATH
pip install -r requirements-dev.txt
```
- Launch Mailpile (substituting your own Mailpale data directory in MAILPILE_HOME):
```
export PATH=/home/jack/.local/bin:$PATH
export PYTHONHOME=/home/jack/.local
export MAILPILE_HOME="/home/jack/.local/share/Mailpile/jack"
./mp
```

Notes:

- ** If the apt install step specified above is not performed, the "make" step produces the following output:
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _curses            _curses_panel   
_sqlite3           _ssl               _tkinter        
bsddb185           bz2                dbm             
dl                 gdbm               imageop         
readline           sunaudiodev
Then pip crashes because it is unable to use https. The apt install step corrects this. The make step still complains about some "missing bits", but _ssl is not among them, and pip works.

- The make clean step does not appear to completely clean the installation configuration. It may be necessary to manually delete
/home/jack/.local/lib/pkgconfig
/home/jack/.local/lib/python2.7
/home/jack/.local/lib/libpython2.7.a
/home/jack/.local/include/python2.7

WIth Mailpile not working, I was forced to access my email with Thunderbird and K9Mail for a couple of weeks. This reminded me how much I like Mailpile, especially it's search capability. Thanks @BjarniRunar and the other contributors!

**Comment by fpiesche** [comment]
An alternate option might be to just run Mailpile from a Docker container, which requires a lot less messing around with your system installation. I've got a [GitHub repo](https://github.com/fpiesche/docker-mailpile) that automatically builds Docker images of both release versions (as and when they come out) and nightly builds of Mailpile's `master` branch whenever changes have been made.

My image is available at https://hub.docker.com/r/florianpiesche/mailpile/ and is my personal daily driver for email, and can be used in single-user mode by running
```
docker run -d \
  -v $HOME/.local/share/Mailpile:/home/mailpile/.local/share/Mailpile \
  -p 8080:33411 \
  florianpiesche/mailpile
```
This will make Mailpile accessible on your local machine at http://localhost:8080/, and store data in your home directory on the host for persistence.

**Comment by JackDca** [comment]
Thanks for the suggestion and the link. I've seen a lot of references to Docker in discussions of Mailpile. l've never used Docker myself, so for me there would be some learning required, but for some people this sounds like a good solution.

**Comment by BjarniRunar** [comment]
To facilitate running Mailpile v1 on modern distros, I've put together and published and documented "official" Mailpile docker images. See: https://github.com/mailpile/Mailpile-v1-Docker

Thanks everyone for helping out here!
