### ISSUE TITLE
Internal error: 'NoneType' object has no attribute 'mailbox_info'

### ISSUE THREAD

**Issue by alakel1** [mailpile/Mailpile#2310]
I recently installed Mailpile via Dockerfile to test it out, I connected an Outlook account to it and I configured it this way:
- IMAP/TLS: outlook.office365.com - port 993 - Authentication: `Password`
- No SMTP configuration 
- Encryption key: `Disable encryption for this account`

Now, what happens is that it was able to retrieve emails only from the "Sent" folder, but not from the inbox, and every time i open the inbox I get the message "Internal error! Sleeping", so I checked the logs and i found this traceback:

```
    "traceback": "Traceback (most recent call last):
  File \"/Mailpile/mailpile/mail_source/__init__.py\", line 1094, in run
    self.sync_mail()
  File \"/Mailpile/mailpile/mail_source/__init__.py\", line 307, in sync_mail
    elif (self._has_mailbox_changed(mbx_cfg, state) or
  File \"/Mailpile/mailpile/mail_source/imap.py\", line 983, in _has_mailbox_changed
    uv = state['uv'] = shared_mbox.mailbox_info('UIDVALIDITY', ['0'])[0]
AttributeError: 'NoneType' object has no attribute 'mailbox_info'
"
```

Is there something I can look for to get it working?

**Comment by BjarniRunar** [comment]
Mailpile v1 is no longer being developed, so at this point this probably won't get fixed.

Mailpile v2 is being written in Python 3, but it's not ready yet.

Thanks everyone for helping out here!
