### ISSUE TITLE
SSL certificate has expired for https://community.mailpile.is

### ISSUE THREAD

**Issue by BjornW** [mailpile/Mailpile#2311]
Hi, 
The link https://community.mailpile.is/t/a-very-uninformative-progress-update-mailpile-2/785 mentioned in https://github.com/mailpile/Mailpile/commit/0989ac1fe341d969ab2cc4d35af5625b3a122964 has an expired SSL certificate. It was expired the first of june 2022 See
![screenshot-2022-06-07_09-44-52](https://user-images.githubusercontent.com/65042/172325195-34377c39-b9c4-4f22-8f66-d92c99333e08.png).

**Comment by BjarniRunar** [comment]
Fixed, thanks for reporting!
