### ISSUE TITLE
Raspi: Epiphany will not load local network web-pages

### ISSUE THREAD

**Issue by FlailAway** [mailpile/Mailpile#2319]
I have an old Pi-B+ (will not pay scalper prices for 3-B+). It cannot run Chromium so I installed Epiphany but it will not load an IoT web-page (Ajax Updating). I can ping the router OK, but E sits there thinking about it for 2-minutes then says "Unable to display that website." There is no Internet on that network.

The router is at 192.168.100.1, the Raspi local IP is 192.168.100.38, the router is working with IoT-Nodes beyond that, like 192.168.100.132 so it is unlikely to be out of range as it is set 192.168.100.2 -- 192.168.100.150.

I know the Network is Live as I can see (laptop Mint+MATE 21.1) a clock ticking from a Node in the garage 600-feet away. I have tried both wired and Wifi, both Ping but no webpage.

What do I need to do to make this work as I need to set it for lxsession-autostart when working.

**Comment by BjarniRunar** [comment]
I think you have filed this in the wrong place! This is Mailpile, not Epiphany, not Raspberry Pi.

Closing as off-topic.
