### ISSUE TITLE
Alternative data storage (S3 or DB)

### ISSUE THREAD

**Issue by brmassa** [mailpile/Mailpile#2322]
I've recently installed Mailpile in my VPS but downloading Gmail (that over there it says it's about 3gb) became 23gb by 1/3 of the mails, exausting the VPS local storage.

I would suggest to implement a either a DB efficient storage option or even S3 to allow off loading the storage requirements.

Also, would like to understand this huge storage consumption.

**Comment by verbunk** [comment]
I'm not sure of the current options in Mailpile for this but echoing brmassa, I'd love to see an 'Outlook style' approach. If designated by the admin an (ideally s3 compatible) HTTP object store can be used to offload the files into and the bare message text can be indexed into some DB with search seperately.

I can imagine Mailpile stripping the files from the message and rehydrating into a file pushed to object store when the mail is being accepted form the upstream MTA and the link in the viewer just links to it.

**Comment by BjarniRunar** [comment]
This code-base is no longer being updated, as is made clear in the README and on the front-page of the github repo. Sorry!
