### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [mailpile/Mailpile#2323]
### Description:

In the "Mailpile/packages/windows-wix/provide/cache.py", I have identified a security vulnerability about insecure SSL/TLS Verification and configuration. Bypassing certificate verification or accepting all host names are considered insecure. "ssl._create_unverified_context()" shouldn't be used to create SSL/TLS context

### Location:

https://github.com/mailpile/Mailpile/blob/master/packages/windows-wix/provide/cache.py#L55

```python
context = ssl._create_unverified_context()
```

### Reference

- **CWE-295: Improper Certificate Validation**

### Recommendations:

Use a SECURE SSL context with proper verification.

**Comment by BjarniRunar** [comment]
This code-base is no longer being updated, as is made clear in the README and on the front-page of the github repo. Sorry!

But in any case, I doubt that code is used anywhere - using grep to find "security vulnerabilities" is not helpful, please stop.
