### ISSUE TITLE
google

### ISSUE THREAD

**Issue by gabi21yt** [mailpile/Mailpile#2324]
hello i think google credential is outdated ?
![Screenshot_20240902_024101](https://github.com/user-attachments/assets/bfe5ccdd-93ec-4a4c-a1ad-022d5ba30f2a)

**Comment by Angelokz** [comment]
I think we should upgrade the system

**Comment by BjarniRunar** [comment]
Thank you for reporting this, but this codebase is not being updated or maintained. Sorry!
