### ISSUE TITLE
Develop "SMS" Plugin

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#268]
Wouldn't it be cool to send and receive SMS messages right along side your emails? How about threading together conversations of email & SMS? This is a Plugin idea to do just that.

We've started spec-ing out some possible places for plugins to interface with Mailpile, and in doing so setup a repo with a few rough, plugins https://github.com/mailpile/plugins

Anyway, ping me @brennannovak about this if you're interested in working on this!

**Comment by BjarniRunar** [comment]
AFAICT, there is no way to send SMS messages without authenticated access to proprietary services. Since there's no way for us to include such in the open-source Mailpile, this is probably never going to happen.

Closing for that reason.
