### ISSUE TITLE
Feature: Undo & Better UI Notification Bubbles

### ISSUE THREAD

**Issue by raphaelbastide** [mailpile/Mailpile#34]
I really love Gmail's "Undo" option after an email is sent.
It could be awesome to find it back in Mailpile.

**Comment by BjarniRunar** [comment]
Clarification: Undoing send has not yet been implemented. However, tagging can be undone; unfortunately the send action is more than just a tag, the message is finalized and becomes immutable. That might need to change. :)  Commenting further on #1077.
