### ISSUE TITLE
RFE: Trust on first contact opportunistic GPG

### ISSUE THREAD

**Issue by sdaugherty** [mailpile/Mailpile#38]
Several of the GPG developers have discussed the possibility of opportunistic GPG encryption and message signing on a "trust on first contact" model, similar to that of SSH. (article here: http://lwn.net/Articles/464137/)., whereby the public key for email correspondents would be automatically retrieved and imported, and given some indication of "marginal" trust (and assurance that the key can't be changed without you knowing once you begin corresponding with someone).

Despite the obvious security weakness, in the form of one-time vulnerability to man in the middle attacks, this strategy overcomes a serious usability weakness for a net gain in security in most real-world circumstances. Noting the benefits and limitations, this should obviously be a supplement to traditional rigorous GPG verification and key management practices , with clear indications as to the level of identity assurance in the user interface.

I think Mailpile could be a good place to experiment with this strategy, since a web based interface can be easily tailored to display necessary trust information and security warnings in an intuitive way, and can automate the necessary GPG functions to automatically track keys.

**Comment by BjarniRunar** [comment]
This is now part of our security roadmap: https://github.com/mailpile/Mailpile/wiki/Security-roadmap
