### ISSUE TITLE
Alternate UIs resembling popular webmail services

### ISSUE THREAD

**Issue by malexmave** [mailpile/Mailpile#402]
This is not per se a feature request for the core developers, and more of a general idea for the community:

It would be awesome if we could develop some frontends (Skins) that resemble popular webmail services (GMail, Outlook.com, web.de, ...). This would make migrations of users of those services to mailpile easier, as they do not have to learn a new UI.

Question to the core devs: Is it useful to start working on something like this right now, or will everything change so much that everything we develop now would have to be rewritten until beta / launch?

**Comment by nkoehring** [comment]
I don't know the current state of the frontend part and how modular/themeable it is. But having a theme based frontend shipped with a default theme has (in my oppinion) more value than just beeing able to make transitions from (again in my oppinion) ugly web interfaces like that from web.de easier.

It is way more valuable to see this as an possibility to make future changes simple and elegant. As Mailpile becomes more mature some day, peoples oppinions about design and layout will change. To be chained to the original layout or the way it was thought of in the beginning could be hindering then.

**Comment by lukebranch** [comment]
@bnvk ,

I just wanted to check if there has there been any developments on the separation of the design from the content to allow for themes for this project.

I am considering integrating it into a project i'm building with Odoo (ERP + CMS) to allow users to access webmail from their Odoo login/interface. Mailpile seems like the ideal project for it as it's built in python.

I'd be looking to use an already pre-built admin template like Porto Admin which has some webmail layouts already, and simply integrate it into the project that way. With this in mind some form of modularity when it comes to the interface design would be great, as it would allow for tighter/smoother UI integration with current projects.

**Comment by bnvk** [comment]
@lukebranch no real progress has been made towards themeing of Mailpile. Based on the [Roadmap](https://www.mailpile.is/roadmap/) it's not going to be worked on until post 1.0 release.

**Comment by lukebranch** [comment]
@bnvk ,

Thanks for letting me know. I'll look into forking it for my own uses in the meantime.

Really nice work on this project by the way, it's going to come in very handy for a number of projects in the future.
