### ISSUE TITLE
Non standard directories (linux)

### ISSUE THREAD

**Issue by comzeradd** [mailpile/Mailpile#425]
Setting up Mailpile requires some files to be placed in places that are not standard for most linux distributions. (I can open separate bugs for each case if you think it would help address them.)

_Static_
These are stored under /usr/static/default which besides the fact that it doesn't relate to mailpile (eg. /usr/static/mailpile/) is not really the correct dir for web based projects. It should be something like: /usr/share/mailpile/static/

_Localization_
These are stored under /usr/locale/ but they should be under /usr/share/locale/

_Tests_
These are stored under {python_sitelib}/tests again with no reference to mailpile. Probably something like {python_sitelib}/mailpile/tests would be better.

**Comment by BjarniRunar** [comment]
I think this has been addressed by @aviau 's packaging work. I am going to close this, will reopen if bugs are found when we start building packages.
