### ISSUE TITLE
Why I use Outlook.com

### ISSUE THREAD

**Issue by OscarGodson** [mailpile/Mailpile#45]
As per the request of @brennannovak, here's the reasons why I use Outlook.

I used to use Gmail. I was a user since the beta. A friend invited me, and I remember the little invite module on the bottom left ;) Gmail has grown a lot, and the features keep on coming. It's becoming bloatware, in my opinion. I mean here's a _quick_ breakdown of the features of Gmail.
- Make calls
- Video chat
- Send texts
- Chats
- Group chats
- Labels
- Filters
- Promotions
- Social tab
- Priority inbox
- Display densities
- Themes
- Contacts
- Tasks
- Google + Integration

Those are the ones I thought of off the bat. Almost all of these features are shown on the main inbox page. Some are hidden in dropdowns, but there's buttons on that page. I dont want my email to be a task list, phone, contact organizing, social all-in-one app, _I want it to do email_. 

Outlook has contacts in a separate app. You can completely hide chat. I never use it, so it's alway hidden so it's like it doesn't exist. It has categories and filters and all that, but again I can hide it. This is the left sidebar:

![image](https://f.cloud.github.com/assets/20615/913175/5b4b1622-fe11-11e2-971e-1669d64d270e.png)

Much cleaner. Now look at the header / action bar area:

![image](https://f.cloud.github.com/assets/20615/913176/67ea2d8c-fe11-11e2-81aa-9c71f8f8b086.png)

This will change. If you go to an email some buttons will appear, but not many (like, Reply). This is Gmail (taken from a friends):

![image](https://f.cloud.github.com/assets/20615/913183/839fd0e0-fe11-11e2-984a-08233ec53974.png)

There is one feature I do like that I don't think Gmail has, or if it did or does I never found it. At the bottom of all newsletters and things like GitHub notifications Outlook will have a "unsubscribe" link. It'll automatically unsubscribe you from newsletters without you having to click the link, login, etc.

![image](https://f.cloud.github.com/assets/20615/913198/d3c8d864-fe11-11e2-90e2-7e3c552e1cb3.png)

Hope this helps!

**Comment by step21** [comment]
And you think Outlook is not bloatware? It is also changing all the time. Even the business/apps version. Which is prob why most ppl use it.

**Comment by BjarniRunar** [comment]
Thanks for your input everyone, but I'm going to close this as it doesn't actually contain any concrete issues to work on or discuss. A general anecdote requesting we not overload Mailpile with features one person doesn't want (but others obviously do...) isn't really on topic when our main concern is a lack of programmers and resources - we couldn't overload Mailpile with features even if we wanted to; we don't have the developers (yet).
