### ISSUE TITLE
Make "map" view of contact locations plugin

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#460]
I've always wanted a visual way of plotting where my social graph exists on a map, so I can easily navigate to and browse my friends & contacts in different cities when I'm visiting. This startup **Connect** has done a pretty nice job, no reason why a plugin couldn't be made to do a similar thing!

![screenshot 2014-02-26 01 52 01](https://f.cloud.github.com/assets/48677/2265815/b6623b68-9e88-11e3-983e-fbe468513ca5.png)

**Comment by BjarniRunar** [comment]
I don't see where we'll get the input data: e-mail isn't exactly geocoded and we often don't even get an IP address. I'm going to be a spoilsport and close this as infeasible - it's certainly not low hanging fruit if we don't even have a data source. :-)

**Comment by bnvk** [comment]
@BjarniRunar I had been thinking looking at addresses in vCard data, as well as in email signatures or perhaps a plugin that runs a regex on message contents in general, then does geocoding, like @smari mentioned...

But yah, pipe dream feature and not needed for a 1.0 ;)
