### ISSUE TITLE
Create a plugin allowing users to send password protected links to Mailpile's web server instead of attachments

### ISSUE THREAD

**Issue by eternaltyro** [mailpile/Mailpile#475]
It'll be nice to have a way of sending (symmetric key) encrypted messages to people who don't use encryption. This can be done by way of a challenge response system. I've seen this in action when I used libpurple (libOTR). 

So you can have an "Encrypt for noobs" checkbox or so. And then there'll be two text boxes: one where you'd put a question (which you know the recipient knows the exact answer to) and another where you'd type the expected answer (case sensitive). This answer would serve as a key to the encryption algorithm. Optionally, you could have a drop down to select the cipher (AES, Twofish, etc) with the default being the least CPU intensive. 

Once Alice clicks send, Bob gets a mail in his inbox with a link to alice.com/secretstuff/somerandomshitherededicatedtobob123.html or so and clicking on it takes Bob to a page that shows him the question.

Question: How did the squirrel crack the Walnut?
Answer:  Some placeholder text here asking him to type the answer
[decrypt button]

Typing the right answer and clicking 'decrypt' button could display the mail in a new tab. Just an idea.

**Comment by BjarniRunar** [comment]
I have removed the low-hanging-fruit label; this isn't actually easy to do until Mailpile's remote access support is a bit more developed.
