### ISSUE TITLE
Folders not visible on lower resolutions

### ISSUE THREAD

**Issue by oerdnj** [mailpile/Mailpile#485]
I have an oldish HP mini-notebook with 1024x600 resolution and the responsive (is that the new webX.0 word, right?) hides the left side menu with folders with no way of showing them.

Various other usability bugs reveal if you lower the browser window size (double scrollbars, etc.)

**Comment by BjarniRunar** [comment]
Closing this, I am pretty sure responsive design issues are being tracked elsewhere. Thanks for filing!
