### ISSUE TITLE
Implement smart per-contact "crypto policy"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#487]
Mailpile should automatically figure out what is the best way to communicate with someone, based on the history of how they have communicated in the recent past. This should allow us to, by default, offer the highest level of security that doesn't become a nuisance during everyday use.

Original issue text: This should allow deleting of a PGP key from keychain, but not the contact from contacts API

**Comment by BjarniRunar** [comment]
This works as of ce1da3b4c83df5eadf89393ada88ef62605ab8fe - some UI is missing for setting custom per-contact policies, but the basics are now in place.
