### ISSUE TITLE
The Filters system needs to be documented

### ISSUE THREAD

**Issue by pagekite** [mailpile/Mailpile#506]
We need to document, promote and improve the Filters system, so people will know it exists and can be used instead of writing custom plugins for adding/removing tags. 

Hopefully, encouraging contributors to make sure the attributes they want to filter on are searchable, and then using filters to assign/remove tags should lead to a more powerful and flexible search engine and minimal duplication of functionality in the codebase.

The Wiki page that needs improving is here: https://github.com/pagekite/Mailpile/wiki/Filters

**Comment by robotanarchy** [comment]
The wiki page is two years old now, and has outdated information (there is no `mailpile/plugins/filters.py` file anymore).

Can someone give an example of how to add one filter via CLI? I can't get it working:
```
mailpile> help filter

Commands:
    filter        [new|read] [notag|maketag] [=<mid>] [<terms>] [+<tag>] [-<tag>] [<comment>]
                                                                     Add auto-tag rule for current search or terms
    filter/delete <filter-id>                                        Delete an auto-tagging rule
    filter/list   [<search>|=<id>|@<type>]                           List (all) auto-tagging rules
    filter/move   <filter-id> <position>                             Move an auto-tagging rule
mailpile> filter new notag from:notifications@github.com +github "GitHub notifications"
Elapsed: 0.002s (filter: filter)
Need flags and search terms or a hook
```
Mailpile version: 0.5.2 ("Beta III updated")
I will try to rewrite the wiki page once I can get filters working in my setup.
