### ISSUE TITLE
Add "Filter" preset + UI nav elements 

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#519]
As discussed in this article http://time.com/25472/5-email-mistakes-that-are-basically-killing-you/

"You get sucked into the “cc” black hole. If you’ve been cc’d, your input isn’t critical and you probably don’t even need to reply, experts say. Add default rules or filter in your email system that bumps messages where you’re not the primary recipient into another folder"

This seems like something reasonably easy to implement!

**Comment by BjarniRunar** [comment]
This never got designed or worked on; although not a bad idea I don't think we need an open issue for every single unexplored UI idea. Closing. :-)
