### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by nospoftombl** [mailpile/Mailpile#53]
Are there any plans to implement a calendar, e.g. reading from an exchange-server, caldav-support, ... ?

**Comment by redeyesdemonkyo** [comment]
any headroom in this direction

**Comment by katipallya** [comment]
I'm new to open source development in general but looking to contribute to this project - looks very interesting. Would be willing to help on this functionality with some assistance.

**Comment by BjarniRunar** [comment]
Hi @katipallya! Adding an entire calendar is IMO much too big a task to start with... but if you prove me wrong I will be pleasantly impressed. It would be great to have this functionality, but the core team (just me at the moment) is too busy with other things to work on it any time soon.

You might want to consider browsing our Issues for "low hanging fruit" to find smaller tasks first, to get familiar with the code base. Also come find us on IRC and read the development guidelines! :-)
