### ISSUE TITLE
Improve plugins/smtp_server.py

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#532]
The  SMTP server plug-in is currently barely functional and has some critical security holes. Things to do:
- Incoming e-mail addresses should be checked for validity
- Limits should be placed on the size of incoming data (currently all is buffered to RAM - a DOS attack waiting to happen)
- Activity should be logged to the Event Log (for debugging and user feedback)
- Something should be done to limit spam; some sort of hash-cash would be nice, as well as basic grey-listing and/or a white-list which checks senders against the user's address book.

Fixing this plug-in is critical to getting SMTorP (direct mailpile-to-mailpile delivery over Tor) to a usable state.  See https://github.com/pagekite/Mailpile/wiki/SMTorP for motivation and details.

(If you decide to work on any of these issues, please leave a note in the comments.)

**Comment by matteke** [comment]
I'll do part of them, cant do validation check as I'm not sure how to check them

**Comment by BjarniRunar** [comment]
Hey @matteke ! Thanks, and welcome. Have you visited our IRC channel?

Checking the validity of incoming e-mails is actually tricky; Mailpile doesn't necessarily know about all your e-mail addresses (assuming we want to accept all of them, which there are actually good reasons to do), and since we haven't written the code for integrating this with Tor hidden services, we also don't really know the onion address yet.

Probably as a first start for validation, it makes sense to accept any of the e-mail addresses the user has configured as an account, as well as "plussed" variations of those. So if I have an account "bre@mailpile.is", the SMTP server would accept that e-mail, as well as any "bre+JUNK@mailpile.is".

This will inevitably end up expanded and changed as things develop, but just having a code path (a function or two) for performing validation checks would be a good step forward.

**Comment by matteke** [comment]
Hi @BjarniRunar
I havent visited the irc yet, thanks for mentioning it, i will surely visit. Thanks for explaining it, I need to make some further research, but now I have a slight idea on how to do it :)

**Comment by noahhaasis** [comment]
I would like to work on the validation if that's ok. I looked a but in the code and from what I saw I have to edit _is_dangerous_address and _is_spam_address. Am I right there or is there something I overlooked?

**Comment by BjarniRunar** [comment]
@noahhaasis It would be great to have some improvements here! I took a quick look - those are not the functions that need updating to address the validation of incoming addresses. Those were placeholders for implementing blacklists to reject incoming mail by sender/recipient, which isn't quite the same thing as validating that the incoming mail is actually addressed to us. So the `smtp_RCPT` function needs some new checks I think.

**Comment by noahhaasis** [comment]
Ah ok. So we want to ensure that the incoming emails are actually addressing the user?

**Comment by noahhaasis** [comment]
Two more questions. How to I access the users emai address and should with process the tags of an email or just ignore them. (e.g haasis_noah+sample_tag@yahoo.de)

**Comment by noahhaasis** [comment]
We already have a similar function in javascript https://github.com/mailpile/Mailpile/blob/9d2bfb30bf57cd6fbba8003ae489b07496c7c431/shared-data/default-theme/html/jsapi/compose/recipients.js#L29

**Comment by klosnet** [comment]
lets get this going

**Comment by BjarniRunar** [comment]
Oops, looks like I missed a question there. Sorry @noahhaasis, and thanks @klosnet for the ping.

I think processing the plus-part as a tag is an interesting idea. GMail does this, and it doesn't seem to be a vector of abuse there... so probably we could too, with a few sanity checks (don't want people injecting things into the Outbox or Drafts, for example). But I think that should happen at a different layer, if we decide to support plussed addresses, it should also work for mail arriving over IMAP or from local mailbox files - so it's not directly part of this Issue.
