### ISSUE TITLE
Support nested Maildirs

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#537]
Mailpile currently does not understand nested Maildirs. It would be nice if it did. If I understand this bug correctly, nested Maildirs are Maildirs that in addition to the new/cur/tmp folders, may have other folders which themselves are Maildirs.

Supporting nested Maildirs is requires augmenting the AddMailboxes command in `commands.py` so it doesn't just add discovered mailboxes, but actually looks inside them as well, if they are folders. Care must be taken to ignore the new/cur/tmp folders though, as otherwise individual messages might get added as mailboxes.

Notes:
- This issue replaces #428, which contained a bunch of details about symptoms relating to this limitation, where the user had moved mail into a subfolder, thus rendering it invisible to Mailpile.
- The approach described above has the limitation that new subfolders won't get picked up unless the user re-runs the add command on the same mailbox. This can be ignored for now, as it will get addressed by the re-factoring work done for IMAP, where the same kind of discovery of new/renamed folders is a requirement.

**Comment by jgonsior** [comment]
+1

**Comment by slef** [comment]
+1

**Comment by singpolyma** [comment]
+1

**Comment by dkm** [comment]
+1 :)

Even adding subdir one by one would be ok for me, but my server uses `.<name>` pattern, and dotted names do not show up when browsing from Mailepile `browse` page...

**Comment by davidovitch** [comment]
+1

**Comment by BjarniRunar** [comment]
This has been supported by the local mail source for quite some time, e.g. see CL 1d3c65456ae2d8f1d299b8270e337e0ef0c9a7d9.

The browse interface has had some bugs (and I have a massive PR pending to fix a whole bunch of them), but I am unaware of any code that prevents browsing of folders starting with a "." - quick tests at my end show that I am able to browse IMAP folders starting with a dot just fine.

I'm going to augment the add command as discussed above and close this - if it still doesn't work then that's a bug and I'll need specifics. :-)
