### ISSUE TITLE
Passing sudo -E to Makefile

### ISSUE THREAD

**Issue by douglaskastle** [mailpile/Mailpile#543]
I tried to install mailpile to a local machine I have that is stuck behind a proxy.

As the local user I have HTTP_PROXY and HTTPS_PROXY set as environment variables.  When I want to use pip as sudo you need to use "sudo -E" to pass the user local variables to the sudo command:
```
    sudo -E pip install 'selenium>=2.40.0'
```
Even though I call the make command using -E
```
    sudo -E make debian-dev
```
The -E option is not passed into the make file so the pip and gem installs fail.

I have hacked the Makefile to add -E to all instances of sudo in debian-dev and installation is successful.

I have to say I am not an expert on Makefile and it's interaction with sudo so I don't know if it is possible to the Makefile to pick up the options passed in with the sudo command

**Comment by BjarniRunar** [comment]
I don't think we'll be doing this by default, as sudo -E is probably considered a security risk in many cases. Folks who need it can edit the Makefile, they are developers after all. :-)

Thanks for taking the time to report this issue and file! People having the same problem may well find this bug and your solution, if they try searching, which is great.
