### ISSUE TITLE
Create JS hidden / secret / pass reveal plugin

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#548]
Saw this nifty UX suggestion, should be pretty easy to implement and offer a slight amount of privacy + usability gain for pages with passwords, keys, etc...

![](http://24.media.tumblr.com/247ed473e7f63149cf6eb4eb88623677/tumblr_n0nps0N3HL1qea4hso1_1280.png)

**Comment by BjarniRunar** [comment]
I don't think we're doing this. :-)
