### ISSUE TITLE
All activities of a person

### ISSUE THREAD

**Issue by nospoftombl** [mailpile/Mailpile#559]
emClient has a very nice feature, which lists all activities to one person: emails sent and received, appointments, tasks etc. in chronological order. You get this view if you click on a person (e.g. email-sender or -recipient) anywhere in the GUI. If you move the cursor over an entry in the list a popup shows details of the email, activity etc.

It would be very nice to see this feature in Mailpile too ;-)

**Comment by BjarniRunar** [comment]
This has been implemented to some degree, both for your own accounts (on the home page) and for individual senders when you click on a message from them in the search result view. More will surely be implemented as time passes.
