### ISSUE TITLE
Implement "Notifications" UI dropdown tab

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#560]
The ever so popular Facebook notifications tab gets seen by millions of people per day... we plan to borrow this concept and implement a "Notifications" style drop down that shows a Mailpile users activity and allows them to navigate or perform simple actions on items in menu!

![facebook notifications](https://cloud.githubusercontent.com/assets/48677/2618157/a2147624-bc1c-11e3-86cd-dfb91529e23e.png)

**Comment by BjarniRunar** [comment]
This exists, although not in the original design.
