### ISSUE TITLE
More responsive design :: make the left menu optional below a certain horizontal resolution

### ISSUE THREAD

**Issue by mailpile-issue** [mailpile/Mailpile#565]
![root](https://cloud.githubusercontent.com/assets/7192286/2623871/d59e39f2-bd0d-11e3-8ac2-9bbbac6d115c.png)

when the horizontal resolution becomes too small only parts of the email can be seen in folder view

please make the left menu optional, perhaps with a menu on the bottom on the screen like the current openXchange does.

generally a more responsive Design would be awesome :)

**Comment by BjarniRunar** [comment]
This has been done, but needs a lot more work. Currently being tracked in #1599.
