### ISSUE TITLE
Speed and/or cache attachment thumbnails somehow

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#591]
Currently loading an email with 5 image attachments that are each 3 MB in size, takes about 15 seconds for the thumbnails to display (after rest of page has loaded).

It seems that the browser generates the new thumbnail for `/message/download/preview/=FW4/part:4/` path each time that url is requested. 

Can we explore other options to improve upon this?

**Comment by BjarniRunar** [comment]
AFAICT, the browser caching is working just fine. Some parts of this pipeline are still agonizingly slow, but that's a different issues.
