### ISSUE TITLE
Make spam detection aware of conversations

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#629]
I'm noticing an interesting trend in my spam situation- about 84% (10 / 12 messages today) of the messages that show up in my Inbox are part of threaded conversations. Whatever the current threading algorithm uses to determine such things, it's doing it correctly (or incorrectly), but all these messages contain the same name, subject, and oftentimes content.

Can we leverage that in some way to improve upon spam?

**Comment by BjarniRunar** [comment]
I think this is obsolete, I haven't seen anything like this... for years. :)
