### ISSUE TITLE
Display HTML emails safely and elegantly

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#631]
We have decided to render HTML emails using the HTML5 "sandbox" attribute on IFRAME as it offers lots of security advantages, read more here:
* http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/ 
* http://www.whatwg.org/specs/web-apps/current-work/multipage/the-iframe-element.html#attr-iframe-srcdoc
* http://www.whatwg.org/specs/web-apps/current-work/multipage/the-iframe-element.html#attr-iframe-seamless

The current code looks like:

```
< iframe class="thread-item-html" onload="mailpile.thread_html_iframe(this)" sandbox="allow-same-origin allow-popups allow-top-navigation" seamless target="_blank" srcdoc="" >< /iframe >
```

There is a tiny bit of JS that dynamically resizes the iframe height. Currently the styling of these HTML messages is quite ghastly (bare HTML), and untested with a lot custom styled emails. We **should** make

* Bare HTML styling match that of plain text email styling
* Allow custom styled HTML emails to retain their styling

**Comment by BjarniRunar** [comment]
Additional resources (hints from the helpful guys at Whiteout):

 - https://github.com/whiteout-io/mail-html5/blob/master/src/js/controller/app/read-sandbox.js
 - https://github.com/cure53/DOMPurify

**Comment by BjarniRunar** [comment]
Mostly done! Closing, we're now in bug-squashing territory, except for #1476.
