### ISSUE TITLE
Strip out noisy junk from "Subject" lines

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#633]
Do you hate those noisy subject lines that look like "Re: Re: Re: Fwd: Lets Save The Whales?" Well, hopefully you detest that noise as much as I do. I'm creating a little simple filter that strips those things out.

However, this varies in foreign languages and we will need to expand this filter to account for those as well... hopefully some of you fine community folks who speak other languages and are bothered by this sort of thing can help out here ;)

Currently we are stripping out:

```
Re:
Fwd:
Aw:
```

If you want to add more things to strip out, just edit the regular expression in `mailpile/jinjaextensions.py` inside the `nice_subject` method where it says `re|fwd|aw`

**Comment by ryantate** [comment]
In my experience this was a bad decision.

I received a message today, the Fwd: had been stripped from the subject line, and furthermore Mailpile "helpfully" hid the entirety of the forwarded text under three dots. I completely missed the intended meaning of the message as a result until a series of about 6 messages had been exchanged to clear up the confusion.

You have here referred to this information in the subject line as "noise," "legacy," and part of a "crap interface." But there is a reason these conventions exist and you need to be REALLY careful before you start deciding to throw information on the rubbish heap.

At the very least, you should SHOW not hide the forwarded text, but ideally, maybe stop munging my messages so much or give me an option to opt out of this aggressive processing!

Again, Mailpile is wonderful in many ways but you are making a lot of dubious decisions that have little or nothing to do with making a good encrypted mail client, in my opinion.

**Comment by BjarniRunar** [comment]
Thanks for the feedback, @ryantate. You make totally valid points.

I also have been bitten by the three-dot content suppression being too aggressive. I think that warrants an issue of its own, which I'll open after commenting here.
