### ISSUE TITLE
Improve upon "Photo Attachments" in message view

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#636]
Currently this is a bit meh- it only shows a thumbnail & upon clicking it just downloads the picture. Some obvious ideas are:
- Upon clicking on image show a larger size version in a lightbox
- Offer explicit "Click to download" link under each image (maybe only show on hover)
- Offer a "Download All" link
- Offer a "Forward single (and all) images"

**Comment by teon** [comment]
+1

**Comment by BjarniRunar** [comment]
Potentially useful: http://photoswipe.com

**Comment by ferdiga** [comment]
+1

**Comment by ferdiga** [comment]
1.0.0rc0
the "obvious ideas" above are also valid for all other attachment types
