### ISSUE TITLE
Implement better Signature & Quote detection

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#644]
I'm not quite sure of how the backend text part filtering process happens, 

For some of the custom, yet highly repeated signatures, I imagine the solution will be to regex this junk into a `text_part.type.quote` similar to we are doing for Subject lines in #633 for strings like:
- `Sent from my iPhone`

A common thing I am seeing that eludes our current `quote` detection code is these variations:
- `On 04/23/2014 10:04 AM, Brennan Novak wrote:`
- `On May 1, 2014 at 3:29:00 PM, Brennan Novak (email@address.com<mailto:email@address.com>) wrote:`
- `On Wednesday, June 4, 2014 3:36 AM, Brennan Novak`
- `On Thu, May 8, 2014 at 1:01 PM, thuglyfe@gangstermail.com`
- `-----Original Message-----`
- `---- Original Message ----`
- `---------- Forwarded message ----------`
- `-----Ricky James wrote: -----`

Of course, growing these regex's for other languages will be an ongoing process, but a really worthy one, I believe :)

*`-----Ursprüngliche Nachricht-----`
*`Am Samstag, 27. Dezember 2014 schrieb Brennan Novak :`
*`Den torsdag 15. januar 2015 skrev Brennan Novak <`

As @BjarniRunar described in a previous issue: the code that does this lives in mailpile/mailutils.py in and around the parse_line_type function. Labelling as low hanging fruit in case someone wants to get their hands dirty...

**Comment by wiml** [comment]
For plaintext emails, it might be worth examining the behavior of [Emacs Supercite](https://www.gnu.org/software/emacs/manual/html_mono/sc.html) for inspiration. [This page](http://www.emacswiki.org/emacs/CategoryMailAddons) points to a few other citation/quoting packages developed for emacs-based mail and news readers.

**Comment by GaryHoppenworth** [comment]
I would totally like to give this issue a try.
Could you please assign me?

**Comment by BjarniRunar** [comment]
Hi Gary! No need to be assigned - just start hacking! This issue is a bit old and broad in scpoe, and I haven't given it much thought recently. So perhaps we should begin with defining what exactly you'd like to improve?
