### ISSUE TITLE
Plugin that makes a "read receipt" on messages

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#649]
So that you can know your message has been read by the recipient. Of course, this would require both users to be using Mailpile as a client.

And for privacy sake it would need to be enabled by the person "reading" the email. 

One approach would be to kick back email with a specially encoded header that communicates it is a read receipt only. Another approach would be to hit a webhook API endpoint (only works for parties that have public URL instance of Mailpile).

**Comment by BjarniRunar** [comment]
There's a standard for that: https://tools.ietf.org/html/rfc3798
