### ISSUE TITLE
Install: missing dependency

### ISSUE THREAD

**Issue by Tastalian** [mailpile/Mailpile#653]
Hi guys,

I have been installing Mailpile on Debian Wheezy and needed to install an extra dependency, namely *python-lxml*, which is not included in the Makefile's debian-dev rule.

(Also, as of today there is no *phantomjs* package on wheezy.)

Hope this helps,

**Comment by BjarniRunar** [comment]
This may or may not still be broken. Closing because it's a year old - I'm sure packagers will figure things out when packaging work happens. :)
