### ISSUE TITLE
Create "Social Feed" plugin that renders a search result like a Facebook feed

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#672]
There is a rough template for this idea called "Social Feed" in the plugins folder. 

Early interface designs for Mailpile included a more detailed style search view (but not quite a full social media experience), you can see this concept here:

![mailpile_0_1_interface_inbox](https://cloud.githubusercontent.com/assets/48677/2929978/01bf85f8-d790-11e3-9a08-591901865421.png)

That has been moved out of the core theme due to how nasty & complicated the HTML in the search view would have become... hopefully someone will feel inspired to hack on this :)

**Comment by Konzertheld** [comment]
Oh great, that looks similar to what I have in mind. If this can be combined with better conversation merging (so that really all messages from a person are grouped to this person to be then shown like in your image) I'm in.
