### ISSUE TITLE
Add ability to drag & drop tags onto message Thread View

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#685]
Not sure if this functionality should exist ONLY on the thread (all messages) or on individual messages. My hunch is adding both functionalities would be overkill, but one of the two would be nice. 

Design wise, it's most easy to add to the whole thread (at the top). However, this then opens up questions about what it actually "does"
- This should go through and apply the tag to all messages in thread
- Does this behavior auto add that Tag to new messages downloaded in the future?
- Does removing tag remove from all messages in thread?
- Can we do interesting "actions" bound to Tags that are assigned to a thread? Such as:
- \* Auto remove message from Inbox after last message is replied to

**Comment by BjarniRunar** [comment]
This is obsolete; the inline e-mail view is working well enough (and has this feature) that I think thread view is actually destined for removal. Maintaining both doesn't really make sense given the current resources of the project.
