### ISSUE TITLE
accessing encryption features?

### ISSUE THREAD

**Issue by titaniumbones** [mailpile/Mailpile#687]
Hi,

I'm trying to use the Web UI to encrypt an outgoing message to myself. My public key is stored in ~/gnupg/pubring.gpg.  However, I don't see any kind of options in the webui for managing contect key, and when i try to sign the outgoing message, the signing operation fails.  Just for kicks I've tried the same on the demo, and e.g. trying to send an encrypted message to Brendan fails with "Error prepping this message for decryption".  Is this feature available, and if so, how do I access it/perform ordinary tasks like key management, etc.?  I have made a quick search through the wiki and don't see how to do it.  Thanks!

Matt

**Comment by BjarniRunar** [comment]
This issue lacks enough detail to be reproduced, and is probably obsolete by now. Closing - but thanks for filing!
