### ISSUE TITLE
CardDAV integration for contact sync

### ISSUE THREAD

**Issue by deepdivingspearo** [mailpile/Mailpile#705]
Would allow users of services like OwnCloud to sync contacts seamlessly between devices/applications and Mailpile address book.

**Comment by BjarniRunar** [comment]
This is a dup of #104, closing. I made a note there that there are many useful comments on this thread.

**Comment by BjarniRunar** [comment]
This is a dup of #104, closing. I made a note there that there are many useful comments on this thread.
