### ISSUE TITLE
Handle password protected keys.

### ISSUE THREAD

**Issue by boris-arzur** [mailpile/Mailpile#707]
My own gpg key is password protected.

Mailpile never asks for me to unlock the key, so I figure this is why it fails at :

$ ./mp
Access denied: GPG (version: gpg (GnuPG) 2.0.22, location: /usr/bin/gpg) was unable to decrypt the data: error

**Comment by BjarniRunar** [comment]
Mailpile is not compatible with gpg2 yet, follow #1133 for progress/news.
