### ISSUE TITLE
Improve PGP compatibility of outoing mail?

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#710]
Currently, all PGP signed or encrypted messages we generate, use PGP/MIME. This is the most elegant and standards-compliant way to do PGP.

However, the real world is not elegant. This approach means those messages will not be verifiable or decryptable by people using tools like Google's new browser plug-in, that just operates on visible text on a web-mail site (the plug-in almost certainly has no access to the MIME structure of the underlying message). We had been assuming that such plug-ins were a dead-end and dying technology, but Google's entrance into the space means we should probably reconsider.

In the relatively common case where we are ONLY sending plain text, we could use in-the-body PGP ASCII armour encryption or signatures, instead of PGP/MIME. This will allow more people to read our messages. If we implement #632, this will not degrade our own user's experience at all.

Any reason not to do this, @smari , @brennannovak ?

**Comment by BjarniRunar** [comment]
Folks using webmail or other clients which do not support PGP/MIME out of the box are a vast majority, not a minority. :-)

This was done a while back, haven't heard many complaints. Not sure why it is still open, really.

**Comment by JocelynDelalande** [comment]
> Folks using webmail or other clients which do not support PGP/MIME out of the box are a vast majority, not a minority. :-)

I was speaking about gmail users only, because, other webmail/phone/heavy clients users don't have something like pgp/inline support at all and will see the noisy blobs. (this is particularly bad user experience on phones...).

**Comment by BjarniRunar** [comment]
It may be an ugly experience, but it is also the only experience that allows them to copy/paste the blobs into an external tool and verify the signature or decrypt the data. The choice boils down to "ugly, but works" vs. "elegant but unusable".

Humans are good at ignoring stuff they don't understand, the --BEGIN PGP....-- preamble may be ugly but it does not prevent communication in my experience.

**Comment by JocelynDelalande** [comment]
> It may be an ugly experience, but it is also the only experience that allows them to copy/paste the blobs into an external tool and verify the signature or decrypt the data. The choice boils down to "ugly, but works" vs. "elegant but unusable".

Makes sense.

Thinks like [webpg](https://addons.mozilla.org/en-US/firefox/addon/webpg-firefox/?src=search) goes in the direction of your point as well.

What about a default to only include armoured pgp to the people we know a key for ? (that means they are pgp-aware, and prevent the others from seeing the pgp blobs).

**Comment by JocelynDelalande** [comment]
> However, the real world is not elegant. This approach means those messages will not be verifiable or decryptable by people using tools like Google's new browser plug-in, that just operates on visible text on a web-mail site (the plug-in almost certainly has no access to the MIME structure of the underlying message). We had been assuming that such plug-ins were a dead-end and dying technology, but Google's entrance into the space means we should probably reconsider.

Bumping that, because context changed.

 Google end2end now [supports PGP/Mime](https://github.com/google/end-to-end/pull/323). So maybe there is no longer need to promote ugly pgp/inline signature by default ?

**Comment by BjarniRunar** [comment]
Not really. There are still a vast number of mail clients that don't support PGP/MIME, and it is still the case that PGP/MIME with its crypto attachments is way more confusing to a non-technical recipient than an inline signature is.

People are good at ignoring crap at the bottom of an e-mail (no doubt thanks to legalese-happy people adding gigantic disclaimers to the bottom of all mails), but attachments are "important" and people get worried when they can't open them.

I consider PGP/MIME harmful and avoid it whenever possible.
