### ISSUE TITLE
"Failed to rescan" after following instructions

### ISSUE THREAD

**Issue by Cathryne** [mailpile/Mailpile#713]
Thanks to your instructions, I got Mailpile installed just fine on Ubuntu 14.04. Adding existing Thunderbird folders also worked, but the [synchronisation/scanning](https://github.com/pagekite/Mailpile/wiki/Synchronizing-Mailpile-with-Thunderbird#synchronizing) always results in the above error, followed by the folder path Mailpile previously seems to have added correctly.

The eventlog reads:
>{
        "data": {
            "elapsed": 924, 
            "output": "text", 
            "ui": ".ui.UserInteraction"
        }, 
        "date": "Sat, 14 Jun 2014 09:17:10 -0000", 
        "event_id": "539c1315.00009.4d96", 
        **"flags": "c", 
        "message": "rescan: Rescanned vcards and mailboxes", 
        "private_data": {},**
        "source": ".commands.Rescan", 
        "ts": 1402737430.78078
>    }

Thanks for any hints & advice to solve this problem.

**Comment by BjarniRunar** [comment]
This stuff has changed quite a bit, I suspect this bug is obsolete.
