### ISSUE TITLE
Need strategy for validating TLS certs of IMAP/POP3/SMTP servers

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#717]
Cryptographer / maker of HTTPSEverywhere (@bcrypt on Twitter) suggested we implement this into Mailpile

https://github.com/EFForg/starttls-everywhere

As it helps prevent MITM and downgrade attacks until DANE is mature. Curious your thoughts @smari @BjarniRunar

**Comment by BjarniRunar** [comment]
That project looks pretty dead, and doesn't really apply anyway. However, I am going to rename this issue to track the fact that it would be nice to somehow keep track of SMTP server SSL certificates.

**Comment by BjarniRunar** [comment]
Progress was made in 41026817a96d37c9e4d34c69f2ffb11bfdf5012a, but the current state of things is poor - we are quite likely to fail completely connections with servers using self-signed SSL certs at the moment.
