### ISSUE TITLE
Make web UI show "crypto_state" for Attachment parts

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#720]
The case is likely to come up whereby a message has no text or html parts and has an attachment with `crypto_state: missingkey or error` the goal is provide some useful steps to the user, but the current data structure does not give any possibilities as attachments.

For @brennannovak testing env use this message [http://localhost:33411/thread/=M7F/](http://localhost:33411/thread/=M7F/)

**Comment by BjarniRunar** [comment]
The UI currently shows state when attachments are either successfully decrypted or undecryptable. I've experimented with directly applying the crypto-state-changed logic directly to attachments and it doesn't really work with the current UI.

I'm going to punt this to 1.1 but make a note that #1791 should clearly indicate crypto state.
