### ISSUE TITLE
Support Proxies

### ISSUE THREAD

**Issue by malexmave** [mailpile/Mailpile#724]
So, I am not sure if this may actually already be in the code, a quick search turned up nothing, so I'll open an issue and if it's already implemented, just close it again :).

I am currently struggling with thunderbird as it refuses to use a (mandatory in the network) HTTP proxy, so I just wanted to make sure that Mailpile will support proxies for network access, and not only SOCKS (for Tor) but also HTTP(S) proxies.

**Comment by BjarniRunar** [comment]
This is now supported. Setting the sys.proxy.* variables will make Mailpile use a proxy for outgoing connections. HTTP, SOCKS4, SOCKS5 and Tor are supported, as long as either the socksipy or socksipychain python modules are installed.
