### ISSUE TITLE
Errors sending mail need to be communicated to the user somehow

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#735]
The current smtp_client.py went a bit too far in its assumptions that underlying code would throw exceptions when things fail, and will silently ignore a bunch of error conditions at the moment, including:

   * Rejected SMTP DATA command
   * Error response on "." at end of DATA
   * Non-zero exit codes from popen'ed delivery tools

**Comment by wiml** [comment]
Just encountered this in 6174d4a. After a failed send (the sending route's password is unset), there's no indication that there was any problem sending a message, except that it remains in outbox.
