### ISSUE TITLE
Navigating to https://demo.mailpile.is/group/list/ returns "Internal Error"

### ISSUE THREAD

**Issue by lewiscowper** [mailpile/Mailpile#737]
As in title, only message displayed is "Internal Error" on page, nothing logged to console.

Tested in:

Firefox Nightly (build 33.0a1 (2014-06-25))
Google Chrome (Version 35.0.1916.153)
Google Chrome (Version 37.0.2027.0 canary)
Safari (Version 7.0.4 (9537.76.4))

All tested on OS X Version 10.9.3 Build 13D65

**Comment by BjarniRunar** [comment]
Thanks for filing! This issue is now obsolete, our demo is broken for completely different reasons now! ;)
