### ISSUE TITLE
RFE: STEED Integration / Implementation

### ISSUE THREAD

**Issue by malexmave** [mailpile/Mailpile#74]
As discussed in Issue #59 and requested by @ioerror [on Twitter](https://twitter.com/ioerror/status/366697899872104448), let's implement [STEED](http://g10code.com/steed.html) for Mailpile.

As far as I know, no major provider supports it yet (I don't even know if any server software has been written for it), but we can implement the protocol and that will remove the argument of "there are no clients for it, so we don't need a server" (while the client guys will probably say "there is no server, so why should we write a client?").

**Comment by BjarniRunar** [comment]
I don't think STEED is really a thing any more. Now we have Autocrypt and WKD. Closing!
