### ISSUE TITLE
Implement the GMail API (server side)

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#741]
It would be pretty neat if Mailpile implemented the GMail API, so clients written to interact with GMail could also interact with Mailpile instances. This is a relatively large task, but could probably be done using the current Mailpile plugin system.

See also: https://developers.google.com/gmail/api/

**Comment by waseem18** [comment]
Hi @BjarniRunar ,

I would like to look into this issue!

Thank You.

**Comment by BjarniRunar** [comment]
It's a huge job, but you're more than welcome to try! If you haven't already, please join the IRC channel on Freenode. I'm not online myself nearly often enough, but it's still our best venue for discussion.
