### ISSUE TITLE
Position of »Compose« function: merge Composer and Drafts

### ISSUE THREAD

**Issue by jancborchardt** [mailpile/Mailpile#750]
This serves as a reminder/discussion issue for where the »Compose« button should be. ;) @brennannovak 

As written in the previous pull request: https://github.com/pagekite/Mailpile/pull/746

> Compose is one of the most essential functions. Hence it feels strange that it’s just in the top bar where it kind of blends in with other options-like items.
> 
> In the sidebar as the first item it’s more present, always first in the list, and especially now it has the text attached to it to make clear what it is for.
> (Maybe it also needs wording improvement on »Compose« but for now I just used what is there.)

**Comment by BjarniRunar** [comment]
This is arguably still a bug in our UI, the composer shouldn't be hard to find.

I know how I want this fixed. One old suggestion, was to put the compose button where the Drafts tag is. A lot of people expect it there.

I'd like to take it a step further and combine the two: embed the main composer into the Drafts page itself. Changing the Draft tag's display into a calling-to-action Compose button would probably also be appropriate.

The reason I want to embed the composer into the Drafts view, is twofold:

1. To help remind the user to finish/clean up old drafts. 
2. Set up a UI pattern we can re-use for "social media" type interactions over e-mail

Once we can embed custom composers into other tag views as well, it becomes very natural to have a composer at embedded into the view of a Mailing list's archives, for example, which defaults to composing a message to the list. Same applies when searching any e-mail address, really. And this pattern gets reused yet again when we eventually have our own concept of groups (private mailing lists).

I've made some progress in this direction already (see `.../partials/pile_compose.html`), but I hadn't written about the though process behind that anywhere. I'm marking this as Low Hanging Fruit in case someone wants to try and help out.
