### ISSUE TITLE
Mailpile doesn't fit well in small screens

### ISSUE THREAD

**Issue by danc** [mailpile/Mailpile#758]
Hi, Mailpile doesn't fit well in small screens such as 1024x600.
Please find screenshot from demo 
![capture du 2014-07-05 18 55 06](https://cloud.githubusercontent.com/assets/306555/3487122/0a30d342-0466-11e4-9acf-bfce367ada2a.png)

**Comment by BjarniRunar** [comment]
This is now much improved. Thanks for filing!
