### ISSUE TITLE
RFE / Discussion: Tor-Integration

### ISSUE THREAD

**Issue by malexmave** [mailpile/Mailpile#76]
Also a topic mentioned by the Mailpile-team on twitter in a conversation with @ioerror. Let's discuss this here, so everyone can participate. A few questions to start this off:
- How could a Tor Integration look like?
- What features should be usable via Tor?
- What features should _not_ be usable via Tor, if any?
- What features should run via Tor by default (see proposal 2 in #75)?
- How do we get all of this platform-independent and portable?

**Comment by olokos** [comment]
I wanted to fix this issue
https://github.com/syrusakbary/validate_email/issues/76
But sadly the issue is on another repo.
