### ISSUE TITLE
Adding a contact is broken or lacking in a clear error message

### ISSUE THREAD

**Issue by jparyani** [mailpile/Mailpile#770]
I am unable to add contacts from the `/contacts` page. After typing in a name (test) and email (test@test.com), clicking "Add Contact" directs me to a page that says "Internal Server Error". Nothing stands out in the console output other than:

```
http://localhost:33411 "GET /contacts/?csrf=&name=test&email=test%40test.com HTTP/1.1" 500 14
```

**Comment by BjarniRunar** [comment]
Thank you for filing this! I am very sorry you never got a reply, we got too much attention and couldn't keep up. Our bad.

I am closing this since it's quite obsolete now.
