### ISSUE TITLE
small inconsistencies when switching between display styles

### ISSUE THREAD

**Issue by Cathryne** [mailpile/Mailpile#775]
I found several small inconsistencies in the [current demo UI](https://demo.mailpile.is/in/inbox/) with Firefox 30.0, Safari 7.0.5 & Chrome 36.0.1985.125 (all on Mac OS X 10.9.4):
1. Movement of the sidebar entries is animated (at least when switching between Snug & Cozy), while the email list switches to any display style instantly. I suggest a highlighting of those emails that (a; before expansion) will slide out of the view and (b; after shrinking) slid into view. In both cases, the highlighting could fade away synchronized to the sliding animation.
2. Switching between Comfy & Cozy gives the sidebar entries a jolt upwards, before the animation proceeds.
3. Switching between Comfy & Snug does not trigger any animation of the sidebar entries.
4. The Display menu has no indicator, which one is currently set. Maybe a check mark could be added here, or the same color inversion as the mouseover could be applied to the currently selected field. Icing-on-cake: mouse-over preview.

Nothing major, but IMHO some disorientation can be prevented by harmonizing all cases to the same animation style that exists for the switch between Snug & Cozy.

**Comment by BjarniRunar** [comment]
Thank you for filing this!

I suspect some of these points may actually still be valid, so I'm leaving this open. Sorry about the hilariously late reply.
