### ISSUE TITLE
Select thread -> archive only archives one of the messages

### ISSUE THREAD

**Issue by olorin** [mailpile/Mailpile#783]
Steps to reproduce: 

 - have thread with 100 unread emails in inbox
 - select thread, click 'archive'

Observed behaviour: thread disappears from inbox in its entirety, but upon reloading it returns - the number of unread inbox emails in the left pane is decreased by one and the thread as a whole is still listed.

Expected behaviour: when I select a whole thread and apply an action, it seems intuitive for it to apply to the whole thread (especially if archiving it makes the whole thread disappear). 

Running alpha release 0.2.0.

**Comment by BjarniRunar** [comment]
This bug had to do with how threads were handled internally; it should be fixed for *new* messages, old ones sadly are unfixable given the current state of the code. Thank you for reporting this!
