### ISSUE TITLE
Create a ToxMail plugin

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#792]
Came across this secure mail concept using the Tox network created by @tarekziade It  appears to be a more secure transport layer for email similar to our SMTorP spec. There might be some benefits to using the Tox network as opposed to Tor. Would love to hear any thoughts from others about the pros / cons.

We've been tinkering with UI aspects & our API design to allow seamless integration with multiple transports (SMTorP, DarkMail, ToxMail) as there perhaps specific uses cases for each.

[Writeup about ToxMail](http://blog.ziade.org/2014/07/26/toxmail-experiment/)

[ToxMail source code](https://github.com/tarekziade/toxmail)

**Comment by BjarniRunar** [comment]
It's been four years and ToxMail still isn't really a thing. I think we can close this and assume an equivalent issue will be (re-)opened if ToxMail comes back to life and becomes relevant.
