### ISSUE TITLE
Easy way to unsubscribe from mailing lists and notifications

### ISSUE THREAD

**Issue by jancborchardt** [mailpile/Mailpile#798]
Notification mails and mailing lists usually have an »unsubscribe« feature – often well-hidden. Especially for notifications this would be useful to present in a standardized fashion.

**Comment by jfreak53** [comment]
It's more or less started. The person who finishes that function should take into account, a LOT of newsletters have a simple link to click to unsubscribe. Why write an entire email, send, save in sent box, etc when you can just click unsubscribe? Thunderbird has a plugin that does this, albeit not the best at times, but it does this:
https://addons.mozilla.org/en-us/thunderbird/addon/unsubscribe-from-mailing-list/

I actually use this in my Thunderbird install and it works perfect. Just a thought, but I would much rather follow a quick link than to write an email :)

**Comment by HugoHugoson** [comment]
Once or twice I thought it would be nice to be able to easily re-subscribe to a mailing list.
I am thinking like there should be an automatic contacts "folder" (similar to search folders in Outlook) that keeps a record of mailing lists Mailpile came across.
