### ISSUE TITLE
Scrolling on iPad needs attention

### ISSUE THREAD

**Issue by bugtracer** [mailpile/Mailpile#805]
In the current demo scrolling on the iPad is not working correctly. When I move my finger over the screen it is supposed to glide (so that when your finger is not on the screen the mail thread rolls further).
At this moment when i remove my finger from the screen the scrolling stops instant. Because of this it takes a long time and a lot of finger strokes to get at the end of a long e-mail.

Keep up the good work! 

Best regards,

Bugtracer

**Comment by BjarniRunar** [comment]
Thanks for filing this! In general, our responsive and tablet behaviour needs work, so much so that it does not make sense to track individual issues for individual devices at this point. So I'm closing this; not because you're wrong but because the underlying issue is being tracked elsewhere.
