### ISSUE TITLE
S/MIME certificate support

### ISSUE THREAD

**Issue by mikegioia** [mailpile/Mailpile#81]
While PGP support is a great feature for email security, I was wondering if you were planning to support S/MIME certificate signing and encryption? 

The problems I have with PGP are:
- ugly headers wrap message body for non-PGP users when signing email
- much harder to implement for friends/family

S/MIME allows me to generate certificates for my company/family/friends through my own CA and easily import them into users' mail clients.

**Comment by ttanner** [comment]
FYI: I'm currently implementing S/MIME support in https://github.com/ttanner/kryptomime which could be used as a backend for Mailpile in the future
