### ISSUE TITLE
Make it easy to backup and restore e-mail, contacts, settings and metadata

### ISSUE THREAD

**Issue by smtalk** [mailpile/Mailpile#811]
People's e-mail contains large amounts of valuable personal information. Considering that part of Mailpile's mission is to make it easy for people to self-host and remove their private data from the corporate clouds, it is vitally important that we take steps to ensure this valuable data does not get lost due hardware malfunction, software bugs or human error. Mailpile needs to help people make secure backups of their mail, whether to removable physical media or to remote online storage.

(Updated for roadmap, original issue text is below)

Hello,

It would be very nice to have a command-line tool, which dumps everything account-related (address book, identities, contacts etc.) to an XML/JSON file for an easy restore, so that server-to-server account transfers could be easily done.

Thank you!

**Comment by BjarniRunar** [comment]
An update on the status of this, and the strategy currently being implemented:

Status: There is now a backup tool on the Mailpile settings page which generates a .zip the user can download and save manually. The backup contains the user's settings, tags, contacts and keys. It is possible to upload this .zip during the setup of a new Mailpile to import the data. Only the e-mail data (and metadata) is missing from this archive. The contents are encrypted and protected by the same password/passphrase as Mailpile itself.

Strategy: Javascript in the web UI will automatically store this backup .zip in Localstorage on the user's browser - once users are encouraged and assisted with accessing Mailpile from mobile devices, we will automatically have guaranteed a backup that lives on separate hardware from Mailpile itself. Some Javascript magic will be needed to help the user extract the backup for use with their new Mailpile.

The second phase of the backup strategy will be to upload e-mails and metadata (encrypted) to one of the user's IMAP accounts. We might also upload the .zip archive itself, but unless we know our users have generated very strong passphrases (how can we?), that isn't really safe.

**Comment by gellenburg** [comment]
Hi Bjarni. I'm trying to follow the strategy listed here to backup my mail to mbox format: https://github.com/mailpile/Mailpile/wiki/Troubleshooting#backing-up-and-restoring-downloaded-mail

But doing the search is only returning 120 maximum messages at a time.

I have over 9,000 emails that I'd like to backup / export out of Mailpile.

I tried pointing Thunderbird to MailPiles local maildirs but that was a disaster. :-)

Any hints or tips on how I can export/ backup all the mail out of Mailpile in case my laptop dies? :-)

**Comment by BjarniRunar** [comment]
If you're just concerned with the laptop dying, why don't you just copy the Mailpile data (and GnuPG) folder in its entirety? If you think the `search` or `export` commands are broken, please file a separate issue to discuss that, I'd rather not derail this issue. The only comment I have there, is to point out that even if a `search` command only displays the first page of results, the `export ... all` command will include all results (page 2, 3, etc.). If your search returns too few results, change the search terms?

**Comment by gellenburg** [comment]
I'll try it again. I followed the exact search query as specified on that web page.

**Comment by neurokrish** [comment]
> An update on the status of this, and the strategy currently being implemented:
> 
> Status: There is now a backup tool on the Mailpile settings page which generates a .zip the user can download and save manually. The backup contains the user's settings, tags, contacts and keys. It is possible to upload this .zip during the setup of a new Mailpile to import the data. Only the e-mail data (and metadata) is missing from this archive. The contents are encrypted and protected by the same password/passphrase as Mailpile itself.
> 
> Strategy: Javascript in the web UI will automatically store this backup .zip in Localstorage on the user's browser - once users are encouraged and assisted with accessing Mailpile from mobile devices, we will automatically have guaranteed a backup that lives on separate hardware from Mailpile itself. Some Javascript magic will be needed to help the user extract the backup for use with their new Mailpile.
> 
> The second phase of the backup strategy will be to upload e-mails and metadata (encrypted) to one of the user's IMAP accounts. We might also upload the .zip archive itself, but unless we know our users have generated very strong passphrases (how can we?), that isn't really safe.

Have you looked at rclone for saving backups to different destinations? This may be useful for many of them who already have cloud storage elsewhere. I think the program allows one to generate a strong random passphrase but unless you force the user to use this, may be you can't ensure that a strong passphrase is used (more here - https://rclone.org/crypt/)?

**Comment by BjarniRunar** [comment]
@neurokrish That's a good idea - I have not looked into rclone myself. My gut reaction is that the "core team" should focus on getting IMAP-based backups to work as planned, but hopefully someone will contribute something like rclone support as a plugin down the line. And the core team should take care to design the backup system so it's amenable to such things.

That's largely academic at this point though, since I'm not able to work much on Mailpile these days, for various reasons. So if someone volunteered to just implement rclone and skip my idea, that would be way better than nothing! I'd cheer them on. :grin:

**Comment by neurokrish** [comment]
I understand! 

I want to also put this out there, just in case someone is interested. There are two programs, restic and rclone. The former is more focused on backups and the latter is more focused on providing a way to sync to various cloud destinations. In fact, both these authors have come together and integrated their work to use rclone as a backend to restic (https://restic.net/blog/2018-04-01/rclone-backend).
