### ISSUE TITLE
ownCloud plugin

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#813]
Would be great if there is a plugin which connects mailpile with [ownCloud](http://owncloud.org) with the following features:
- synchronize the mailpile adress book with ownClouds contacts feature
- directly upload files to ownCloud while using mailpile and generating private URIs for file sharing, maybe automatically if a file attachement is larger than X mb

**Comment by jfreak53** [comment]
+100000000000000e definitely needed!
