### ISSUE TITLE
Implement support for Libravatar and/or X-Face

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#814]
In addition to getting contact pictures from Gravatar, we should also support getting pics from https://www.libravatar.org , the X-Face header, and other alternate sources.

**Comment by ryneeverett** [comment]
I looked at several other email clients that support x-face and they all use compface and netpbm to convert it into an image. I doubt we want to add those as mailpile dependencies, but, given the low resolution of x-face images, I would think it would be feasible to convert into a bitmap format that can be displayed in html (bmp?) without too much of a performance cost.
