### ISSUE TITLE
Malformed Subject lines (from Yahoo Conversations)

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#818]
=?iso-8859-1?Q?m8jwHi=2Ew=3AD2youvmessedyupbomajor=2Euav3ghrem4kdt5m5=40w?= =?iso-8859-1?Q?ww=2Ei3f7kipjy=2E=26=2309=3Blisafbookcam=26=23x2E=3B=26=23?= =?iso-8859-1?Q?09=3Binfo=FF=2E=DBkinkyand=DCsweetkara=2Ei=E2nfoetx1lusjob?= =?iso-8859-1?Q?ther

**Comment by BjarniRunar** [comment]
I don't have enough data to reproduce this, for all I know it was fixed long ago... closing.
