### ISSUE TITLE
Make Mailpile useful in shared-hosting and multiuser environments

### ISSUE THREAD

**Issue by marxistvegan** [mailpile/Mailpile#820]
Mailpile is currently a personal webmail client, which only handles e-mail for one person. The project should be expanded so Mailpile can be used in shared-hosting and multiuser environments, such as small to medium businesses and organizations. This will further our mission to bring user-friendly encryption to a wider audience, and make the project more sustainable as larger organizations become motivated to contribute resources to the development and upkeep of Mailpile.

(Rephrased for roadmap, original text preserved below)

Hey all, was chatting with bnvk in IRC, recommending to try to explain the idea. 

The idea is to have Mailpile be an available webmail client on an actual remote server, in this example I am talking about the mayfirst.org community, we have already horde and roundcube that connects to our mail server for members. The problem I am seeing is that people do not like a lot of change and the idea is for the times that they are not in front of their own computer that it would be really good to give them the same over all interface. The remote-web interface would not have the gpg key capabilities cause of the security of having ones gpg on a remote server is not ideal. But for the non-gpg encrypted communication to have a space for them to connect to, but if they have their local system they would install mailpile locally so that they would have their gpg encryption abilities. I am not sure exactly how to differentiate between the two. As people may want to still visit the actual web page when on their own system. But to have a local install and a server install I think is a good idea cause Mailpile creates the first I can think of where there can be that familarity on either.

Let me know what people think of this idea or feature

I attached a rough sketch to illustrate what I am thinking.
![mailpile](https://cloud.githubusercontent.com/assets/6064303/3936266/5cfeb996-249f-11e4-9677-b103a48175ec.png)

**Comment by whitef0x0** [comment]
What is the update of this? Interested in using mailpile for shared user environments. Has this been delayed or is there a current working branch?

**Comment by russellballestrini** [comment]
The only work I have done is wrote some Salt States for speeding up the deployment on a machine:

http://russell.ballestrini.net/mailpile-salt-states-for-ubuntu-or-debian/

**Comment by BjarniRunar** [comment]
@whitef0x0 There are some major architectural issues I need to clean up before this is remotely viable, in particular Mailpile uses too much RAM for most multi-user setups and starts up too slowly. I have made progress on both, but they are in a private branch because they involve completely revamping our storage systems, which will break everyone's Mailpiles if I ship the code before it is ready and has working migrations.

System integration and installation work is premature at this point and although I appreciate the effort, it's likely to lead to bitrot very quickly unless people write tests and keep up with the changes I'll be making during the next few weeks/months.

**Comment by BjarniRunar** [comment]
I have pushed up my working branch so people can see it: https://github.com/mailpile/Mailpile/tree/features/metadata.ng ... don't expect it to run though! :-)

**Comment by BjarniRunar** [comment]
News: in bd2695ffdcede4544b10984d06992ecb8eba8c90 I created a tool name `mailpile-admin.py`, which can be used to configure Apache for multi-user Mailpile installations.

This does nothing to address the resource constraints, but it does provide a working-out-of-the-box solution for folks that one to host a few Mailpile instances for family or friends.

See https://github.com/mailpile/Mailpile/wiki/Apache-Integration for some docs.

**Comment by BjarniRunar** [comment]
Closing this, as the functionality now exists! Improvements and bug reports belong in their own issues. :-)
