### ISSUE TITLE
Implement a fix for Gmail's crazy disabled IMAP

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#822]
Accessing Gmail via IMAP is by default turned off. A user must manually go to the settings of their "Less Secure Apps" section and enable it [http://google.com/settings/security/lesssecureapps](http://google.com/settings/security/lesssecureapps). This is a UX dark pattern, as it scares people from using standards compliant IMAP email clients out of fear!

![ux_gmail_less_secure_apps](https://cloud.githubusercontent.com/assets/48677/3936342/680e81d0-24a0-11e4-9810-5e95f147173a.png)

![ux_gmail_less_secure_apps_2](https://cloud.githubusercontent.com/assets/48677/3936343/6dbd2bfe-24a0-11e4-8053-03c6a2538d5d.png)

@BjarniRunar seems to think there is a technical work around but it will take development time. Other ideas are some user popup windows that explain how to do this to users!

Google© also nicely sends a warning email to the account owner filled with nice FUD and discourages people from using any non Google® products...

![gmail_blocking_other_email_accounts](https://cloud.githubusercontent.com/assets/48677/3942719/3c52a95e-2572-11e4-97c2-23f70564bd67.png)

**Comment by BjarniRunar** [comment]
The solution will be #1371. :-)
