### ISSUE TITLE
*Conversation* (not just threaded) view

### ISSUE THREAD

**Issue by Bugsbane** [mailpile/Mailpile#85]
Please, please, please for the love of $DIETY understand the difference between threaded view and a Gmail-like "conversation" view. This is _the_ UX feature that every single Gmail user uses and one of the key things that separates them from other webmail. For some reason though, every single FOSS webmail has avoided this feature, despite all of them having people telling them that they're waiting for conversation view before switching from Gmail.

Repeat, this is NOT a request for just a threaded view. I want to see the full content of all emails in a conversation, including mine, but collapsing read ones unless their header is clicked on.

Look at Thunderbird's "Conversations" plugins for an excellent, FOSS implementation (although it's for Thunderbird, not webmail, obviously).

**Comment by step21** [comment]
@Cathryne does this have to be turned on specifically? Not working for me in latest beta III

**Comment by step21** [comment]
@Bugsbane @briankb Though for me Thunderbird Conversations is actually a bad example, as compared to regular Thunderbird it's quite buggy. Frequently messages don't load and stuff.
Also, Postbox is just a proprietary fork of Thunderbird, though admittedly a very nice one. And no Linux version ... boooh.

**Comment by bnvk** [comment]
@step21 I'm not sure how this is not working. Someones messages don't get "threaded" as per some mail clients not following proper email standards / potential bugs in support edge cases. But, messages that Mailpile interprets as a "thread" show in what is a "conversation" once clicked on from a search view.

**Comment by step21** [comment]
@bnvk Well, in this example it is a GMail account. In Gmail, messages show as conversations/threads, whereas in Mailpile none of the ones I checked did. This is on release/beta, and just ran git pull again just to be sure.

**Comment by Bugsbane** [comment]
@step21 - Thunderbird Conversations has always Worked for Me™ Anyway, what you're describing sounds more like coding bugs per se, than a fault of the UI design, which is really what we're talking about here.
