### ISSUE TITLE
Separate web login password

### ISSUE THREAD

**Issue by donpdonp** [mailpile/Mailpile#857]
The current setup asks for a password that is used to decrypt the gpgkey and at the same time, define the web login password. These should be separate passwords.

1. its confusing to both ask for an existing password (gpg key pass) and define a new password (login pass) in one field.
2. its broken if the gpgkey pass doesnt already meet the web login pass requirements (10 chars or more)

The opportunities to acquire the gpgkey pass, arguably the average users most important password, increase a hundred fold if the user is using that password at every login. It should be used once at mailpile setup, and not again.

**Comment by BjarniRunar** [comment]
Note: The passphrase used to unlock your Mailpile is no longer the same as is used to unlock your GPG key. However, if you let Mailpile create GPG keys for you, it will unlock those automatically; this can be controlled via the Keys tool on the home page.
