### ISSUE TITLE
XSS in profile settings

### ISSUE THREAD

**Issue by NielsH** [mailpile/Mailpile#858]
Hi,

The profile settings (/setup/#profiles/<vcardid>) currently doesn't properly sanitize user input, resulting in an XSS vulnerability.

When using the following input as name or note: `abc"><script>alert('uh-oh');</script>` a pop-up is displayed and the html becomes like so:

```
<div id="validation-note">
        <label class="validation-message">Note</label>
        <input type="text" class="profile-update" name="note" data-vcard_name="note" autocorrect="off" autocapitalize="off" placeholder="Personal, Work" value="abc"><script>alert('uh-oh');</script>" tabindex="4"&gt;
      </div>
```

```
<div id="validation-name">
        <label class="validation-message">Name</label>
        <span></span>      
        <input id="input-setup-profile-name" type="text" class="profile-update" name="name" data-vcard_name="fn" autocorrect="off" autocapitalize="off" placeholder="Chelsea Manning" value="Niels Hendriks"><script>alert('xss');</script>" tabindex="1"&gt;
      </div>
```

Also, when changing the name, this also shows up under /setup/profiles:

```
<span class="name">Niels Hendriks"&gt;<script>alert('xss');</script></span>
```

![xssmailpile](https://cloud.githubusercontent.com/assets/848114/4101929/3d303062-310c-11e4-9e76-5d1f1e761ed6.png)

It seems that the e-mail validation filter prevents this from happening for the e-mail address.

---

Edit - 

This also seems to happen for /setup/#sources for the `Name mail source`, `Username`, and `Host` fields

**Comment by BjarniRunar** [comment]
This page is no longer in use, this issue is now obsolete. But thank you for filing!
