### ISSUE TITLE
Make expanded Sidebar Tags stay expanded on refresh 

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#859]
This idea was brought up in #667 we need to make Sidebar tags (that have child tags) remember this

What needs to happen for this to exist is something like the following:
- Add a config setting to `defaults.py` to keep track of open Tags
- Add an AJAX call to the current "Show Tags" event
- Modify HTML template to take into account the config setting

**Comment by JocelynDelalande** [comment]
@bnvk using last master, it's not working I think: if I expand à group, and then change page, it's collapsed again.
