### ISSUE TITLE
Need to be able to run more than one Mailpile at a time on the same machine

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#877]
Currently, Mailpile listens on port 33411 by default. This means that without manual configuration, it is not easy to launch two instances of the app at once on the same machine. This will frustrate users in at least the following cases:
- Multiple users on a VPS or home server
- Users sharing a Mac and using the "switch users" feature (also applies on Linux and Windows)
- Users who want to run more than once instance of Mailpile for their own use

Possible solutions to this include:
1. Choose the port at random on startup (ok for desktop, bad for shared servers)
2. Choose the port at random on setup (ok for desktop, tolerable for shared servers)
3. Use a local dispatcher that proxies by hostname (requires varying hostnames and a registration protocol, might be able to use PageKite, great for large deployments, barely workable on desktop)
4. Try to use the standard port, but move to another one if it is unavailable (ok for desktop, bad for servers)

Of these, 2. and 3. are probably the most appropriate, with 2. being preferred on a desktop and 3. in a multipile type environment.

All of these have the drawback that we can no longer tell the user ahead of time which port Mailpile will be listening on, which has a negative effect on the ability to document things (but a positive effect on security). This is probably unavoidable, though.

**Comment by BjarniRunar** [comment]
This issue is in part addressed by mailpile-admin.py, which adds a management and proxy layer via. Apache. So this issue is at least partially solved on Linux servers (assuming folks are happy to use Apache), but still unresolved in all the desktop environments (Linux included).

**Comment by BjarniRunar** [comment]
This is now "good enough", we know how this will work both on desktops and in "multipile."

**Comment by gerroon** [comment]
Sorry to bump this but I d onot get how this is achieved atm. I am trying to reun multiple Mailpiles on the same pc.

**Comment by kubrikseu** [comment]
_Regardless of whether Mailpile is currently able to achieve this, you can easily achieve this yourself. For this, I am assuming you run Linux or Unix._

### Creating multiple users

Create multiple users for Mailpile, as much users as you want instances. Eg:

```
# useradd -b /home -m mailpile1
```

Make sure you have `tmux` installed and available to you. Login as the first user and start Mailpile:

```
# su - mailpile1
$ tmux new -s mailpile1
$ mailpile --www=127.0.0.1:33411 --wait
```

You can detach the tmux session with `CTRL + b`, followed by a seperate keypress of the `d` key. This makes sure it keeps running. Exit the user shell with `exit` and repeat the process for other instances, eg:

```
# useradd -b /home -m mailpile2
# su - mailpile2
$ tmux new -s mailpile2
$ mailpile --www=127.0.0.1:33412 --wait
```

**Do note that you have not only to increment the user for each instance, but also the port!**

### Using the different instances

Logon as your own user again, fire up the browser and enter `localhost:33411` for the first instance, `localhost:33412` for the second instance and so on. If you already have older data, recover that to the accounts _before_ launching the respective Mailpile instances.

If you need to set a different storage location, use the `MAILPILE_HOME` environment variable. Eg:

```
export MAILPILE_HOME=/home/mailpile1/apps/mailpile
```

This can be added to the shell configuration to make it more permanent.

**Comment by gerroon** [comment]
@kubrikseu  Thanks  for the answer and the help.
