### ISSUE TITLE
Fix "Bulk Tag Picker"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#879]
Upon implementing the "Bulk Tag Picker" I am overjoyed to be using it. I simply don't know why I waited to SO LONG to finish this feature- it rocks! Here is a screenshot of what it partially looks like:

![screen shot 2014-09-07 at 4 49 10 pm](https://cloud.githubusercontent.com/assets/48677/4178932/f9917b42-36ae-11e4-9db5-b2a4faf137a8.png)

I say partial, because this is a version on my personal Mailpile with upwards of 45 tags. Despite being quite useful already, there are a few aspects of the UI / UX which could be improved upon. I'm opening this issue to keep track of those things.
- All types of tags with the _"tag"_ attribute are grouped together in one big list (should segment?)
- Nested tags are out of order & expanded, not sure best thing to do here (collapse?)
- Gets too long and has lots of scrolling with my 45+ tags (should collapse things?)
- Could provide a small "search" field to type tag names to filter

![screen shot 2014-09-07 at 8 09 20 pm](https://cloud.githubusercontent.com/assets/48677/4179531/ec5f0a7c-36ca-11e4-816a-28cbd41da96c.png)
- I find the current implementing showing "tags" selected which are not seen in search view (e.g. Inbox)

**Comment by BjarniRunar** [comment]
@kasbah and @miguelbernadi, support for tagging "all messages matching this search" has been added recently. However, the good/bad-ness of the bulk tag picker is still an issue.

**Comment by BjarniRunar** [comment]
I don't think this issue is getting fixed for 1.0. The icon is just going to get hidden; bumping to 1.1.
