### ISSUE TITLE
Downloading should not mark all messages as read

### ISSUE THREAD

**Issue by gusandrews** [mailpile/Mailpile#880]
A colleague started using Mailpile and noted that it automatically marks all mail as read when downloading. She says "This is a big failure for me as I use multiple clients to check my mail and rely on leaving messages marked unread if I haven't read or dealt with them." 

Count this as two votes, as I do the same, and having everything marked as read would mess up my workflow.

**Comment by TmCTux** [comment]
Well, what is the status on how mailboxes are opened today ? I've authorize mail to be deleted on the server, I also asked to leave mail on the server (I guess that's an old classic option to avoid deleting on download of emails, as it was by default long ago on other clients when using pop3).
My issue is that if mail is read and mark as read in Mailpile, it stays unread on server. Also, it seems I cannot move or delete emails from server. So as if, mailboxes are still readonly despites the option to allow deletion on mail server.
thanks and sorry for commenting on a close issue but I'm guessing it's either a false issue or it is already open elsewhere :)

**Comment by TmCTux** [comment]
Oh that's a bummer ! 
As many I guess, I use many client to retrieve my mail so of course I leave mail on server but I can't go through unread and spam and so on each time I use a different client.
Thus I can't use Mailpile today for external account, I try to keep it for local mail boxes so I can stay in till the official version. I hope the sync will come in a not so far day.
thanks for your job and thanks for replying !
