### ISSUE TITLE
Reply to a specific message in a thread from UI

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#891]
When working with mail-lists, it's often handy to reply and quote a specific message, and not the last of the thread. The CLI offers that, not the GUI.

**Comment by JocelynDelalande** [comment]
Using that feature for a couple of mounths, works pretty well, except in that case :

- A sends an email to a mailling-list, B and me are members of the list
- B forwards it to me (yeah, that's pointless but he doesn't know ;-))

In thread view, I have a button to reply the forward from B, but not the original message from A (I had it before receiving the forwarded version)

**Comment by BjarniRunar** [comment]
The new inline e-mail view fixed this.
