### ISSUE TITLE
Konqueror misformats

### ISSUE THREAD

**Issue by uboslinux** [mailpile/Mailpile#892]
Version: "Konqueror, Version 4.14.0, Using KDE Development Platform 4.14.0" on Arch Linux.
http://localhost:33411/setup/crypto/ is horribly broken. I'm filing this because Konqueror is the default browser on some distros.

Firefox on the same host works fine.

**Comment by BjarniRunar** [comment]
Thanks for the report!

This is either obsolete, or we're just not worried about it - Konqueror isn't one of the browsers we're targetting. We'll accept PRs to improve compatibility, but we're not tracking such issues specifically at the moment.
