### ISSUE TITLE
setup edge case: dead end after editing route 

### ISSUE THREAD

**Issue by Cathryne** [mailpile/Mailpile#896]
In case one decides to click through "Edit Profile" and "Edit Route" (again) from the "Profiles"-dialogue (http://localhost:33411/setup/#profiles), there is no automatic redirect (or labelled link) back to that from "Sending Routes" after saving the edited route like there is when creating a route.

Of course, this is probably only an edge case and the main workflow works very nicely :-)

**Comment by wiml** [comment]
I ran into this as well (using today's version from git). You can get out of this either using the back button or by clicking to an earlier stage in the steps-bar at the top of the page, but it's a little confusing for a guided setup process to dead-end like that.

**Comment by BjarniRunar** [comment]
Thanks for filing! This code is being rewritten as part of the "Short Setup Flow" theme on the current roadmap (see https://www.mailpile.is/roadmap/ and the linkekd blog post).

So closing this, as it applies to doomed code anyway. :-)
