### ISSUE TITLE
Cannot permanently remove a mail source

### ISSUE THREAD

**Issue by mapperfr** [mailpile/Mailpile#899]
It would be nice to be able to permanently remove a mail source, not only to disable it.

**Comment by whummer** [comment]
+1 would be an important feature

**Comment by BjarniRunar** [comment]
In some cases, deleting the mail source would also require deleting all references to the mail, effectively deleting large volumes of e-mail from the user's pile at once. This is a scary enough thing that I'm not in a big rush to implement it. :-)

Deleting sources where mail has been downloaded and local copies made (hopefully the common case) would be less disruptive though.

**Comment by LFlare** [comment]
@BjarniRunar, how feasible is this? I've encountered a weird bug where I have 'phantom' sources fetching emails to a previously deleted account. This doesn't seem right! Is there a 'backend' way to delete off the sources?
