### ISSUE TITLE
Will need themes, or at least dark/night mode.

### ISSUE THREAD

**Issue by asfsgfdsfaber** [mailpile/Mailpile#90]
Dark mode is mandatory for me. I could give or take themes but I need a night mode.

**Comment by itanny999** [comment]
Well, I can work on creating a night-mode mockup for the webapp. Let me know if the solution is still required and how can I help.

**Comment by BjarniRunar** [comment]
Hi @itanny999 ! Thanks for the generous offer, that would be amazing!

I don't want you to waste your time though, so I want to be sure we can actually make use of your work before you spend too much time. I took a quick look at the current code - the colors in use by Mailpile today are defined in two places:

   - https://github.com/mailpile/Mailpile/blob/master/shared-data/default-theme/theme.json
   - https://github.com/mailpile/Mailpile/blob/master/shared-data/default-theme/less/config.less

If (and this isn't guaranteed) simply modifying those definitions gives good results, this should be relatively easy.

Integration into the app should be relatively straightforward. We would simply modify our build system to build a different .CSS file for each available color scheme and add a setting to let the user choose at run-time.

**Comment by BjarniRunar** [comment]
Addendum: Slightly fancier, would be to make Mailpile itself inject the colors into the CSS dynamically, which would allow users to customize the schemes themselves. That makes this more of a programming task than a design task, but is maybe something we should aim for long-term.

**Comment by ktpx** [comment]
I have eye disease, and white is the enemy.  A night mode would be extremely welcome.
