### ISSUE TITLE
Sending Route for SMTP.STRATO.DE not working

### ISSUE THREAD

**Issue by poil20** [mailpile/Mailpile#911]
Hi,
trying to use mailpile with smtp.strato.de, but get an error in the connection. Possible because Strato.de using SSL/TLS for smtp. 
Is it supported by the Beta-Version?
Anyway, great user experience and nice design.

**Comment by BjarniRunar** [comment]
Closing this because it is old. The issue may have been fixed in the meantime; there were some bugs fixed that prevented funky characters in SMTP/IMAP passwords. If not, someone will hopefully re-open after testing against HEAD. Thanks for filing!
