### ISSUE TITLE
Test/Installation on other UNIX-Systems

### ISSUE THREAD

**Issue by MercSec** [mailpile/Mailpile#928]
I did not find any information on what specific Linux Distribution (or any other UNIX) this software was tested on. Would it be possible to test the Software on OpenBSD/FreeBSD as well and add suggestions for users how to install the software there?

**Comment by BjarniRunar** [comment]
This is not really done, but since this is just a tiny sub-task of the larger "write proper docs" task, I'm going to close it. Thank you for filing and the discussion guys!
