### ISSUE TITLE
Mark as read / unread action from within the thread

### ISSUE THREAD

**Issue by Heliosmaster** [mailpile/Mailpile#929]
Currently there is no way to set a message as unread from within the thread.

Additionally, this will go toward an improvement in the general read/unread UX (see #784)

**Comment by Robsteranium** [comment]
This would be great. I do this every time I check my email (scan a message and mark it unread so I don't forget to reply/ deal with it properly later).

It would be enough for me to toggle the thread as read/unread from the top. Gmail allows you to "mark as unread from here" which is useful for keeping your place in longer threads (as per #784).

**Comment by BjarniRunar** [comment]
@Robsteranium I wasn't aware of that feature, but that sounds really useful. Thanks for commenting!

**Comment by BjarniRunar** [comment]
This is solved by the new within-search-results message display.
