### ISSUE TITLE
PGP Encrypt & Sign fail poorly if Profile is missing PGP key

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#930]
I was experiencing a weird "can't encrypt" and "can't sign" messages. I researched a bit and here is my understanding of some current weak spots with Profiles & PGP Keys. This issue relates to the now closed #683 

* Profile VCard has empty `pgp_keys` value
* Sending tries to find a PGP key that matches the sending email address
* Sending finds a PGP but only has public key
* Failure to perform action

This needs to be handled better in the UI by the following sort of things:

* Do not allow a user to encrypt or sign at all if the selected sending profile does not have a pgp_key value set
* Provide similar UI feedback & user actionable options on how to add a PGP key to a profile

This relates to #912

**Comment by BjarniRunar** [comment]
I think this is pretty much fixed by recent changes.
