### ISSUE TITLE
osx yosemite print private key issue

### ISSUE THREAD

**Issue by ido370** [mailpile/Mailpile#932]
Hi,
i just download Mailpile for OSX (yosemite, DP build14A343f) and noticed the following:
-first time startup took very long (on Seagate SSHD), 30+ seconds.
-after entering my provider details for my first profile, i said it imported 3 of 4, but when wizard was completed, i saw 4 mails not 3.
-It gave notififcation to save PGP key, so i entered a passphrase, and it gave me a page to print with the private key. The print button does not trigger the OSX print dialog. I had to go manually to Safari's File menu, choose print, and the Save as PDF to save it.

Hope you continue to make it a good program. I like to finally have a program which I control, and from which i can receive my mail when 3rd party is down/offline etc..

Greets from Holland,
Ido

**Comment by BjarniRunar** [comment]
Sorry we didn't help with this! :-(

Closing as obsolete.
