### ISSUE TITLE
Some Issues I've noticed in Beta

### ISSUE THREAD

**Issue by meirad** [mailpile/Mailpile#933]
- no way to edit signatures
- no themes
- checkbox to select all messages doesn't select them
- doesn't seem to link to riseup email accounts possibly due to lack of TLS support.
- Whitelist, black list, smart filters would be an amazing improvement.
- No way to empty trash.
- No way to add pgp key's of friends in address book.
- Once a tag is archived is there a way to resurrect it?

Other than that, runs amazing on elementary os (linux), looks good, can't wait to use it daily.

**Comment by BjarniRunar** [comment]
Thanks for filing this. Closing, because we prefer single-bug-issues, except for the tracking issues we create ourselves. These issues are all on our radar and tracked elsewhere, you're not being ignored. :-)
