### ISSUE TITLE
Can't toggle encryption lock when composing a new message

### ISSUE THREAD

**Issue by micahflee** [mailpile/Mailpile#938]
When I try writing myself an email (to an email address that's a UID on my key), I can toggle the sign checkbox but I cannot toggle the encrypt checkbox. I definitely have a trusted public key associated with that email address though.

I like the settings I currently use in Thunderbird where the encrypt checkbox is always checked by default. If I try sending an email and Enigmail can't figure out what public keys it should use, it pauses and asks me what I'd like to use. This way I never accidentally send a plaintext email when I don't mean to, and I have the option to send encrypted email to addresses that aren't listed as UIDs of a key.

**Comment by BjarniRunar** [comment]
This works as long as one has keys for all the recipients. Brennan made progress on making such keys more findable, and there are separate issues tracking that. Closing this, AFAICT it's a red herring. :-)
