### ISSUE TITLE
Download/Leave on Server doesn't stay selected when changing options

### ISSUE THREAD

**Issue by stevesbrain** [mailpile/Mailpile#942]
When you have selected either "Download" or "Leave on Server" for an account, and saved that setting, it instantly defaults back to "Download" again (same as when you get off the page, and go back to it). This makes it difficult to tell if
a) It's being set, and the interface just doesn't query it, or
b) It's never being properly set

Ubuntu 14.04 64-bit desktop

**Comment by BjarniRunar** [comment]
This entire UI is gone. Thanks for filing, sorry about our ridiculously late response.

**Comment by stevesbrain** [comment]
Haha, no worries @BjarniRunar - thanks for getting back to me anyway :)
