### ISSUE TITLE
Create package for YunoHost

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#944]
A few people have requested Mailpile be easy to install using [YunoHost](https://yunohost.org)

Creating a manifest looks like a relatively straight forward procedure. Here is some documentation for it [https://yunohost.org/#/packaging_apps](https://yunohost.org/#/packaging_apps)

**Comment by BjarniRunar** [comment]
It looks like Yunohost uses nginx, but it is still worth looking at scripts/mailpile-admin.py and the Apache integration it does - a similar strategy would almost certainly make sense for Yunohost. In fact, it would be bad for the two to be unnecessarily different, as that will make it harder for users to find instructions, documentation and answers to questions.

**Comment by ghagerer** [comment]
I've started by preparing a Debian install script according to the [Mailpile documentation](https://github.com/mailpile/Mailpile/wiki/Getting-started-on-Linux), since Yunohost is Debian-based:

https://github.com/ghagerer/mailpile-for-yunohost

I'd appreciate any help on this. For TODOs, check the link. Feel free to fork and everything.

**Comment by BjarniRunar** [comment]
@ghagerer Why is that not using the Debian packages we have prepared? Installing from github is a bit gross, IMO.

**Comment by BjarniRunar** [comment]
Sorry, that was a bit hasty and unhelpful. First, @ghagerer, THANK YOU. That should always be my first response. :grin: 

Details on our Debian packages are here: https://www.mailpile.is/download/linux.html

However, the debian package question remains - I would really prefer people not use virtualhost and github and magic scripts in that kind of environment. We provide a Debian repository which includes all the dependencies that aren't already in Debian, but it's also possible to download individual packages if people don't want to add an entire repo (a legit security concern). The up-side to using the repo, is you get security updates from us when (not if) problems are found.

**Comment by ghagerer** [comment]
Actually both of your comments appear to be very helpful, so thanks. Of course the Debian package is much better, and I just wasn't aware of it. I have to see if I can integrate it.
