### ISSUE TITLE
Make Setup Complete screen show downloading data

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#947]
A couple of usability studies have indicated that the Setup flow should inform a user when Mailpile is "DONE" downloading mail from the mail sources! Currently it just keeps showing the clever copy & jokes indefinitely.

This is largely because the Complete stage does not current import any of the eventlong data about the state of downloading!

Relates to #914

**Comment by BjarniRunar** [comment]
This stage of the setup flow is gone. :)
