### ISSUE TITLE
A network error occurred

### ISSUE THREAD

**Issue by elimisteve** [mailpile/Mailpile#956]
```
Events in progress:
 5419ec84.001ef.7d2:R A network error occurred
```

What's the best way to go about troubleshooting this? It occurs when I try to get mail from a Mail Source over SSL'd IMAP.

**Comment by TomDrinkwater** [comment]
I also have this, I also would like to know what to troubleshoot.

**Comment by emschwartz** [comment]
Same issue for me too

**Comment by BjarniRunar** [comment]
This stuff has been improved quite a bit; there are now notification tooltips to explain what is going on. I'm going to close this, because I suspect it is obsolete. Sorry we never replied to this, we were a bit swamped with issues...

Thanks for filing and testing!
