### ISSUE TITLE
Provide UI confirmation feedback after "Add Contact"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#960]
Currently, adding a contact from the modal has poor UX. This needs to improved upon in a big way by offering confirmation that the contact has been added!

![add-contact](https://cloud.githubusercontent.com/assets/48677/4318064/4b2b9ee2-3f1a-11e4-9b18-2a5f96c9aa51.png)

To achieve this, there should be an HTML template of the "Contacts" list item that looks like this:

![screen shot 2014-09-18 at 12 13 51 pm](https://cloud.githubusercontent.com/assets/48677/4318257/91aff8de-3f1c-11e4-933a-d6bcb03289d6.png)

JS should them simply access this and insert it into the list.

**Comment by danger89** [comment]
huh? I don't have a contact UI? Where can I find this..

**Comment by BjarniRunar** [comment]
You can't because this issue is obsolete, it's discussing a part of the app that is currently not shipping.

(Some of the code is still there, but the contact management stuff isn't on the 1.0 roadmap.)
