### ISSUE TITLE
Addressbook/calendar support/sharing via Radicale

### ISSUE THREAD

**Issue by renne** [mailpile/Mailpile#968]
[Radicale](http://radicale.org/) is a CardDAV/CalDAV-server written in Python. I suggest to use Radicale as addressbook and calendar backend with a HTML5 addressbook/calender frontend in MailPile. This would simplify adding full-fledged addressbooks and calendars to MailPile and allow sharing calendars and addressbooks with other devices at the same time.

[Radicale source code](https://github.com/Kozea/Radicale) is hosted on Github and can be shipped with MailPile as GIT submodule.

**Comment by XmlmXmlmX** [comment]
This would be nice. I'm searching for a webmailer with calendar and contacts as well.

**Comment by BjarniRunar** [comment]
This is a dup of #104, although I do very much appreciate the pointer to Radicale!

I will consider it carefully. My initial reservations have to do with the fact that outsourcing storage to some external tool violates our goals of storing everything encrypted. I'll also have to check whether Radicale's address book supports the features we need to implement our PGP key flows and rapid contact-search during composition. Things like that.

But making Radicale use low-level storage services from Mailpile might still be a great way to get this working...
