### ISSUE TITLE
Puppy Linux questions

### ISSUE THREAD

**Issue by FredWol** [mailpile/Mailpile#971]
I use Puppy Linux Slacko 5.7 as my main operating system.

Usually "out of the box" linux apps need some "doctoring" to work with Puppy. Has anyone tried Mailpile with Puppy?

Puppy Linux is frequently used as a "frugal install", which is the way I use it. One aspect of this is that all changes to the original system are saved in a single "save file", which one usually hopes will not grow to be too large, i.e., less than a gigabyte. Is there a way to use Mailpile so as to not download any email to the local drive; using IMAP with all mail remaining only in the cloud? I'm able to do this with Thunderbird with the Enigma plugin.

**Comment by BjarniRunar** [comment]
I haven't heard any reports of success (or failure) using Puppy Linux.

However, Mailpile is not a traditional IMAP client, it is a search engine and as such it keeps a lot of data - building a search index is not a light-weight thing. I don't think Mailpile is the right tool for what you want to do.

Sorry about the late response, and thank you for filing your issue. :-)
