### ISSUE TITLE
Error | Message Not Found

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [mailpile/Mailpile#972]
Trying to read an e-mail by clicking on the Subject and it says

![mailpile_buy](https://cloud.githubusercontent.com/assets/788244/4352771/2bc623e8-422a-11e4-9c77-74a3d171b5ca.png)

This is on Crunchbang 11 (Debian based) with Python 2.7.7

While the message aren't actually deleted. They are there. It appears for most of the messages.

**Comment by hermann88** [comment]
same here, cant read messages from "Inbox" folder from one out of 3 accounts, any ideas?
