### ISSUE TITLE
incorrect name & default mailprofile

### ISSUE THREAD

**Issue by webmind** [mailpile/Mailpile#981]
During configuration I selected a keypair and then configured one of many suggested uid's/profiles. 

When I started to use mailpile, it selected the name from a uid that was neither in the keypair I select nor was it the name of the profile I configured one, it was one of the unconfigured profiles.

I rather would have it that mailpile doesn't try to do 'the right thing', but ask for the name and/or default profile to use/offer. Is this possible?

**Comment by DaLynX** [comment]
I think this was fixed by 74d1eea99bdb892555b0cf191b612b9340df1c48
