### ISSUE TITLE
Security settings interface

### ISSUE THREAD

**Issue by Heliosmaster** [mailpile/Mailpile#982]
Apparently, after a first setting of the application (I do not recollect ever using the dropdown that is on the security page, with "you collect tinfoil hats", "paranoid", and whatnot). I have a few settings checked, when I go back and forth between all the settings in the dropdown the status of the checkboxes changes, and there is no easy way for me to remember what i had selected or not.

This is not really a critical thing, but if that page would display something like a table for comparison 
![](http://autolockdown.com/images/featuresCompare.jpg)

(a bit prettier though), it'd be better imho.

**Comment by BjarniRunar** [comment]
The old settings stuff is gone, so this is somewhat obsolete. However, there's a new issue discussing closely related issues: #1547
