### ISSUE TITLE
Mailpile leaks data 

### ISSUE THREAD

**Issue by webmind** [mailpile/Mailpile#989]
when mailpile runs it scans your mailboxes for contacts and then uses the contact database to slowly check with gravatar if they have a picture, especially since this does not go over tor yet, this seriously leaks private information to gravatar, any of their subcontractors or anyone who can get hands on their logs. While this process is relatively slow, when it finishes there is a very large dataset where all the e-mail addresses can be linked to an IP-address. The hashing of the e-mail address here is insignificant considering how easy it is get large sets of e-mail addresses as an 'rainbow table'.

I would prefer if any call mailpile makes to the outside happens with consent of the user or make it opt-in or opt-out before any of these calls happen. 

If anyone of these elements is considered broken, I would suggest to not enable the feature, until it is fixed considering the impact of these bugs.

**Comment by BjarniRunar** [comment]
This is now resolved, at least until we change our mind and enable it by default again. :-)

Basically, the gravatar plugin will by default request anonymous connections from the internal connection broker - and those requests will currently fail unless the user has configured Tor as a proxy.

The gravatar plugin can be reconfigured to not require anonymity, but the default is "safe", at least for now.

**Comment by bnvk** [comment]
@BjarniRunar great choice & w00t, w00t, on implementing Tor support :grin:
