### ISSUE TITLE
iOS Push Support

### ISSUE THREAD

**Issue by zwaldowski** [mailpile/Mailpile#99]
[Suggestion]

IMAP IDLE or potentially an Exchange ActiveSync frontend might get users most of the way on most of the mobile platforms, but push nirvana with iOS is achievable and might lessen the need for a mobile app/interface, at least on one platform.

"Apple's way" of push is implemented as an extremely lightweight open-source plugin to Dovecot. They're essentially opening a socket to APNS [with the proper certificates](https://identity.apple.com/pushcert/) and sending a username.

Delivering push notifications doesn't involve actually sending the message over the wire to APNS, and shouldn't be considered a security issue. It really just issues a "ping" that tells the device to download the email itself.

Resources:
- [Source for the dovecot plugin](http://opensource.apple.com/source/dovecot/dovecot-239.8/dovecot/src/plugins/push-notify/)
- [Source for the push daemon](http://opensource.apple.com/source/dovecot/dovecot-239.8/dovecot.push-notify/daemon/)
- [Some experimental details about the implementation](http://jesse.hollington.ca/2012/07/improving-mail-push-notifications-on.html), not my article.

**Comment by BjarniRunar** [comment]
I don't think this is applicable. This looks to me like a suggestion based on the assumption that Mailpile is a mail server that mobile applications download mail from. That's never really been on our roadmap (and still isn't), our mobile strategy is to provide users with a responsive web interface (a progressive web app) - aside from some local caching, the data and logic will reside on the machine running Mailpile.

Thanks for the suggestions though!
