### ISSUE TITLE
Create Debian and RPM packages for Linux

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#996]
We should provide binary packages of Mailpile for all the major Linux distributions.

**Comment by justinmayer** [comment]
@m0n5t3r: Now that 0.4.3 is out, would you be willing to give it another go?  (^_^)

**Comment by m0n5t3r** [comment]
@justinmayer I pushed the package when I saw the email, only got to look at what it installs now; files seem to be in the right places, indeed :)

don't have time to test right now, though...

**Comment by plsng** [comment]
@BjarniRunar can you update the package available on OBS?

**Comment by justinmayer** [comment]
@m0n5t3r: I appreciate you giving it an initial shot. Thanks! Would you please let us know once you've had a chance to try again?

**Comment by m0n5t3r** [comment]
All right, I got some time to play today; pushed the 0.4.3 package for
utopic (14.10), got it installed on my laptop and everything worked from
the first try.

I guess Ubuntu users that are afraid of `setup.py install` can give it a
shot now (got packages for 14.04 and 14.10):

https://launchpad.net/~iacobs/+archive/ubuntu/mailpile

Me, I won't give up on Thunderbird + conversations just yet, there are
still small annoyances in the UI and thread grouping is not very smart
yet, but this thing is starting to look like a serious contender :)

sent with mailpile, just for kicks :D

**Comment by aviau** [comment]
If it wasn't clear already, I'll be doing the deb packages, and they will be pushed to the official Debian repositories.

I can also help whoever is doing the RPMs, as I also have (limited) experience rpm packaging.

**Comment by step21** [comment]
Is the plan also to add some kind of desktop integration? Just tried the RC, on ubuntu 16.04 the dash does not show any icons. Is that WIP or to be expected?

**Comment by BjarniRunar** [comment]
@step21 There has been some code written in that direction. It will be added, I would like the Mac / Win / Linux desktops to all have a very similar experience.
